/*
 Highcharts JS v8.2.2 (2020-12-12)

 Boost module

 (c) 2010-2019 Highsoft AS
 Author: Torstein Honsi

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/modules/boost-canvas",["highcharts"],function(m){c(m);c.Highcharts=m;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function m(c,m,q,v){c.hasOwnProperty(m)||(c[m]=v.apply(null,q))}c=c?c._modules:{};m(c,"Extensions/BoostCanvas.js",[c["Core/Chart/Chart.js"],c["Core/Color/Color.js"],c["Core/Globals.js"],c["Series/Line/LineSeries.js"],
c["Core/Color/Palette.js"],c["Core/Series/Series.js"],c["Core/Utilities.js"]],function(c,m,q,v,ca,A,r){var da=m.parse,B=q.doc,ea=q.noop,C=r.addEvent,x=r.extend,fa=r.fireEvent,ha=r.isNumber,ia=r.merge,ja=r.pick,y=r.wrap,k=A.seriesTypes,M;return function(){q.seriesTypes.heatmap&&y(q.seriesTypes.heatmap.prototype,"drawPoints",function(){var a=this.chart,b=this.getContext(),f=this.chart.inverted,c=this.xAxis,d=this.yAxis;b?(this.points.forEach(function(e){var g=e.plotY;"undefined"===typeof g||isNaN(g)||
null===e.y||(g=e.shapeArgs,e=a.styledMode?e.series.colorAttribs(e):e.series.pointAttribs(e),b.fillStyle=e.fill,f?b.fillRect(d.len-g.y+c.left,c.len-g.x+d.top,-g.height,-g.width):b.fillRect(g.x+c.left,g.y+d.top,g.width,g.height))}),this.canvasToSVG()):this.chart.showLoading("Your browser doesn't support HTML5 canvas, <br>please use a modern browser")});x(v.prototype,{getContext:function(){var a=this.chart,b=a.chartWidth,f=a.chartHeight,c=a.seriesGroup||this.group,d=this,m=function(a,d,f,b,c,e,g){a.call(this,
f,d,b,c,e,g)};a.isChartSeriesBoosting()&&(d=a,c=a.seriesGroup);var g=d.ctx;d.canvas||(d.canvas=B.createElement("canvas"),d.renderTarget=a.renderer.image("",0,0,b,f).addClass("highcharts-boost-canvas").add(c),d.ctx=g=d.canvas.getContext("2d"),a.inverted&&["moveTo","lineTo","rect","arc"].forEach(function(a){y(g,a,m)}),d.boostCopy=function(){d.renderTarget.attr({href:d.canvas.toDataURL("image/png")})},d.boostClear=function(){g.clearRect(0,0,d.canvas.width,d.canvas.height);d===this&&d.renderTarget.attr({href:""})},
d.boostClipRect=a.renderer.clipRect(),d.renderTarget.clip(d.boostClipRect));d.canvas.width!==b&&(d.canvas.width=b);d.canvas.height!==f&&(d.canvas.height=f);d.renderTarget.attr({x:0,y:0,width:b,height:f,style:"pointer-events: none",href:""});d.boostClipRect.attr(a.getBoostClipRect(d));return g},canvasToSVG:function(){this.chart.isChartSeriesBoosting()?this.boostClear&&this.boostClear():(this.boostCopy||this.chart.boostCopy)&&(this.boostCopy||this.chart.boostCopy)()},cvsLineTo:function(a,b,f){a.lineTo(b,
f)},renderCanvas:function(){var a=this,b=a.options,f=a.chart,c=this.xAxis,d=this.yAxis,k=(f.options.boost||{}).timeRendering||!1,g=0,v=a.processedXData,y=a.processedYData,N=b.data,l=c.getExtremes(),D=l.min,E=l.max;l=d.getExtremes();var A=l.min,B=l.max,O={},F,ka=!!a.sampling,G=b.marker&&b.marker.radius,P=this.cvsDrawPoint,H=b.lineWidth?this.cvsLineTo:void 0,Q=G&&1>=G?this.cvsMarkerSquare:this.cvsMarkerCircle,la=this.cvsStrokeBatch||1E3,ma=!1!==b.enableMouseTracking,R;l=b.threshold;var u=d.getThreshold(l),
S=ha(l),T=u,na=this.fill,U=a.pointArrayMap&&"low,high"===a.pointArrayMap.join(","),V=!!b.stacking,W=a.cropStart||0;l=f.options.loading;var oa=a.requireSorting,X,pa=b.connectNulls,Y=!v,I,J,w,z,K,t=V?a.data:v||N,qa=a.fillOpacity?(new m(a.color)).setOpacity(ja(b.fillOpacity,.75)).get():a.color,Z=function(){na?(n.fillStyle=qa,n.fill()):(n.strokeStyle=a.color,n.lineWidth=b.lineWidth,n.stroke())},aa=function(d,b,c,e){0===g&&(n.beginPath(),H&&(n.lineJoin="round"));f.scroller&&"highcharts-navigator-series"===
a.options.className?(b+=f.scroller.top,c&&(c+=f.scroller.top)):b+=f.plotTop;d+=f.plotLeft;X?n.moveTo(d,b):P?P(n,d,b,c,R):H?H(n,d,b):Q&&Q.call(a,n,d,b,G,e);g+=1;g===la&&(Z(),g=0);R={clientX:d,plotY:b,yBottom:c}},ra="x"===b.findNearestPointBy,ba=this.xData||this.options.xData||this.processedXData||!1,L=function(a,b,e){K=ra?a:a+","+b;ma&&!O[K]&&(O[K]=!0,f.inverted&&(a=c.len-a,b=d.len-b),sa.push({x:ba?ba[W+e]:!1,clientX:a,plotX:a,plotY:b,i:W+e}))};this.renderTarget&&this.renderTarget.attr({href:""});
(this.points||this.graph)&&this.destroyGraphics();a.plotGroup("group","series",a.visible?"visible":"hidden",b.zIndex,f.seriesGroup);a.markerGroup=a.group;C(a,"destroy",function(){a.markerGroup=null});var sa=this.points=[];var n=this.getContext();a.buildKDTree=ea;this.boostClear&&this.boostClear();this.visible&&(99999<N.length&&(f.options.loading=ia(l,{labelStyle:{backgroundColor:da(ca.backgroundColor).setOpacity(.75).get(),padding:"1em",borderRadius:"0.5em"},style:{backgroundColor:"none",opacity:1}}),
r.clearTimeout(M),f.showLoading("Drawing..."),f.options.loading=l),k&&console.time("canvas rendering"),q.eachAsync(t,function(b,e){var g=!1,m=!1,k=!1,l=!1,n="undefined"===typeof f.index,r=!0;if(!n){if(Y){var p=b[0];var h=b[1];t[e+1]&&(k=t[e+1][0]);t[e-1]&&(l=t[e-1][0])}else p=b,h=y[e],t[e+1]&&(k=t[e+1]),t[e-1]&&(l=t[e-1]);k&&k>=D&&k<=E&&(g=!0);l&&l>=D&&l<=E&&(m=!0);if(U){Y&&(h=b.slice(1,3));var q=h[0];h=h[1]}else V&&(p=b.x,h=b.stackY,q=h-b.y);b=null===h;oa||(r=h>=A&&h<=B);if(!b&&(p>=D&&p<=E&&r||g||
m))if(p=Math.round(c.toPixels(p,!0)),ka){if("undefined"===typeof w||p===F){U||(q=h);if("undefined"===typeof z||h>J)J=h,z=e;if("undefined"===typeof w||q<I)I=q,w=e}p!==F&&("undefined"!==typeof w&&(h=d.toPixels(J,!0),u=d.toPixels(I,!0),aa(p,S?Math.min(h,T):h,S?Math.max(u,T):u,e),L(p,h,z),u!==h&&L(p,u,w)),w=z=void 0,F=p)}else h=Math.round(d.toPixels(h,!0)),aa(p,h,u,e),L(p,h,e);X=b&&!pa;0===e%5E4&&(a.boostCopy||a.chart.boostCopy)&&(a.boostCopy||a.chart.boostCopy)()}return!n},function(){var b=f.loadingDiv,
d=f.loadingShown;Z();a.canvasToSVG();k&&console.timeEnd("canvas rendering");fa(a,"renderedCanvas");d&&(x(b.style,{transition:"opacity 250ms",opacity:0}),f.loadingShown=!1,M=setTimeout(function(){b.parentNode&&b.parentNode.removeChild(b);f.loadingDiv=f.loadingSpan=null},250));delete a.buildKDTree;a.buildKDTree()},f.renderer.forExport?Number.MAX_VALUE:void 0))}});k.scatter.prototype.cvsMarkerCircle=function(a,b,c,e){a.moveTo(b,c);a.arc(b,c,e,0,2*Math.PI,!1)};k.scatter.prototype.cvsMarkerSquare=function(a,
b,c,e){a.rect(b-e,c-e,2*e,2*e)};k.scatter.prototype.fill=!0;k.bubble&&(k.bubble.prototype.cvsMarkerCircle=function(a,b,c,e,d){a.moveTo(b,c);a.arc(b,c,this.radii&&this.radii[d],0,2*Math.PI,!1)},k.bubble.prototype.cvsStrokeBatch=1);x(k.area.prototype,{cvsDrawPoint:function(a,b,c,e,d){d&&b!==d.clientX&&(a.moveTo(d.clientX,d.yBottom),a.lineTo(d.clientX,d.plotY),a.lineTo(b,c),a.lineTo(b,e))},fill:!0,fillOpacity:!0,sampling:!0});x(k.column.prototype,{cvsDrawPoint:function(a,b,c,e){a.rect(b-1,c,1,e-c)},
fill:!0,sampling:!0});c.prototype.callbacks.push(function(a){C(a,"predraw",function(){a.renderTarget&&a.renderTarget.attr({href:""});a.canvas&&a.canvas.getContext("2d").clearRect(0,0,a.canvas.width,a.canvas.height)});C(a,"render",function(){a.boostCopy&&a.boostCopy()})})}});m(c,"masters/modules/boost-canvas.src.js",[],function(){})});
//# sourceMappingURL=boost-canvas.js.map