/*
 Highcharts JS v8.2.2 (2020-12-12)

 Bullet graph series type for Highcharts

 (c) 2010-2019 Kacper Madej

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/bullet",["highcharts"],function(c){b(c);b.Highcharts=c;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function c(b,c,a,k){b.hasOwnProperty(c)||(b[c]=k.apply(null,a))}b=b?b._modules:{};c(b,"Series/Bullet/BulletPoint.js",[b["Series/Column/ColumnSeries.js"]],function(b){var c=this&&this.__extends||function(){var b=function(a,
d){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var d in a)a.hasOwnProperty(d)&&(b[d]=a[d])};return b(a,d)};return function(a,d){function c(){this.constructor=a}b(a,d);a.prototype=null===d?Object.create(d):(c.prototype=d.prototype,new c)}}();return function(b){function a(){var a=null!==b&&b.apply(this,arguments)||this;a.options=void 0;a.series=void 0;return a}c(a,b);a.prototype.destroy=function(){this.targetGraphic&&(this.targetGraphic=this.targetGraphic.destroy());
b.prototype.destroy.apply(this,arguments)};return a}(b.prototype.pointClass)});c(b,"Series/Bullet/BulletSeries.js",[b["Core/Series/Series.js"],b["Series/Bullet/BulletPoint.js"],b["Core/Utilities.js"]],function(b,c,a){var k=this&&this.__extends||function(){var b=function(a,e){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var e in a)a.hasOwnProperty(e)&&(b[e]=a[e])};return b(a,e)};return function(a,e){function c(){this.constructor=a}b(a,e);
a.prototype=null===e?Object.create(e):(c.prototype=e.prototype,new c)}}(),d=b.seriesTypes.column,q=a.extend,l=a.isNumber,r=a.merge,n=a.pick,u=a.relativeLength;a=function(b){function a(){var a=null!==b&&b.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;a.targetData=void 0;return a}k(a,b);a.prototype.drawPoints=function(){var a=this,c=a.chart,d=a.options,k=d.animationLimit||250;b.prototype.drawPoints.apply(this,arguments);a.points.forEach(function(b){var e=b.options,f=b.targetGraphic,
m=b.target,p=b.y;if(l(m)&&null!==m){var g=r(d.targetOptions,e.targetOptions);var q=g.height;var h=b.shapeArgs;var t=u(g.width,h.width);var v=a.yAxis.translate(m,!1,!0,!1,!0)-g.height/2-.5;h=a.crispCol.apply({chart:c,borderWidth:g.borderWidth,options:{crisp:d.crisp}},[h.x+h.width/2-t/2,v,t,q]);f?(f[c.pointCount<k?"animate":"attr"](h),l(p)&&null!==p?f.element.point=b:f.element.point=void 0):b.targetGraphic=f=c.renderer.rect().attr(h).add(a.group);c.styledMode||f.attr({fill:n(g.color,e.color,a.zones.length&&
(b.getZone.call({series:a,x:b.x,y:m,options:{}}).color||a.color)||void 0,b.color,a.color),stroke:n(g.borderColor,b.borderColor,a.options.borderColor),"stroke-width":g.borderWidth});l(p)&&null!==p&&(f.element.point=b);f.addClass(b.getClassName()+" highcharts-bullet-target",!0)}else f&&(b.targetGraphic=f.destroy())})};a.prototype.getExtremes=function(a){var c=this.targetData;a=b.prototype.getExtremes.call(this,a);c&&c.length&&(c=b.prototype.getExtremes.call(this,c),l(c.dataMin)&&(a.dataMin=Math.min(n(a.dataMin,
Infinity),c.dataMin)),l(c.dataMax)&&(a.dataMax=Math.max(n(a.dataMax,-Infinity),c.dataMax)));return a};a.defaultOptions=r(d.defaultOptions,{targetOptions:{width:"140%",height:3,borderWidth:0},tooltip:{pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.y}</b>. Target: <b>{point.target}</b><br/>'}});return a}(d);q(a.prototype,{parallelArrays:["x","y","target"],pointArrayMap:["y","target"]});a.prototype.pointClass=c;b.registerSeriesType("bullet",a);"";return a});c(b,
"masters/modules/bullet.src.js",[],function(){})});
//# sourceMappingURL=bullet.js.map