/*
 Highcharts JS v8.2.2 (2020-12-12)

 Highcharts cylinder module

 (c) 2010-2019 Kacper Madej

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/cylinder",["highcharts","highcharts/highcharts-3d"],function(k){a(k);a.Highcharts=k;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function k(a,b,h,m){a.hasOwnProperty(b)||(a[b]=m.apply(null,h))}a=a?a._modules:{};k(a,"Series/Cylinder/CylinderPoint.js",[a["Core/Series/Series.js"],a["Core/Utilities.js"]],function(a,b){var d=
this&&this.__extends||function(){var a=function(d,l){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,d){a.__proto__=d}||function(a,d){for(var p in d)d.hasOwnProperty(p)&&(a[p]=d[p])};return a(d,l)};return function(d,l){function b(){this.constructor=d}a(d,l);d.prototype=null===l?Object.create(l):(b.prototype=l.prototype,new b)}}();b=b.extend;a=function(a){function b(){var d=null!==a&&a.apply(this,arguments)||this;d.options=void 0;d.series=void 0;return d}d(b,a);return b}(a.seriesTypes.column.prototype.pointClass);
b(a.prototype,{shapeType:"cylinder"});return a});k(a,"Series/Cylinder/CylinderComposition.js",[a["Core/Color/Color.js"],a["Core/Globals.js"],a["Extensions/Math3D.js"],a["Core/Utilities.js"]],function(a,b,h,m){var d=a.parse,l=b.charts,k=b.deg2rad;a=b.Renderer.prototype;var w=h.perspective;h=m.merge;var p=m.pick,q=a.cuboidPath,n=function(c){return!c.some(function(c){return"C"===c[0]})};m=h(a.elements3d.cuboid,{parts:["top","bottom","front","back"],pathType:"cylinder",fillSetter:function(c){this.singleSetterForParts("fill",
null,{front:c,back:c,top:d(c).brighten(.1).get(),bottom:d(c).brighten(-.1).get()});this.color=this.fill=c;return this}});a.elements3d.cylinder=m;a.cylinder=function(c){return this.element3d("cylinder",c)};a.cylinderPath=function(c){var a=l[this.chartIndex],g=q.call(this,c),e=!g.isTop,d=!g.isFront,b=this.getCylinderEnd(a,c);c=this.getCylinderEnd(a,c,!0);return{front:this.getCylinderFront(b,c),back:this.getCylinderBack(b,c),top:b,bottom:c,zIndexes:{top:e?3:0,bottom:e?0:3,front:d?2:1,back:d?1:2,group:g.zIndexes.group}}};
a.getCylinderFront=function(c,a){c=c.slice(0,3);if(n(a)){var g=a[0];"M"===g[0]&&(c.push(a[2]),c.push(a[1]),c.push(["L",g[1],g[2]]))}else{g=a[0];var e=a[1];a=a[2];"M"===g[0]&&"C"===e[0]&&"C"===a[0]&&(c.push(["L",a[5],a[6]]),c.push(["C",a[3],a[4],a[1],a[2],e[5],e[6]]),c.push(["C",e[3],e[4],e[1],e[2],g[1],g[2]]))}c.push(["Z"]);return c};a.getCylinderBack=function(a,f){var c=[];if(n(a)){var e=a[0],d=a[2];"M"===e[0]&&"L"===d[0]&&(c.push(["M",d[1],d[2]]),c.push(a[3]),c.push(["L",e[1],e[2]]))}else"C"===
a[2][0]&&c.push(["M",a[2][5],a[2][6]]),c.push(a[3],a[4]);n(f)?(e=f[0],"M"===e[0]&&(c.push(["L",e[1],e[2]]),c.push(f[3]),c.push(f[2]))):(a=f[2],e=f[3],f=f[4],"C"===a[0]&&"C"===e[0]&&"C"===f[0]&&(c.push(["L",f[5],f[6]]),c.push(["C",f[3],f[4],f[1],f[2],e[5],e[6]]),c.push(["C",e[3],e[4],e[1],e[2],a[5],a[6]])));c.push(["Z"]);return c};a.getCylinderEnd=function(a,f,d){var c=p(f.depth,f.width),b=Math.min(f.width,c)/2,q=k*(a.options.chart.options3d.beta-90+(f.alphaCorrection||0));d=f.y+(d?f.height:0);var g=
.5519*b,h=f.width/2+f.x,l=c/2+f.z,n=[{x:0,y:d,z:b},{x:g,y:d,z:b},{x:b,y:d,z:g},{x:b,y:d,z:0},{x:b,y:d,z:-g},{x:g,y:d,z:-b},{x:0,y:d,z:-b},{x:-g,y:d,z:-b},{x:-b,y:d,z:-g},{x:-b,y:d,z:0},{x:-b,y:d,z:g},{x:-g,y:d,z:b},{x:0,y:d,z:b}],m=Math.cos(q),u=Math.sin(q),r,t;n.forEach(function(a,c){r=a.x;t=a.z;n[c].x=r*m-t*u+h;n[c].z=t*m+r*u+l});a=w(n,a,!0);return 2.5>Math.abs(a[3].y-a[9].y)&&2.5>Math.abs(a[0].y-a[6].y)?this.toLinePath([a[0],a[3],a[6],a[9]],!0):this.getCurvedPath(a)};a.getCurvedPath=function(a){var c=
[["M",a[0].x,a[0].y]],d=a.length-2,b;for(b=1;b<d;b+=3)c.push(["C",a[b].x,a[b].y,a[b+1].x,a[b+1].y,a[b+2].x,a[b+2].y]);return c}});k(a,"Series/Cylinder/CylinderSeries.js",[a["Core/Series/Series.js"],a["Series/Cylinder/CylinderPoint.js"],a["Core/Utilities.js"]],function(a,b,h){var d=this&&this.__extends||function(){var a=function(d,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var d in c)c.hasOwnProperty(d)&&(a[d]=c[d])};return a(d,b)};return function(d,
b){function h(){this.constructor=d}a(d,b);d.prototype=null===b?Object.create(b):(h.prototype=b.prototype,new h)}}(),k=a.seriesTypes.column,l=h.extend,v=h.merge;h=function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}d(b,a);b.defaultOptions=v(k.defaultOptions);return b}(k);l(h.prototype,{pointClass:b});a.registerSeriesType("cylinder",h);"";return h});k(a,"masters/modules/cylinder.src.js",[],function(){})});
//# sourceMappingURL=cylinder.js.map