/*
 Highcharts JS v8.2.2 (2020-12-12)

 Dependency wheel module

 (c) 2010-2018 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/dependency-wheel",["highcharts","highcharts/modules/sankey"],function(l){a(l);a.Highcharts=l;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function l(a,g,h,k){a.hasOwnProperty(g)||(a[g]=k.apply(null,h))}a=a?a._modules:{};l(a,"Series/DependencyWheel/DependencyWheelPoint.js",[a["Core/Series/Series.js"],a["Mixins/Nodes.js"],
a["Core/Utilities.js"]],function(a,g,h){var k=this&&this.__extends||function(){var a=function(f,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var f in b)b.hasOwnProperty(f)&&(a[f]=b[f])};return a(f,b)};return function(f,b){function d(){this.constructor=f}a(f,b);f.prototype=null===b?Object.create(b):(d.prototype=b.prototype,new d)}}();h=h.extend;a=function(a){function f(){var b=null!==a&&a.apply(this,arguments)||this;b.angle=void 0;b.fromNode=
void 0;b.index=void 0;b.linksFrom=void 0;b.linksTo=void 0;b.options=void 0;b.series=void 0;b.shapeArgs=void 0;b.toNode=void 0;return b}k(f,a);f.prototype.getDataLabelPath=function(a){var b=this.series.chart.renderer,f=this.shapeArgs,d=0>this.angle||this.angle>Math.PI,g=f.start,q=f.end;this.dataLabelPath||(this.dataLabelPath=b.arc({open:!0,longArc:Math.abs(Math.abs(g)-Math.abs(q))<Math.PI?0:1}).add(a));this.dataLabelPath.attr({x:f.x,y:f.y,r:f.r+(this.dataLabel.options.distance||0),start:d?g:q,end:d?
q:g,clockwise:+d});return this.dataLabelPath};f.prototype.isValid=function(){return!0};return f}(a.seriesTypes.sankey.prototype.pointClass);h(a.prototype,{setState:g.setNodeState});return a});l(a,"Series/DependencyWheel/DependencyWheelSeries.js",[a["Core/Animation/AnimationUtilities.js"],a["Core/Series/Series.js"],a["Series/DependencyWheel/DependencyWheelPoint.js"],a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,g,h,k,d){var f=this&&this.__extends||function(){var a=function(b,e){a=Object.setPrototypeOf||
{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var e in b)b.hasOwnProperty(e)&&(a[e]=b[e])};return a(b,e)};return function(b,e){function n(){this.constructor=b}a(b,e);b.prototype=null===e?Object.create(e):(n.prototype=e.prototype,new n)}}(),b=a.animObject,l=g.seriesTypes;a=l.pie;var p=l.sankey,r=k.deg2rad;k=d.extend;var t=d.merge;d=function(a){function d(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.nodeColumns=void 0;b.nodes=void 0;
b.points=void 0;return b}f(d,a);d.prototype.animate=function(a){if(!a){var n=b(this.options.animation).duration/2/this.nodes.length;this.nodes.forEach(function(a,b){var d=a.graphic;d&&(d.attr({opacity:0}),setTimeout(function(){d.animate({opacity:1},{duration:n})},n*b))},this);this.points.forEach(function(a){var b=a.graphic;!a.isNode&&b&&b.attr({opacity:0}).animate({opacity:1},this.options.animation)},this)}};d.prototype.createNode=function(a){var b=p.prototype.createNode.call(this,a);b.index=this.nodes.length-
1;b.getSum=function(){return b.linksFrom.concat(b.linksTo).reduce(function(a,b){return a+b.weight},0)};b.offset=function(a){function d(a){return a.fromNode===b?a.toNode:a.fromNode}var f=0,c,e=b.linksFrom.concat(b.linksTo);e.sort(function(a,b){return d(a).index-d(b).index});for(c=0;c<e.length;c++)if(d(e[c]).index>b.index){e=e.slice(0,c).reverse().concat(e.slice(c).reverse());var n=!0;break}n||e.reverse();for(c=0;c<e.length;c++){if(e[c]===a)return f;f+=e[c].weight}};return b};d.prototype.createNodeColumns=
function(){var a=[this.createNodeColumn()];this.nodes.forEach(function(b){b.column=0;a[0].push(b)});return a};d.prototype.getNodePadding=function(){return this.options.nodePadding/Math.PI};d.prototype.translate=function(){var a=this.options,b=2*Math.PI/(this.chart.plotHeight+this.getNodePadding()),d=this.getCenter(),f=(a.startAngle-90)*r;p.prototype.translate.call(this);this.nodeColumns[0].forEach(function(e){if(e.sum){var c=e.shapeArgs,g=d[0],l=d[1],h=d[2]/2,m=h-a.nodeWidth,k=f+b*c.y;c=f+b*(c.y+
c.height);e.angle=k+(c-k)/2;e.shapeType="arc";e.shapeArgs={x:g,y:l,r:h,innerR:m,start:k,end:c};e.dlBox={x:g+Math.cos((k+c)/2)*(h+m)/2,y:l+Math.sin((k+c)/2)*(h+m)/2,width:1,height:1};e.linksFrom.forEach(function(d){if(d.linkBase){var e,c=d.linkBase.map(function(c,k){c*=b;var h=Math.cos(f+c)*(m+1),n=Math.sin(f+c)*(m+1),p=a.curveFactor;e=Math.abs(d.linkBase[3-k]*b-c);e>Math.PI&&(e=2*Math.PI-e);e*=m;e<m&&(p*=e/m);return{x:g+h,y:l+n,cpX:g+(1-p)*h,cpY:l+(1-p)*n}});d.shapeArgs={d:[["M",c[0].x,c[0].y],["A",
m,m,0,0,1,c[1].x,c[1].y],["C",c[1].cpX,c[1].cpY,c[2].cpX,c[2].cpY,c[2].x,c[2].y],["A",m,m,0,0,1,c[3].x,c[3].y],["C",c[3].cpX,c[3].cpY,c[0].cpX,c[0].cpY,c[0].x,c[0].y]]}}})}})};d.defaultOptions=t(p.defaultOptions,{center:[null,null],curveFactor:.6,startAngle:0});return d}(p);k(d.prototype,{orderNodes:!1,getCenter:a.prototype.getCenter});d.prototype.pointClass=h;g.registerSeriesType("dependencywheel",d);"";return d});l(a,"masters/modules/dependency-wheel.src.js",[],function(){})});
//# sourceMappingURL=dependency-wheel.js.map