/*
 Highcharts JS v8.2.2 (2020-12-12)

 (c) 2009-2019 Sebastian Bochan, Rafal Sebestjanski

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/dumbbell",["highcharts"],function(h){a(h);a.Highcharts=h;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function h(a,e,f,k){a.hasOwnProperty(e)||(a[e]=k.apply(null,f))}a=a?a._modules:{};h(a,"Series/AreaRange/AreaRangePoint.js",[a["Series/Area/AreaSeries.js"],a["Core/Series/Point.js"],a["Core/Utilities.js"]],function(a,
e,f){var k=this&&this.__extends||function(){var b=function(a,c){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,a){c.__proto__=a}||function(c,a){for(var b in a)a.hasOwnProperty(b)&&(c[b]=a[b])};return b(a,c)};return function(a,c){function p(){this.constructor=a}b(a,c);a.prototype=null===c?Object.create(c):(p.prototype=c.prototype,new p)}}(),l=e.prototype,r=f.defined,d=f.isNumber;return function(a){function b(){var c=null!==a&&a.apply(this,arguments)||this;c.high=void 0;c.low=void 0;
c.options=void 0;c.plotHigh=void 0;c.plotLow=void 0;c.plotHighX=void 0;c.plotLowX=void 0;c.plotX=void 0;c.series=void 0;return c}k(b,a);b.prototype.setState=function(){var a=this.state,b=this.series,d=b.chart.polar;r(this.plotHigh)||(this.plotHigh=b.yAxis.toPixels(this.high,!0));r(this.plotLow)||(this.plotLow=this.plotY=b.yAxis.toPixels(this.low,!0));b.stateMarkerGraphic&&(b.lowerStateMarkerGraphic=b.stateMarkerGraphic,b.stateMarkerGraphic=b.upperStateMarkerGraphic);this.graphic=this.upperGraphic;
this.plotY=this.plotHigh;d&&(this.plotX=this.plotHighX);l.setState.apply(this,arguments);this.state=a;this.plotY=this.plotLow;this.graphic=this.lowerGraphic;d&&(this.plotX=this.plotLowX);b.stateMarkerGraphic&&(b.upperStateMarkerGraphic=b.stateMarkerGraphic,b.stateMarkerGraphic=b.lowerStateMarkerGraphic,b.lowerStateMarkerGraphic=void 0);l.setState.apply(this,arguments)};b.prototype.haloPath=function(){var b=this.series.chart.polar,a=[];this.plotY=this.plotLow;b&&(this.plotX=this.plotLowX);this.isInside&&
(a=l.haloPath.apply(this,arguments));this.plotY=this.plotHigh;b&&(this.plotX=this.plotHighX);this.isTopInside&&(a=a.concat(l.haloPath.apply(this,arguments)));return a};b.prototype.destroyElements=function(){["lowerGraphic","upperGraphic"].forEach(function(b){this[b]&&(this[b]=this[b].destroy())},this);this.graphic=null;return l.destroyElements.apply(this,arguments)};b.prototype.isValid=function(){return d(this.low)&&d(this.high)};return b}(a.prototype.pointClass)});h(a,"Series/Dumbbell/DumbbellPoint.js",
[a["Series/AreaRange/AreaRangePoint.js"],a["Core/Utilities.js"]],function(a,e){var f=this&&this.__extends||function(){var a=function(d,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(d,b)};return function(d,b){function e(){this.constructor=d}a(d,b);d.prototype=null===b?Object.create(b):(e.prototype=b.prototype,new e)}}(),k=e.extend,l=e.pick;e=function(a){function d(){var b=null!==a&&a.apply(this,
arguments)||this;b.series=void 0;b.options=void 0;b.connector=void 0;b.pointWidth=void 0;return b}f(d,a);d.prototype.setState=function(){var a=this.series,d=a.chart,c=a.options.marker,e=this.options,f=l(e.lowColor,a.options.lowColor,e.color,this.zone&&this.zone.color,this.color,a.color),h="attr";this.pointSetState.apply(this,arguments);this.state||(h="animate",this.lowerGraphic&&!d.styledMode&&(this.lowerGraphic.attr({fill:f}),this.upperGraphic&&(d={y:this.y,zone:this.zone},this.y=this.high,this.zone=
this.zone?this.getZone():void 0,c=l(this.marker?this.marker.fillColor:void 0,c?c.fillColor:void 0,e.color,this.zone?this.zone.color:void 0,this.color),this.upperGraphic.attr({fill:c}),k(this,d))));this.connector[h](a.getConnectorAttribs(this))};return d}(a);k(e.prototype,{pointSetState:a.prototype.setState});return e});h(a,"Series/Dumbbell/DumbbellSeries.js",[a["Series/Dumbbell/DumbbellPoint.js"],a["Series/Column/ColumnSeries.js"],a["Series/Line/LineSeries.js"],a["Core/Series/Series.js"],a["Core/Renderer/SVG/SVGRenderer.js"],
a["Core/Color/Palette.js"],a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,e,f,h,l,r,d,b){var k=this&&this.__extends||function(){var a=function(b,g){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,g){a.__proto__=g}||function(a,g){for(var b in g)g.hasOwnProperty(b)&&(a[b]=g[b])};return a(b,g)};return function(b,g){function c(){this.constructor=b}a(b,g);b.prototype=null===g?Object.create(g):(c.prototype=g.prototype,new c)}}(),c=e.prototype,p=f.prototype;f=h.seriesTypes;var t=
f.arearange;f=f.columnrange.prototype;var u=t.prototype;d=d.noop;var v=b.extend,w=b.merge,m=b.pick;b=function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;b.columnMetrics=void 0;return b}k(b,a);b.prototype.getConnectorAttribs=function(a){var b=this.chart,g=a.options,c=this.options,d=this.xAxis,e=this.yAxis,f=m(g.connectorWidth,c.connectorWidth),h=m(g.connectorColor,c.connectorColor,g.color,a.zone?a.zone.color:void 0,a.color),k=m(c.states&&
c.states.hover&&c.states.hover.connectorWidthPlus,1),p=m(g.dashStyle,c.dashStyle),q=m(a.plotLow,a.plotY),n=e.toPixels(c.threshold||0,!0);n=m(a.plotHigh,b.inverted?e.len-n:n);a.state&&(f+=k);0>q?q=0:q>=e.len&&(q=e.len);0>n?n=0:n>=e.len&&(n=e.len);if(0>a.plotX||a.plotX>d.len)f=0;a.upperGraphic&&(d={y:a.y,zone:a.zone},a.y=a.high,a.zone=a.zone?a.getZone():void 0,h=m(g.connectorColor,c.connectorColor,g.color,a.zone?a.zone.color:void 0,a.color),v(a,d));a={d:l.prototype.crispLine([["M",a.plotX,q],["L",a.plotX,
n]],f,"ceil")};b.styledMode||(a.stroke=h,a["stroke-width"]=f,p&&(a.dashstyle=p));return a};b.prototype.drawConnector=function(a){var b=m(this.options.animationLimit,250);b=a.connector&&this.chart.pointCount<b?"animate":"attr";a.connector||(a.connector=this.chart.renderer.path().addClass("highcharts-lollipop-stem").attr({zIndex:-1}).add(this.markerGroup));a.connector[b](this.getConnectorAttribs(a))};b.prototype.getColumnMetrics=function(){var a=c.getColumnMetrics.apply(this,arguments);a.offset+=a.width/
2;return a};b.prototype.translate=function(){this.setShapeArgs.apply(this);this.translatePoint.apply(this,arguments);this.points.forEach(function(a){var b=a.shapeArgs,c=a.pointWidth;a.plotX=b.x;b.x=a.plotX-c/2;a.tooltipPos=null});this.columnMetrics.offset-=this.columnMetrics.width/2};b.prototype.drawPoints=function(){var a=this.chart,b=this.points.length,c=this.lowColor=this.options.lowColor,e=0;for(this.seriesDrawPoints.apply(this,arguments);e<b;){var d=this.points[e];this.drawConnector(d);d.upperGraphic&&
(d.upperGraphic.element.point=d,d.upperGraphic.addClass("highcharts-lollipop-high"));d.connector.element.point=d;if(d.lowerGraphic){var f=d.zone&&d.zone.color;f=m(d.options.lowColor,c,d.options.color,f,d.color,this.color);a.styledMode||d.lowerGraphic.attr({fill:f});d.lowerGraphic.addClass("highcharts-lollipop-low")}e++}};b.prototype.markerAttribs=function(){var a=u.markerAttribs.apply(this,arguments);a.x=Math.floor(a.x);a.y=Math.floor(a.y);return a};b.prototype.pointAttribs=function(a,b){var c=p.pointAttribs.apply(this,
arguments);"hover"===b&&delete c.fill;return c};b.defaultOptions=w(t.defaultOptions,{trackByArea:!1,fillColor:"none",lineWidth:0,pointRange:1,connectorWidth:1,stickyTracking:!1,groupPadding:.2,crisp:!1,pointPadding:.1,lowColor:r.neutralColor80,states:{hover:{lineWidthPlus:0,connectorWidthPlus:1,halo:!1}}});return b}(t);v(b.prototype,{crispCol:c.crispCol,drawGraph:d,drawTracker:e.prototype.drawTracker,pointClass:a,setShapeArgs:f.translate,seriesDrawPoints:u.drawPoints,trackerGroups:["group","markerGroup",
"dataLabelsGroup"],translatePoint:u.translate});h.registerSeriesType("dumbbell",b);"";return b});h(a,"masters/modules/dumbbell.src.js",[],function(){})});
//# sourceMappingURL=dumbbell.js.map