/*
 Highcharts JS v8.2.2 (2020-12-12)

 Exporting module

 (c) 2010-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/modules/exporting",["highcharts"],function(n){c(n);c.Highcharts=n;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function n(c,k,g,l){c.hasOwnProperty(k)||(c[k]=l.apply(null,g))}c=c?c._modules:{};n(c,"Extensions/FullScreen.js",[c["Core/Chart/Chart.js"],c["Core/Globals.js"],c["Core/Utilities.js"]],function(c,k,g){var l=g.addEvent;
g=function(){function c(h){this.chart=h;this.isOpen=!1;h=h.renderTo;this.browserProps||("function"===typeof h.requestFullscreen?this.browserProps={fullscreenChange:"fullscreenchange",requestFullscreen:"requestFullscreen",exitFullscreen:"exitFullscreen"}:h.mozRequestFullScreen?this.browserProps={fullscreenChange:"mozfullscreenchange",requestFullscreen:"mozRequestFullScreen",exitFullscreen:"mozCancelFullScreen"}:h.webkitRequestFullScreen?this.browserProps={fullscreenChange:"webkitfullscreenchange",
requestFullscreen:"webkitRequestFullScreen",exitFullscreen:"webkitExitFullscreen"}:h.msRequestFullscreen&&(this.browserProps={fullscreenChange:"MSFullscreenChange",requestFullscreen:"msRequestFullscreen",exitFullscreen:"msExitFullscreen"}))}c.prototype.close=function(){var h=this.chart;if(this.isOpen&&this.browserProps&&h.container.ownerDocument instanceof Document)h.container.ownerDocument[this.browserProps.exitFullscreen]();this.unbindFullscreenEvent&&this.unbindFullscreenEvent();this.isOpen=!1;
this.setButtonText()};c.prototype.open=function(){var h=this,c=h.chart;if(h.browserProps){h.unbindFullscreenEvent=l(c.container.ownerDocument,h.browserProps.fullscreenChange,function(){h.isOpen?(h.isOpen=!1,h.close()):(h.isOpen=!0,h.setButtonText())});var g=c.renderTo[h.browserProps.requestFullscreen]();if(g)g["catch"](function(){alert("Full screen is not supported inside a frame.")});l(c,"destroy",h.unbindFullscreenEvent)}};c.prototype.setButtonText=function(){var c,g=this.chart,l=g.exportDivElements,
k=g.options.exporting,E=null===(c=null===k||void 0===k?void 0:k.buttons)||void 0===c?void 0:c.contextButton.menuItems;c=g.options.lang;(null===k||void 0===k?0:k.menuItemDefinitions)&&(null===c||void 0===c?0:c.exitFullscreen)&&c.viewFullscreen&&E&&l&&l.length&&(l[E.indexOf("viewFullscreen")].innerHTML=this.isOpen?c.exitFullscreen:k.menuItemDefinitions.viewFullscreen.text||c.viewFullscreen)};c.prototype.toggle=function(){this.isOpen?this.close():this.open()};return c}();k.Fullscreen=g;l(c,"beforeRender",
function(){this.fullscreen=new k.Fullscreen(this)});return k.Fullscreen});n(c,"Mixins/Navigation.js",[],function(){return{initUpdate:function(c){c.navigation||(c.navigation={updates:[],update:function(c,g){this.updates.forEach(function(k){k.update.call(k.context,c,g)})}})},addUpdate:function(c,k){k.navigation||this.initUpdate(k);k.navigation.updates.push({update:c,context:k})}}});n(c,"Extensions/Exporting.js",[c["Core/Chart/Chart.js"],c["Mixins/Navigation.js"],c["Core/Globals.js"],c["Core/Options.js"],
c["Core/Color/Palette.js"],c["Core/Renderer/SVG/SVGRenderer.js"],c["Core/Utilities.js"]],function(c,k,g,l,u,h,p){var n=g.doc,E=g.isTouchDevice,A=g.win;l=l.defaultOptions;var z=p.addEvent,v=p.css,x=p.createElement,F=p.discardElement,y=p.extend,H=p.find,C=p.fireEvent,I=p.isObject,w=p.merge,G=p.objectEach,q=p.pick,J=p.removeEvent,K=p.uniqueKey;y(l.lang,{viewFullscreen:"View in full screen",exitFullscreen:"Exit from full screen",printChart:"Print chart",downloadPNG:"Download PNG image",downloadJPEG:"Download JPEG image",
downloadPDF:"Download PDF document",downloadSVG:"Download SVG vector image",contextButtonTitle:"Chart context menu"});l.navigation||(l.navigation={});w(!0,l.navigation,{buttonOptions:{theme:{},symbolSize:14,symbolX:12.5,symbolY:10.5,align:"right",buttonSpacing:3,height:22,verticalAlign:"top",width:24}});w(!0,l.navigation,{menuStyle:{border:"1px solid "+u.neutralColor40,background:u.backgroundColor,padding:"5px 0"},menuItemStyle:{padding:"0.5em 1em",color:u.neutralColor80,background:"none",fontSize:E?
"14px":"11px",transition:"background 250ms, color 250ms"},menuItemHoverStyle:{background:u.highlightColor80,color:u.backgroundColor},buttonOptions:{symbolFill:u.neutralColor60,symbolStroke:u.neutralColor60,symbolStrokeWidth:3,theme:{padding:5}}});l.exporting={type:"image/png",url:"https://export.highcharts.com/",printMaxWidth:780,scale:2,buttons:{contextButton:{className:"highcharts-contextbutton",menuClassName:"highcharts-contextmenu",symbol:"menu",titleKey:"contextButtonTitle",menuItems:"viewFullscreen printChart separator downloadPNG downloadJPEG downloadPDF downloadSVG".split(" ")}},
menuItemDefinitions:{viewFullscreen:{textKey:"viewFullscreen",onclick:function(){this.fullscreen.toggle()}},printChart:{textKey:"printChart",onclick:function(){this.print()}},separator:{separator:!0},downloadPNG:{textKey:"downloadPNG",onclick:function(){this.exportChart()}},downloadJPEG:{textKey:"downloadJPEG",onclick:function(){this.exportChart({type:"image/jpeg"})}},downloadPDF:{textKey:"downloadPDF",onclick:function(){this.exportChart({type:"application/pdf"})}},downloadSVG:{textKey:"downloadSVG",
onclick:function(){this.exportChart({type:"image/svg+xml"})}}}};g.post=function(a,b,e){var d=x("form",w({method:"post",action:a,enctype:"multipart/form-data"},e),{display:"none"},n.body);G(b,function(a,b){x("input",{type:"hidden",name:b,value:a},null,d)});d.submit();F(d)};g.isSafari&&g.win.matchMedia("print").addListener(function(a){g.printingChart&&(a.matches?g.printingChart.beforePrint():g.printingChart.afterPrint())});y(c.prototype,{sanitizeSVG:function(a,b){var e=a.indexOf("</svg>")+6,d=a.substr(e);
a=a.substr(0,e);b&&b.exporting&&b.exporting.allowHTML&&d&&(d='<foreignObject x="0" y="0" width="'+b.chart.width+'" height="'+b.chart.height+'"><body xmlns="http://www.w3.org/1999/xhtml">'+d.replace(/(<(?:img|br).*?(?=>))>/g,"$1 />")+"</body></foreignObject>",a=a.replace("</svg>",d+"</svg>"));a=a.replace(/zIndex="[^"]+"/g,"").replace(/symbolName="[^"]+"/g,"").replace(/jQuery[0-9]+="[^"]+"/g,"").replace(/url\(("|&quot;)(.*?)("|&quot;);?\)/g,"url($2)").replace(/url\([^#]+#/g,"url(#").replace(/<svg /,
'<svg xmlns:xlink="http://www.w3.org/1999/xlink" ').replace(/ (|NS[0-9]+:)href=/g," xlink:href=").replace(/\n/," ").replace(/(fill|stroke)="rgba\(([ 0-9]+,[ 0-9]+,[ 0-9]+),([ 0-9\.]+)\)"/g,'$1="rgb($2)" $1-opacity="$3"').replace(/&nbsp;/g,"\u00a0").replace(/&shy;/g,"\u00ad");this.ieSanitizeSVG&&(a=this.ieSanitizeSVG(a));return a},getChartHTML:function(){this.styledMode&&this.inlineStyles();return this.container.innerHTML},getSVG:function(a){var b,e=w(this.options,a);e.plotOptions=w(this.userOptions.plotOptions,
a&&a.plotOptions);e.time=w(this.userOptions.time,a&&a.time);var d=x("div",null,{position:"absolute",top:"-9999em",width:this.chartWidth+"px",height:this.chartHeight+"px"},n.body);var g=this.renderTo.style.width;var r=this.renderTo.style.height;g=e.exporting.sourceWidth||e.chart.width||/px$/.test(g)&&parseInt(g,10)||(e.isGantt?800:600);r=e.exporting.sourceHeight||e.chart.height||/px$/.test(r)&&parseInt(r,10)||400;y(e.chart,{animation:!1,renderTo:d,forExport:!0,renderer:"SVGRenderer",width:g,height:r});
e.exporting.enabled=!1;delete e.data;e.series=[];this.series.forEach(function(a){b=w(a.userOptions,{animation:!1,enableMouseTracking:!1,showCheckbox:!1,visible:a.visible});b.isInternal||e.series.push(b)});this.axes.forEach(function(a){a.userOptions.internalKey||(a.userOptions.internalKey=K())});var h=new c(e,this.callback);a&&["xAxis","yAxis","series"].forEach(function(b){var d={};a[b]&&(d[b]=a[b],h.update(d))});this.axes.forEach(function(a){var b=H(h.axes,function(b){return b.options.internalKey===
a.userOptions.internalKey}),d=a.getExtremes(),e=d.userMin;d=d.userMax;b&&("undefined"!==typeof e&&e!==b.min||"undefined"!==typeof d&&d!==b.max)&&b.setExtremes(e,d,!0,!1)});g=h.getChartHTML();C(this,"getSVG",{chartCopy:h});g=this.sanitizeSVG(g,e);e=null;h.destroy();F(d);return g},getSVGForExport:function(a,b){var e=this.options.exporting;return this.getSVG(w({chart:{borderRadius:0}},e.chartOptions,b,{exporting:{sourceWidth:a&&a.sourceWidth||e.sourceWidth,sourceHeight:a&&a.sourceHeight||e.sourceHeight}}))},
getFilename:function(){var a=this.userOptions.title&&this.userOptions.title.text,b=this.options.exporting.filename;if(b)return b.replace(/\//g,"-");"string"===typeof a&&(b=a.toLowerCase().replace(/<\/?[^>]+(>|$)/g,"").replace(/[\s_]+/g,"-").replace(/[^a-z0-9\-]/g,"").replace(/^[\-]+/g,"").replace(/[\-]+/g,"-").substr(0,24).replace(/[\-]+$/g,""));if(!b||5>b.length)b="chart";return b},exportChart:function(a,b){b=this.getSVGForExport(a,b);a=w(this.options.exporting,a);g.post(a.url,{filename:a.filename?
a.filename.replace(/\//g,"-"):this.getFilename(),type:a.type,width:a.width||0,scale:a.scale,svg:b},a.formAttributes)},moveContainers:function(a){(this.fixedDiv?[this.fixedDiv,this.scrollingContainer]:[this.container]).forEach(function(b){a.appendChild(b)})},beforePrint:function(){var a=n.body,b=this.options.exporting.printMaxWidth,e={childNodes:a.childNodes,origDisplay:[],resetParams:void 0};this.isPrinting=!0;this.pointer.reset(null,0);C(this,"beforePrint");b&&this.chartWidth>b&&(e.resetParams=[this.options.chart.width,
void 0,!1],this.setSize(b,void 0,!1));[].forEach.call(e.childNodes,function(a,b){1===a.nodeType&&(e.origDisplay[b]=a.style.display,a.style.display="none")});this.moveContainers(a);this.printReverseInfo=e},afterPrint:function(){if(this.printReverseInfo){var a=this.printReverseInfo.childNodes,b=this.printReverseInfo.origDisplay,e=this.printReverseInfo.resetParams;this.moveContainers(this.renderTo);[].forEach.call(a,function(a,e){1===a.nodeType&&(a.style.display=b[e]||"")});this.isPrinting=!1;e&&this.setSize.apply(this,
e);delete this.printReverseInfo;delete g.printingChart;C(this,"afterPrint")}},print:function(){var a=this;a.isPrinting||(g.printingChart=a,g.isSafari||a.beforePrint(),setTimeout(function(){A.focus();A.print();g.isSafari||setTimeout(function(){a.afterPrint()},1E3)},1))},contextMenu:function(a,b,e,d,c,g,h){var f=this,r=f.options.navigation,k=f.chartWidth,B=f.chartHeight,t="cache-"+a,m=f[t],D=Math.max(c,g);if(!m){f.exportContextMenu=f[t]=m=x("div",{className:a},{position:"absolute",zIndex:1E3,padding:D+
"px",pointerEvents:"auto"},f.fixedDiv||f.container);var l=x("ul",{className:"highcharts-menu"},{listStyle:"none",margin:0,padding:0},m);f.styledMode||v(l,y({MozBoxShadow:"3px 3px 10px #888",WebkitBoxShadow:"3px 3px 10px #888",boxShadow:"3px 3px 10px #888"},r.menuStyle));m.hideMenu=function(){v(m,{display:"none"});h&&h.setState(0);f.openMenu=!1;v(f.renderTo,{overflow:"hidden"});p.clearTimeout(m.hideTimer);C(f,"exportMenuHidden")};f.exportEvents.push(z(m,"mouseleave",function(){m.hideTimer=A.setTimeout(m.hideMenu,
500)}),z(m,"mouseenter",function(){p.clearTimeout(m.hideTimer)}),z(n,"mouseup",function(b){f.pointer.inClass(b.target,a)||m.hideMenu()}),z(m,"click",function(){f.openMenu&&m.hideMenu()}));b.forEach(function(a){"string"===typeof a&&(a=f.options.exporting.menuItemDefinitions[a]);if(I(a,!0)){if(a.separator)var b=x("hr",null,null,l);else"viewData"===a.textKey&&f.isDataTableVisible&&(a.textKey="hideData"),b=x("li",{className:"highcharts-menu-item",onclick:function(b){b&&b.stopPropagation();m.hideMenu();
a.onclick&&a.onclick.apply(f,arguments)},innerHTML:a.text||f.options.lang[a.textKey]},null,l),f.styledMode||(b.onmouseover=function(){v(this,r.menuItemHoverStyle)},b.onmouseout=function(){v(this,r.menuItemStyle)},v(b,y({cursor:"pointer"},r.menuItemStyle)));f.exportDivElements.push(b)}});f.exportDivElements.push(l,m);f.exportMenuWidth=m.offsetWidth;f.exportMenuHeight=m.offsetHeight}b={display:"block"};e+f.exportMenuWidth>k?b.right=k-e-c-D+"px":b.left=e-D+"px";d+g+f.exportMenuHeight>B&&"top"!==h.alignOptions.verticalAlign?
b.bottom=B-d-D+"px":b.top=d+g-D+"px";v(m,b);v(f.renderTo,{overflow:""});f.openMenu=!0;C(f,"exportMenuShown")},addButton:function(a){var b=this,e=b.renderer,d=w(b.options.navigation.buttonOptions,a),c=d.onclick,g=d.menuItems,h=d.symbolSize||12;b.btnCount||(b.btnCount=0);b.exportDivElements||(b.exportDivElements=[],b.exportSVGElements=[]);if(!1!==d.enabled){var f=d.theme,k=f.states,l=k&&k.hover;k=k&&k.select;var B;b.styledMode||(f.fill=q(f.fill,u.backgroundColor),f.stroke=q(f.stroke,"none"));delete f.states;
c?B=function(a){a&&a.stopPropagation();c.call(b,a)}:g&&(B=function(a){a&&a.stopPropagation();b.contextMenu(t.menuClassName,g,t.translateX,t.translateY,t.width,t.height,t);t.setState(2)});d.text&&d.symbol?f.paddingLeft=q(f.paddingLeft,25):d.text||y(f,{width:d.width,height:d.height,padding:0});b.styledMode||(f["stroke-linecap"]="round",f.fill=q(f.fill,u.backgroundColor),f.stroke=q(f.stroke,"none"));var t=e.button(d.text,0,0,B,f,l,k).addClass(a.className).attr({title:q(b.options.lang[d._titleKey||d.titleKey],
"")});t.menuClassName=a.menuClassName||"highcharts-menu-"+b.btnCount++;if(d.symbol){var m=e.symbol(d.symbol,d.symbolX-h/2,d.symbolY-h/2,h,h,{width:h,height:h}).addClass("highcharts-button-symbol").attr({zIndex:1}).add(t);b.styledMode||m.attr({stroke:d.symbolStroke,fill:d.symbolFill,"stroke-width":d.symbolStrokeWidth||1})}t.add(b.exportingGroup).align(y(d,{width:t.width,x:q(d.x,b.buttonOffset)}),!0,"spacingBox");b.buttonOffset+=(t.width+d.buttonSpacing)*("right"===d.align?-1:1);b.exportSVGElements.push(t,
m)}},destroyExport:function(a){var b=a?a.target:this;a=b.exportSVGElements;var e=b.exportDivElements,d=b.exportEvents,c;a&&(a.forEach(function(a,d){a&&(a.onclick=a.ontouchstart=null,c="cache-"+a.menuClassName,b[c]&&delete b[c],b.exportSVGElements[d]=a.destroy())}),a.length=0);b.exportingGroup&&(b.exportingGroup.destroy(),delete b.exportingGroup);e&&(e.forEach(function(a,d){p.clearTimeout(a.hideTimer);J(a,"mouseleave");b.exportDivElements[d]=a.onmouseout=a.onmouseover=a.ontouchstart=a.onclick=null;
F(a)}),e.length=0);d&&(d.forEach(function(a){a()}),d.length=0)}});h.prototype.inlineToAttributes="fill stroke strokeLinecap strokeLinejoin strokeWidth textAnchor x y".split(" ");h.prototype.inlineBlacklist=[/-/,/^(clipPath|cssText|d|height|width)$/,/^font$/,/[lL]ogical(Width|Height)$/,/perspective/,/TapHighlightColor/,/^transition/,/^length$/];h.prototype.unstyledElements=["clipPath","defs","desc"];c.prototype.inlineStyles=function(){function a(a){return a.replace(/([A-Z])/g,function(a,b){return"-"+
b.toLowerCase()})}function b(c){function e(b,e){n=v=!1;if(k){for(q=k.length;q--&&!v;)v=k[q].test(e);n=!v}"transform"===e&&"none"===b&&(n=!0);for(q=h.length;q--&&!n;)n=h[q].test(e)||"function"===typeof b;n||z[e]===b&&"svg"!==c.nodeName||f[c.nodeName][e]===b||(d&&-1===d.indexOf(e)?m+=a(e)+":"+b+";":b&&c.setAttribute(a(e),b))}var m="",n,v,q;if(1===c.nodeType&&-1===l.indexOf(c.nodeName)){var r=A.getComputedStyle(c,null);var z="svg"===c.nodeName?{}:A.getComputedStyle(c.parentNode,null);if(!f[c.nodeName]){p=
u.getElementsByTagName("svg")[0];var x=u.createElementNS(c.namespaceURI,c.nodeName);p.appendChild(x);f[c.nodeName]=w(A.getComputedStyle(x,null));"text"===c.nodeName&&delete f.text.fill;p.removeChild(x)}if(g.isFirefox||g.isMS)for(var y in r)e(r[y],y);else G(r,e);m&&(r=c.getAttribute("style"),c.setAttribute("style",(r?r+";":"")+m));"svg"===c.nodeName&&c.setAttribute("stroke-width","1px");"text"!==c.nodeName&&[].forEach.call(c.children||c.childNodes,b)}}var c=this.renderer,d=c.inlineToAttributes,h=c.inlineBlacklist,
k=c.inlineWhitelist,l=c.unstyledElements,f={},p;c=n.createElement("iframe");v(c,{width:"1px",height:"1px",visibility:"hidden"});n.body.appendChild(c);var u=c.contentWindow.document;u.open();u.write('<svg xmlns="http://www.w3.org/2000/svg"></svg>');u.close();b(this.container.querySelector("svg"));p.parentNode.remove();c.remove()};g.Renderer.prototype.symbols.menu=function(a,b,c,d){return[["M",a,b+2.5],["L",a+c,b+2.5],["M",a,b+d/2+.5],["L",a+c,b+d/2+.5],["M",a,b+d-1.5],["L",a+c,b+d-1.5]]};g.Renderer.prototype.symbols.menuball=
function(a,b,c,d){a=[];d=d/3-2;return a=a.concat(this.circle(c-d,b,d,d),this.circle(c-d,b+d+4,d,d),this.circle(c-d,b+2*(d+4),d,d))};c.prototype.renderExporting=function(){var a=this,b=a.options.exporting,c=b.buttons,d=a.isDirtyExporting||!a.exportSVGElements;a.buttonOffset=0;a.isDirtyExporting&&a.destroyExport();d&&!1!==b.enabled&&(a.exportEvents=[],a.exportingGroup=a.exportingGroup||a.renderer.g("exporting-group").attr({zIndex:3}).add(),G(c,function(b){a.addButton(b)}),a.isDirtyExporting=!1)};z(c,
"init",function(){var a=this;a.exporting={update:function(b,c){a.isDirtyExporting=!0;w(!0,a.options.exporting,b);q(c,!0)&&a.redraw()}};k.addUpdate(function(b,c){a.isDirtyExporting=!0;w(!0,a.options.navigation,b);q(c,!0)&&a.redraw()},a)});c.prototype.callbacks.push(function(a){a.renderExporting();z(a,"redraw",a.renderExporting);z(a,"destroy",a.destroyExport)})});n(c,"masters/modules/exporting.src.js",[],function(){})});
//# sourceMappingURL=exporting.js.map