/*
 Highcharts JS v8.2.2 (2020-12-12)

 Exporting module

 (c) 2010-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/export-data",["highcharts","highcharts/modules/exporting"],function(k){a(k);a.Highcharts=k;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function k(a,b,p,f){a.hasOwnProperty(b)||(a[b]=f.apply(null,p))}a=a?a._modules:{};k(a,"Extensions/DownloadURL.js",[a["Core/Globals.js"]],function(a){var b=a.win,p=b.document,f=b.URL||
b.webkitURL||b,k=a.dataURLtoBlob=function(a){if((a=a.replace(/filename=.*;/,"").match(/data:([^;]*)(;base64)?,([0-9A-Za-z+/]+)/))&&3<a.length&&b.atob&&b.ArrayBuffer&&b.Uint8Array&&b.Blob&&f.createObjectURL){var m=b.atob(a[3]),c=new b.ArrayBuffer(m.length);c=new b.Uint8Array(c);for(var e=0;e<c.length;++e)c[e]=m.charCodeAt(e);a=new b.Blob([c],{type:a[1]});return f.createObjectURL(a)}};a=a.downloadURL=function(a,f){var c=b.navigator,e=p.createElement("a");if("string"===typeof a||a instanceof String||
!c.msSaveOrOpenBlob){a=""+a;if(/Edge\/\d+/.test(c.userAgent)||2E6<a.length)if(a=k(a)||"",!a)throw Error("Failed to convert to blob");if("undefined"!==typeof e.download)e.href=a,e.download=f,p.body.appendChild(e),e.click(),p.body.removeChild(e);else try{var m=b.open(a,"chart");if("undefined"===typeof m||null===m)throw Error("Failed to open window");}catch(E){b.location.href=a}}else c.msSaveOrOpenBlob(a,f)};return{dataURLtoBlob:k,downloadURL:a}});k(a,"Extensions/ExportData.js",[a["Core/Axis/Axis.js"],
a["Core/Chart/Chart.js"],a["Core/Globals.js"],a["Core/Utilities.js"],a["Extensions/DownloadURL.js"]],function(a,b,p,f,k){function m(a,b){var d=e.navigator,t=-1<d.userAgent.indexOf("WebKit")&&0>d.userAgent.indexOf("Chrome"),c=e.URL||e.webkitURL||e;try{if(d.msSaveOrOpenBlob&&e.MSBlobBuilder){var q=new e.MSBlobBuilder;q.append(a);return q.getBlob("image/svg+xml")}if(!t)return c.createObjectURL(new e.Blob(["\ufeff"+a],{type:b}))}catch(N){}}var I=p.doc,c=p.seriesTypes,e=p.win;p=f.addEvent;var J=f.defined,
E=f.extend,K=f.find,C=f.fireEvent,L=f.getOptions,M=f.isNumber,w=f.pick;f=f.setOptions;var F=k.downloadURL;f({exporting:{csv:{annotations:{itemDelimiter:"; ",join:!1},columnHeaderFormatter:null,dateFormat:"%Y-%m-%d %H:%M:%S",decimalPoint:null,itemDelimiter:null,lineDelimiter:"\n"},showTable:!1,useMultiLevelHeaders:!0,useRowspanHeaders:!0},lang:{downloadCSV:"Download CSV",downloadXLS:"Download XLS",exportData:{annotationHeader:"Annotations",categoryHeader:"Category",categoryDatetimeHeader:"DateTime"},
viewData:"View data table",hideData:"Hide data table"}});p(b,"render",function(){this.options&&this.options.exporting&&this.options.exporting.showTable&&!this.options.chart.forExport&&!this.dataTableDiv&&this.viewData()});b.prototype.setUpKeyToAxis=function(){c.arearange&&(c.arearange.prototype.keyToAxis={low:"y",high:"y"});c.gantt&&(c.gantt.prototype.keyToAxis={start:"x",end:"x"})};b.prototype.getDataRows=function(d){var b=this.hasParallelCoordinates,c=this.time,e=this.options.exporting&&this.options.exporting.csv||
{},f=this.xAxis,q={},k=[],p=[],D=[],A;var x=this.options.lang.exportData;var u=x.categoryHeader,g=x.categoryDatetimeHeader,G=function(n,b,c){if(e.columnHeaderFormatter){var h=e.columnHeaderFormatter(n,b,c);if(!1!==h)return h}return n?n instanceof a?n.options.title&&n.options.title.text||(n.dateTime?g:u):d?{columnTitle:1<c?b:n.name,topLevelColumnTitle:n.name}:n.name+(1<c?" ("+b+")":""):u},H=function(a,b,d){var n={},c={};b.forEach(function(b){var g=(a.keyToAxis&&a.keyToAxis[b]||b)+"Axis";g=M(d)?a.chart[g][d]:
a[g];n[b]=g&&g.categories||[];c[b]=g&&g.dateTime});return{categoryMap:n,dateTimeValueAxisMap:c}},v=function(a,b){return a.data.filter(function(a){return"undefined"!==typeof a.y&&a.name}).length&&b&&!b.categories&&!a.keyToAxis?a.pointArrayMap&&a.pointArrayMap.filter(function(a){return"x"===a}).length?(a.pointArrayMap.unshift("x"),a.pointArrayMap):["x","y"]:a.pointArrayMap||["y"]},h=[];var y=0;this.setUpKeyToAxis();this.series.forEach(function(a){var g=a.xAxis,n=a.options.keys||v(a,g),t=n.length,l=
!a.requireSorting&&{},k=f.indexOf(g),B=H(a,n),u;if(!1!==a.options.includeInDataExport&&!a.options.isInternal&&!1!==a.visible){K(h,function(a){return a[0]===k})||h.push([k,y]);for(u=0;u<t;)A=G(a,n[u],n.length),D.push(A.columnTitle||A),d&&p.push(A.topLevelColumnTitle||A),u++;var m={chart:a.chart,autoIncrement:a.autoIncrement,options:a.options,pointArrayMap:a.pointArrayMap};a.options.data.forEach(function(d,h){b&&(B=H(a,n,h));var f={series:m};a.pointClass.prototype.applyOptions.apply(f,[d]);d=f.x;var v=
a.data[h]&&a.data[h].name;u=0;if(!g||"name"===a.exportKey||!b&&g&&g.hasNames&&v)d=v;l&&(l[d]&&(d+="|"+h),l[d]=!0);q[d]||(q[d]=[],q[d].xValues=[]);q[d].x=f.x;q[d].name=v;for(q[d].xValues[k]=f.x;u<t;)h=n[u],v=f[h],q[d][y+u]=w(B.categoryMap[h][v],B.dateTimeValueAxisMap[h]?c.dateFormat(e.dateFormat,v):null,v),u++});y+=u}});for(l in q)Object.hasOwnProperty.call(q,l)&&k.push(q[l]);var l=d?[p,D]:[D];for(y=h.length;y--;){var m=h[y][0];var r=h[y][1];var z=f[m];k.sort(function(a,d){return a.xValues[m]-d.xValues[m]});
x=G(z);l[0].splice(r,0,x);d&&l[1]&&l[1].splice(r,0,x);k.forEach(function(a){var d=a.name;z&&!J(d)&&(z.dateTime?(a.x instanceof Date&&(a.x=a.x.getTime()),d=c.dateFormat(e.dateFormat,a.x)):d=z.categories?w(z.names[a.x],z.categories[a.x],a.x):a.x);a.splice(r,0,d)})}l=l.concat(k);C(this,"exportData",{dataRows:l});return l};b.prototype.getCSV=function(a){var d="",b=this.getDataRows(),c=this.options.exporting.csv,f=w(c.decimalPoint,","!==c.itemDelimiter&&a?(1.1).toLocaleString()[1]:"."),e=w(c.itemDelimiter,
","===f?";":","),k=c.lineDelimiter;b.forEach(function(a,c){for(var t,q=a.length;q--;)t=a[q],"string"===typeof t&&(t='"'+t+'"'),"number"===typeof t&&"."!==f&&(t=t.toString().replace(".",f)),a[q]=t;d+=a.join(e);c<b.length-1&&(d+=k)});return d};b.prototype.getTable=function(a){var b='<table id="highcharts-data-table-'+this.index+'">',d=this.options,c=a?(1.1).toLocaleString()[1]:".",f=w(d.exporting.useMultiLevelHeaders,!0);a=this.getDataRows(f);var e=0,k=f?a.shift():null,p=a.shift(),m=function(a,b,d,
f){var g=w(f,"");b="text"+(b?" "+b:"");"number"===typeof g?(g=g.toString(),","===c&&(g=g.replace(".",c)),b="number"):f||(b="empty");return"<"+a+(d?" "+d:"")+' class="'+b+'">'+g+"</"+a+">"};!1!==d.exporting.tableCaption&&(b+='<caption class="highcharts-table-caption">'+w(d.exporting.tableCaption,d.title.text?d.title.text.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#x27;").replace(/\//g,"&#x2F;"):"Chart")+"</caption>");for(var r=0,x=a.length;r<
x;++r)a[r].length>e&&(e=a[r].length);b+=function(a,b,c){var e="<thead>",g=0;c=c||b&&b.length;var h,k=0;if(h=f&&a&&b){a:if(h=a.length,b.length===h){for(;h--;)if(a[h]!==b[h]){h=!1;break a}h=!0}else h=!1;h=!h}if(h){for(e+="<tr>";g<c;++g){h=a[g];var l=a[g+1];h===l?++k:k?(e+=m("th","highcharts-table-topheading",'scope="col" colspan="'+(k+1)+'"',h),k=0):(h===b[g]?d.exporting.useRowspanHeaders?(l=2,delete b[g]):(l=1,b[g]=""):l=1,e+=m("th","highcharts-table-topheading",'scope="col"'+(1<l?' valign="top" rowspan="'+
l+'"':""),h))}e+="</tr>"}if(b){e+="<tr>";g=0;for(c=b.length;g<c;++g)"undefined"!==typeof b[g]&&(e+=m("th",null,'scope="col"',b[g]));e+="</tr>"}return e+"</thead>"}(k,p,Math.max(e,p.length));b+="<tbody>";a.forEach(function(a){b+="<tr>";for(var d=0;d<e;d++)b+=m(d?"td":"th",null,d?"":'scope="row"',a[d]);b+="</tr>"});b+="</tbody></table>";a={html:b};C(this,"afterGetTable",a);return a.html};b.prototype.downloadCSV=function(){var a=this.getCSV(!0);F(m(a,"text/csv")||"data:text/csv,\ufeff"+encodeURIComponent(a),
this.getFilename()+".csv")};b.prototype.downloadXLS=function(){var a='<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><head>\x3c!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>Ark1</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--\x3e<style>td{border:none;font-family: Calibri, sans-serif;} .number{mso-number-format:"0.00";} .text{ mso-number-format:"@";}</style><meta name=ProgId content=Excel.Sheet><meta charset=UTF-8></head><body>'+
this.getTable(!0)+"</body></html>";F(m(a,"application/vnd.ms-excel")||"data:application/vnd.ms-excel;base64,"+e.btoa(unescape(encodeURIComponent(a))),this.getFilename()+".xls")};b.prototype.viewData=function(){this.dataTableDiv||(this.dataTableDiv=I.createElement("div"),this.dataTableDiv.className="highcharts-data-table",this.renderTo.parentNode.insertBefore(this.dataTableDiv,this.renderTo.nextSibling),this.dataTableDiv.innerHTML=this.getTable());if(""===this.dataTableDiv.style.display||"none"===
this.dataTableDiv.style.display)this.dataTableDiv.style.display="block";this.isDataTableVisible=!0;C(this,"afterViewData",this.dataTableDiv)};b.prototype.hideData=function(){this.dataTableDiv&&"block"===this.dataTableDiv.style.display&&(this.dataTableDiv.style.display="none");this.isDataTableVisible=!1};b.prototype.toggleDataTable=function(){var a=this.exportDivElements,b=this.options.exporting;b=b&&b.buttons&&b.buttons.contextButton.menuItems;var c=this.options.lang;this.isDataTableVisible?this.hideData():
this.viewData();(null===r||void 0===r?0:r.menuItemDefinitions)&&(null===c||void 0===c?0:c.viewData)&&c.hideData&&b&&a&&a.length&&(a[b.indexOf("viewData")].innerHTML=this.isDataTableVisible?c.hideData:c.viewData)};var r=L().exporting;r&&(E(r.menuItemDefinitions,{downloadCSV:{textKey:"downloadCSV",onclick:function(){this.downloadCSV()}},downloadXLS:{textKey:"downloadXLS",onclick:function(){this.downloadXLS()}},viewData:{textKey:"viewData",onclick:function(){this.toggleDataTable()}}}),r.buttons&&r.buttons.contextButton.menuItems.push("separator",
"downloadCSV","downloadXLS","viewData"));c.map&&(c.map.prototype.exportKey="name");c.mapbubble&&(c.mapbubble.prototype.exportKey="name");c.treemap&&(c.treemap.prototype.exportKey="name")});k(a,"masters/modules/export-data.src.js",[],function(){})});
//# sourceMappingURL=export-data.js.map