/*
 Highcharts JS v8.2.2 (2020-12-12)

 Highcharts funnel module

 (c) 2010-2019 Kacper Madej

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/funnel3d",["highcharts","highcharts/highcharts-3d","highcharts/modules/cylinder"],function(k){a(k);a.Highcharts=k;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function k(a,f,l,b){a.hasOwnProperty(f)||(a[f]=b.apply(null,l))}a=a?a._modules:{};k(a,"Series/Funnel3D/Funnel3DPoint.js",[a["Core/Series/Series.js"],a["Core/Utilities.js"]],
function(a,f){var l=this&&this.__extends||function(){var a=function(b,n){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var h in b)b.hasOwnProperty(h)&&(a[h]=b[h])};return a(b,n)};return function(b,n){function f(){this.constructor=b}a(b,n);b.prototype=null===n?Object.create(n):(f.prototype=n.prototype,new f)}}();f=f.extend;a=function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.dlBoxRaw=void 0;b.options=void 0;b.series=void 0;
b.y=void 0;return b}l(b,a);return b}(a.seriesTypes.column.prototype.pointClass);f(a.prototype,{shapeType:"funnel3d"});return a});k(a,"Series/Funnel3D/Funnel3DComposition.js",[a["Core/Color/Color.js"],a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,f,l){var b=a.parse,k=f.charts;a=f.Renderer.prototype;var n=a.cuboidPath;a=a.elements3d;var w=l.error,x=l.extend,h=l.merge;a.funnel3d=h(a.cuboid,{parts:"top bottom frontUpper backUpper frontLower backLower rightUpper rightLower".split(" "),mainParts:["top",
"bottom"],sideGroups:["upperGroup","lowerGroup"],sideParts:{upperGroup:["frontUpper","backUpper","rightUpper"],lowerGroup:["frontLower","backLower","rightLower"]},pathType:"funnel3d",opacitySetter:function(a){var c=this,d=c.parts,b=f.charts[c.renderer.chartIndex],e="group-opacity-"+a+"-"+b.index;c.parts=c.mainParts;c.singleSetterForParts("opacity",a);c.parts=d;b.renderer.filterId||(b.renderer.definition({tagName:"filter",id:e,children:[{tagName:"feComponentTransfer",children:[{tagName:"feFuncA",type:"table",
tableValues:"0 "+a}]}]}),c.sideGroups.forEach(function(a){c[a].attr({filter:"url(#"+e+")"})}),c.renderer.styledMode&&(b.renderer.definition({tagName:"style",textContent:".highcharts-"+e+" {filter:url(#"+e+")}"}),c.sideGroups.forEach(function(c){c.addClass("highcharts-"+e)})));return c},fillSetter:function(a){var c=this,d=b(a),t=d.rgba[3],e={top:b(a).brighten(.1).get(),bottom:b(a).brighten(-.2).get()};1>t?(d.rgba[3]=1,d=d.get("rgb"),c.attr({opacity:t})):d=a;d.linearGradient||d.radialGradient||!c.gradientForSides||
(d={linearGradient:{x1:0,x2:1,y1:1,y2:1},stops:[[0,b(a).brighten(-.2).get()],[.5,a],[1,b(a).brighten(-.2).get()]]});d.linearGradient?c.sideGroups.forEach(function(a){var b=c[a].gradientBox,p=d.linearGradient,t=h(d,{linearGradient:{x1:b.x+p.x1*b.width,y1:b.y+p.y1*b.height,x2:b.x+p.x2*b.width,y2:b.y+p.y2*b.height}});c.sideParts[a].forEach(function(a){e[a]=t})}):(h(!0,e,{frontUpper:d,backUpper:d,rightUpper:d,frontLower:d,backLower:d,rightLower:d}),d.radialGradient&&c.sideGroups.forEach(function(a){var d=
c[a].gradientBox,b=d.x+d.width/2,e=d.y+d.height/2,H=Math.min(d.width,d.height);c.sideParts[a].forEach(function(a){c[a].setRadialReference([b,e,H])})}));c.singleSetterForParts("fill",null,e);c.color=c.fill=a;d.linearGradient&&[c.frontLower,c.frontUpper].forEach(function(a){(a=(a=a.element)&&c.renderer.gradients[a.gradient])&&"userSpaceOnUse"!==a.attr("gradientUnits")&&a.attr({gradientUnits:"userSpaceOnUse"})});return c},adjustForGradient:function(){var a=this,c;a.sideGroups.forEach(function(d){var b=
{x:Number.MAX_VALUE,y:Number.MAX_VALUE},e={x:-Number.MAX_VALUE,y:-Number.MAX_VALUE};a.sideParts[d].forEach(function(d){c=a[d].getBBox(!0);b={x:Math.min(b.x,c.x),y:Math.min(b.y,c.y)};e={x:Math.max(e.x,c.x+c.width),y:Math.max(e.y,c.y+c.height)}});a[d].gradientBox={x:b.x,width:e.x-b.x,y:b.y,height:e.y-b.y}})},zIndexSetter:function(){this.finishedOnAdd&&this.adjustForGradient();return this.renderer.Element.prototype.zIndexSetter.apply(this,arguments)},onAdd:function(){this.adjustForGradient();this.finishedOnAdd=
!0}});x(f.Renderer.prototype,{funnel3d:function(a){var c=this.element3d("funnel3d",a),d=this.styledMode,b={"stroke-width":1,stroke:"none"};c.upperGroup=this.g("funnel3d-upper-group").attr({zIndex:c.frontUpper.zIndex}).add(c);[c.frontUpper,c.backUpper,c.rightUpper].forEach(function(a){d||a.attr(b);a.add(c.upperGroup)});c.lowerGroup=this.g("funnel3d-lower-group").attr({zIndex:c.frontLower.zIndex}).add(c);[c.frontLower,c.backLower,c.rightLower].forEach(function(a){d||a.attr(b);a.add(c.lowerGroup)});
c.gradientForSides=a.gradientForSides;return c},funnel3dPath:function(a){this.getCylinderEnd||w("A required Highcharts module is missing: cylinder.js",!0,k[this.chartIndex]);var c=k[this.chartIndex],b=a.alphaCorrection=90-Math.abs(c.options.chart.options3d.alpha%180-90),d=n.call(this,h(a,{depth:a.width,width:(a.width+a.bottom.width)/2})),e=d.isTop,f=!d.isFront,z=!!a.middle,p=this.getCylinderEnd(c,h(a,{x:a.x-a.width/2,z:a.z-a.width/2,alphaCorrection:b})),D=a.bottom.width,H=h(a,{width:D,x:a.x-D/2,z:a.z-
D/2,alphaCorrection:b}),I=this.getCylinderEnd(c,H,!0),y=D,r=H,l=I,g=I;z&&(y=a.middle.width,r=h(a,{y:a.y+a.middle.fraction*a.height,width:y,x:a.x-y/2,z:a.z-y/2}),l=this.getCylinderEnd(c,r,!1),g=this.getCylinderEnd(c,r,!1));d={top:p,bottom:I,frontUpper:this.getCylinderFront(p,l),zIndexes:{group:d.zIndexes.group,top:0!==e?0:3,bottom:1!==e?0:3,frontUpper:f?2:1,backUpper:f?1:2,rightUpper:f?2:1}};d.backUpper=this.getCylinderBack(p,l);p=1!==Math.min(y,a.width)/Math.max(y,a.width);d.rightUpper=this.getCylinderFront(this.getCylinderEnd(c,
h(a,{x:a.x-a.width/2,z:a.z-a.width/2,alphaCorrection:p?-b:0}),!1),this.getCylinderEnd(c,h(r,{alphaCorrection:p?-b:0}),!z));z&&(p=1!==Math.min(y,D)/Math.max(y,D),h(!0,d,{frontLower:this.getCylinderFront(g,I),backLower:this.getCylinderBack(g,I),rightLower:this.getCylinderFront(this.getCylinderEnd(c,h(H,{alphaCorrection:p?-b:0}),!0),this.getCylinderEnd(c,h(r,{alphaCorrection:p?-b:0}),!1)),zIndexes:{frontLower:f?2:1,backLower:f?1:2,rightLower:f?1:2}}));return d}})});k(a,"Series/Funnel3D/Funnel3DSeries.js",
[a["Core/Series/Series.js"],a["Series/Funnel3D/Funnel3DPoint.js"],a["Core/Globals.js"],a["Extensions/Math3D.js"],a["Core/Utilities.js"]],function(a,f,l,b,k){var n=this&&this.__extends||function(){var a=function(c,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(c,b)};return function(c,b){function d(){this.constructor=c}a(c,b);c.prototype=null===b?Object.create(b):(d.prototype=b.prototype,
new d)}}(),w=a.seriesTypes,x=w.column,h=w.line;l=l.noop;var d=b.perspective,c=k.extend,N=k.merge,t=k.pick,e=k.relativeLength;b=function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.center=void 0;b.data=void 0;b.options=void 0;b.points=void 0;return b}n(b,a);b.prototype.alignDataLabel=function(a,b,c){var d=a.dlBoxRaw,e=this.chart.inverted,f=a.plotY>t(this.translatedThreshold,this.yAxis.len),h=t(c.inside,!!this.options.stacking),g={x:d.x,y:d.y,height:0};c.align=t(c.align,!e||h?"center":
f?"right":"left");c.verticalAlign=t(c.verticalAlign,e||h?"middle":f?"top":"bottom");"top"!==c.verticalAlign&&(g.y+=d.bottom/("bottom"===c.verticalAlign?1:2));g.width=this.getWidthAt(g.y);this.options.reversed&&(g.width=d.fullWidth-g.width);h?g.x-=g.width/2:"left"===c.align?(c.align="right",g.x-=1.5*g.width):"right"===c.align?(c.align="left",g.x+=g.width/2):g.x-=g.width/2;a.dlBox=g;x.prototype.alignDataLabel.apply(this,arguments)};b.prototype.bindAxes=function(){h.prototype.bindAxes.apply(this,arguments);
c(this.xAxis.options,{gridLineWidth:0,lineWidth:0,title:null,tickPositions:[]});c(this.yAxis.options,{gridLineWidth:0,title:null,labels:{enabled:!1}})};b.prototype.translate=function(){h.prototype.translate.apply(this,arguments);var a=0,b=this.chart,f=this.options,k=f.reversed,l=f.ignoreHiddenPoint,r=b.plotWidth,n=b.plotHeight,g=0,x=f.center,E=e(x[0],r),F=e(x[1],n),w=e(f.width,r),u,A,q=e(f.height,n),z=e(f.neckWidth,r),K=e(f.neckHeight,n),G=F-q/2+q-K;r=this.data;var B,L,v,C,M,J,m;this.getWidthAt=A=
function(a){var b=F-q/2;return a>G||q===K?z:z+(w-z)*(1-(a-b)/(q-K))};this.center=[E,F,q];this.centerX=E;r.forEach(function(b){l&&!1===b.visible||(a+=b.y)});r.forEach(function(e){M=null;B=a?e.y/a:0;v=F-q/2+g*q;C=v+B*q;u=A(v);J=C-v;m={gradientForSides:t(e.options.gradientForSides,f.gradientForSides),x:E,y:v,height:J,width:u,z:1,top:{width:u}};u=A(C);m.bottom={fraction:B,width:u};v>=G?m.isCylinder=!0:C>G&&(M=C,u=A(G),C=G,m.bottom.width=u,m.middle={fraction:J?(G-v)/J:0,width:u});k&&(m.y=v=F+q/2-(g+B)*
q,m.middle&&(m.middle.fraction=1-(J?m.middle.fraction:0)),u=m.width,m.width=m.bottom.width,m.bottom.width=u);e.shapeArgs=c(e.shapeArgs,m);e.percentage=100*B;e.plotX=E;e.plotY=k?F+q/2-(g+B/2)*q:(v+(M||C))/2;L=d([{x:E,y:e.plotY,z:k?-(w-A(e.plotY))/2:-A(e.plotY)/2}],b,!0)[0];e.tooltipPos=[L.x,L.y];e.dlBoxRaw={x:E,width:A(e.plotY),y:v,bottom:m.height,fullWidth:w};l&&!1===e.visible||(g+=B)})};b.defaultOptions=N(x.defaultOptions,{center:["50%","50%"],width:"90%",neckWidth:"30%",height:"100%",neckHeight:"25%",
reversed:!1,gradientForSides:!0,animation:!1,edgeWidth:0,colorByPoint:!0,showInLegend:!1,dataLabels:{align:"right",crop:!1,inside:!1,overflow:"allow"}});return b}(x);c(b.prototype,{pointClass:f,translate3dShapes:l});a.registerSeriesType("funnel3d",b);"";return b});k(a,"masters/modules/funnel3d.src.js",[],function(){})});
//# sourceMappingURL=funnel3d.js.map