/*
 Highcharts JS v8.2.2 (2020-12-12)

 Highcharts funnel module

 (c) 2010-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/funnel",["highcharts"],function(f){a(f);a.Highcharts=f;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function f(a,D,m,f){a.hasOwnProperty(D)||(a[D]=f.apply(null,m))}a=a?a._modules:{};f(a,"Series/Funnel/FunnelSeries.js",[a["Core/Series/Series.js"],a["Core/Chart/Chart.js"],a["Core/Globals.js"],a["Core/Color/Palette.js"],
a["Core/Utilities.js"]],function(a,f,m,x,d){var E=this&&this.__extends||function(){var a=function(b,e){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(e,a){e.__proto__=a}||function(e,a){for(var l in a)a.hasOwnProperty(l)&&(e[l]=a[l])};return a(b,e)};return function(b,e){function t(){this.constructor=b}a(b,e);b.prototype=null===e?Object.create(e):(t.prototype=e.prototype,new t)}}(),c=a.seriesTypes,y=c.line,F=c.pie,K=m.noop;m=d.addEvent;c=d.extend;var D=d.fireEvent,J=d.isArray,M=d.merge,
L=d.pick;d=function(c){function b(){var e=null!==c&&c.apply(this,arguments)||this;e.data=void 0;e.options=void 0;e.points=void 0;return e}E(b,c);b.prototype.alignDataLabel=function(e,a,l,b,h){var c=e.series;b=c.options.reversed;var g=e.dlBox||e.shapeArgs,d=l.align,t=l.verticalAlign,f=((c.options||{}).dataLabels||{}).inside,k=c.center[1];c=c.getWidthAt((b?2*k-e.plotY:e.plotY)-g.height/2+a.height);c="middle"===t?(g.topWidth-g.bottomWidth)/4:(c-g.bottomWidth)/2;k=g.y;var n=g.x;"middle"===t?k=g.y-g.height/
2+a.height/2:"top"===t&&(k=g.y-g.height+a.height+l.padding);if("top"===t&&!b||"bottom"===t&&b||"middle"===t)"right"===d?n=g.x-l.padding+c:"left"===d&&(n=g.x+l.padding-c);b={x:n,y:b?k-g.height:k,width:g.bottomWidth,height:g.height};l.verticalAlign="bottom";f&&!e.visible||y.prototype.alignDataLabel.call(this,e,a,l,b,h);f&&(!e.visible&&e.dataLabel&&(e.dataLabel.placed=!1),e.contrastColor&&a.css({color:e.contrastColor}))};b.prototype.drawDataLabels=function(){var e=this.data,c=this.options.dataLabels.distance,
l,b=e.length;for(this.center[2]-=2*c;b--;){var h=e[b];var d=(l=h.half)?1:-1;var g=h.plotY;h.labelDistance=L(h.options.dataLabels&&h.options.dataLabels.distance,c);this.maxLabelDistance=Math.max(h.labelDistance,this.maxLabelDistance||0);var f=this.getX(g,l,h);h.labelPosition={natural:{x:0,y:g},"final":{},alignment:l?"right":"left",connectorPosition:{breakAt:{x:f+(h.labelDistance-5)*d,y:g},touchingSliceAt:{x:f+h.labelDistance*d,y:g}}}}a.seriesTypes[this.options.dataLabels.inside?"column":"pie"].prototype.drawDataLabels.call(this)};
b.prototype.translate=function(){function a(a,b){return/%$/.test(a)?b*parseInt(a,10)/100:parseInt(a,10)}var c=0,b=this,d=b.chart,h=b.options,f=h.reversed,g=h.ignoreHiddenPoint,y=d.plotWidth;d=d.plotHeight;var m=0,E=h.center,k=a(E[0],y),n=a(E[1],d),F=a(h.width,y),u,v=a(h.height,d),A=a(h.neckWidth,y),x=a(h.neckHeight,d),B=n-v/2+v-x;y=b.data;var G,H,J="left"===h.dataLabels.position?1:0,C,p,I,w,q,z,r;b.getWidthAt=function(a){var b=n-v/2;return a>B||v===x?A:A+(F-A)*(1-(a-b)/(v-x))};b.getX=function(a,c,
e){return k+(c?-1:1)*(b.getWidthAt(f?2*n-a:a)/2+e.labelDistance)};b.center=[k,n,v];b.centerX=k;y.forEach(function(a){g&&!1===a.visible||(c+=a.y)});y.forEach(function(a){r=null;H=c?a.y/c:0;p=n-v/2+m*v;q=p+H*v;u=b.getWidthAt(p);C=k-u/2;I=C+u;u=b.getWidthAt(q);w=k-u/2;z=w+u;p>B?(C=w=k-A/2,I=z=k+A/2):q>B&&(r=q,u=b.getWidthAt(B),w=k-u/2,z=w+u,q=B);f&&(p=2*n-p,q=2*n-q,null!==r&&(r=2*n-r));G=[["M",C,p],["L",I,p],["L",z,q]];null!==r&&G.push(["L",z,r],["L",w,r]);G.push(["L",w,q],["Z"]);a.shapeType="path";
a.shapeArgs={d:G};a.percentage=100*H;a.plotX=k;a.plotY=(p+(r||q))/2;a.tooltipPos=[k,a.plotY];a.dlBox={x:w,y:p,topWidth:I-C,bottomWidth:z-w,height:Math.abs(L(r,q)-p),width:NaN};a.slice=K;a.half=J;g&&!1===a.visible||(m+=H)});D(b,"afterTranslate")};b.prototype.sortByAngle=function(a){a.sort(function(a,b){return a.plotY-b.plotY})};b.defaultOptions=M(F.defaultOptions,{animation:!1,center:["50%","50%"],width:"90%",neckWidth:"30%",height:"100%",neckHeight:"25%",reversed:!1,size:!0,dataLabels:{connectorWidth:1,
verticalAlign:"middle"},states:{select:{color:x.neutralColor20,borderColor:x.neutralColor100}}});return b}(F);c(d.prototype,{animate:K});m(f,"afterHideAllOverlappingLabels",function(){this.series.forEach(function(a){var b=a.options&&a.options.dataLabels;J(b)&&(b=b[0]);a.is("pie")&&a.placeDataLabels&&b&&!b.inside&&a.placeDataLabels()})});a.registerSeriesType("funnel",d);"";return d});f(a,"Series/Pyramid/PyramidSeries.js",[a["Core/Series/Series.js"],a["Series/Funnel/FunnelSeries.js"],a["Core/Utilities.js"]],
function(a,f,m){var x=this&&this.__extends||function(){var a=function(c,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var d in c)c.hasOwnProperty(d)&&(a[d]=c[d])};return a(c,d)};return function(c,d){function f(){this.constructor=c}a(c,d);c.prototype=null===d?Object.create(d):(f.prototype=d.prototype,new f)}}(),d=m.merge;m=function(a){function c(){var c=null!==a&&a.apply(this,arguments)||this;c.data=void 0;c.options=void 0;c.points=void 0;
return c}x(c,a);c.defaultOptions=d(f.defaultOptions,{neckWidth:"0%",neckHeight:"0%",reversed:!0});return c}(f);a.registerSeriesType("pyramid",m);"";return m});f(a,"masters/modules/funnel.src.js",[],function(){})});
//# sourceMappingURL=funnel.js.map