/*
 Highmaps JS v8.2.2 (2020-12-12)

 (c) 2009-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/heatmap",["highcharts"],function(q){a(q);a.Highcharts=q;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function q(a,d,k,u){a.hasOwnProperty(d)||(a[d]=u.apply(null,k))}a=a?a._modules:{};q(a,"Mixins/ColorSeries.js",[],function(){return{colorPointMixin:{setVisible:function(a){var d=this,k=a?"show":"hide";d.visible=d.options.visible=
!!a;["graphic","dataLabel"].forEach(function(a){if(d[a])d[a][k]()});this.series.buildKDTree()}},colorSeriesMixin:{optionalAxis:"colorAxis",colorAxis:0,translateColors:function(){var a=this,d=this.options.nullColor,k=this.colorAxis,u=this.colorKey;(this.data.length?this.data:this.points).forEach(function(n){var r=n.getNestedProperty(u);(r=n.options.color||(n.isNull||null===n.value?d:k&&"undefined"!==typeof r?k.toColor(r,n):n.color||a.color))&&n.color!==r&&(n.color=r,"point"===a.options.legendType&&
n.legendItem&&a.chart.legend.colorizeItem(n,n.visible))})}}}});q(a,"Core/Axis/ColorAxis.js",[a["Core/Axis/Axis.js"],a["Core/Chart/Chart.js"],a["Core/Color/Color.js"],a["Mixins/ColorSeries.js"],a["Core/Animation/Fx.js"],a["Core/Globals.js"],a["Core/Legend.js"],a["Mixins/LegendSymbol.js"],a["Series/Line/LineSeries.js"],a["Core/Color/Palette.js"],a["Core/Series/Point.js"],a["Core/Utilities.js"]],function(a,d,k,u,n,r,z,A,B,f,y,v){var H=this&&this.__extends||function(){var c=function(b,e){c=Object.setPrototypeOf||
{__proto__:[]}instanceof Array&&function(e,g){e.__proto__=g}||function(e,g){for(var h in g)g.hasOwnProperty(h)&&(e[h]=g[h])};return c(b,e)};return function(b,e){function h(){this.constructor=b}c(b,e);b.prototype=null===e?Object.create(e):(h.prototype=e.prototype,new h)}}(),p=k.parse;k=u.colorPointMixin;u=u.colorSeriesMixin;var D=r.noop,w=v.addEvent,C=v.erase,t=v.extend,F=v.isNumber,G=v.merge,x=v.pick,c=v.splat;"";t(B.prototype,u);t(y.prototype,k);d.prototype.collectionsWithUpdate.push("colorAxis");
d.prototype.collectionsWithInit.colorAxis=[d.prototype.addColorAxis];var l=function(c){function b(e,h){var g=c.call(this,e,h)||this;g.beforePadding=!1;g.chart=void 0;g.coll="colorAxis";g.dataClasses=void 0;g.legendItem=void 0;g.legendItems=void 0;g.name="";g.options=void 0;g.stops=void 0;g.visible=!0;g.init(e,h);return g}H(b,c);b.buildOptions=function(e,h,g){e=e.options.legend||{};var c=g.layout?"vertical"!==g.layout:"vertical"!==e.layout;return G(h,{side:c?2:1,reversed:!c},g,{opposite:!c,showEmpty:!1,
title:null,visible:e.enabled&&(g?!1!==g.visible:!0)})};b.prototype.init=function(e,h){var g=b.buildOptions(e,b.defaultOptions,h);this.coll="colorAxis";c.prototype.init.call(this,e,g);h.dataClasses&&this.initDataClasses(h);this.initStops();this.horiz=!g.opposite;this.zoomEnabled=!1};b.prototype.initDataClasses=function(e){var h=this.chart,g,c=0,b=h.options.chart.colorCount,a=this.options,f=e.dataClasses.length;this.dataClasses=g=[];this.legendItems=[];e.dataClasses.forEach(function(e,E){e=G(e);g.push(e);
if(h.styledMode||!e.color)"category"===a.dataClassColor?(h.styledMode||(E=h.options.colors,b=E.length,e.color=E[c]),e.colorIndex=c,c++,c===b&&(c=0)):e.color=p(a.minColor).tweenTo(p(a.maxColor),2>f?.5:E/(f-1))})};b.prototype.hasData=function(){return!!(this.tickPositions||[]).length};b.prototype.setTickPositions=function(){if(!this.dataClasses)return c.prototype.setTickPositions.call(this)};b.prototype.initStops=function(){this.stops=this.options.stops||[[0,this.options.minColor],[1,this.options.maxColor]];
this.stops.forEach(function(e){e.color=p(e[1])})};b.prototype.setOptions=function(e){c.prototype.setOptions.call(this,e);this.options.crosshair=this.options.marker};b.prototype.setAxisSize=function(){var e=this.legendSymbol,h=this.chart,g=h.options.legend||{},c,a;e?(this.left=g=e.attr("x"),this.top=c=e.attr("y"),this.width=a=e.attr("width"),this.height=e=e.attr("height"),this.right=h.chartWidth-g-a,this.bottom=h.chartHeight-c-e,this.len=this.horiz?a:e,this.pos=this.horiz?g:c):this.len=(this.horiz?
g.symbolWidth:g.symbolHeight)||b.defaultLegendLength};b.prototype.normalizedValue=function(e){this.logarithmic&&(e=this.logarithmic.log2lin(e));return 1-(this.max-e)/(this.max-this.min||1)};b.prototype.toColor=function(e,h){var g=this.dataClasses,c=this.stops,b;if(g)for(b=g.length;b--;){var a=g[b];var f=a.from;c=a.to;if(("undefined"===typeof f||e>=f)&&("undefined"===typeof c||e<=c)){var m=a.color;h&&(h.dataClass=b,h.colorIndex=a.colorIndex);break}}else{e=this.normalizedValue(e);for(b=c.length;b--&&
!(e>c[b][0]););f=c[b]||c[b+1];c=c[b+1]||f;e=1-(c[0]-e)/(c[0]-f[0]||1);m=f.color.tweenTo(c.color,e)}return m};b.prototype.getOffset=function(){var e=this.legendGroup,h=this.chart.axisOffset[this.side];e&&(this.axisParent=e,c.prototype.getOffset.call(this),this.added||(this.added=!0,this.labelLeft=0,this.labelRight=this.width),this.chart.axisOffset[this.side]=h)};b.prototype.setLegendColor=function(){var e=this.reversed,h=e?1:0;e=e?0:1;h=this.horiz?[h,0,e,0]:[0,e,0,h];this.legendColor={linearGradient:{x1:h[0],
y1:h[1],x2:h[2],y2:h[3]},stops:this.stops}};b.prototype.drawLegendSymbol=function(e,h){var c=e.padding,a=e.options,f=this.horiz,m=x(a.symbolWidth,f?b.defaultLegendLength:12),l=x(a.symbolHeight,f?12:b.defaultLegendLength),d=x(a.labelPadding,f?16:30);a=x(a.itemDistance,10);this.setLegendColor();h.legendSymbol=this.chart.renderer.rect(0,e.baseline-11,m,l).attr({zIndex:1}).add(h.legendGroup);this.legendItemWidth=m+c+(f?a:d);this.legendItemHeight=l+c+(f?d:0)};b.prototype.setState=function(e){this.series.forEach(function(c){c.setState(e)})};
b.prototype.setVisible=function(){};b.prototype.getSeriesExtremes=function(){var e=this.series,c=e.length,g;this.dataMin=Infinity;for(this.dataMax=-Infinity;c--;){var b=e[c];var a=b.colorKey=x(b.options.colorKey,b.colorKey,b.pointValKey,b.zoneAxis,"y");var f=b.pointArrayMap;var m=b[a+"Min"]&&b[a+"Max"];if(b[a+"Data"])var l=b[a+"Data"];else if(f){l=[];f=f.indexOf(a);var d=b.yData;if(0<=f&&d)for(g=0;g<d.length;g++)l.push(x(d[g][f],d[g]))}else l=b.yData;m?(b.minColorValue=b[a+"Min"],b.maxColorValue=
b[a+"Max"]):(l=B.prototype.getExtremes.call(b,l),b.minColorValue=l.dataMin,b.maxColorValue=l.dataMax);"undefined"!==typeof b.minColorValue&&(this.dataMin=Math.min(this.dataMin,b.minColorValue),this.dataMax=Math.max(this.dataMax,b.maxColorValue));m||B.prototype.applyExtremes.call(b)}};b.prototype.drawCrosshair=function(e,b){var g=b&&b.plotX,h=b&&b.plotY,a=this.pos,f=this.len;if(b){var m=this.toPixels(b.getNestedProperty(b.series.colorKey));m<a?m=a-2:m>a+f&&(m=a+f+2);b.plotX=m;b.plotY=this.len-m;c.prototype.drawCrosshair.call(this,
e,b);b.plotX=g;b.plotY=h;this.cross&&!this.cross.addedToColorAxis&&this.legendGroup&&(this.cross.addClass("highcharts-coloraxis-marker").add(this.legendGroup),this.cross.addedToColorAxis=!0,!this.chart.styledMode&&this.crosshair&&this.cross.attr({fill:this.crosshair.color}))}};b.prototype.getPlotLinePath=function(e){var b=this.left,g=e.translatedValue,a=this.top;return F(g)?this.horiz?[["M",g-4,a-6],["L",g+4,a-6],["L",g,a],["Z"]]:[["M",b,g],["L",b-6,g+6],["L",b-6,g-6],["Z"]]:c.prototype.getPlotLinePath.call(this,
e)};b.prototype.update=function(e,a){var g=this.chart,h=g.legend,f=b.buildOptions(g,{},e);this.series.forEach(function(b){b.isDirtyData=!0});(e.dataClasses&&h.allItems||this.dataClasses)&&this.destroyItems();g.options[this.coll]=G(this.userOptions,f);c.prototype.update.call(this,f,a);this.legendItem&&(this.setLegendColor(),h.colorizeItem(this,!0))};b.prototype.destroyItems=function(){var b=this.chart;this.legendItem?b.legend.destroyItem(this):this.legendItems&&this.legendItems.forEach(function(e){b.legend.destroyItem(e)});
b.isDirtyLegend=!0};b.prototype.remove=function(b){this.destroyItems();c.prototype.remove.call(this,b)};b.prototype.getDataClassLegendSymbols=function(){var b=this,c=b.chart,a=b.legendItems,f=c.options.legend,m=f.valueDecimals,l=f.valueSuffix||"",d;a.length||b.dataClasses.forEach(function(e,g){var h=!0,f=e.from,x=e.to,y=c.numberFormatter;d="";"undefined"===typeof f?d="< ":"undefined"===typeof x&&(d="> ");"undefined"!==typeof f&&(d+=y(f,m)+l);"undefined"!==typeof f&&"undefined"!==typeof x&&(d+=" - ");
"undefined"!==typeof x&&(d+=y(x,m)+l);a.push(t({chart:c,name:d,options:{},drawLegendSymbol:A.drawRectangle,visible:!0,setState:D,isDataClass:!0,setVisible:function(){h=b.visible=!h;b.series.forEach(function(b){b.points.forEach(function(b){b.dataClass===g&&b.setVisible(h)})});c.legend.colorizeItem(this,h)}},e))});return a};b.defaultLegendLength=200;b.defaultOptions={lineWidth:0,minPadding:0,maxPadding:0,gridLineWidth:1,tickPixelInterval:72,startOnTick:!0,endOnTick:!0,offset:0,marker:{animation:{duration:50},
width:.01,color:f.neutralColor40},labels:{overflow:"justify",rotation:0},minColor:f.highlightColor10,maxColor:f.highlightColor100,tickLength:5,showInLegend:!0};b.keepProps=["legendGroup","legendItemHeight","legendItemWidth","legendItem","legendSymbol"];return b}(a);Array.prototype.push.apply(a.keepProps,l.keepProps);r.ColorAxis=l;["fill","stroke"].forEach(function(c){n.prototype[c+"Setter"]=function(){this.elem.attr(c,p(this.start).tweenTo(p(this.end),this.pos),null,!0)}});w(d,"afterGetAxes",function(){var a=
this,b=a.options;this.colorAxis=[];b.colorAxis&&(b.colorAxis=c(b.colorAxis),b.colorAxis.forEach(function(b,c){b.index=c;new l(a,b)}))});w(B,"bindAxes",function(){var c=this.axisTypes;c?-1===c.indexOf("colorAxis")&&c.push("colorAxis"):this.axisTypes=["colorAxis"]});w(z,"afterGetAllItems",function(c){var b=[],e,a;(this.chart.colorAxis||[]).forEach(function(a){(e=a.options)&&e.showInLegend&&(e.dataClasses&&e.visible?b=b.concat(a.getDataClassLegendSymbols()):e.visible&&b.push(a),a.series.forEach(function(b){if(!b.options.showInLegend||
e.dataClasses)"point"===b.options.legendType?b.points.forEach(function(b){C(c.allItems,b)}):C(c.allItems,b)}))});for(a=b.length;a--;)c.allItems.unshift(b[a])});w(z,"afterColorizeItem",function(c){c.visible&&c.item.legendColor&&c.item.legendSymbol.attr({fill:c.item.legendColor})});w(z,"afterUpdate",function(){var c=this.chart.colorAxis;c&&c.forEach(function(b,c,a){b.update({},a)})});w(B,"afterTranslate",function(){(this.chart.colorAxis&&this.chart.colorAxis.length||this.colorAttribs)&&this.translateColors()});
return l});q(a,"Mixins/ColorMapSeries.js",[a["Core/Globals.js"],a["Core/Series/Point.js"],a["Core/Utilities.js"]],function(a,d,k){var u=k.defined;return{colorMapPointMixin:{dataLabelOnNull:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==this.value},setState:function(a){d.prototype.setState.call(this,a);this.graphic&&this.graphic.attr({zIndex:"hover"===a?1:0})}},colorMapSeriesMixin:{pointArrayMap:["value"],axisTypes:["xAxis","yAxis","colorAxis"],trackerGroups:["group",
"markerGroup","dataLabelsGroup"],getSymbol:a.noop,parallelArrays:["x","y","value"],colorKey:"value",pointAttribs:a.seriesTypes.column.prototype.pointAttribs,colorAttribs:function(a){var d={};u(a.color)&&(d[this.colorProp||"fill"]=a.color);return d}}}});q(a,"Series/Heatmap/HeatmapPoint.js",[a["Core/Series/Series.js"],a["Mixins/ColorMapSeries.js"],a["Core/Utilities.js"]],function(a,d,k){var u=this&&this.__extends||function(){var a=function(d,f){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&
function(a,f){a.__proto__=f}||function(a,f){for(var d in f)f.hasOwnProperty(d)&&(a[d]=f[d])};return a(d,f)};return function(d,f){function y(){this.constructor=d}a(d,f);d.prototype=null===f?Object.create(f):(y.prototype=f.prototype,new y)}}();d=d.colorMapPointMixin;var n=k.clamp,r=k.extend,z=k.pick;a=function(a){function d(){var f=null!==a&&a.apply(this,arguments)||this;f.options=void 0;f.series=void 0;f.value=void 0;f.x=void 0;f.y=void 0;return f}u(d,a);d.prototype.applyOptions=function(f,d){f=a.prototype.applyOptions.call(this,
f,d);f.formatPrefix=f.isNull||null===f.value?"null":"point";return f};d.prototype.getCellAttributes=function(){var a=this.series,d=a.options,k=(d.colsize||1)/2,u=(d.rowsize||1)/2,p=a.xAxis,r=a.yAxis,w=this.options.marker||a.options.marker;a=a.pointPlacementToXValue();var q=z(this.pointPadding,d.pointPadding,0),t={x1:n(Math.round(p.len-(p.translate(this.x-k,!1,!0,!1,!0,-a)||0)),-p.len,2*p.len),x2:n(Math.round(p.len-(p.translate(this.x+k,!1,!0,!1,!0,-a)||0)),-p.len,2*p.len),y1:n(Math.round(r.translate(this.y-
u,!1,!0,!1,!0)||0),-r.len,2*r.len),y2:n(Math.round(r.translate(this.y+u,!1,!0,!1,!0)||0),-r.len,2*r.len)};[["width","x"],["height","y"]].forEach(function(a){var f=a[0];a=a[1];var d=a+"1",c=a+"2",l=Math.abs(t[d]-t[c]),m=w&&w.lineWidth||0,b=Math.abs(t[d]+t[c])/2;w[f]&&w[f]<l&&(t[d]=b-w[f]/2-m/2,t[c]=b+w[f]/2+m/2);q&&("y"===a&&(d=c,c=a+"1"),t[d]+=q,t[c]-=q)});return t};d.prototype.haloPath=function(a){if(!a)return[];var d=this.shapeArgs;return["M",d.x-a,d.y-a,"L",d.x-a,d.y+d.height+a,d.x+d.width+a,d.y+
d.height+a,d.x+d.width+a,d.y-a,"Z"]};d.prototype.isValid=function(){return Infinity!==this.value&&-Infinity!==this.value};return d}(a.seriesTypes.scatter.prototype.pointClass);r(a.prototype,{dataLabelOnNull:d.dataLabelOnNull,setState:d.setState});return a});q(a,"Series/Heatmap/HeatmapSeries.js",[a["Core/Series/Series.js"],a["Mixins/ColorMapSeries.js"],a["Core/Globals.js"],a["Series/Heatmap/HeatmapPoint.js"],a["Mixins/LegendSymbol.js"],a["Core/Color/Palette.js"],a["Core/Renderer/SVG/SVGRenderer.js"],
a["Core/Utilities.js"]],function(a,d,k,u,n,r,q,A){var B=this&&this.__extends||function(){var a=function(d,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(d,c)};return function(d,c){function f(){this.constructor=d}a(d,c);d.prototype=null===c?Object.create(c):(f.prototype=c.prototype,new f)}}(),f=a.seriesTypes,y=f.column,v=f.line,z=f.scatter;d=d.colorMapSeriesMixin;f=k.noop;var p=q.prototype.symbols,
D=A.extend,w=A.fireEvent,C=A.isNumber,t=A.merge,F=A.pick;q=function(a){function d(){var c=null!==a&&a.apply(this,arguments)||this;c.colorAxis=void 0;c.data=void 0;c.options=void 0;c.points=void 0;c.valueMax=NaN;c.valueMin=NaN;return c}B(d,a);d.prototype.drawPoints=function(){var a=this;if((this.options.marker||{}).enabled||this._hasPointMarkers)v.prototype.drawPoints.call(this),this.points.forEach(function(c){c.graphic&&c.graphic[a.chart.styledMode?"css":"animate"](a.colorAttribs(c))})};d.prototype.getExtremes=
function(){var a=v.prototype.getExtremes.call(this,this.valueData),d=a.dataMin;a=a.dataMax;C(d)&&(this.valueMin=d);C(a)&&(this.valueMax=a);return v.prototype.getExtremes.call(this)};d.prototype.getValidPoints=function(a,d){return v.prototype.getValidPoints.call(this,a,d,!0)};d.prototype.hasData=function(){return!!this.processedXData.length};d.prototype.init=function(){v.prototype.init.apply(this,arguments);var a=this.options;a.pointRange=F(a.pointRange,a.colsize||1);this.yAxis.axisPointRange=a.rowsize||
1;D(p,{ellipse:p.circle,rect:p.square})};d.prototype.markerAttribs=function(a,d){var c=a.marker||{},b=this.options.marker||{},e=a.shapeArgs||{},f={};if(a.hasImage)return{x:a.plotX,y:a.plotY};if(d){var g=b.states[d]||{};var l=c.states&&c.states[d]||{};[["width","x"],["height","y"]].forEach(function(a){f[a[0]]=(l[a[0]]||g[a[0]]||e[a[0]])+(l[a[0]+"Plus"]||g[a[0]+"Plus"]||0);f[a[1]]=e[a[1]]+(e[a[0]]-f[a[0]])/2})}return d?f:e};d.prototype.pointAttribs=function(a,d){var c=v.prototype.pointAttribs.call(this,
a,d),b=this.options||{},e=this.chart.options.plotOptions||{},f=e.series||{},g=e.heatmap||{};e=b.borderColor||g.borderColor||f.borderColor;f=b.borderWidth||g.borderWidth||f.borderWidth||c["stroke-width"];c.stroke=a&&a.marker&&a.marker.lineColor||b.marker&&b.marker.lineColor||e||this.color;c["stroke-width"]=f;d&&(a=t(b.states[d],b.marker&&b.marker.states[d],a&&a.options.states&&a.options.states[d]||{}),d=a.brightness,c.fill=a.color||k.color(c.fill).brighten(d||0).get(),c.stroke=a.lineColor);return c};
d.prototype.setClip=function(a){var d=this.chart;v.prototype.setClip.apply(this,arguments);(!1!==this.options.clip||a)&&this.markerGroup.clip((a||this.clipBox)&&this.sharedClipKey?d[this.sharedClipKey]:d.clipRect)};d.prototype.translate=function(){var a=this.options,d=a.marker&&a.marker.symbol||"",f=p[d]?d:"rect";a=this.options;var b=-1!==["circle","square"].indexOf(f);this.generatePoints();this.points.forEach(function(a){var c=a.getCellAttributes(),e={x:Math.min(c.x1,c.x2),y:Math.min(c.y1,c.y2),
width:Math.max(Math.abs(c.x2-c.x1),0),height:Math.max(Math.abs(c.y2-c.y1),0)};var l=a.hasImage=0===(a.marker&&a.marker.symbol||d||"").indexOf("url");if(b){var k=Math.abs(e.width-e.height);e.x=Math.min(c.x1,c.x2)+(e.width<e.height?0:k/2);e.y=Math.min(c.y1,c.y2)+(e.width<e.height?k/2:0);e.width=e.height=Math.min(e.width,e.height)}k={plotX:(c.x1+c.x2)/2,plotY:(c.y1+c.y2)/2,clientX:(c.x1+c.x2)/2,shapeType:"path",shapeArgs:t(!0,e,{d:p[f](e.x,e.y,e.width,e.height)})};l&&(a.marker={width:e.width,height:e.height});
D(a,k)});w(this,"afterTranslate")};d.defaultOptions=t(z.defaultOptions,{animation:!1,borderWidth:0,nullColor:r.neutralColor3,dataLabels:{formatter:function(){return this.point.value},inside:!0,verticalAlign:"middle",crop:!1,overflow:!1,padding:0},marker:{symbol:"rect",radius:0,lineColor:void 0,states:{hover:{lineWidthPlus:0},select:{}}},clip:!0,pointRange:null,tooltip:{pointFormat:"{point.x}, {point.y}: {point.value}<br/>"},states:{hover:{halo:!1,brightness:.2}}});return d}(z);D(q.prototype,{alignDataLabel:y.prototype.alignDataLabel,
axisTypes:d.axisTypes,colorAttribs:d.colorAttribs,colorKey:d.colorKey,directTouch:!0,drawLegendSymbol:n.drawRectangle,getBox:f,getExtremesFromAll:!0,getSymbol:v.prototype.getSymbol,hasPointSpecificOptions:!0,parallelArrays:d.parallelArrays,pointArrayMap:["y","value"],pointClass:u,trackerGroups:d.trackerGroups});a.registerSeriesType("heatmap",q);"";"";return q});q(a,"masters/modules/heatmap.src.js",[],function(){})});
//# sourceMappingURL=heatmap.js.map