/*
 Highcharts JS v8.2.2 (2020-12-12)

 Item series type for Highcharts

 (c) 2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/item-series",["highcharts"],function(c){b(c);b.Highcharts=c;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function c(b,f,c,a){b.hasOwnProperty(f)||(b[f]=a.apply(null,c))}b=b?b._modules:{};c(b,"Series/Item/ItemPoint.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,f){var c=this&&this.__extends||function(){var b=
function(a,e){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var e in a)a.hasOwnProperty(e)&&(b[e]=a[e])};return b(a,e)};return function(a,e){function g(){this.constructor=a}b(a,e);a.prototype=null===e?Object.create(e):(g.prototype=e.prototype,new g)}}(),a=b.seriesTypes;b=a.line;f=f.extend;a=function(b){function a(){var a=null!==b&&b.apply(this,arguments)||this;a.graphics=void 0;a.options=void 0;a.series=void 0;return a}c(a,b);return a}(a.pie.prototype.pointClass);
f(a.prototype,{haloPath:b.prototype.pointClass.prototype.haloPath});return a});c(b,"Series/Item/ItemSeries.js",[b["Core/Series/Series.js"],b["Core/Globals.js"],b["Series/Item/ItemPoint.js"],b["Core/Options.js"],b["Core/Utilities.js"]],function(b,c,I,a,g){var f=this&&this.__extends||function(){var b=function(a,d){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,d){b.__proto__=d}||function(b,d){for(var a in d)d.hasOwnProperty(a)&&(b[a]=d[a])};return b(a,d)};return function(a,d){function x(){this.constructor=
a}b(a,d);a.prototype=null===d?Object.create(d):(x.prototype=d.prototype,new x)}}(),e=b.seriesTypes.pie,J=a.defaultOptions,K=g.defined,w=g.extend,L=g.fireEvent,y=g.isNumber,z=g.merge,M=g.objectEach,N=g.pick;a=function(b){function a(){var a=null!==b&&b.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}f(a,b);a.prototype.animate=function(a){a?this.group.attr({opacity:0}):this.group.animate({opacity:1},this.options.animation)};a.prototype.drawDataLabels=function(){this.center&&
this.slots?c.seriesTypes.pie.prototype.drawDataLabels.call(this):this.points.forEach(function(a){a.destroyElements({dataLabel:1})})};a.prototype.drawPoints=function(){var a=this,b=this.options,c=a.chart.renderer,e=b.marker,g=this.borderWidth%2?.5:1,A=0,f=this.getRows(),v=Math.ceil(this.total/f),r=this.chart.plotWidth/v,t=this.chart.plotHeight/f,u=this.itemSize||Math.min(r,t);this.points.forEach(function(d){var n,x,l=d.marker||{},p=l.symbol||e.symbol;l=N(l.radius,e.radius);var E=K(l)?2*l:u,q=E*b.itemPadding,
F;d.graphics=n=d.graphics||{};a.chart.styledMode||(x=a.pointAttribs(d,d.selected&&"select"));if(!d.isNull&&d.visible){d.graphic||(d.graphic=c.g("point").add(a.group));for(var h=0;h<d.y;h++){if(a.center&&a.slots){var m=a.slots.shift();var k=m.x-u/2;m=m.y-u/2}else"horizontal"===b.layout?(k=A%v*r,m=t*Math.floor(A/v)):(k=r*Math.floor(A/f),m=A%f*t);k+=q;m+=q;var O=F=Math.round(E-2*q);a.options.crisp&&(k=Math.round(k)-g,m=Math.round(m)+g);k={x:k,y:m,width:F,height:O};"undefined"!==typeof l&&(k.r=l);n[h]?
n[h].animate(k):n[h]=c.symbol(p,null,null,null,null,{backgroundSize:"within"}).attr(w(k,x)).add(d.graphic);n[h].isActive=!0;A++}}M(n,function(a,b){a.isActive?a.isActive=!1:(a.destroy(),delete n[b])})})};a.prototype.getRows=function(){var a=this.options.rows;if(!a){var b=this.chart.plotWidth/this.chart.plotHeight;a=Math.sqrt(this.total);if(1<b)for(a=Math.ceil(a);0<a;){var c=this.total/a;if(c/a>b)break;a--}else for(a=Math.floor(a);a<this.total;){c=this.total/a;if(c/a<b)break;a++}}return a};a.prototype.getSlots=
function(){function a(a){0<C&&(a.row.colCount--,C--)}for(var b=this.center,c=b[2],e=b[3],f,g=this.slots,w,v,r,t,u,y,n,B,l=0,p,D=this.endAngleRad-this.startAngleRad,q=Number.MAX_VALUE,z,h,m,k=this.options.rows,G=(c-e)/c,H=0===D%(2*Math.PI);q>this.total+(h&&H?h.length:0);)for(z=q,q=g.length=0,h=m,m=[],l++,p=c/l/2,k?(e=(p-k)/p*c,0<=e?p=k:(e=0,G=1)):p=Math.floor(p*G),f=p;0<f;f--)r=(e+f/p*(c-e-l))/2,t=D*r,u=Math.ceil(t/l),m.push({rowRadius:r,rowLength:t,colCount:u}),q+=u+1;if(h){for(var C=z-this.total-
(H?h.length:0);0<C;)h.map(function(a){return{angle:a.colCount/a.rowLength,row:a}}).sort(function(a,b){return b.angle-a.angle}).slice(0,Math.min(C,Math.ceil(h.length/2))).forEach(a);h.forEach(function(a){var c=a.rowRadius;y=(a=a.colCount)?D/a:0;for(B=0;B<=a;B+=1)n=this.startAngleRad+B*y,w=b[0]+Math.cos(n)*c,v=b[1]+Math.sin(n)*c,g.push({x:w,y:v,angle:n})},this);g.sort(function(a,b){return a.angle-b.angle});this.itemSize=l;return g}};a.prototype.translate=function(a){0===this.total&&(this.center=this.getCenter());
this.slots||(this.slots=[]);y(this.options.startAngle)&&y(this.options.endAngle)?(c.seriesTypes.pie.prototype.translate.apply(this,arguments),this.slots=this.getSlots()):(this.generatePoints(),L(this,"afterTranslate"))};a.defaultOptions=z(e.defaultOptions,{endAngle:void 0,innerSize:"40%",itemPadding:.1,layout:"vertical",marker:z(J.plotOptions.line.marker,{radius:null}),rows:void 0,crisp:!1,showInLegend:!0,startAngle:void 0});return a}(e);w(a.prototype,{markerAttribs:void 0});a.prototype.pointClass=
I;b.registerSeriesType("item",a);"";return a});c(b,"masters/modules/item-series.src.js",[],function(){})});
//# sourceMappingURL=item-series.js.map