/*
 Highcharts JS v8.2.2 (2020-12-12)

 (c) 2009-2019 Sebastian Bochan, Rafal Sebestjanski

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/lollipop",["highcharts"],function(d){a(d);a.Highcharts=d;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function d(a,c,g,e){a.hasOwnProperty(c)||(a[c]=e.apply(null,g))}a=a?a._modules:{};d(a,"Series/Lollipop/LollipopPoint.js",[a["Core/Series/Series.js"],a["Core/Utilities.js"]],function(a,c){var g=this&&this.__extends||
function(){var a=function(b,h){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var k in b)b.hasOwnProperty(k)&&(a[k]=b[k])};return a(b,h)};return function(b,h){function c(){this.constructor=b}a(b,h);b.prototype=null===h?Object.create(h):(c.prototype=h.prototype,new c)}}(),e=a.seriesTypes;a=e.area.prototype;var f=e.line.prototype.pointClass,d=c.isObject;c=c.extend;e=function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.series=
void 0;b.options=void 0;return b}g(b,a);return b}(e.dumbbell.prototype.pointClass);c(e.prototype,{pointSetState:a.pointClass.prototype.setState,isValid:f.prototype.isValid,init:function(a,b,c){d(b)&&"low"in b&&(b.y=b.low,delete b.low);return f.prototype.init.apply(this,arguments)}});return e});d(a,"Series/Lollipop/LollipopSeries.js",[a["Series/Lollipop/LollipopPoint.js"],a["Core/Series/Series.js"],a["Core/Utilities.js"]],function(a,c,g){var e=this&&this.__extends||function(){var a=function(b,c){a=
Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),f=c.seriesTypes,d=f.area.prototype,l=f.column.prototype,b=f.dumbbell,h=g.pick,m=g.merge;g=g.extend;f=function(a){function c(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=
void 0;return b}e(c,a);c.prototype.toYData=function(a){return[h(a.y,a.low)]};c.defaultOptions=m(b.defaultOptions,{lowColor:void 0,threshold:0,connectorWidth:1,groupPadding:.2,pointPadding:.1,states:{hover:{lineWidthPlus:0,connectorWidthPlus:1,halo:!1}},tooltip:{pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.y}</b><br/>'}});return c}(b);g(f.prototype,{pointArrayMap:["y"],pointValKey:"y",translatePoint:d.translate,drawPoint:d.drawPoints,drawDataLabels:l.drawDataLabels,
setShapeArgs:l.translate,pointClass:a});c.registerSeriesType("lollipop",f);"";return f});d(a,"masters/modules/lollipop.src.js",[],function(){})});
//# sourceMappingURL=lollipop.js.map