/*
 Highmaps JS v8.2.2 (2020-12-12)

 Highmaps as a plugin for Highcharts or Highstock.

 (c) 2011-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/map",["highcharts"],function(y){a(y);a.Highcharts=y;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function y(a,c,m,p){a.hasOwnProperty(c)||(a[c]=p.apply(null,m))}a=a?a._modules:{};y(a,"Core/Axis/MapAxis.js",[a["Core/Axis/Axis.js"],a["Core/Utilities.js"]],function(a,c){var m=c.addEvent,p=c.pick,h=function(){return function(a){this.axis=
a}}();c=function(){function a(){}a.compose=function(a){a.keepProps.push("mapAxis");m(a,"init",function(){this.mapAxis||(this.mapAxis=new h(this))});m(a,"getSeriesExtremes",function(){if(this.mapAxis){var a=[];this.isXAxis&&(this.series.forEach(function(e,b){e.useMapGeometry&&(a[b]=e.xData,e.xData=[])}),this.mapAxis.seriesXData=a)}});m(a,"afterGetSeriesExtremes",function(){if(this.mapAxis){var a=this.mapAxis.seriesXData||[],e;if(this.isXAxis){var b=p(this.dataMin,Number.MAX_VALUE);var d=p(this.dataMax,
-Number.MAX_VALUE);this.series.forEach(function(f,n){f.useMapGeometry&&(b=Math.min(b,p(f.minX,b)),d=Math.max(d,p(f.maxX,d)),f.xData=a[n],e=!0)});e&&(this.dataMin=b,this.dataMax=d);this.mapAxis.seriesXData=void 0}}});m(a,"afterSetAxisTranslation",function(){if(this.mapAxis){var a=this.chart,e=a.plotWidth/a.plotHeight;a=a.xAxis[0];var b;"yAxis"===this.coll&&"undefined"!==typeof a.transA&&this.series.forEach(function(d){d.preserveAspectRatio&&(b=!0)});if(b&&(this.transA=a.transA=Math.min(this.transA,
a.transA),e/=(a.max-a.min)/(this.max-this.min),e=1>e?this:a,a=(e.max-e.min)*e.transA,e.mapAxis.pixelPadding=e.len-a,e.minPixelPadding=e.mapAxis.pixelPadding/2,a=e.mapAxis.fixTo)){a=a[1]-e.toValue(a[0],!0);a*=e.transA;if(Math.abs(a)>e.minPixelPadding||e.min===e.dataMin&&e.max===e.dataMax)a=0;e.minPixelPadding-=a}}});m(a,"render",function(){this.mapAxis&&(this.mapAxis.fixTo=void 0)})};return a}();c.compose(a);return c});y(a,"Mixins/ColorSeries.js",[],function(){return{colorPointMixin:{setVisible:function(a){var c=
this,m=a?"show":"hide";c.visible=c.options.visible=!!a;["graphic","dataLabel"].forEach(function(a){if(c[a])c[a][m]()});this.series.buildKDTree()}},colorSeriesMixin:{optionalAxis:"colorAxis",colorAxis:0,translateColors:function(){var a=this,c=this.options.nullColor,m=this.colorAxis,p=this.colorKey;(this.data.length?this.data:this.points).forEach(function(h){var u=h.getNestedProperty(p);(u=h.options.color||(h.isNull||null===h.value?c:m&&"undefined"!==typeof u?m.toColor(u,h):h.color||a.color))&&h.color!==
u&&(h.color=u,"point"===a.options.legendType&&h.legendItem&&a.chart.legend.colorizeItem(h,h.visible))})}}}});y(a,"Core/Axis/ColorAxis.js",[a["Core/Axis/Axis.js"],a["Core/Chart/Chart.js"],a["Core/Color/Color.js"],a["Mixins/ColorSeries.js"],a["Core/Animation/Fx.js"],a["Core/Globals.js"],a["Core/Legend.js"],a["Mixins/LegendSymbol.js"],a["Series/Line/LineSeries.js"],a["Core/Color/Palette.js"],a["Core/Series/Point.js"],a["Core/Utilities.js"]],function(a,c,m,p,h,u,k,n,e,b,d,f){var v=this&&this.__extends||
function(){var b=function(g,x){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(l,b){l.__proto__=b}||function(l,b){for(var g in b)b.hasOwnProperty(g)&&(l[g]=b[g])};return b(g,x)};return function(g,x){function l(){this.constructor=g}b(g,x);g.prototype=null===x?Object.create(x):(l.prototype=x.prototype,new l)}}(),A=m.parse;m=p.colorPointMixin;p=p.colorSeriesMixin;var F=u.noop,z=f.addEvent,E=f.erase,w=f.extend,B=f.isNumber,t=f.merge,r=f.pick,g=f.splat;"";w(e.prototype,p);w(d.prototype,
m);c.prototype.collectionsWithUpdate.push("colorAxis");c.prototype.collectionsWithInit.colorAxis=[c.prototype.addColorAxis];var q=function(g){function d(d,l){var b=g.call(this,d,l)||this;b.beforePadding=!1;b.chart=void 0;b.coll="colorAxis";b.dataClasses=void 0;b.legendItem=void 0;b.legendItems=void 0;b.name="";b.options=void 0;b.stops=void 0;b.visible=!0;b.init(d,l);return b}v(d,g);d.buildOptions=function(b,l,d){b=b.options.legend||{};var g=d.layout?"vertical"!==d.layout:"vertical"!==b.layout;return t(l,
{side:g?2:1,reversed:!g},d,{opposite:!g,showEmpty:!1,title:null,visible:b.enabled&&(d?!1!==d.visible:!0)})};d.prototype.init=function(b,l){var x=d.buildOptions(b,d.defaultOptions,l);this.coll="colorAxis";g.prototype.init.call(this,b,x);l.dataClasses&&this.initDataClasses(l);this.initStops();this.horiz=!x.opposite;this.zoomEnabled=!1};d.prototype.initDataClasses=function(b){var l=this.chart,d,g=0,x=l.options.chart.colorCount,a=this.options,f=b.dataClasses.length;this.dataClasses=d=[];this.legendItems=
[];b.dataClasses.forEach(function(b,r){b=t(b);d.push(b);if(l.styledMode||!b.color)"category"===a.dataClassColor?(l.styledMode||(r=l.options.colors,x=r.length,b.color=r[g]),b.colorIndex=g,g++,g===x&&(g=0)):b.color=A(a.minColor).tweenTo(A(a.maxColor),2>f?.5:r/(f-1))})};d.prototype.hasData=function(){return!!(this.tickPositions||[]).length};d.prototype.setTickPositions=function(){if(!this.dataClasses)return g.prototype.setTickPositions.call(this)};d.prototype.initStops=function(){this.stops=this.options.stops||
[[0,this.options.minColor],[1,this.options.maxColor]];this.stops.forEach(function(b){b.color=A(b[1])})};d.prototype.setOptions=function(b){g.prototype.setOptions.call(this,b);this.options.crosshair=this.options.marker};d.prototype.setAxisSize=function(){var b=this.legendSymbol,l=this.chart,g=l.options.legend||{},a,f;b?(this.left=g=b.attr("x"),this.top=a=b.attr("y"),this.width=f=b.attr("width"),this.height=b=b.attr("height"),this.right=l.chartWidth-g-f,this.bottom=l.chartHeight-a-b,this.len=this.horiz?
f:b,this.pos=this.horiz?g:a):this.len=(this.horiz?g.symbolWidth:g.symbolHeight)||d.defaultLegendLength};d.prototype.normalizedValue=function(b){this.logarithmic&&(b=this.logarithmic.log2lin(b));return 1-(this.max-b)/(this.max-this.min||1)};d.prototype.toColor=function(b,l){var g=this.dataClasses,d=this.stops,a;if(g)for(a=g.length;a--;){var f=g[a];var r=f.from;d=f.to;if(("undefined"===typeof r||b>=r)&&("undefined"===typeof d||b<=d)){var x=f.color;l&&(l.dataClass=a,l.colorIndex=f.colorIndex);break}}else{b=
this.normalizedValue(b);for(a=d.length;a--&&!(b>d[a][0]););r=d[a]||d[a+1];d=d[a+1]||r;b=1-(d[0]-b)/(d[0]-r[0]||1);x=r.color.tweenTo(d.color,b)}return x};d.prototype.getOffset=function(){var b=this.legendGroup,l=this.chart.axisOffset[this.side];b&&(this.axisParent=b,g.prototype.getOffset.call(this),this.added||(this.added=!0,this.labelLeft=0,this.labelRight=this.width),this.chart.axisOffset[this.side]=l)};d.prototype.setLegendColor=function(){var b=this.reversed,l=b?1:0;b=b?0:1;l=this.horiz?[l,0,b,
0]:[0,b,0,l];this.legendColor={linearGradient:{x1:l[0],y1:l[1],x2:l[2],y2:l[3]},stops:this.stops}};d.prototype.drawLegendSymbol=function(b,l){var g=b.padding,a=b.options,f=this.horiz,x=r(a.symbolWidth,f?d.defaultLegendLength:12),q=r(a.symbolHeight,f?12:d.defaultLegendLength),e=r(a.labelPadding,f?16:30);a=r(a.itemDistance,10);this.setLegendColor();l.legendSymbol=this.chart.renderer.rect(0,b.baseline-11,x,q).attr({zIndex:1}).add(l.legendGroup);this.legendItemWidth=x+g+(f?a:e);this.legendItemHeight=
q+g+(f?e:0)};d.prototype.setState=function(b){this.series.forEach(function(l){l.setState(b)})};d.prototype.setVisible=function(){};d.prototype.getSeriesExtremes=function(){var b=this.series,l=b.length,d;this.dataMin=Infinity;for(this.dataMax=-Infinity;l--;){var g=b[l];var a=g.colorKey=r(g.options.colorKey,g.colorKey,g.pointValKey,g.zoneAxis,"y");var f=g.pointArrayMap;var q=g[a+"Min"]&&g[a+"Max"];if(g[a+"Data"])var t=g[a+"Data"];else if(f){t=[];f=f.indexOf(a);var v=g.yData;if(0<=f&&v)for(d=0;d<v.length;d++)t.push(r(v[d][f],
v[d]))}else t=g.yData;q?(g.minColorValue=g[a+"Min"],g.maxColorValue=g[a+"Max"]):(t=e.prototype.getExtremes.call(g,t),g.minColorValue=t.dataMin,g.maxColorValue=t.dataMax);"undefined"!==typeof g.minColorValue&&(this.dataMin=Math.min(this.dataMin,g.minColorValue),this.dataMax=Math.max(this.dataMax,g.maxColorValue));q||e.prototype.applyExtremes.call(g)}};d.prototype.drawCrosshair=function(b,l){var d=l&&l.plotX,a=l&&l.plotY,f=this.pos,r=this.len;if(l){var q=this.toPixels(l.getNestedProperty(l.series.colorKey));
q<f?q=f-2:q>f+r&&(q=f+r+2);l.plotX=q;l.plotY=this.len-q;g.prototype.drawCrosshair.call(this,b,l);l.plotX=d;l.plotY=a;this.cross&&!this.cross.addedToColorAxis&&this.legendGroup&&(this.cross.addClass("highcharts-coloraxis-marker").add(this.legendGroup),this.cross.addedToColorAxis=!0,!this.chart.styledMode&&this.crosshair&&this.cross.attr({fill:this.crosshair.color}))}};d.prototype.getPlotLinePath=function(b){var l=this.left,d=b.translatedValue,a=this.top;return B(d)?this.horiz?[["M",d-4,a-6],["L",d+
4,a-6],["L",d,a],["Z"]]:[["M",l,d],["L",l-6,d+6],["L",l-6,d-6],["Z"]]:g.prototype.getPlotLinePath.call(this,b)};d.prototype.update=function(b,l){var a=this.chart,f=a.legend,r=d.buildOptions(a,{},b);this.series.forEach(function(b){b.isDirtyData=!0});(b.dataClasses&&f.allItems||this.dataClasses)&&this.destroyItems();a.options[this.coll]=t(this.userOptions,r);g.prototype.update.call(this,r,l);this.legendItem&&(this.setLegendColor(),f.colorizeItem(this,!0))};d.prototype.destroyItems=function(){var b=
this.chart;this.legendItem?b.legend.destroyItem(this):this.legendItems&&this.legendItems.forEach(function(g){b.legend.destroyItem(g)});b.isDirtyLegend=!0};d.prototype.remove=function(b){this.destroyItems();g.prototype.remove.call(this,b)};d.prototype.getDataClassLegendSymbols=function(){var b=this,g=b.chart,d=b.legendItems,a=g.options.legend,f=a.valueDecimals,r=a.valueSuffix||"",q;d.length||b.dataClasses.forEach(function(l,a){var e=!0,t=l.from,v=l.to,x=g.numberFormatter;q="";"undefined"===typeof t?
q="< ":"undefined"===typeof v&&(q="> ");"undefined"!==typeof t&&(q+=x(t,f)+r);"undefined"!==typeof t&&"undefined"!==typeof v&&(q+=" - ");"undefined"!==typeof v&&(q+=x(v,f)+r);d.push(w({chart:g,name:q,options:{},drawLegendSymbol:n.drawRectangle,visible:!0,setState:F,isDataClass:!0,setVisible:function(){e=b.visible=!e;b.series.forEach(function(b){b.points.forEach(function(b){b.dataClass===a&&b.setVisible(e)})});g.legend.colorizeItem(this,e)}},l))});return d};d.defaultLegendLength=200;d.defaultOptions=
{lineWidth:0,minPadding:0,maxPadding:0,gridLineWidth:1,tickPixelInterval:72,startOnTick:!0,endOnTick:!0,offset:0,marker:{animation:{duration:50},width:.01,color:b.neutralColor40},labels:{overflow:"justify",rotation:0},minColor:b.highlightColor10,maxColor:b.highlightColor100,tickLength:5,showInLegend:!0};d.keepProps=["legendGroup","legendItemHeight","legendItemWidth","legendItem","legendSymbol"];return d}(a);Array.prototype.push.apply(a.keepProps,q.keepProps);u.ColorAxis=q;["fill","stroke"].forEach(function(b){h.prototype[b+
"Setter"]=function(){this.elem.attr(b,A(this.start).tweenTo(A(this.end),this.pos),null,!0)}});z(c,"afterGetAxes",function(){var b=this,d=b.options;this.colorAxis=[];d.colorAxis&&(d.colorAxis=g(d.colorAxis),d.colorAxis.forEach(function(g,d){g.index=d;new q(b,g)}))});z(e,"bindAxes",function(){var b=this.axisTypes;b?-1===b.indexOf("colorAxis")&&b.push("colorAxis"):this.axisTypes=["colorAxis"]});z(k,"afterGetAllItems",function(b){var g=[],d,l;(this.chart.colorAxis||[]).forEach(function(l){(d=l.options)&&
d.showInLegend&&(d.dataClasses&&d.visible?g=g.concat(l.getDataClassLegendSymbols()):d.visible&&g.push(l),l.series.forEach(function(g){if(!g.options.showInLegend||d.dataClasses)"point"===g.options.legendType?g.points.forEach(function(g){E(b.allItems,g)}):E(b.allItems,g)}))});for(l=g.length;l--;)b.allItems.unshift(g[l])});z(k,"afterColorizeItem",function(b){b.visible&&b.item.legendColor&&b.item.legendSymbol.attr({fill:b.item.legendColor})});z(k,"afterUpdate",function(){var b=this.chart.colorAxis;b&&
b.forEach(function(b,g,d){b.update({},d)})});z(e,"afterTranslate",function(){(this.chart.colorAxis&&this.chart.colorAxis.length||this.colorAttribs)&&this.translateColors()});return q});y(a,"Mixins/ColorMapSeries.js",[a["Core/Globals.js"],a["Core/Series/Point.js"],a["Core/Utilities.js"]],function(a,c,m){var p=m.defined;return{colorMapPointMixin:{dataLabelOnNull:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==this.value},setState:function(a){c.prototype.setState.call(this,
a);this.graphic&&this.graphic.attr({zIndex:"hover"===a?1:0})}},colorMapSeriesMixin:{pointArrayMap:["value"],axisTypes:["xAxis","yAxis","colorAxis"],trackerGroups:["group","markerGroup","dataLabelsGroup"],getSymbol:a.noop,parallelArrays:["x","y","value"],colorKey:"value",pointAttribs:a.seriesTypes.column.prototype.pointAttribs,colorAttribs:function(a){var h={};p(a.color)&&(h[this.colorProp||"fill"]=a.color);return h}}}});y(a,"Maps/MapNavigation.js",[a["Core/Chart/Chart.js"],a["Core/Globals.js"],a["Core/Utilities.js"]],
function(a,c,m){function p(b){b&&(b.preventDefault&&b.preventDefault(),b.stopPropagation&&b.stopPropagation(),b.cancelBubble=!0)}function h(b){this.init(b)}var u=c.doc,k=m.addEvent,n=m.extend,e=m.merge,b=m.objectEach,d=m.pick;h.prototype.init=function(b){this.chart=b;b.mapNavButtons=[]};h.prototype.update=function(a){var f=this.chart,h=f.options.mapNavigation,c,u,m,w,B,t=function(b){this.handler.call(f,b);p(b)},r=f.mapNavButtons;a&&(h=f.options.mapNavigation=e(f.options.mapNavigation,a));for(;r.length;)r.pop().destroy();
d(h.enableButtons,h.enabled)&&!f.renderer.forExport&&b(h.buttons,function(b,d){c=e(h.buttonOptions,b);f.styledMode||(u=c.theme,u.style=e(c.theme.style,c.style),w=(m=u.states)&&m.hover,B=m&&m.select);b=f.renderer.button(c.text,0,0,t,u,w,B,0,"zoomIn"===d?"topbutton":"bottombutton").addClass("highcharts-map-navigation highcharts-"+{zoomIn:"zoom-in",zoomOut:"zoom-out"}[d]).attr({width:c.width,height:c.height,title:f.options.lang[d],padding:c.padding,zIndex:5}).add();b.handler=c.onclick;k(b.element,"dblclick",
p);r.push(b);var g=c,a=k(f,"load",function(){b.align(n(g,{width:b.width,height:2*b.height}),null,g.alignTo);a()})});this.updateEvents(h)};h.prototype.updateEvents=function(b){var a=this.chart;d(b.enableDoubleClickZoom,b.enabled)||b.enableDoubleClickZoomTo?this.unbindDblClick=this.unbindDblClick||k(a.container,"dblclick",function(b){a.pointer.onContainerDblClick(b)}):this.unbindDblClick&&(this.unbindDblClick=this.unbindDblClick());d(b.enableMouseWheelZoom,b.enabled)?this.unbindMouseWheel=this.unbindMouseWheel||
k(a.container,"undefined"===typeof u.onmousewheel?"DOMMouseScroll":"mousewheel",function(b){a.pointer.onContainerMouseWheel(b);p(b);return!1}):this.unbindMouseWheel&&(this.unbindMouseWheel=this.unbindMouseWheel())};n(a.prototype,{fitToBox:function(b,d){[["x","width"],["y","height"]].forEach(function(a){var f=a[0];a=a[1];b[f]+b[a]>d[f]+d[a]&&(b[a]>d[a]?(b[a]=d[a],b[f]=d[f]):b[f]=d[f]+d[a]-b[a]);b[a]>d[a]&&(b[a]=d[a]);b[f]<d[f]&&(b[f]=d[f])});return b},mapZoom:function(b,a,e,h,k){var f=this.xAxis[0],
c=f.max-f.min,n=d(a,f.min+c/2),t=c*b;c=this.yAxis[0];var r=c.max-c.min,g=d(e,c.min+r/2);r*=b;n=this.fitToBox({x:n-t*(h?(h-f.pos)/f.len:.5),y:g-r*(k?(k-c.pos)/c.len:.5),width:t,height:r},{x:f.dataMin,y:c.dataMin,width:f.dataMax-f.dataMin,height:c.dataMax-c.dataMin});t=n.x<=f.dataMin&&n.width>=f.dataMax-f.dataMin&&n.y<=c.dataMin&&n.height>=c.dataMax-c.dataMin;h&&f.mapAxis&&(f.mapAxis.fixTo=[h-f.pos,a]);k&&c.mapAxis&&(c.mapAxis.fixTo=[k-c.pos,e]);"undefined"===typeof b||t?(f.setExtremes(void 0,void 0,
!1),c.setExtremes(void 0,void 0,!1)):(f.setExtremes(n.x,n.x+n.width,!1),c.setExtremes(n.y,n.y+n.height,!1));this.redraw()}});k(a,"beforeRender",function(){this.mapNavigation=new h(this);this.mapNavigation.update()});c.MapNavigation=h});y(a,"Maps/MapPointer.js",[a["Core/Pointer.js"],a["Core/Utilities.js"]],function(a,c){var m=c.extend,p=c.pick;c=c.wrap;m(a.prototype,{onContainerDblClick:function(a){var c=this.chart;a=this.normalize(a);c.options.mapNavigation.enableDoubleClickZoomTo?c.pointer.inClass(a.target,
"highcharts-tracker")&&c.hoverPoint&&c.hoverPoint.zoomTo():c.isInsidePlot(a.chartX-c.plotLeft,a.chartY-c.plotTop)&&c.mapZoom(.5,c.xAxis[0].toValue(a.chartX),c.yAxis[0].toValue(a.chartY),a.chartX,a.chartY)},onContainerMouseWheel:function(a){var c=this.chart;a=this.normalize(a);var k=a.detail||-(a.wheelDelta/120);c.isInsidePlot(a.chartX-c.plotLeft,a.chartY-c.plotTop)&&c.mapZoom(Math.pow(c.options.mapNavigation.mouseWheelSensitivity,k),c.xAxis[0].toValue(a.chartX),c.yAxis[0].toValue(a.chartY),a.chartX,
a.chartY)}});c(a.prototype,"zoomOption",function(a){var c=this.chart.options.mapNavigation;p(c.enableTouchZoom,c.enabled)&&(this.chart.options.chart.pinchType="xy");a.apply(this,[].slice.call(arguments,1))});c(a.prototype,"pinchTranslate",function(a,c,k,n,e,b,d){a.call(this,c,k,n,e,b,d);"map"===this.chart.options.chart.type&&this.hasZoom&&(a=n.scaleX>n.scaleY,this.pinchTranslateDirection(!a,c,k,n,e,b,d,a?n.scaleX:n.scaleY))})});y(a,"Maps/Map.js",[a["Core/Chart/Chart.js"],a["Core/Globals.js"],a["Core/Options.js"],
a["Core/Renderer/SVG/SVGRenderer.js"],a["Core/Utilities.js"]],function(a,c,m,p,h){function u(b,a,d,c,e,n,k,h){return[["M",b+e,a],["L",b+d-n,a],["C",b+d-n/2,a,b+d,a+n/2,b+d,a+n],["L",b+d,a+c-k],["C",b+d,a+c-k/2,b+d-k/2,a+c,b+d-k,a+c],["L",b+h,a+c],["C",b+h/2,a+c,b,a+c-h/2,b,a+c-h],["L",b,a+e],["C",b,a+e/2,b+e/2,a,b+e,a],["Z"]]}m=m.defaultOptions;var k=h.extend,n=h.getOptions,e=h.merge,b=h.pick;h=c.Renderer;var d=c.VMLRenderer;k(m.lang,{zoomIn:"Zoom in",zoomOut:"Zoom out"});m.mapNavigation={buttonOptions:{alignTo:"plotBox",
align:"left",verticalAlign:"top",x:0,width:18,height:18,padding:5,style:{fontSize:"15px",fontWeight:"bold"},theme:{"stroke-width":1,"text-align":"center"}},buttons:{zoomIn:{onclick:function(){this.mapZoom(.5)},text:"+",y:0},zoomOut:{onclick:function(){this.mapZoom(2)},text:"-",y:28}},mouseWheelSensitivity:1.1};m=c.splitPath=function(b){"string"===typeof b&&(b=b.replace(/([A-Za-z])/g," $1 ").replace(/^\s*/,"").replace(/\s*$/,""),b=b.split(/[ ,;]+/).map(function(b){return/[A-za-z]/.test(b)?b:parseFloat(b)}));
return p.prototype.pathToSegments(b)};c.maps={};p.prototype.symbols.topbutton=function(b,a,d,c,e){e=e&&e.r||0;return u(b-1,a-1,d,c,e,e,0,0)};p.prototype.symbols.bottombutton=function(b,a,d,c,e){e=e&&e.r||0;return u(b-1,a-1,d,c,0,0,e,e)};h===d&&["topbutton","bottombutton"].forEach(function(b){d.prototype.symbols[b]=p.prototype.symbols[b]});return{mapChart:c.Map=c.mapChart=function(d,c,k){var f="string"===typeof d||d.nodeName,h=arguments[f?1:0],m=h,u={endOnTick:!1,visible:!1,minPadding:0,maxPadding:0,
startOnTick:!1},B=n().credits;var t=h.series;h.series=null;h=e({chart:{panning:{enabled:!0,type:"xy"},type:"map"},credits:{mapText:b(B.mapText,' \u00a9 <a href="{geojson.copyrightUrl}">{geojson.copyrightShort}</a>'),mapTextFull:b(B.mapTextFull,"{geojson.copyright}")},tooltip:{followTouchMove:!1},xAxis:u,yAxis:e(u,{reversed:!0})},h,{chart:{inverted:!1,alignTicks:!1}});h.series=m.series=t;return f?new a(d,h,k):new a(h,c)},maps:c.maps,splitPath:m}});y(a,"Series/Map/MapPoint.js",[a["Core/Series/Series.js"],
a["Mixins/ColorMapSeries.js"],a["Core/Utilities.js"]],function(a,c,m){var p=this&&this.__extends||function(){var a=function(c,n){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d])};return a(c,n)};return function(c,n){function e(){this.constructor=c}a(c,n);c.prototype=null===n?Object.create(n):(e.prototype=n.prototype,new e)}}();c=c.colorMapPointMixin;var h=m.extend;a=function(a){function c(){var c=null!==
a&&a.apply(this,arguments)||this;c.options=void 0;c.path=void 0;c.series=void 0;return c}p(c,a);c.prototype.applyOptions=function(c,e){var b=this.series;c=a.prototype.applyOptions.call(this,c,e);e=b.joinBy;b.mapData&&b.mapMap&&(e=a.prototype.getNestedProperty.call(c,e[1]),(e="undefined"!==typeof e&&b.mapMap[e])?(b.xyFromShape&&(c.x=e._midX,c.y=e._midY),h(c,e)):c.value=c.value||null);return c};c.prototype.onMouseOver=function(c){m.clearTimeout(this.colorInterval);if(null!==this.value||this.series.options.nullInteraction)a.prototype.onMouseOver.call(this,
c);else this.series.onMouseOut(c)};c.prototype.zoomTo=function(){var a=this.series;a.xAxis.setExtremes(this._minX,this._maxX,!1);a.yAxis.setExtremes(this._minY,this._maxY,!1);a.chart.redraw()};return c}(a.seriesTypes.scatter.prototype.pointClass);h(a.prototype,{dataLabelOnNull:c.dataLabelOnNull,isValid:c.isValid,setState:c.setState});return a});y(a,"Series/Map/MapSeries.js",[a["Core/Series/Series.js"],a["Mixins/ColorMapSeries.js"],a["Core/Globals.js"],a["Mixins/LegendSymbol.js"],a["Series/Line/LineSeries.js"],
a["Maps/Map.js"],a["Core/Color/Palette.js"],a["Series/Map/MapPoint.js"],a["Core/Renderer/SVG/SVGRenderer.js"],a["Core/Utilities.js"]],function(a,c,m,p,h,u,k,n,e,b){var d=this&&this.__extends||function(){var b=function(a,d){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var d in a)a.hasOwnProperty(d)&&(b[d]=a[d])};return b(a,d)};return function(a,d){function g(){this.constructor=a}b(a,d);a.prototype=null===d?Object.create(d):(g.prototype=d.prototype,
new g)}}(),f=a.seriesTypes,v=f.column,A=f.scatter;c=c.colorMapSeriesMixin;f=m.noop;var G=u.maps,z=u.splitPath;u=b.extend;var E=b.fireEvent,w=b.getNestedProperty,B=b.isArray,t=b.isNumber,r=b.merge,g=b.objectEach,q=b.pick,D=b.splat;b=function(b){function a(){var a=null!==b&&b.apply(this,arguments)||this;a.baseTrans=void 0;a.chart=void 0;a.data=void 0;a.group=void 0;a.joinBy=void 0;a.options=void 0;a.points=void 0;a.transformGroup=void 0;return a}d(a,b);a.prototype.animate=function(b){var a=this.options.animation,
d=this.group,g=this.xAxis,l=this.yAxis,c=g.pos,r=l.pos;this.chart.renderer.isSVG&&(!0===a&&(a={duration:1E3}),b?d.attr({translateX:c+g.len/2,translateY:r+l.len/2,scaleX:.001,scaleY:.001}):d.animate({translateX:c,translateY:r,scaleX:1,scaleY:1},a))};a.prototype.animateDrilldown=function(b){var a=this.chart.plotBox,d=this.chart.drilldownLevels[this.chart.drilldownLevels.length-1],g=d.bBox,l=this.chart.options.drilldown.animation;b||(b=Math.min(g.width/a.width,g.height/a.height),d.shapeArgs={scaleX:b,
scaleY:b,translateX:g.x,translateY:g.y},this.points.forEach(function(b){b.graphic&&b.graphic.attr(d.shapeArgs).animate({scaleX:1,scaleY:1,translateX:0,translateY:0},l)}))};a.prototype.animateDrillupFrom=function(b){v.prototype.animateDrillupFrom.call(this,b)};a.prototype.animateDrillupTo=function(b){v.prototype.animateDrillupTo.call(this,b)};a.prototype.doFullTranslate=function(){return this.isDirtyData||this.chart.isResizing||this.chart.renderer.isVML||!this.baseTrans};a.prototype.drawMapDataLabels=
function(){h.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)};a.prototype.drawPoints=function(){var b=this,a=b.xAxis,d=b.yAxis,g=b.group,c=b.chart,r=c.renderer,f=this.baseTrans;b.transformGroup||(b.transformGroup=r.g().attr({scaleX:1,scaleY:1}).add(g),b.transformGroup.survive=!0);if(b.doFullTranslate())c.hasRendered&&!c.styledMode&&b.points.forEach(function(a){a.shapeArgs&&(a.shapeArgs.fill=b.pointAttribs(a,a.state).fill)}),b.group=b.transformGroup,
v.prototype.drawPoints.apply(b),b.group=g,b.points.forEach(function(a){if(a.graphic){var d="";a.name&&(d+="highcharts-name-"+a.name.replace(/ /g,"-").toLowerCase());a.properties&&a.properties["hc-key"]&&(d+=" highcharts-key-"+a.properties["hc-key"].toLowerCase());d&&a.graphic.addClass(d);c.styledMode&&a.graphic.css(b.pointAttribs(a,a.selected&&"select"||void 0))}}),this.baseTrans={originX:a.min-a.minPixelPadding/a.transA,originY:d.min-d.minPixelPadding/d.transA+(d.reversed?0:d.len/d.transA),transAX:a.transA,
transAY:d.transA},this.transformGroup.animate({translateX:0,translateY:0,scaleX:1,scaleY:1});else{var e=a.transA/f.transAX;var t=d.transA/f.transAY;var k=a.toPixels(f.originX,!0);var h=d.toPixels(f.originY,!0);.99<e&&1.01>e&&.99<t&&1.01>t&&(t=e=1,k=Math.round(k),h=Math.round(h));var n=this.transformGroup;if(c.renderer.globalAnimation){var C=n.attr("translateX");var D=n.attr("translateY");var m=n.attr("scaleX");var x=n.attr("scaleY");n.attr({animator:0}).animate({animator:1},{step:function(b,a){n.attr({translateX:C+
(k-C)*a.pos,translateY:D+(h-D)*a.pos,scaleX:m+(e-m)*a.pos,scaleY:x+(t-x)*a.pos})}})}else n.attr({translateX:k,translateY:h,scaleX:e,scaleY:t})}c.styledMode||g.element.setAttribute("stroke-width",q(b.options[b.pointAttrToOptions&&b.pointAttrToOptions["stroke-width"]||"borderWidth"],1)/(e||1));this.drawMapDataLabels()};a.prototype.getBox=function(b){var a=Number.MAX_VALUE,d=-a,g=a,c=-a,l=a,r=a,f=this.xAxis,t=this.yAxis,k;(b||[]).forEach(function(b){if(b.path){"string"===typeof b.path?b.path=z(b.path):
"M"===b.path[0]&&(b.path=e.prototype.pathToSegments(b.path));var f=b.path||[],t=-a,h=a,n=-a,C=a,D=b.properties;b._foundBox||(f.forEach(function(b){var a=b[b.length-2];b=b[b.length-1];"number"===typeof a&&"number"===typeof b&&(h=Math.min(h,a),t=Math.max(t,a),C=Math.min(C,b),n=Math.max(n,b))}),b._midX=h+(t-h)*q(b.middleX,D&&D["hc-middle-x"],.5),b._midY=C+(n-C)*q(b.middleY,D&&D["hc-middle-y"],.5),b._maxX=t,b._minX=h,b._maxY=n,b._minY=C,b.labelrank=q(b.labelrank,(t-h)*(n-C)),b._foundBox=!0);d=Math.max(d,
b._maxX);g=Math.min(g,b._minX);c=Math.max(c,b._maxY);l=Math.min(l,b._minY);r=Math.min(b._maxX-b._minX,b._maxY-b._minY,r);k=!0}});k&&(this.minY=Math.min(l,q(this.minY,a)),this.maxY=Math.max(c,q(this.maxY,-a)),this.minX=Math.min(g,q(this.minX,a)),this.maxX=Math.max(d,q(this.maxX,-a)),f&&"undefined"===typeof f.options.minRange&&(f.minRange=Math.min(5*r,(this.maxX-this.minX)/5,f.minRange||a)),t&&"undefined"===typeof t.options.minRange&&(t.minRange=Math.min(5*r,(this.maxY-this.minY)/5,t.minRange||a)))};
a.prototype.getExtremes=function(){var b=h.prototype.getExtremes.call(this,this.valueData),a=b.dataMin;b=b.dataMax;this.chart.hasRendered&&this.isDirtyData&&this.getBox(this.options.data);t(a)&&(this.valueMin=a);t(b)&&(this.valueMax=b);return{dataMin:this.minY,dataMax:this.maxY}};a.prototype.hasData=function(){return!!this.processedXData.length};a.prototype.pointAttribs=function(b,a){a=b.series.chart.styledMode?this.colorAttribs(b):v.prototype.pointAttribs.call(this,b,a);a["stroke-width"]=q(b.options[this.pointAttrToOptions&&
this.pointAttrToOptions["stroke-width"]||"borderWidth"],"inherit");return a};a.prototype.render=function(){var b=this,a=h.prototype.render;b.chart.renderer.isVML&&3E3<b.data.length?setTimeout(function(){a.call(b)}):a.call(b)};a.prototype.setData=function(b,a,d,c){var f=this.options,l=this.chart.options.chart,e=l&&l.map,q=f.mapData,k=this.joinBy,C=f.keys||this.pointArrayMap,D=[],x={},v=this.chart.mapTransforms;!q&&e&&(q="string"===typeof e?G[e]:e);b&&b.forEach(function(a,d){var g=0;if(t(a))b[d]={value:a};
else if(B(a)){b[d]={};!f.keys&&a.length>C.length&&"string"===typeof a[0]&&(b[d]["hc-key"]=a[0],++g);for(var c=0;c<C.length;++c,++g)C[c]&&"undefined"!==typeof a[g]&&(0<C[c].indexOf(".")?n.prototype.setNestedProperty(b[d],a[g],C[c]):b[d][C[c]]=a[g])}k&&"_i"===k[0]&&(b[d]._i=d)});this.getBox(b);(this.chart.mapTransforms=v=l&&l.mapTransforms||q&&q["hc-transform"]||v)&&g(v,function(b){b.rotation&&(b.cosAngle=Math.cos(b.rotation),b.sinAngle=Math.sin(b.rotation))});if(q){"FeatureCollection"===q.type&&(this.mapTitle=
q.title,q=m.geojson(q,this.type,this));this.mapData=q;this.mapMap={};for(v=0;v<q.length;v++)l=q[v],e=l.properties,l._i=v,k[0]&&e&&e[k[0]]&&(l[k[0]]=e[k[0]]),x[l[k[0]]]=l;this.mapMap=x;if(b&&k[1]){var u=k[1];b.forEach(function(b){b=w(u,b);x[b]&&D.push(x[b])})}if(f.allAreas){this.getBox(q);b=b||[];if(k[1]){var p=k[1];b.forEach(function(b){D.push(w(p,b))})}D="|"+D.map(function(b){return b&&b[k[0]]}).join("|")+"|";q.forEach(function(a){k[0]&&-1!==D.indexOf("|"+a[k[0]]+"|")||(b.push(r(a,{value:null})),
c=!1)})}else this.getBox(D)}h.prototype.setData.call(this,b,a,d,c)};a.prototype.setOptions=function(b){b=h.prototype.setOptions.call(this,b);var a=b.joinBy;null===a&&(a="_i");a=this.joinBy=D(a);a[1]||(a[1]=a[0]);return b};a.prototype.translate=function(){var b=this,a=b.xAxis,d=b.yAxis,g=b.doFullTranslate();b.generatePoints();b.data.forEach(function(c){t(c._midX)&&t(c._midY)&&(c.plotX=a.toPixels(c._midX,!0),c.plotY=d.toPixels(c._midY,!0));g&&(c.shapeType="path",c.shapeArgs={d:b.translatePath(c.path)})});
E(b,"afterTranslate")};a.prototype.translatePath=function(b){var a=this.xAxis,d=this.yAxis,g=a.min,c=a.transA,f=a.minPixelPadding,r=d.min,e=d.transA,q=d.minPixelPadding,l=[];b&&b.forEach(function(b){"M"===b[0]?l.push(["M",(b[1]-(g||0))*c+f,(b[2]-(r||0))*e+q]):"L"===b[0]?l.push(["L",(b[1]-(g||0))*c+f,(b[2]-(r||0))*e+q]):"C"===b[0]?l.push(["C",(b[1]-(g||0))*c+f,(b[2]-(r||0))*e+q,(b[3]-(g||0))*c+f,(b[4]-(r||0))*e+q,(b[5]-(g||0))*c+f,(b[6]-(r||0))*e+q]):"Q"===b[0]?l.push(["Q",(b[1]-(g||0))*c+f,(b[2]-
(r||0))*e+q,(b[3]-(g||0))*c+f,(b[4]-(r||0))*e+q]):"Z"===b[0]&&l.push(["Z"])});return l};a.defaultOptions=r(A.defaultOptions,{animation:!1,dataLabels:{crop:!1,formatter:function(){return this.point.value},inside:!0,overflow:!1,padding:0,verticalAlign:"middle"},marker:null,nullColor:k.neutralColor3,stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:"{point.name}: {point.value}<br/>"},turboThreshold:0,allAreas:!0,borderColor:k.neutralColor20,borderWidth:1,joinBy:"hc-key",states:{hover:{halo:null,
brightness:.2},normal:{animation:!0},select:{color:k.neutralColor20},inactive:{opacity:1}}});return a}(A);u(b.prototype,{type:"map",axisTypes:c.axisTypes,colorAttribs:c.colorAttribs,colorKey:c.colorKey,directTouch:!0,drawDataLabels:f,drawGraph:f,drawLegendSymbol:p.drawRectangle,forceDL:!0,getExtremesFromAll:!0,getSymbol:c.getSymbol,parallelArrays:c.parallelArrays,pointArrayMap:c.pointArrayMap,pointClass:n,preserveAspectRatio:!0,searchPoint:f,trackerGroups:c.trackerGroups,useMapGeometry:!0});a.registerSeriesType("map",
b);"";return b});y(a,"Series/MapLine/MapLineSeries.js",[a["Core/Series/Series.js"],a["Series/Map/MapSeries.js"],a["Core/Utilities.js"]],function(a,c,m){var p=this&&this.__extends||function(){var a=function(c,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var d in a)a.hasOwnProperty(d)&&(b[d]=a[d])};return a(c,b)};return function(c,b){function d(){this.constructor=c}a(c,b);c.prototype=null===b?Object.create(b):(d.prototype=b.prototype,new d)}}(),
h=a.seriesTypes.line,u=m.extend,k=m.merge;m=function(a){function e(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}p(e,a);e.prototype.pointAttribs=function(b,a){b=c.prototype.pointAttribs.call(this,b,a);b.fill=this.options.fillColor;return b};e.defaultOptions=k(c.defaultOptions,{lineWidth:1,fillColor:"none"});return e}(c);u(m.prototype,{type:"mapline",colorProp:"stroke",drawLegendSymbol:h.prototype.drawLegendSymbol,pointAttrToOptions:{stroke:"color",
"stroke-width":"lineWidth"}});a.registerSeriesType("mapline",m);"";return m});y(a,"Series/MapPoint/MapPointPoint.js",[a["Core/Series/Series.js"],a["Core/Utilities.js"]],function(a,c){var m=this&&this.__extends||function(){var a=function(c,k){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(c,k)};return function(c,k){function h(){this.constructor=c}a(c,k);c.prototype=null===k?Object.create(k):
(h.prototype=k.prototype,new h)}}(),p=c.merge;return function(a){function c(){var c=null!==a&&a.apply(this,arguments)||this;c.options=void 0;c.series=void 0;return c}m(c,a);c.prototype.applyOptions=function(c,h){c="undefined"!==typeof c.lat&&"undefined"!==typeof c.lon?p(c,this.series.chart.fromLatLonToPoint(c)):c;return a.prototype.applyOptions.call(this,c,h)};return c}(a.seriesTypes.scatter.prototype.pointClass)});y(a,"Series/MapPoint/MapPointSeries.js",[a["Core/Series/Series.js"],a["Core/Color/Palette.js"],
a["Series/MapPoint/MapPointPoint.js"],a["Core/Utilities.js"]],function(a,c,m,p){var h=this&&this.__extends||function(){var a=function(b,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var d in a)a.hasOwnProperty(d)&&(b[d]=a[d])};return a(b,d)};return function(b,d){function c(){this.constructor=b}a(b,d);b.prototype=null===d?Object.create(d):(c.prototype=d.prototype,new c)}}(),u=a.seriesTypes.scatter,k=p.extend,n=p.merge;p=function(a){function b(){var b=
null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}h(b,a);b.prototype.drawDataLabels=function(){a.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)};b.defaultOptions=n(u.defaultOptions,{dataLabels:{crop:!1,defer:!1,enabled:!0,formatter:function(){return this.point.name},overflow:!1,style:{color:c.neutralColor100}}});return b}(u);k(p.prototype,{type:"mappoint",forceDL:!0,pointClass:m});a.registerSeriesType("mappoint",
p);"";return p});y(a,"Series/Bubble/BubblePoint.js",[a["Core/Series/Series.js"],a["Core/Series/Point.js"],a["Core/Utilities.js"]],function(a,c,m){var p=this&&this.__extends||function(){var a=function(c,k){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(c,k)};return function(c,k){function h(){this.constructor=c}a(c,k);c.prototype=null===k?Object.create(k):(h.prototype=k.prototype,new h)}}();
m=m.extend;a=function(a){function h(){var c=null!==a&&a.apply(this,arguments)||this;c.options=void 0;c.series=void 0;return c}p(h,a);h.prototype.haloPath=function(a){return c.prototype.haloPath.call(this,0===a?0:(this.marker?this.marker.radius||0:0)+a)};return h}(a.seriesTypes.scatter.prototype.pointClass);m(a.prototype,{ttBelow:!1});return a});y(a,"Series/Bubble/BubbleLegend.js",[a["Core/Chart/Chart.js"],a["Core/Color/Color.js"],a["Core/Globals.js"],a["Core/Legend.js"],a["Series/Line/LineSeries.js"],
a["Core/Color/Palette.js"],a["Core/Utilities.js"]],function(a,c,m,p,h,u,k){var n=c.parse,e=m.noop;c=k.addEvent;var b=k.arrayMax,d=k.arrayMin,f=k.isNumber,v=k.merge,A=k.objectEach,F=k.pick,z=k.setOptions,E=k.stableSort,w=k.wrap;"";z({legend:{bubbleLegend:{borderColor:void 0,borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,connectorColor:void 0,connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,align:"right",style:{fontSize:10,
color:void 0},x:0,y:0},maxSize:60,minSize:10,legendIndex:0,ranges:{value:void 0,borderColor:void 0,color:void 0,connectorColor:void 0},sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}}});z=function(){function a(b,a){this.options=this.symbols=this.visible=this.ranges=this.movementX=this.maxLabel=this.legendSymbol=this.legendItemWidth=this.legendItemHeight=this.legendItem=this.legendGroup=this.legend=this.fontMetrics=this.chart=void 0;this.setState=e;this.init(b,a)}a.prototype.init=function(b,
a){this.options=b;this.visible=!0;this.chart=a.chart;this.legend=a};a.prototype.addToLegend=function(b){b.splice(this.options.legendIndex,0,this)};a.prototype.drawLegendSymbol=function(b){var a=this.chart,d=this.options,c=F(b.options.itemDistance,20),e=d.ranges;var t=d.connectorDistance;this.fontMetrics=a.renderer.fontMetrics(d.labels.style.fontSize.toString()+"px");e&&e.length&&f(e[0].value)?(E(e,function(b,a){return a.value-b.value}),this.ranges=e,this.setOptions(),this.render(),a=this.getMaxLabelSize(),
e=this.ranges[0].radius,b=2*e,t=t-e+a.width,t=0<t?t:0,this.maxLabel=a,this.movementX="left"===d.labels.align?t:0,this.legendItemWidth=b+t+c,this.legendItemHeight=b+this.fontMetrics.h/2):b.options.bubbleLegend.autoRanges=!0};a.prototype.setOptions=function(){var b=this.ranges,a=this.options,d=this.chart.series[a.seriesIndex],c=this.legend.baseline,f={"z-index":a.zIndex,"stroke-width":a.borderWidth},e={"z-index":a.zIndex,"stroke-width":a.connectorWidth},k=this.getLabelStyles(),l=d.options.marker.fillOpacity,
h=this.chart.styledMode;b.forEach(function(g,r){h||(f.stroke=F(g.borderColor,a.borderColor,d.color),f.fill=F(g.color,a.color,1!==l?n(d.color).setOpacity(l).get("rgba"):d.color),e.stroke=F(g.connectorColor,a.connectorColor,d.color));b[r].radius=this.getRangeRadius(g.value);b[r]=v(b[r],{center:b[0].radius-b[r].radius+c});h||v(!0,b[r],{bubbleStyle:v(!1,f),connectorStyle:v(!1,e),labelStyle:k})},this)};a.prototype.getLabelStyles=function(){var b=this.options,a={},d="left"===b.labels.align,c=this.legend.options.rtl;
A(b.labels.style,function(b,d){"color"!==d&&"fontSize"!==d&&"z-index"!==d&&(a[d]=b)});return v(!1,a,{"font-size":b.labels.style.fontSize,fill:F(b.labels.style.color,u.neutralColor100),"z-index":b.zIndex,align:c||d?"right":"left"})};a.prototype.getRangeRadius=function(b){var a=this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,a.ranges[a.ranges.length-1].value,a.ranges[0].value,a.minSize,a.maxSize,b)};a.prototype.render=function(){var b=this.chart.renderer,a=this.options.zThreshold;
this.symbols||(this.symbols={connectors:[],bubbleItems:[],labels:[]});this.legendSymbol=b.g("bubble-legend");this.legendItem=b.g("bubble-legend-item");this.legendSymbol.translateX=0;this.legendSymbol.translateY=0;this.ranges.forEach(function(b){b.value>=a&&this.renderRange(b)},this);this.legendSymbol.add(this.legendItem);this.legendItem.add(this.legendGroup);this.hideOverlappingLabels()};a.prototype.renderRange=function(b){var a=this.options,d=a.labels,c=this.chart.renderer,f=this.symbols,e=f.labels,
t=b.center,l=Math.abs(b.radius),h=a.connectorDistance||0,k=d.align,n=d.style.fontSize;h=this.legend.options.rtl||"left"===k?-h:h;d=a.connectorWidth;var m=this.ranges[0].radius||0,v=t-l-a.borderWidth/2+d/2;n=n/2-(this.fontMetrics.h-n)/2;var p=c.styledMode;"center"===k&&(h=0,a.connectorDistance=0,b.labelStyle.align="center");k=v+a.labels.y;var B=m+h+a.labels.x;f.bubbleItems.push(c.circle(m,t+((v%1?1:.5)-(d%2?0:.5)),l).attr(p?{}:b.bubbleStyle).addClass((p?"highcharts-color-"+this.options.seriesIndex+
" ":"")+"highcharts-bubble-legend-symbol "+(a.className||"")).add(this.legendSymbol));f.connectors.push(c.path(c.crispLine([["M",m,v],["L",m+h,v]],a.connectorWidth)).attr(p?{}:b.connectorStyle).addClass((p?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+(a.connectorClassName||"")).add(this.legendSymbol));b=c.text(this.formatLabel(b),B,k+n).attr(p?{}:b.labelStyle).addClass("highcharts-bubble-legend-labels "+(a.labels.className||"")).add(this.legendSymbol);
e.push(b);b.placed=!0;b.alignAttr={x:B,y:k+n}};a.prototype.getMaxLabelSize=function(){var b,a;this.symbols.labels.forEach(function(d){a=d.getBBox(!0);b=b?a.width>b.width?a:b:a});return b||{}};a.prototype.formatLabel=function(b){var a=this.options,d=a.labels.formatter;a=a.labels.format;var c=this.chart.numberFormatter;return a?k.format(a,b):d?d.call(b):c(b.value,1)};a.prototype.hideOverlappingLabels=function(){var b=this.chart,a=this.symbols;!this.options.labels.allowOverlap&&a&&(b.hideOverlappingLabels(a.labels),
a.labels.forEach(function(b,d){b.newOpacity?b.newOpacity!==b.oldOpacity&&a.connectors[d].show():a.connectors[d].hide()}))};a.prototype.getRanges=function(){var a=this.legend.bubbleLegend,c=a.options.ranges,g,e=Number.MAX_VALUE,h=-Number.MAX_VALUE;a.chart.series.forEach(function(a){a.isBubble&&!a.ignoreSeries&&(g=a.zData.filter(f),g.length&&(e=F(a.options.zMin,Math.min(e,Math.max(d(g),!1===a.options.displayNegative?a.options.zThreshold:-Number.MAX_VALUE))),h=F(a.options.zMax,Math.max(h,b(g)))))});
var k=e===h?[{value:h}]:[{value:e},{value:(e+h)/2},{value:h,autoRanges:!0}];c.length&&c[0].radius&&k.reverse();k.forEach(function(b,a){c&&c[a]&&(k[a]=v(!1,c[a],b))});return k};a.prototype.predictBubbleSizes=function(){var b=this.chart,a=this.fontMetrics,d=b.legend.options,c="horizontal"===d.layout,f=c?b.legend.lastLineHeight:0,e=b.plotSizeX,h=b.plotSizeY,l=b.series[this.options.seriesIndex];b=Math.ceil(l.minPxSize);var k=Math.ceil(l.maxPxSize);l=l.options.maxSize;var n=Math.min(h,e);if(d.floating||
!/%$/.test(l))a=k;else if(l=parseFloat(l),a=(n+f-a.h/2)*l/100/(l/100+1),c&&h-a>=e||!c&&e-a>=h)a=k;return[b,Math.ceil(a)]};a.prototype.updateRanges=function(b,a){var d=this.legend.options.bubbleLegend;d.minSize=b;d.maxSize=a;d.ranges=this.getRanges()};a.prototype.correctSizes=function(){var b=this.legend,a=this.chart.series[this.options.seriesIndex];1<Math.abs(Math.ceil(a.maxPxSize)-this.options.maxSize)&&(this.updateRanges(this.options.minSize,a.maxPxSize),b.render())};return a}();c(p,"afterGetAllItems",
function(b){var a=this.bubbleLegend,d=this.options,c=d.bubbleLegend,f=this.chart.getVisibleBubbleSeriesIndex();a&&a.ranges&&a.ranges.length&&(c.ranges.length&&(c.autoRanges=!!c.ranges[0].autoRanges),this.destroyItem(a));0<=f&&d.enabled&&c.enabled&&(c.seriesIndex=f,this.bubbleLegend=new m.BubbleLegend(c,this),this.bubbleLegend.addToLegend(b.allItems))});a.prototype.getVisibleBubbleSeriesIndex=function(){for(var b=this.series,a=0;a<b.length;){if(b[a]&&b[a].isBubble&&b[a].visible&&b[a].zData.length)return a;
a++}return-1};p.prototype.getLinesHeights=function(){var b=this.allItems,a=[],d=b.length,c,f=0;for(c=0;c<d;c++)if(b[c].legendItemHeight&&(b[c].itemHeight=b[c].legendItemHeight),b[c]===b[d-1]||b[c+1]&&b[c]._legendItemPos[1]!==b[c+1]._legendItemPos[1]){a.push({height:0});var e=a[a.length-1];for(f;f<=c;f++)b[f].itemHeight>e.height&&(e.height=b[f].itemHeight);e.step=c}return a};p.prototype.retranslateItems=function(b){var a,d,c,f=this.options.rtl,e=0;this.allItems.forEach(function(g,q){a=g.legendGroup.translateX;
d=g._legendItemPos[1];if((c=g.movementX)||f&&g.ranges)c=f?a-g.options.maxSize/2:a+c,g.legendGroup.attr({translateX:c});q>b[e].step&&e++;g.legendGroup.attr({translateY:Math.round(d+b[e].height/2)});g._legendItemPos[1]=d+b[e].height/2})};c(h,"legendItemClick",function(){var b=this.chart,a=this.visible,d=this.chart.legend;d&&d.bubbleLegend&&(this.visible=!a,this.ignoreSeries=a,b=0<=b.getVisibleBubbleSeriesIndex(),d.bubbleLegend.visible!==b&&(d.update({bubbleLegend:{enabled:b}}),d.bubbleLegend.visible=
b),this.visible=a)});w(a.prototype,"drawChartBox",function(b,a,d){var c=this.legend,f=0<=this.getVisibleBubbleSeriesIndex();if(c&&c.options.enabled&&c.bubbleLegend&&c.options.bubbleLegend.autoRanges&&f){var e=c.bubbleLegend.options;f=c.bubbleLegend.predictBubbleSizes();c.bubbleLegend.updateRanges(f[0],f[1]);e.placed||(c.group.placed=!1,c.allItems.forEach(function(b){b.legendGroup.translateY=null}));c.render();this.getMargins();this.axes.forEach(function(b){b.visible&&b.render();e.placed||(b.setScale(),
b.updateNames(),A(b.ticks,function(b){b.isNew=!0;b.isNewLabel=!0}))});e.placed=!0;this.getMargins();b.call(this,a,d);c.bubbleLegend.correctSizes();c.retranslateItems(c.getLinesHeights())}else b.call(this,a,d),c&&c.options.enabled&&c.bubbleLegend&&(c.render(),c.retranslateItems(c.getLinesHeights()))});m.BubbleLegend=z;return m.BubbleLegend});y(a,"Series/Bubble/BubbleSeries.js",[a["Core/Axis/Axis.js"],a["Core/Series/Series.js"],a["Series/Bubble/BubblePoint.js"],a["Core/Color/Color.js"],a["Core/Globals.js"],
a["Series/Line/LineSeries.js"],a["Core/Utilities.js"]],function(a,c,m,p,h,u,k){var n=this&&this.__extends||function(){var b=function(a,d){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var d in a)a.hasOwnProperty(d)&&(b[d]=a[d])};return b(a,d)};return function(a,d){function c(){this.constructor=a}b(a,d);a.prototype=null===d?Object.create(d):(c.prototype=d.prototype,new c)}}(),e=c.seriesTypes,b=e.column,d=e.scatter,f=p.parse;p=h.noop;var v=
k.arrayMax,A=k.arrayMin,F=k.clamp,z=k.extend,E=k.isNumber,w=k.merge,B=k.pick,t=k.pInt;k=function(b){function a(){var a=null!==b&&b.apply(this,arguments)||this;a.data=void 0;a.maxPxSize=void 0;a.minPxSize=void 0;a.options=void 0;a.points=void 0;a.radii=void 0;a.yData=void 0;a.zData=void 0;return a}n(a,b);a.prototype.animate=function(b){!b&&this.points.length<this.options.animationLimit&&this.points.forEach(function(b){var a=b.graphic;a&&a.width&&(this.hasRendered||a.attr({x:b.plotX,y:b.plotY,width:1,
height:1}),a.animate(this.markerAttribs(b),this.options.animation))},this)};a.prototype.getRadii=function(b,a,d){var c=this.zData,g=this.yData,f=d.minPxSize,e=d.maxPxSize,h=[];var k=0;for(d=c.length;k<d;k++){var q=c[k];h.push(this.getRadius(b,a,f,e,q,g[k]))}this.radii=h};a.prototype.getRadius=function(b,a,d,c,g,f){var e=this.options,l="width"!==e.sizeBy,h=e.zThreshold,k=a-b,q=.5;if(null===f||null===g)return null;if(E(g)){e.sizeByAbsoluteValue&&(g=Math.abs(g-h),k=Math.max(a-h,Math.abs(b-h)),b=0);if(g<
b)return d/2-1;0<k&&(q=(g-b)/k)}l&&0<=q&&(q=Math.sqrt(q));return Math.ceil(d+q*(c-d))/2};a.prototype.hasData=function(){return!!this.processedXData.length};a.prototype.pointAttribs=function(b,a){var d=this.options.marker.fillOpacity;b=u.prototype.pointAttribs.call(this,b,a);1!==d&&(b.fill=f(b.fill).setOpacity(d).get("rgba"));return b};a.prototype.translate=function(){var a,d=this.data,c=this.radii;b.prototype.translate.call(this);for(a=d.length;a--;){var g=d[a];var f=c?c[a]:0;E(f)&&f>=this.minPxSize/
2?(g.marker=z(g.marker,{radius:f,width:2*f,height:2*f}),g.dlBox={x:g.plotX-f,y:g.plotY-f,width:2*f,height:2*f}):g.shapeArgs=g.plotY=g.dlBox=void 0}};a.defaultOptions=w(d.defaultOptions,{dataLabels:{formatter:function(){return this.point.z},inside:!0,verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},
turboThreshold:0,zThreshold:0,zoneAxis:"z"});return a}(d);z(k.prototype,{alignDataLabel:b.prototype.alignDataLabel,applyZones:p,bubblePadding:!0,buildKDTree:p,directTouch:!0,isBubble:!0,pointArrayMap:["y","z"],pointClass:m,parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",zoneAxis:"z"});a.prototype.beforePadding=function(){var b=this,a=this.len,d=this.chart,c=0,f=a,e=this.isXAxis,l=e?"xData":"yData",h=this.min,k={},n=Math.min(d.plotWidth,d.plotHeight),m=Number.MAX_VALUE,
p=-Number.MAX_VALUE,u=this.max-h,w=a/u,z=[];this.series.forEach(function(a){var c=a.options;!a.bubblePadding||!a.visible&&d.options.chart.ignoreHiddenSeries||(b.allowZoomOutside=!0,z.push(a),e&&(["minSize","maxSize"].forEach(function(b){var a=c[b],d=/%$/.test(a);a=t(a);k[b]=d?n*a/100:a}),a.minPxSize=k.minSize,a.maxPxSize=Math.max(k.maxSize,k.minSize),a=a.zData.filter(E),a.length&&(m=B(c.zMin,F(A(a),!1===c.displayNegative?c.zThreshold:-Number.MAX_VALUE,m)),p=B(c.zMax,Math.max(p,v(a))))))});z.forEach(function(a){var d=
a[l],g=d.length;e&&a.getRadii(m,p,a);if(0<u)for(;g--;)if(E(d[g])&&b.dataMin<=d[g]&&d[g]<=b.max){var k=a.radii?a.radii[g]:0;c=Math.min((d[g]-h)*w-k,c);f=Math.max((d[g]-h)*w+k,f)}});z.length&&0<u&&!this.logarithmic&&(f-=a,w*=(a+Math.max(0,c)-Math.min(f,a))/a,[["min","userMin",c],["max","userMax",f]].forEach(function(a){"undefined"===typeof B(b.options[a[0]],b[a[1]])&&(b[a[0]]+=a[2]/w)}))};c.registerSeriesType("bubble",k);"";"";return k});y(a,"Series/MapBubble/MapBubblePoint.js",[a["Core/Series/Series.js"],
a["Core/Utilities.js"]],function(a,c){var m=this&&this.__extends||function(){var a=function(c,e){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,d){a.__proto__=d}||function(a,d){for(var b in d)d.hasOwnProperty(b)&&(a[b]=d[b])};return a(c,e)};return function(c,e){function b(){this.constructor=c}a(c,e);c.prototype=null===e?Object.create(e):(b.prototype=e.prototype,new b)}}(),p=a.seriesTypes,h=p.map;a=c.extend;var u=c.merge;c=function(a){function c(){return null!==a&&a.apply(this,
arguments)||this}m(c,a);c.prototype.applyOptions=function(c,b){return c&&"undefined"!==typeof c.lat&&"undefined"!==typeof c.lon?a.prototype.applyOptions.call(this,u(c,this.series.chart.fromLatLonToPoint(c)),b):h.prototype.pointClass.prototype.applyOptions.call(this,c,b)};c.prototype.isValid=function(){return"number"===typeof this.z};return c}(p.bubble.prototype.pointClass);a(c.prototype,{ttBelow:!1});return c});y(a,"Series/MapBubble/MapBubbleSeries.js",[a["Core/Series/Series.js"],a["Series/Bubble/BubbleSeries.js"],
a["Series/MapBubble/MapBubblePoint.js"],a["Series/Map/MapSeries.js"],a["Core/Utilities.js"]],function(a,c,m,p,h){var u=this&&this.__extends||function(){var a=function(b,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d])};return a(b,d)};return function(b,d){function c(){this.constructor=b}a(b,d);b.prototype=null===d?Object.create(d):(c.prototype=d.prototype,new c)}}(),k=h.extend,n=h.merge;h=function(a){function b(){var b=
null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}u(b,a);b.defaultOptions=n(c.defaultOptions,{animationLimit:500,tooltip:{pointFormat:"{point.name}: {point.z}"}});return b}(c);k(h.prototype,{type:"mapbubble",getBox:p.prototype.getBox,pointArrayMap:["z"],pointClass:m,setData:p.prototype.setData,setOptions:p.prototype.setOptions,xyFromShape:!0});a.registerSeriesType("mapbubble",h);"";return h});y(a,"Series/Heatmap/HeatmapPoint.js",[a["Core/Series/Series.js"],
a["Mixins/ColorMapSeries.js"],a["Core/Utilities.js"]],function(a,c,m){var p=this&&this.__extends||function(){var a=function(c,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d])};return a(c,b)};return function(c,b){function d(){this.constructor=c}a(c,b);c.prototype=null===b?Object.create(b):(d.prototype=b.prototype,new d)}}();c=c.colorMapPointMixin;var h=m.clamp,u=m.extend,k=m.pick;a=function(a){function c(){var b=
null!==a&&a.apply(this,arguments)||this;b.options=void 0;b.series=void 0;b.value=void 0;b.x=void 0;b.y=void 0;return b}p(c,a);c.prototype.applyOptions=function(b,d){b=a.prototype.applyOptions.call(this,b,d);b.formatPrefix=b.isNull||null===b.value?"null":"point";return b};c.prototype.getCellAttributes=function(){var a=this.series,d=a.options,c=(d.colsize||1)/2,e=(d.rowsize||1)/2,m=a.xAxis,n=a.yAxis,p=this.options.marker||a.options.marker;a=a.pointPlacementToXValue();var u=k(this.pointPadding,d.pointPadding,
0),w={x1:h(Math.round(m.len-(m.translate(this.x-c,!1,!0,!1,!0,-a)||0)),-m.len,2*m.len),x2:h(Math.round(m.len-(m.translate(this.x+c,!1,!0,!1,!0,-a)||0)),-m.len,2*m.len),y1:h(Math.round(n.translate(this.y-e,!1,!0,!1,!0)||0),-n.len,2*n.len),y2:h(Math.round(n.translate(this.y+e,!1,!0,!1,!0)||0),-n.len,2*n.len)};[["width","x"],["height","y"]].forEach(function(a){var b=a[0];a=a[1];var d=a+"1",c=a+"2",f=Math.abs(w[d]-w[c]),e=p&&p.lineWidth||0,h=Math.abs(w[d]+w[c])/2;p[b]&&p[b]<f&&(w[d]=h-p[b]/2-e/2,w[c]=
h+p[b]/2+e/2);u&&("y"===a&&(d=c,c=a+"1"),w[d]+=u,w[c]-=u)});return w};c.prototype.haloPath=function(a){if(!a)return[];var b=this.shapeArgs;return["M",b.x-a,b.y-a,"L",b.x-a,b.y+b.height+a,b.x+b.width+a,b.y+b.height+a,b.x+b.width+a,b.y-a,"Z"]};c.prototype.isValid=function(){return Infinity!==this.value&&-Infinity!==this.value};return c}(a.seriesTypes.scatter.prototype.pointClass);u(a.prototype,{dataLabelOnNull:c.dataLabelOnNull,setState:c.setState});return a});y(a,"Series/Heatmap/HeatmapSeries.js",
[a["Core/Series/Series.js"],a["Mixins/ColorMapSeries.js"],a["Core/Globals.js"],a["Series/Heatmap/HeatmapPoint.js"],a["Mixins/LegendSymbol.js"],a["Core/Color/Palette.js"],a["Core/Renderer/SVG/SVGRenderer.js"],a["Core/Utilities.js"]],function(a,c,m,p,h,u,k,n){var e=this&&this.__extends||function(){var a=function(b,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d])};return a(b,d)};return function(b,d){function c(){this.constructor=
b}a(b,d);b.prototype=null===d?Object.create(d):(c.prototype=d.prototype,new c)}}(),b=a.seriesTypes,d=b.column,f=b.line,v=b.scatter;c=c.colorMapSeriesMixin;b=m.noop;var A=k.prototype.symbols,y=n.extend,z=n.fireEvent,E=n.isNumber,w=n.merge,B=n.pick;k=function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.colorAxis=void 0;b.data=void 0;b.options=void 0;b.points=void 0;b.valueMax=NaN;b.valueMin=NaN;return b}e(b,a);b.prototype.drawPoints=function(){var a=this;if((this.options.marker||
{}).enabled||this._hasPointMarkers)f.prototype.drawPoints.call(this),this.points.forEach(function(b){b.graphic&&b.graphic[a.chart.styledMode?"css":"animate"](a.colorAttribs(b))})};b.prototype.getExtremes=function(){var a=f.prototype.getExtremes.call(this,this.valueData),b=a.dataMin;a=a.dataMax;E(b)&&(this.valueMin=b);E(a)&&(this.valueMax=a);return f.prototype.getExtremes.call(this)};b.prototype.getValidPoints=function(a,b){return f.prototype.getValidPoints.call(this,a,b,!0)};b.prototype.hasData=function(){return!!this.processedXData.length};
b.prototype.init=function(){f.prototype.init.apply(this,arguments);var a=this.options;a.pointRange=B(a.pointRange,a.colsize||1);this.yAxis.axisPointRange=a.rowsize||1;y(A,{ellipse:A.circle,rect:A.square})};b.prototype.markerAttribs=function(a,b){var d=a.marker||{},c=this.options.marker||{},f=a.shapeArgs||{},g={};if(a.hasImage)return{x:a.plotX,y:a.plotY};if(b){var e=c.states[b]||{};var h=d.states&&d.states[b]||{};[["width","x"],["height","y"]].forEach(function(a){g[a[0]]=(h[a[0]]||e[a[0]]||f[a[0]])+
(h[a[0]+"Plus"]||e[a[0]+"Plus"]||0);g[a[1]]=f[a[1]]+(f[a[0]]-g[a[0]])/2})}return b?g:f};b.prototype.pointAttribs=function(a,b){var d=f.prototype.pointAttribs.call(this,a,b),c=this.options||{},g=this.chart.options.plotOptions||{},e=g.series||{},h=g.heatmap||{};g=c.borderColor||h.borderColor||e.borderColor;e=c.borderWidth||h.borderWidth||e.borderWidth||d["stroke-width"];d.stroke=a&&a.marker&&a.marker.lineColor||c.marker&&c.marker.lineColor||g||this.color;d["stroke-width"]=e;b&&(a=w(c.states[b],c.marker&&
c.marker.states[b],a&&a.options.states&&a.options.states[b]||{}),b=a.brightness,d.fill=a.color||m.color(d.fill).brighten(b||0).get(),d.stroke=a.lineColor);return d};b.prototype.setClip=function(a){var b=this.chart;f.prototype.setClip.apply(this,arguments);(!1!==this.options.clip||a)&&this.markerGroup.clip((a||this.clipBox)&&this.sharedClipKey?b[this.sharedClipKey]:b.clipRect)};b.prototype.translate=function(){var a=this.options,b=a.marker&&a.marker.symbol||"",d=A[b]?b:"rect";a=this.options;var c=
-1!==["circle","square"].indexOf(d);this.generatePoints();this.points.forEach(function(a){var f=a.getCellAttributes(),e={x:Math.min(f.x1,f.x2),y:Math.min(f.y1,f.y2),width:Math.max(Math.abs(f.x2-f.x1),0),height:Math.max(Math.abs(f.y2-f.y1),0)};var g=a.hasImage=0===(a.marker&&a.marker.symbol||b||"").indexOf("url");if(c){var h=Math.abs(e.width-e.height);e.x=Math.min(f.x1,f.x2)+(e.width<e.height?0:h/2);e.y=Math.min(f.y1,f.y2)+(e.width<e.height?h/2:0);e.width=e.height=Math.min(e.width,e.height)}h={plotX:(f.x1+
f.x2)/2,plotY:(f.y1+f.y2)/2,clientX:(f.x1+f.x2)/2,shapeType:"path",shapeArgs:w(!0,e,{d:A[d](e.x,e.y,e.width,e.height)})};g&&(a.marker={width:e.width,height:e.height});y(a,h)});z(this,"afterTranslate")};b.defaultOptions=w(v.defaultOptions,{animation:!1,borderWidth:0,nullColor:u.neutralColor3,dataLabels:{formatter:function(){return this.point.value},inside:!0,verticalAlign:"middle",crop:!1,overflow:!1,padding:0},marker:{symbol:"rect",radius:0,lineColor:void 0,states:{hover:{lineWidthPlus:0},select:{}}},
clip:!0,pointRange:null,tooltip:{pointFormat:"{point.x}, {point.y}: {point.value}<br/>"},states:{hover:{halo:!1,brightness:.2}}});return b}(v);y(k.prototype,{alignDataLabel:d.prototype.alignDataLabel,axisTypes:c.axisTypes,colorAttribs:c.colorAttribs,colorKey:c.colorKey,directTouch:!0,drawLegendSymbol:h.drawRectangle,getBox:b,getExtremesFromAll:!0,getSymbol:f.prototype.getSymbol,hasPointSpecificOptions:!0,parallelArrays:c.parallelArrays,pointArrayMap:["y","value"],pointClass:p,trackerGroups:c.trackerGroups});
a.registerSeriesType("heatmap",k);"";"";return k});y(a,"Extensions/GeoJSON.js",[a["Core/Chart/Chart.js"],a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,c,m){function p(a,d){var b,c=!1,e=a.x,h=a.y;a=0;for(b=d.length-1;a<d.length;b=a++){var k=d[a][1]>h;var m=d[b][1]>h;k!==m&&e<(d[b][0]-d[a][0])*(h-d[a][1])/(d[b][1]-d[a][1])+d[a][0]&&(c=!c)}return c}var h=c.win,u=m.error,k=m.extend,n=m.format,e=m.merge;m=m.wrap;"";a.prototype.transformFromLatLon=function(a,d){var b,c=(null===(b=this.userOptions.chart)||
void 0===b?void 0:b.proj4)||h.proj4;if(!c)return u(21,!1,this),{x:0,y:null};a=c(d.crs,[a.lon,a.lat]);b=d.cosAngle||d.rotation&&Math.cos(d.rotation);c=d.sinAngle||d.rotation&&Math.sin(d.rotation);a=d.rotation?[a[0]*b+a[1]*c,-a[0]*c+a[1]*b]:a;return{x:((a[0]-(d.xoffset||0))*(d.scale||1)+(d.xpan||0))*(d.jsonres||1)+(d.jsonmarginX||0),y:(((d.yoffset||0)-a[1])*(d.scale||1)+(d.ypan||0))*(d.jsonres||1)-(d.jsonmarginY||0)}};a.prototype.transformToLatLon=function(a,d){if("undefined"===typeof h.proj4)u(21,
!1,this);else{a={x:((a.x-(d.jsonmarginX||0))/(d.jsonres||1)-(d.xpan||0))/(d.scale||1)+(d.xoffset||0),y:((-a.y-(d.jsonmarginY||0))/(d.jsonres||1)+(d.ypan||0))/(d.scale||1)+(d.yoffset||0)};var b=d.cosAngle||d.rotation&&Math.cos(d.rotation),c=d.sinAngle||d.rotation&&Math.sin(d.rotation);d=h.proj4(d.crs,"WGS84",d.rotation?{x:a.x*b+a.y*-c,y:a.x*c+a.y*b}:a);return{lat:d.y,lon:d.x}}};a.prototype.fromPointToLatLon=function(a){var b=this.mapTransforms,c;if(b){for(c in b)if(Object.hasOwnProperty.call(b,c)&&
b[c].hitZone&&p({x:a.x,y:-a.y},b[c].hitZone.coordinates[0]))return this.transformToLatLon(a,b[c]);return this.transformToLatLon(a,b["default"])}u(22,!1,this)};a.prototype.fromLatLonToPoint=function(a){var b=this.mapTransforms,c;if(!b)return u(22,!1,this),{x:0,y:null};for(c in b)if(Object.hasOwnProperty.call(b,c)&&b[c].hitZone){var e=this.transformFromLatLon(a,b[c]);if(p({x:e.x,y:-e.y},b[c].hitZone.coordinates[0]))return e}return this.transformFromLatLon(a,b["default"])};c.geojson=function(a,c,e){var b=
[],d=[],f=function(a){a.forEach(function(a,b){0===b?d.push(["M",a[0],-a[1]]):d.push(["L",a[0],-a[1]])})};c=c||"map";a.features.forEach(function(a){var e=a.geometry,h=e.type;e=e.coordinates;a=a.properties;var m;d=[];"map"===c||"mapbubble"===c?("Polygon"===h?(e.forEach(f),d.push(["Z"])):"MultiPolygon"===h&&(e.forEach(function(a){a.forEach(f)}),d.push(["Z"])),d.length&&(m={path:d})):"mapline"===c?("LineString"===h?f(e):"MultiLineString"===h&&e.forEach(f),d.length&&(m={path:d})):"mappoint"===c&&"Point"===
h&&(m={x:e[0],y:-e[1]});m&&b.push(k(m,{name:a.name||a.NAME,properties:a}))});e&&a.copyrightShort&&(e.chart.mapCredits=n(e.chart.options.credits.mapText,{geojson:a}),e.chart.mapCreditsFull=n(e.chart.options.credits.mapTextFull,{geojson:a}));return b};m(a.prototype,"addCredits",function(a,c){c=e(!0,this.options.credits,c);this.mapCredits&&(c.href=null);a.call(this,c);this.credits&&this.mapCreditsFull&&this.credits.attr({title:this.mapCreditsFull})})});y(a,"masters/modules/map.src.js",[],function(){})});
//# sourceMappingURL=map.js.map