/*
 Highcharts JS v8.2.2 (2020-12-12)

 Force directed graph module

 (c) 2010-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(f){"object"===typeof module&&module.exports?(f["default"]=f,module.exports=f):"function"===typeof define&&define.amd?define("highcharts/modules/networkgraph",["highcharts"],function(h){f(h);f.Highcharts=h;return f}):f("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(f){function h(f,c,b,e){f.hasOwnProperty(c)||(f[c]=e.apply(null,b))}f=f?f._modules:{};h(f,"Mixins/Nodes.js",[f["Core/Globals.js"],f["Series/Line/LineSeries.js"],f["Core/Series/Point.js"],f["Core/Utilities.js"]],function(f,
c,b,e){var d=e.defined,g=e.extend,q=e.find,k=e.pick;return f.NodesMixin={createNode:function(d){function b(a,d){return q(a,function(a){return a.id===d})}var a=b(this.nodes,d),c=this.pointClass;if(!a){var e=this.options.nodes&&b(this.options.nodes,d);a=(new c).init(this,g({className:"highcharts-node",isNode:!0,id:d,y:1},e));a.linksTo=[];a.linksFrom=[];a.formatPrefix="node";a.name=a.name||a.options.id||"";a.mass=k(a.options.mass,a.options.marker&&a.options.marker.radius,this.options.marker&&this.options.marker.radius,
4);a.getSum=function(){var d=0,b=0;a.linksTo.forEach(function(a){d+=a.weight});a.linksFrom.forEach(function(a){b+=a.weight});return Math.max(d,b)};a.offset=function(d,b){for(var c=0,e=0;e<a[b].length;e++){if(a[b][e]===d)return c;c+=a[b][e].weight}};a.hasShape=function(){var d=0;a.linksTo.forEach(function(a){a.outgoing&&d++});return!a.linksTo.length||d!==a.linksTo.length};this.nodes.push(a)}return a},generatePoints:function(){var b=this.chart,e={};c.prototype.generatePoints.call(this);this.nodes||
(this.nodes=[]);this.colorCounter=0;this.nodes.forEach(function(a){a.linksFrom.length=0;a.linksTo.length=0;a.level=a.options.level});this.points.forEach(function(a){d(a.from)&&(e[a.from]||(e[a.from]=this.createNode(a.from)),e[a.from].linksFrom.push(a),a.fromNode=e[a.from],b.styledMode?a.colorIndex=k(a.options.colorIndex,e[a.from].colorIndex):a.color=a.options.color||e[a.from].color);d(a.to)&&(e[a.to]||(e[a.to]=this.createNode(a.to)),e[a.to].linksTo.push(a),a.toNode=e[a.to]);a.name=a.name||a.id},this);
this.nodeLookup=e},setData:function(){this.nodes&&(this.nodes.forEach(function(d){d.destroy()}),this.nodes.length=0);c.prototype.setData.apply(this,arguments)},destroy:function(){this.data=[].concat(this.points||[],this.nodes);return c.prototype.destroy.apply(this,arguments)},setNodeState:function(d){var e=arguments,a=this.isNode?this.linksTo.concat(this.linksFrom):[this.fromNode,this.toNode];"select"!==d&&a.forEach(function(a){a&&a.series&&(b.prototype.setState.apply(a,e),a.isNode||(a.fromNode.graphic&&
b.prototype.setState.apply(a.fromNode,e),a.toNode&&a.toNode.graphic&&b.prototype.setState.apply(a.toNode,e)))});b.prototype.setState.apply(this,e)}}});h(f,"Series/Networkgraph/Integrations.js",[f["Core/Globals.js"]],function(f){f.networkgraphIntegrations={verlet:{attractiveForceFunction:function(c,b){return(b-c)/c},repulsiveForceFunction:function(c,b){return(b-c)/c*(b>c?1:0)},barycenter:function(){var c=this.options.gravitationalConstant,b=this.barycenter.xFactor,e=this.barycenter.yFactor;b=(b-(this.box.left+
this.box.width)/2)*c;e=(e-(this.box.top+this.box.height)/2)*c;this.nodes.forEach(function(d){d.fixedPosition||(d.plotX-=b/d.mass/d.degree,d.plotY-=e/d.mass/d.degree)})},repulsive:function(c,b,e){b=b*this.diffTemperature/c.mass/c.degree;c.fixedPosition||(c.plotX+=e.x*b,c.plotY+=e.y*b)},attractive:function(c,b,e){var d=c.getMass(),g=-e.x*b*this.diffTemperature;b=-e.y*b*this.diffTemperature;c.fromNode.fixedPosition||(c.fromNode.plotX-=g*d.fromNode/c.fromNode.degree,c.fromNode.plotY-=b*d.fromNode/c.fromNode.degree);
c.toNode.fixedPosition||(c.toNode.plotX+=g*d.toNode/c.toNode.degree,c.toNode.plotY+=b*d.toNode/c.toNode.degree)},integrate:function(c,b){var e=-c.options.friction,d=c.options.maxSpeed,g=(b.plotX+b.dispX-b.prevX)*e;e*=b.plotY+b.dispY-b.prevY;var f=Math.abs,k=f(g)/(g||1);f=f(e)/(e||1);g=k*Math.min(d,Math.abs(g));e=f*Math.min(d,Math.abs(e));b.prevX=b.plotX+b.dispX;b.prevY=b.plotY+b.dispY;b.plotX+=g;b.plotY+=e;b.temperature=c.vectorLength({x:g,y:e})},getK:function(c){return Math.pow(c.box.width*c.box.height/
c.nodes.length,.5)}},euler:{attractiveForceFunction:function(c,b){return c*c/b},repulsiveForceFunction:function(c,b){return b*b/c},barycenter:function(){var c=this.options.gravitationalConstant,b=this.barycenter.xFactor,e=this.barycenter.yFactor;this.nodes.forEach(function(d){if(!d.fixedPosition){var g=d.getDegree();g*=1+g/2;d.dispX+=(b-d.plotX)*c*g/d.degree;d.dispY+=(e-d.plotY)*c*g/d.degree}})},repulsive:function(c,b,e,d){c.dispX+=e.x/d*b/c.degree;c.dispY+=e.y/d*b/c.degree},attractive:function(c,
b,e,d){var g=c.getMass(),f=e.x/d*b;b*=e.y/d;c.fromNode.fixedPosition||(c.fromNode.dispX-=f*g.fromNode/c.fromNode.degree,c.fromNode.dispY-=b*g.fromNode/c.fromNode.degree);c.toNode.fixedPosition||(c.toNode.dispX+=f*g.toNode/c.toNode.degree,c.toNode.dispY+=b*g.toNode/c.toNode.degree)},integrate:function(c,b){b.dispX+=b.dispX*c.options.friction;b.dispY+=b.dispY*c.options.friction;var e=b.temperature=c.vectorLength({x:b.dispX,y:b.dispY});0!==e&&(b.plotX+=b.dispX/e*Math.min(Math.abs(b.dispX),c.temperature),
b.plotY+=b.dispY/e*Math.min(Math.abs(b.dispY),c.temperature))},getK:function(c){return Math.pow(c.box.width*c.box.height/c.nodes.length,.3)}}}});h(f,"Series/Networkgraph/QuadTree.js",[f["Core/Globals.js"],f["Core/Utilities.js"]],function(f,c){c=c.extend;var b=f.QuadTreeNode=function(e){this.box=e;this.boxSize=Math.min(e.width,e.height);this.nodes=[];this.body=this.isInternal=!1;this.isEmpty=!0};c(b.prototype,{insert:function(e,d){this.isInternal?this.nodes[this.getBoxPosition(e)].insert(e,d-1):(this.isEmpty=
!1,this.body?d?(this.isInternal=!0,this.divideBox(),!0!==this.body&&(this.nodes[this.getBoxPosition(this.body)].insert(this.body,d-1),this.body=!0),this.nodes[this.getBoxPosition(e)].insert(e,d-1)):(d=new b({top:e.plotX,left:e.plotY,width:.1,height:.1}),d.body=e,d.isInternal=!1,this.nodes.push(d)):(this.isInternal=!1,this.body=e))},updateMassAndCenter:function(){var e=0,d=0,b=0;this.isInternal?(this.nodes.forEach(function(c){c.isEmpty||(e+=c.mass,d+=c.plotX*c.mass,b+=c.plotY*c.mass)}),d/=e,b/=e):
this.body&&(e=this.body.mass,d=this.body.plotX,b=this.body.plotY);this.mass=e;this.plotX=d;this.plotY=b},divideBox:function(){var e=this.box.width/2,d=this.box.height/2;this.nodes[0]=new b({left:this.box.left,top:this.box.top,width:e,height:d});this.nodes[1]=new b({left:this.box.left+e,top:this.box.top,width:e,height:d});this.nodes[2]=new b({left:this.box.left+e,top:this.box.top+d,width:e,height:d});this.nodes[3]=new b({left:this.box.left,top:this.box.top+d,width:e,height:d})},getBoxPosition:function(b){var d=
b.plotY<this.box.top+this.box.height/2;return b.plotX<this.box.left+this.box.width/2?d?0:3:d?1:2}});f=f.QuadTree=function(e,d,c,f){this.box={left:e,top:d,width:c,height:f};this.maxDepth=25;this.root=new b(this.box,"0");this.root.isInternal=!0;this.root.isRoot=!0;this.root.divideBox()};c(f.prototype,{insertNodes:function(b){b.forEach(function(b){this.root.insert(b,this.maxDepth)},this)},visitNodeRecursive:function(b,d,c){var e;b||(b=this.root);b===this.root&&d&&(e=d(b));!1!==e&&(b.nodes.forEach(function(b){if(b.isInternal){d&&
(e=d(b));if(!1===e)return;this.visitNodeRecursive(b,d,c)}else b.body&&d&&d(b.body);c&&c(b)},this),b===this.root&&c&&c(b))},calculateMassAndCenter:function(){this.visitNodeRecursive(null,null,function(b){b.updateMassAndCenter()})}})});h(f,"Series/Networkgraph/Layouts.js",[f["Core/Chart/Chart.js"],f["Core/Animation/AnimationUtilities.js"],f["Core/Globals.js"],f["Core/Utilities.js"]],function(f,c,b,e){var d=c.setAnimation;c=e.addEvent;var g=e.clamp,q=e.defined,k=e.extend,p=e.isFunction,m=e.pick;b.layouts=
{"reingold-fruchterman":function(){}};k(b.layouts["reingold-fruchterman"].prototype,{init:function(a){this.options=a;this.nodes=[];this.links=[];this.series=[];this.box={x:0,y:0,width:0,height:0};this.setInitialRendering(!0);this.integration=b.networkgraphIntegrations[a.integration];this.enableSimulation=a.enableSimulation;this.attractiveForce=m(a.attractiveForce,this.integration.attractiveForceFunction);this.repulsiveForce=m(a.repulsiveForce,this.integration.repulsiveForceFunction);this.approximation=
a.approximation},updateSimulation:function(a){this.enableSimulation=m(a,this.options.enableSimulation)},start:function(){var a=this.series,b=this.options;this.currentStep=0;this.forces=a[0]&&a[0].forces||[];this.chart=a[0]&&a[0].chart;this.initialRendering&&(this.initPositions(),a.forEach(function(a){a.finishedAnimating=!0;a.render()}));this.setK();this.resetSimulation(b);this.enableSimulation&&this.step()},step:function(){var a=this,c=this.series;a.currentStep++;"barnes-hut"===a.approximation&&(a.createQuadTree(),
a.quadTree.calculateMassAndCenter());a.forces.forEach(function(b){a[b+"Forces"](a.temperature)});a.applyLimits(a.temperature);a.temperature=a.coolDown(a.startTemperature,a.diffTemperature,a.currentStep);a.prevSystemTemperature=a.systemTemperature;a.systemTemperature=a.getSystemTemperature();a.enableSimulation&&(c.forEach(function(a){a.chart&&a.render()}),a.maxIterations--&&isFinite(a.temperature)&&!a.isStable()?(a.simulation&&b.win.cancelAnimationFrame(a.simulation),a.simulation=b.win.requestAnimationFrame(function(){a.step()})):
a.simulation=!1)},stop:function(){this.simulation&&b.win.cancelAnimationFrame(this.simulation)},setArea:function(a,b,c,d){this.box={left:a,top:b,width:c,height:d}},setK:function(){this.k=this.options.linkLength||this.integration.getK(this)},addElementsToCollection:function(a,b){a.forEach(function(a){-1===b.indexOf(a)&&b.push(a)})},removeElementFromCollection:function(a,b){a=b.indexOf(a);-1!==a&&b.splice(a,1)},clear:function(){this.nodes.length=0;this.links.length=0;this.series.length=0;this.resetSimulation()},
resetSimulation:function(){this.forcedStop=!1;this.systemTemperature=0;this.setMaxIterations();this.setTemperature();this.setDiffTemperature()},restartSimulation:function(){this.simulation?this.resetSimulation():(this.setInitialRendering(!1),this.enableSimulation?this.start():this.setMaxIterations(1),this.chart&&this.chart.redraw(),this.setInitialRendering(!0))},setMaxIterations:function(a){this.maxIterations=m(a,this.options.maxIterations)},setTemperature:function(){this.temperature=this.startTemperature=
Math.sqrt(this.nodes.length)},setDiffTemperature:function(){this.diffTemperature=this.startTemperature/(this.options.maxIterations+1)},setInitialRendering:function(a){this.initialRendering=a},createQuadTree:function(){this.quadTree=new b.QuadTree(this.box.left,this.box.top,this.box.width,this.box.height);this.quadTree.insertNodes(this.nodes)},initPositions:function(){var a=this.options.initialPositions;p(a)?(a.call(this),this.nodes.forEach(function(a){q(a.prevX)||(a.prevX=a.plotX);q(a.prevY)||(a.prevY=
a.plotY);a.dispX=0;a.dispY=0})):"circle"===a?this.setCircularPositions():this.setRandomPositions()},setCircularPositions:function(){function a(b){b.linksFrom.forEach(function(b){u[b.toNode.id]||(u[b.toNode.id]=!0,l.push(b.toNode),a(b.toNode))})}var b=this.box,c=this.nodes,d=2*Math.PI/(c.length+1),e=c.filter(function(a){return 0===a.linksTo.length}),l=[],u={},v=this.options.initialPositionRadius;e.forEach(function(b){l.push(b);a(b)});l.length?c.forEach(function(a){-1===l.indexOf(a)&&l.push(a)}):l=
c;l.forEach(function(a,c){a.plotX=a.prevX=m(a.plotX,b.width/2+v*Math.cos(c*d));a.plotY=a.prevY=m(a.plotY,b.height/2+v*Math.sin(c*d));a.dispX=0;a.dispY=0})},setRandomPositions:function(){function a(a){a=a*a/Math.PI;return a-=Math.floor(a)}var b=this.box,c=this.nodes,d=c.length+1;c.forEach(function(c,e){c.plotX=c.prevX=m(c.plotX,b.width*a(e));c.plotY=c.prevY=m(c.plotY,b.height*a(d+e));c.dispX=0;c.dispY=0})},force:function(a){this.integration[a].apply(this,Array.prototype.slice.call(arguments,1))},barycenterForces:function(){this.getBarycenter();
this.force("barycenter")},getBarycenter:function(){var a=0,b=0,c=0;this.nodes.forEach(function(d){b+=d.plotX*d.mass;c+=d.plotY*d.mass;a+=d.mass});return this.barycenter={x:b,y:c,xFactor:b/a,yFactor:c/a}},barnesHutApproximation:function(a,b){var c=this.getDistXY(a,b),d=this.vectorLength(c);if(a!==b&&0!==d)if(b.isInternal)if(b.boxSize/d<this.options.theta&&0!==d){var e=this.repulsiveForce(d,this.k);this.force("repulsive",a,e*b.mass,c,d);var l=!1}else l=!0;else e=this.repulsiveForce(d,this.k),this.force("repulsive",
a,e*b.mass,c,d);return l},repulsiveForces:function(){var a=this;"barnes-hut"===a.approximation?a.nodes.forEach(function(b){a.quadTree.visitNodeRecursive(null,function(c){return a.barnesHutApproximation(b,c)})}):a.nodes.forEach(function(b){a.nodes.forEach(function(c){if(b!==c&&!b.fixedPosition){var d=a.getDistXY(b,c);var e=a.vectorLength(d);if(0!==e){var l=a.repulsiveForce(e,a.k);a.force("repulsive",b,l*c.mass,d,e)}}})})},attractiveForces:function(){var a=this,b,c,d;a.links.forEach(function(e){e.fromNode&&
e.toNode&&(b=a.getDistXY(e.fromNode,e.toNode),c=a.vectorLength(b),0!==c&&(d=a.attractiveForce(c,a.k),a.force("attractive",e,d,b,c)))})},applyLimits:function(){var a=this;a.nodes.forEach(function(b){b.fixedPosition||(a.integration.integrate(a,b),a.applyLimitBox(b,a.box),b.dispX=0,b.dispY=0)})},applyLimitBox:function(a,b){var c=a.radius;a.plotX=g(a.plotX,b.left+c,b.width-c);a.plotY=g(a.plotY,b.top+c,b.height-c)},coolDown:function(a,b,c){return a-b*c},isStable:function(){return.00001>Math.abs(this.systemTemperature-
this.prevSystemTemperature)||0>=this.temperature},getSystemTemperature:function(){return this.nodes.reduce(function(a,b){return a+b.temperature},0)},vectorLength:function(a){return Math.sqrt(a.x*a.x+a.y*a.y)},getDistR:function(a,b){a=this.getDistXY(a,b);return this.vectorLength(a)},getDistXY:function(a,b){var c=a.plotX-b.plotX;a=a.plotY-b.plotY;return{x:c,y:a,absX:Math.abs(c),absY:Math.abs(a)}}});c(f,"predraw",function(){this.graphLayoutsLookup&&this.graphLayoutsLookup.forEach(function(a){a.stop()})});
c(f,"render",function(){function a(a){a.maxIterations--&&isFinite(a.temperature)&&!a.isStable()&&!a.enableSimulation&&(a.beforeStep&&a.beforeStep(),a.step(),c=!1,b=!0)}var b=!1;if(this.graphLayoutsLookup){d(!1,this);for(this.graphLayoutsLookup.forEach(function(a){a.start()});!c;){var c=!0;this.graphLayoutsLookup.forEach(a)}b&&this.series.forEach(function(a){a&&a.layout&&a.render()})}});c(f,"beforePrint",function(){this.graphLayoutsLookup&&(this.graphLayoutsLookup.forEach(function(a){a.updateSimulation(!1)}),
this.redraw())});c(f,"afterPrint",function(){this.graphLayoutsLookup&&this.graphLayoutsLookup.forEach(function(a){a.updateSimulation()});this.redraw()})});h(f,"Series/Networkgraph/DraggableNodes.js",[f["Core/Chart/Chart.js"],f["Core/Globals.js"],f["Core/Utilities.js"]],function(f,c,b){var e=b.addEvent;c.dragNodesMixin={onMouseDown:function(b,c){c=this.chart.pointer.normalize(c);b.fixedPosition={chartX:c.chartX,chartY:c.chartY,plotX:b.plotX,plotY:b.plotY};b.inDragMode=!0},onMouseMove:function(b,c){if(b.fixedPosition&&
b.inDragMode){var d=this.chart;c=d.pointer.normalize(c);var e=b.fixedPosition.chartX-c.chartX,f=b.fixedPosition.chartY-c.chartY;c=d.graphLayoutsLookup;if(5<Math.abs(e)||5<Math.abs(f))e=b.fixedPosition.plotX-e,f=b.fixedPosition.plotY-f,d.isInsidePlot(e,f)&&(b.plotX=e,b.plotY=f,b.hasDragged=!0,this.redrawHalo(b),c.forEach(function(b){b.restartSimulation()}))}},onMouseUp:function(b,c){b.fixedPosition&&(b.hasDragged&&(this.layout.enableSimulation?this.layout.start():this.chart.redraw()),b.inDragMode=
b.hasDragged=!1,this.options.fixedDraggable||delete b.fixedPosition)},redrawHalo:function(b){b&&this.halo&&this.halo.attr({d:b.haloPath(this.options.states.hover.halo.size)})}};e(f,"load",function(){var b=this,c,f,k;b.container&&(c=e(b.container,"mousedown",function(c){var d=b.hoverPoint;d&&d.series&&d.series.hasDraggableNodes&&d.series.options.draggable&&(d.series.onMouseDown(d,c),f=e(b.container,"mousemove",function(a){return d&&d.series&&d.series.onMouseMove(d,a)}),k=e(b.container.ownerDocument,
"mouseup",function(a){f();k();return d&&d.series&&d.series.onMouseUp(d,a)}))}));e(b,"destroy",function(){c()})})});h(f,"Series/Networkgraph/Networkgraph.js",[f["Core/Series/Series.js"],f["Core/Globals.js"],f["Series/Line/LineSeries.js"],f["Mixins/Nodes.js"],f["Core/Series/Point.js"],f["Core/Utilities.js"]],function(f,c,b,e,d,g){var h=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&
(a[c]=b[c])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),k=f.seriesTypes,p=g.addEvent,m=g.css,a=g.defined,t=g.extend,w=g.merge,r=g.pick,n=c.dragNodesMixin;"";g=function(a){function c(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.nodes=void 0;b.options=void 0;b.points=void 0;return b}h(c,a);c.defaultOptions=w(b.defaultOptions,{stickyTracking:!1,inactiveOtherPoints:!0,marker:{enabled:!0,
states:{inactive:{opacity:.3,animation:{duration:50}}}},states:{inactive:{linkOpacity:.3,animation:{duration:50}}},dataLabels:{formatter:function(){return this.key},linkFormatter:function(){return this.point.fromNode.name+"<br>"+this.point.toNode.name},linkTextPath:{enabled:!0},textPath:{enabled:!1},style:{transition:"opacity 2000ms"}},link:{color:"rgba(100, 100, 100, 0.5)",width:1},draggable:!0,layoutAlgorithm:{initialPositions:"circle",initialPositionRadius:1,enableSimulation:!1,theta:.5,maxSpeed:10,
approximation:"none",type:"reingold-fruchterman",integration:"euler",maxIterations:1E3,gravitationalConstant:.0625,friction:-.981},showInLegend:!1});return c}(b);t(g.prototype,{forces:["barycenter","repulsive","attractive"],hasDraggableNodes:!0,drawGraph:null,isCartesian:!1,requireSorting:!1,directTouch:!0,noSharedTooltip:!0,pointArrayMap:["from","to"],trackerGroups:["group","markerGroup","dataLabelsGroup"],drawTracker:k.column.prototype.drawTracker,animate:null,buildKDTree:c.noop,createNode:e.createNode,
destroy:function(){this.layout&&this.layout.removeElementFromCollection(this,this.layout.series);e.destroy.call(this)},init:function(){b.prototype.init.apply(this,arguments);p(this,"updatedData",function(){this.layout&&this.layout.stop()});return this},generatePoints:function(){var a;e.generatePoints.apply(this,arguments);this.options.nodes&&this.options.nodes.forEach(function(a){this.nodeLookup[a.id]||(this.nodeLookup[a.id]=this.createNode(a.id))},this);for(a=this.nodes.length-1;0<=a;a--){var b=
this.nodes[a];b.degree=b.getDegree();b.radius=r(b.marker&&b.marker.radius,this.options.marker&&this.options.marker.radius,0);this.nodeLookup[b.id]||b.remove()}this.data.forEach(function(a){a.formatPrefix="link"});this.indexateNodes()},getPointsCollection:function(){return this.nodes||[]},indexateNodes:function(){this.nodes.forEach(function(a,b){a.index=b})},markerAttribs:function(c,d){d=b.prototype.markerAttribs.call(this,c,d);a(c.plotY)||(d.y=0);d.x=(c.plotX||0)-(d.width/2||0);return d},translate:function(){this.processedXData||
this.processData();this.generatePoints();this.deferLayout();this.nodes.forEach(function(a){a.isInside=!0;a.linksFrom.forEach(function(a){a.shapeType="path";a.y=1})})},deferLayout:function(){var b=this.options.layoutAlgorithm,d=this.chart.graphLayoutsStorage,e=this.chart.graphLayoutsLookup,f=this.chart.options.chart;if(this.visible){d||(this.chart.graphLayoutsStorage=d={},this.chart.graphLayoutsLookup=e=[]);var g=d[b.type];g||(b.enableSimulation=a(f.forExport)?!f.forExport:b.enableSimulation,d[b.type]=
g=new c.layouts[b.type],g.init(b),e.splice(g.index,0,g));this.layout=g;g.setArea(0,0,this.chart.plotWidth,this.chart.plotHeight);g.addElementsToCollection([this],g.series);g.addElementsToCollection(this.nodes,g.nodes);g.addElementsToCollection(this.points,g.links)}},render:function(){var a=this.points,b=this.chart.hoverPoint,c=[];this.points=this.nodes;k.line.prototype.render.call(this);this.points=a;a.forEach(function(a){a.fromNode&&a.toNode&&(a.renderLink(),a.redrawLink())});b&&b.series===this&&
this.redrawHalo(b);this.chart.hasRendered&&!this.options.dataLabels.allowOverlap&&(this.nodes.concat(this.points).forEach(function(a){a.dataLabel&&c.push(a.dataLabel)}),this.chart.hideOverlappingLabels(c))},drawDataLabels:function(){var a=this.options.dataLabels.textPath;b.prototype.drawDataLabels.apply(this,arguments);this.points=this.data;this.options.dataLabels.textPath=this.options.dataLabels.linkTextPath;b.prototype.drawDataLabels.apply(this,arguments);this.points=this.nodes;this.options.dataLabels.textPath=
a},pointAttribs:function(a,c){var d=c||a&&a.state||"normal";c=b.prototype.pointAttribs.call(this,a,d);d=this.options.states[d];a&&!a.isNode&&(c=a.getLinkAttributes(),d&&(c={stroke:d.linkColor||c.stroke,dashstyle:d.linkDashStyle||c.dashstyle,opacity:r(d.linkOpacity,c.opacity),"stroke-width":d.linkColor||c["stroke-width"]}));return c},redrawHalo:n.redrawHalo,onMouseDown:n.onMouseDown,onMouseMove:n.onMouseMove,onMouseUp:n.onMouseUp,setState:function(a,c){c?(this.points=this.nodes.concat(this.data),b.prototype.setState.apply(this,
arguments),this.points=this.data):b.prototype.setState.apply(this,arguments);this.layout.simulation||a||this.render()}});n=function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.degree=void 0;b.linksFrom=void 0;b.linksTo=void 0;b.options=void 0;b.radius=void 0;b.series=void 0;b.toNode=void 0;return b}h(b,a);return b}(b.prototype.pointClass);t(n.prototype,{setState:e.setNodeState,init:function(){d.prototype.init.apply(this,arguments);this.series.options.draggable&&!this.series.chart.styledMode&&
(p(this,"mouseOver",function(){m(this.series.chart.container,{cursor:"move"})}),p(this,"mouseOut",function(){m(this.series.chart.container,{cursor:"default"})}));return this},getDegree:function(){var a=this.isNode?this.linksFrom.length+this.linksTo.length:0;return 0===a?1:a},getLinkAttributes:function(){var a=this.series.options.link,b=this.options;return{"stroke-width":r(b.width,a.width),stroke:b.color||a.color,dashstyle:b.dashStyle||a.dashStyle,opacity:r(b.opacity,a.opacity,1)}},renderLink:function(){if(!this.graphic&&
(this.graphic=this.series.chart.renderer.path(this.getLinkPath()).add(this.series.group),!this.series.chart.styledMode)){var a=this.series.pointAttribs(this);this.graphic.attr(a);(this.dataLabels||[]).forEach(function(b){b&&b.attr({opacity:a.opacity})})}},redrawLink:function(){var a=this.getLinkPath();if(this.graphic){this.shapeArgs={d:a};if(!this.series.chart.styledMode){var b=this.series.pointAttribs(this);this.graphic.attr(b);(this.dataLabels||[]).forEach(function(a){a&&a.attr({opacity:b.opacity})})}this.graphic.animate(this.shapeArgs);
var c=a[0];a=a[1];"M"===c[0]&&"L"===a[0]&&(this.plotX=(c[1]+a[1])/2,this.plotY=(c[2]+a[2])/2)}},getMass:function(){var a=this.fromNode.mass,b=this.toNode.mass,c=a+b;return{fromNode:1-a/c,toNode:1-b/c}},getLinkPath:function(){var a=this.fromNode,b=this.toNode;a.plotX>b.plotX&&(a=this.toNode,b=this.fromNode);return[["M",a.plotX||0,a.plotY||0],["L",b.plotX||0,b.plotY||0]]},isValid:function(){return!this.isNode||a(this.id)},remove:function(a,c){var d=this.series,e=d.options.nodes||[],f,g=e.length;if(this.isNode){d.points=
[];[].concat(this.linksFrom).concat(this.linksTo).forEach(function(a){f=a.fromNode.linksFrom.indexOf(a);-1<f&&a.fromNode.linksFrom.splice(f,1);f=a.toNode.linksTo.indexOf(a);-1<f&&a.toNode.linksTo.splice(f,1);b.prototype.removePoint.call(d,d.data.indexOf(a),!1,!1)});d.points=d.data.slice();for(d.nodes.splice(d.nodes.indexOf(this),1);g--;)if(e[g].id===this.options.id){d.options.nodes.splice(g,1);break}this&&this.destroy();d.isDirty=!0;d.isDirtyData=!0;a&&d.chart.redraw(a)}else d.removePoint(d.data.indexOf(this),
a,c)},destroy:function(){this.isNode&&this.linksFrom.concat(this.linksTo).forEach(function(a){a.destroyElements&&a.destroyElements()});this.series.layout.removeElementFromCollection(this,this.series.layout[this.isNode?"nodes":"links"]);return d.prototype.destroy.apply(this,arguments)}});g.prototype.pointClass=n;f.registerSeriesType("networkgraph",g);"";return g});h(f,"masters/modules/networkgraph.src.js",[],function(){})});
//# sourceMappingURL=networkgraph.js.map