/*
 Highcharts JS v8.2.2 (2020-12-12)
 Organization chart series type

 (c) 2019-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/organization",["highcharts","highcharts/modules/sankey"],function(d){a(d);a.Highcharts=d;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function d(a,d,p,b){a.hasOwnProperty(d)||(a[d]=b.apply(null,p))}a=a?a._modules:{};d(a,"Series/Organization/OrganizationPoint.js",[a["Core/Series/Series.js"]],function(a){var d=this&&
this.__extends||function(){var a=function(b,e){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var e in b)b.hasOwnProperty(e)&&(a[e]=b[e])};return a(b,e)};return function(b,e){function d(){this.constructor=b}a(b,e);b.prototype=null===e?Object.create(e):(d.prototype=e.prototype,new d)}}();return function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.fromNode=void 0;b.linksFrom=void 0;b.linksTo=void 0;b.options=void 0;b.series=
void 0;b.toNode=void 0;return b}d(b,a);b.prototype.getSum=function(){return 1};return b}(a.seriesTypes.sankey.prototype.pointClass)});d(a,"Series/Organization/OrganizationSeries.js",[a["Core/Series/Series.js"],a["Series/Organization/OrganizationPoint.js"],a["Core/Color/Palette.js"],a["Core/Utilities.js"]],function(a,d,p,b){var e=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,a){c.__proto__=a}||function(c,a){for(var f in a)a.hasOwnProperty(f)&&
(c[f]=a[f])};return a(b,c)};return function(b,c){function f(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(f.prototype=c.prototype,new f)}}(),n=a.seriesTypes.sankey,r=b.css,t=b.extend,v=b.merge,w=b.pick,x=b.wrap;b=function(a){function b(){var c=null!==a&&a.apply(this,arguments)||this;c.data=void 0;c.options=void 0;c.points=void 0;return c}e(b,a);b.curvedPath=function(c,a){for(var b=[],f=0;f<c.length;f++){var g=c[f][1],h=c[f][2];if("number"===typeof g&&"number"===typeof h)if(0===
f)b.push(["M",g,h]);else if(f===c.length-1)b.push(["L",g,h]);else if(a){var k=c[f-1],l=c[f+1];if(k&&l){var d=k[1];k=k[2];var m=l[1];l=l[2];if("number"===typeof d&&"number"===typeof m&&"number"===typeof k&&"number"===typeof l&&d!==m&&k!==l){var e=d<m?1:-1,q=k<l?1:-1;b.push(["L",g-e*Math.min(Math.abs(g-d),a),h-q*Math.min(Math.abs(h-k),a)],["C",g,h,g,h,g+e*Math.min(Math.abs(g-m),a),h+q*Math.min(Math.abs(h-l),a)])}}}else b.push(["L",g,h])}return b};b.prototype.alignDataLabel=function(c,b,u){if(u.useHTML){var f=
c.shapeArgs.width,g=c.shapeArgs.height,h=this.options.borderWidth+2*this.options.dataLabels.padding;this.chart.inverted&&(f=g,g=c.shapeArgs.width);g-=h;f-=h;if(h=b.text)r(h.element.parentNode,{width:f+"px",height:g+"px"}),r(h.element,{left:0,top:0,width:"100%",height:"100%",overflow:"hidden"});b.getBBox=function(){return{width:f,height:g}};b.width=f;b.height=g}a.prototype.alignDataLabel.apply(this,arguments)};b.prototype.createNode=function(b){b=a.prototype.createNode.call(this,b);b.getSum=function(){return 1};
return b};b.prototype.createNodeColumn=function(){var b=a.prototype.createNodeColumn.call(this);x(b,"offset",function(b,a,c){b=b.call(this,a,c);return a.hangsFrom?{absoluteTop:a.hangsFrom.nodeY}:b});return b};b.prototype.pointAttribs=function(b,a){var c=this,f=n.prototype.pointAttribs.call(c,b,a),g=c.mapOptionsToLevel[(b.isNode?b.level:b.fromNode.level)||0]||{},h=b.options,d=g.states&&g.states[a]||{};a=["borderRadius","linkColor","linkLineWidth"].reduce(function(b,a){b[a]=w(d[a],h[a],g[a],c.options[a]);
return b},{});b.isNode?a.borderRadius&&(f.r=a.borderRadius):(f.stroke=a.linkColor,f["stroke-width"]=a.linkLineWidth,delete f.fill);return f};b.prototype.translateLink=function(a){var c=a.fromNode,d=a.toNode,e=Math.round(this.options.linkLineWidth)%2/2,g=Math.floor(c.shapeArgs.x+c.shapeArgs.width)+e,h=Math.floor(c.shapeArgs.y+c.shapeArgs.height/2)+e,k=Math.floor(d.shapeArgs.x)+e,l=Math.floor(d.shapeArgs.y+d.shapeArgs.height/2)+e,p=this.options.hangingIndent;var m=d.options.offset;var n=/%$/.test(m)&&
parseInt(m,10),q=this.chart.inverted;q&&(g-=c.shapeArgs.width,k+=d.shapeArgs.width);m=Math.floor(k+(q?1:-1)*(this.colDistance-this.nodeWidth)/2)+e;n&&(50<=n||-50>=n)&&(m=k=Math.floor(k+(q?-.5:.5)*d.shapeArgs.width)+e,l=d.shapeArgs.y,0<n&&(l+=d.shapeArgs.height));d.hangsFrom===c&&(this.chart.inverted?(h=Math.floor(c.shapeArgs.y+c.shapeArgs.height-p/2)+e,l=d.shapeArgs.y+d.shapeArgs.height):h=Math.floor(c.shapeArgs.y+p/2)+e,m=k=Math.floor(d.shapeArgs.x+d.shapeArgs.width/2)+e);a.plotY=1;a.shapeType="path";
a.shapeArgs={d:b.curvedPath([["M",g,h],["L",m,h],["L",m,l],["L",k,l]],this.options.linkRadius)}};b.prototype.translateNode=function(a,b){n.prototype.translateNode.call(this,a,b);a.hangsFrom&&(a.shapeArgs.height-=this.options.hangingIndent,this.chart.inverted||(a.shapeArgs.y+=this.options.hangingIndent));a.nodeHeight=this.chart.inverted?a.shapeArgs.width:a.shapeArgs.height};b.defaultOptions=v(n.defaultOptions,{borderColor:p.neutralColor60,borderRadius:3,linkRadius:10,borderWidth:1,dataLabels:{nodeFormatter:function(){function a(a){return Object.keys(a).reduce(function(b,
c){return b+c+":"+a[c]+";"},'style="')+'"'}var b={width:"100%",height:"100%",display:"flex","flex-direction":"row","align-items":"center","justify-content":"center"},d={"max-height":"100%","border-radius":"50%"},e={width:"100%",padding:0,"text-align":"center","white-space":"normal"},g={margin:0},h={margin:0},k={opacity:.75,margin:"5px"};this.point.image&&(d["max-width"]="30%",e.width="70%");this.series.chart.renderer.forExport&&(b.display="block",e.position="absolute",e.left=this.point.image?"30%":
0,e.top=0);b="<div "+a(b)+">";this.point.image&&(b+='<img src="'+this.point.image+'" '+a(d)+">");b+="<div "+a(e)+">";this.point.name&&(b+="<h4 "+a(g)+">"+this.point.name+"</h4>");this.point.title&&(b+="<p "+a(h)+">"+(this.point.title||"")+"</p>");this.point.description&&(b+="<p "+a(k)+">"+this.point.description+"</p>");return b+"</div></div>"},style:{fontWeight:"normal",fontSize:"13px"},useHTML:!0},hangingIndent:20,linkColor:p.neutralColor60,linkLineWidth:1,nodeWidth:50,tooltip:{nodeFormat:"{point.name}<br>{point.title}<br>{point.description}"}});
return b}(n);t(b.prototype,{pointClass:d});a.registerSeriesType("organization",b);"";"";return b});d(a,"masters/modules/organization.src.js",[],function(){})});
//# sourceMappingURL=organization.js.map