/*
 Highstock JS v8.2.2 (2020-12-12)

 Highstock as a plugin for Highcharts

 (c) 2010-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(f){"object"===typeof module&&module.exports?(f["default"]=f,module.exports=f):"function"===typeof define&&define.amd?define("highcharts/modules/stock",["highcharts"],function(J){f(J);f.Highcharts=J;return f}):f("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(f){function J(f,B,w,r){f.hasOwnProperty(B)||(f[B]=r.apply(null,w))}f=f?f._modules:{};J(f,"Core/Axis/NavigatorAxis.js",[f["Core/Globals.js"],f["Core/Utilities.js"]],function(f,B){var w=f.isTouchDevice,r=B.addEvent,q=B.correctFloat,
E=B.defined,D=B.isNumber,m=B.pick,g=function(){function a(a){this.axis=a}a.prototype.destroy=function(){this.axis=void 0};a.prototype.toFixedRange=function(a,g,c,C){var u=this.axis,d=u.chart;d=d&&d.fixedRange;var z=(u.pointRange||0)/2;a=m(c,u.translate(a,!0,!u.horiz));g=m(C,u.translate(g,!0,!u.horiz));u=d&&(g-a)/d;E(c)||(a=q(a+z));E(C)||(g=q(g-z));.7<u&&1.3>u&&(C?a=g-d:g=a+d);D(a)&&D(g)||(a=g=void 0);return{min:a,max:g}};return a}();return function(){function a(){}a.compose=function(a){a.keepProps.push("navigatorAxis");
r(a,"init",function(){this.navigatorAxis||(this.navigatorAxis=new g(this))});r(a,"zoom",function(a){var c=this.chart.options,g=c.navigator,u=this.navigatorAxis,d=c.chart.pinchType,z=c.rangeSelector;c=c.chart.zoomType;this.isXAxis&&(g&&g.enabled||z&&z.enabled)&&("y"===c?a.zoomed=!1:(!w&&"xy"===c||w&&"xy"===d)&&this.options.range&&(g=u.previousZoom,E(a.newMin)?u.previousZoom=[this.min,this.max]:g&&(a.newMin=g[0],a.newMax=g[1],u.previousZoom=void 0)));"undefined"!==typeof a.zoomed&&a.preventDefault()})};
a.AdditionsClass=g;return a}()});J(f,"Core/Axis/ScrollbarAxis.js",[f["Core/Globals.js"],f["Core/Utilities.js"]],function(f,B){var w=B.addEvent,r=B.defined,q=B.pick;return function(){function E(){}E.compose=function(D,m){w(D,"afterInit",function(){var g=this;g.options&&g.options.scrollbar&&g.options.scrollbar.enabled&&(g.options.scrollbar.vertical=!g.horiz,g.options.startOnTick=g.options.endOnTick=!1,g.scrollbar=new m(g.chart.renderer,g.options.scrollbar,g.chart),w(g.scrollbar,"changed",function(a){var m=
q(g.options&&g.options.min,g.min),I=q(g.options&&g.options.max,g.max),c=r(g.dataMin)?Math.min(m,g.min,g.dataMin):m,C=(r(g.dataMax)?Math.max(I,g.max,g.dataMax):I)-c;r(m)&&r(I)&&(g.horiz&&!g.reversed||!g.horiz&&g.reversed?(m=c+C*this.to,c+=C*this.from):(m=c+C*(1-this.from),c+=C*(1-this.to)),q(this.options.liveRedraw,f.svg&&!f.isTouchDevice&&!this.chart.isBoosting)||"mouseup"===a.DOMType||"touchend"===a.DOMType||!r(a.DOMType)?g.setExtremes(c,m,!0,"mousemove"!==a.DOMType&&"touchmove"!==a.DOMType,a):this.setRange(this.from,
this.to))}))});w(D,"afterRender",function(){var g=Math.min(q(this.options.min,this.min),this.min,q(this.dataMin,this.min)),a=Math.max(q(this.options.max,this.max),this.max,q(this.dataMax,this.max)),f=this.scrollbar,m=this.axisTitleMargin+(this.titleOffset||0),c=this.chart.scrollbarsOffsets,C=this.options.margin||0;f&&(this.horiz?(this.opposite||(c[1]+=m),f.position(this.left,this.top+this.height+2+c[1]-(this.opposite?C:0),this.width,this.height),this.opposite||(c[1]+=C),m=1):(this.opposite&&(c[0]+=
m),f.position(this.left+this.width+2+c[0]-(this.opposite?0:C),this.top,this.width,this.height),this.opposite&&(c[0]+=C),m=0),c[m]+=f.size+f.options.margin,isNaN(g)||isNaN(a)||!r(this.min)||!r(this.max)||this.min===this.max?f.setRange(0,1):(c=(this.min-g)/(a-g),g=(this.max-g)/(a-g),this.horiz&&!this.reversed||!this.horiz&&this.reversed?f.setRange(c,g):f.setRange(1-g,1-c)))});w(D,"afterGetOffset",function(){var g=this.horiz?2:1,a=this.scrollbar;a&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[g]+=
a.size+a.options.margin)})};return E}()});J(f,"Core/Scrollbar.js",[f["Core/Axis/Axis.js"],f["Core/Globals.js"],f["Core/Color/Palette.js"],f["Core/Axis/ScrollbarAxis.js"],f["Core/Utilities.js"],f["Core/Options.js"]],function(f,B,w,r,q,E){var D=q.addEvent,m=q.correctFloat,g=q.defined,a=q.destroyObjectProperties,A=q.fireEvent,I=q.merge,c=q.pick,C=q.removeEvent;q=E.defaultOptions;var u=B.isTouchDevice,d=B.swapXY=function(d,k){k&&d.forEach(function(k){for(var h=k.length,d,G=0;G<h;G+=2)d=k[G+1],"number"===
typeof d&&(k[G+1]=k[G+2],k[G+2]=d)});return d};E=function(){function z(k,d,h){this._events=[];this.from=this.chartY=this.chartX=0;this.scrollbar=this.group=void 0;this.scrollbarButtons=[];this.scrollbarGroup=void 0;this.scrollbarLeft=0;this.scrollbarRifles=void 0;this.scrollbarStrokeWidth=1;this.to=this.size=this.scrollbarTop=0;this.track=void 0;this.trackBorderWidth=1;this.userOptions={};this.y=this.x=0;this.chart=h;this.options=d;this.renderer=h.renderer;this.init(k,d,h)}z.prototype.addEvents=function(){var k=
this.options.inverted?[1,0]:[0,1],d=this.scrollbarButtons,h=this.scrollbarGroup.element,p=this.track.element,c=this.mouseDownHandler.bind(this),a=this.mouseMoveHandler.bind(this),g=this.mouseUpHandler.bind(this);k=[[d[k[0]].element,"click",this.buttonToMinClick.bind(this)],[d[k[1]].element,"click",this.buttonToMaxClick.bind(this)],[p,"click",this.trackClick.bind(this)],[h,"mousedown",c],[h.ownerDocument,"mousemove",a],[h.ownerDocument,"mouseup",g]];B.hasTouch&&k.push([h,"touchstart",c],[h.ownerDocument,
"touchmove",a],[h.ownerDocument,"touchend",g]);k.forEach(function(k){D.apply(null,k)});this._events=k};z.prototype.buttonToMaxClick=function(k){var d=(this.to-this.from)*c(this.options.step,.2);this.updatePosition(this.from+d,this.to+d);A(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:k})};z.prototype.buttonToMinClick=function(k){var d=m(this.to-this.from)*c(this.options.step,.2);this.updatePosition(m(this.from-d),m(this.to-d));A(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",
DOMEvent:k})};z.prototype.cursorToScrollbarPosition=function(k){var d=this.options;d=d.minWidth>this.calculatedWidth?d.minWidth:0;return{chartX:(k.chartX-this.x-this.xOffset)/(this.barWidth-d),chartY:(k.chartY-this.y-this.yOffset)/(this.barWidth-d)}};z.prototype.destroy=function(){var k=this.chart.scroller;this.removeEvents();["track","scrollbarRifles","scrollbar","scrollbarGroup","group"].forEach(function(k){this[k]&&this[k].destroy&&(this[k]=this[k].destroy())},this);k&&this===k.scrollbar&&(k.scrollbar=
null,a(k.scrollbarButtons))};z.prototype.drawScrollbarButton=function(k){var c=this.renderer,h=this.scrollbarButtons,p=this.options,a=this.size;var g=c.g().add(this.group);h.push(g);g=c.rect().addClass("highcharts-scrollbar-button").add(g);this.chart.styledMode||g.attr({stroke:p.buttonBorderColor,"stroke-width":p.buttonBorderWidth,fill:p.buttonBackgroundColor});g.attr(g.crisp({x:-.5,y:-.5,width:a+1,height:a+1,r:p.buttonBorderRadius},g.strokeWidth()));g=c.path(d([["M",a/2+(k?-1:1),a/2-3],["L",a/2+
(k?-1:1),a/2+3],["L",a/2+(k?2:-2),a/2]],p.vertical)).addClass("highcharts-scrollbar-arrow").add(h[k]);this.chart.styledMode||g.attr({fill:p.buttonArrowColor})};z.prototype.init=function(k,d,h){this.scrollbarButtons=[];this.renderer=k;this.userOptions=d;this.options=I(z.defaultOptions,d);this.chart=h;this.size=c(this.options.size,this.options.height);d.enabled&&(this.render(),this.addEvents())};z.prototype.mouseDownHandler=function(k){k=this.chart.pointer.normalize(k);k=this.cursorToScrollbarPosition(k);
this.chartX=k.chartX;this.chartY=k.chartY;this.initPositions=[this.from,this.to];this.grabbedCenter=!0};z.prototype.mouseMoveHandler=function(k){var d=this.chart.pointer.normalize(k),h=this.options.vertical?"chartY":"chartX",p=this.initPositions||[];!this.grabbedCenter||k.touches&&0===k.touches[0][h]||(d=this.cursorToScrollbarPosition(d)[h],h=this[h],h=d-h,this.hasDragged=!0,this.updatePosition(p[0]+h,p[1]+h),this.hasDragged&&A(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:k.type,
DOMEvent:k}))};z.prototype.mouseUpHandler=function(k){this.hasDragged&&A(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:k.type,DOMEvent:k});this.grabbedCenter=this.hasDragged=this.chartX=this.chartY=null};z.prototype.position=function(k,d,h,p){var a=this.options.vertical,c=0,g=this.rendered?"animate":"attr";this.x=k;this.y=d+this.trackBorderWidth;this.width=h;this.xOffset=this.height=p;this.yOffset=c;a?(this.width=this.yOffset=h=c=this.size,this.xOffset=d=0,this.barWidth=p-
2*h,this.x=k+=this.options.margin):(this.height=this.xOffset=p=d=this.size,this.barWidth=h-2*p,this.y+=this.options.margin);this.group[g]({translateX:k,translateY:this.y});this.track[g]({width:h,height:p});this.scrollbarButtons[1][g]({translateX:a?0:h-d,translateY:a?p-c:0})};z.prototype.removeEvents=function(){this._events.forEach(function(k){C.apply(null,k)});this._events.length=0};z.prototype.render=function(){var k=this.renderer,a=this.options,h=this.size,p=this.chart.styledMode,c;this.group=c=
k.g("scrollbar").attr({zIndex:a.zIndex,translateY:-99999}).add();this.track=k.rect().addClass("highcharts-scrollbar-track").attr({x:0,r:a.trackBorderRadius||0,height:h,width:h}).add(c);p||this.track.attr({fill:a.trackBackgroundColor,stroke:a.trackBorderColor,"stroke-width":a.trackBorderWidth});this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%2/2});this.scrollbarGroup=k.g().add(c);this.scrollbar=k.rect().addClass("highcharts-scrollbar-thumb").attr({height:h,
width:h,r:a.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=k.path(d([["M",-3,h/4],["L",-3,2*h/3],["M",0,h/4],["L",0,2*h/3],["M",3,h/4],["L",3,2*h/3]],a.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);p||(this.scrollbar.attr({fill:a.barBackgroundColor,stroke:a.barBorderColor,"stroke-width":a.barBorderWidth}),this.scrollbarRifles.attr({stroke:a.rifleColor,"stroke-width":1}));this.scrollbarStrokeWidth=this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%
2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)};z.prototype.setRange=function(k,d){var h=this.options,a=h.vertical,c=h.minWidth,u=this.barWidth,G,v=!this.rendered||this.hasDragged||this.chart.navigator&&this.chart.navigator.hasDragged?"attr":"animate";if(g(u)){k=Math.max(k,0);var n=Math.ceil(u*k);this.calculatedWidth=G=m(u*Math.min(d,1)-n);G<c&&(n=(u-c+G)*k,G=c);c=Math.floor(n+this.xOffset+this.yOffset);u=G/2-.5;this.from=k;this.to=d;a?(this.scrollbarGroup[v]({translateY:c}),
this.scrollbar[v]({height:G}),this.scrollbarRifles[v]({translateY:u}),this.scrollbarTop=c,this.scrollbarLeft=0):(this.scrollbarGroup[v]({translateX:c}),this.scrollbar[v]({width:G}),this.scrollbarRifles[v]({translateX:u}),this.scrollbarLeft=c,this.scrollbarTop=0);12>=G?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0);!1===h.showFull&&(0>=k&&1<=d?this.group.hide():this.group.show());this.rendered=!0}};z.prototype.trackClick=function(d){var k=this.chart.pointer.normalize(d),h=this.to-this.from,
a=this.y+this.scrollbarTop,c=this.x+this.scrollbarLeft;this.options.vertical&&k.chartY>a||!this.options.vertical&&k.chartX>c?this.updatePosition(this.from+h,this.to+h):this.updatePosition(this.from-h,this.to-h);A(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:d})};z.prototype.update=function(d){this.destroy();this.init(this.chart.renderer,I(!0,this.options,d),this.chart)};z.prototype.updatePosition=function(d,a){1<a&&(d=m(1-m(a-d)),a=1);0>d&&(a=m(a-d),d=0);this.from=d;this.to=
a};z.defaultOptions={height:u?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:void 0,margin:10,minWidth:6,step:.2,zIndex:3,barBackgroundColor:w.neutralColor20,barBorderWidth:1,barBorderColor:w.neutralColor20,buttonArrowColor:w.neutralColor80,buttonBackgroundColor:w.neutralColor10,buttonBorderColor:w.neutralColor20,buttonBorderWidth:1,rifleColor:w.neutralColor80,trackBackgroundColor:w.neutralColor5,trackBorderColor:w.neutralColor5,trackBorderWidth:1};return z}();B.Scrollbar||(q.scrollbar=I(!0,
E.defaultOptions,q.scrollbar),B.Scrollbar=E,r.compose(f,E));return B.Scrollbar});J(f,"Core/Navigator.js",[f["Core/Axis/Axis.js"],f["Core/Series/Series.js"],f["Core/Chart/Chart.js"],f["Core/Color/Color.js"],f["Core/Globals.js"],f["Series/Line/LineSeries.js"],f["Core/Axis/NavigatorAxis.js"],f["Core/Options.js"],f["Core/Color/Palette.js"],f["Core/Scrollbar.js"],f["Core/Utilities.js"]],function(f,B,w,r,q,E,D,m,g,a,A){r=r.parse;var I=q.hasTouch,c=q.isTouchDevice,C=m.defaultOptions,u=A.addEvent,d=A.clamp,
z=A.correctFloat,k=A.defined,G=A.destroyObjectProperties,h=A.erase,p=A.extend,M=A.find,L=A.isArray,F=A.isNumber,v=A.merge,n=A.pick,t=A.removeEvent,b=A.splat,x=function(b){for(var l=[],y=1;y<arguments.length;y++)l[y-1]=arguments[y];l=[].filter.call(l,F);if(l.length)return Math[b].apply(0,l)};B="undefined"===typeof B.seriesTypes.areaspline?"line":"areaspline";p(C,{navigator:{height:40,margin:25,maskInside:!0,handles:{width:7,height:15,symbols:["navigator-handle","navigator-handle"],enabled:!0,lineWidth:1,
backgroundColor:g.neutralColor5,borderColor:g.neutralColor40},maskFill:r(g.highlightColor60).setOpacity(.3).get(),outlineColor:g.neutralColor20,outlineWidth:1,series:{type:B,fillOpacity:.05,lineWidth:1,compare:null,dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,smoothed:!0,units:[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1,2,3,4]],["week",[1,2,3]],["month",[1,3,6]],["year",null]]},dataLabels:{enabled:!1,
zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},threshold:null},xAxis:{overscroll:0,className:"highcharts-navigator-xaxis",tickLength:0,lineWidth:0,gridLineColor:g.neutralColor10,gridLineWidth:1,tickPixelInterval:200,labels:{align:"left",style:{color:g.neutralColor40},x:3,y:-4},crosshair:!1},yAxis:{className:"highcharts-navigator-yaxis",gridLineWidth:0,startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},
crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});q.Renderer.prototype.symbols["navigator-handle"]=function(b,l,y,x,n){b=(n&&n.width||0)/2;l=Math.round(b/3)+.5;n=n&&n.height||0;return[["M",-b-1,.5],["L",b,.5],["L",b,n+.5],["L",-b-1,n+.5],["L",-b-1,.5],["M",-l,4],["L",-l,n-3],["M",l-1,4],["L",l-1,n-3]]};var e=function(){function e(l){this.zoomedMin=this.zoomedMax=this.yAxis=this.xAxis=this.top=this.size=this.shades=this.rendered=this.range=this.outlineHeight=this.outline=this.opposite=this.navigatorSize=
this.navigatorSeries=this.navigatorOptions=this.navigatorGroup=this.navigatorEnabled=this.left=this.height=this.handles=this.chart=this.baseSeries=void 0;this.init(l)}e.prototype.drawHandle=function(l,b,e,x){var y=this.navigatorOptions.handles.height;this.handles[b][x](e?{translateX:Math.round(this.left+this.height/2),translateY:Math.round(this.top+parseInt(l,10)+.5-y)}:{translateX:Math.round(this.left+parseInt(l,10)),translateY:Math.round(this.top+this.height/2-y/2-1)})};e.prototype.drawOutline=
function(l,b,e,x){var y=this.navigatorOptions.maskInside,n=this.outline.strokeWidth(),t=n/2,K=n%2/2;n=this.outlineHeight;var d=this.scrollbarHeight||0,k=this.size,a=this.left-d,h=this.top;e?(a-=t,e=h+b+K,b=h+l+K,K=[["M",a+n,h-d-K],["L",a+n,e],["L",a,e],["L",a,b],["L",a+n,b],["L",a+n,h+k+d]],y&&K.push(["M",a+n,e-t],["L",a+n,b+t])):(l+=a+d-K,b+=a+d-K,h+=t,K=[["M",a,h],["L",l,h],["L",l,h+n],["L",b,h+n],["L",b,h],["L",a+k+2*d,h]],y&&K.push(["M",l-t,h],["L",b+t,h]));this.outline[x]({d:K})};e.prototype.drawMasks=
function(l,b,e,n){var y=this.left,x=this.top,K=this.height;if(e){var t=[y,y,y];var d=[x,x+l,x+b];var k=[K,K,K];var a=[l,b-l,this.size-b]}else t=[y,y+l,y+b],d=[x,x,x],k=[l,b-l,this.size-b],a=[K,K,K];this.shades.forEach(function(l,b){l[n]({x:t[b],y:d[b],width:k[b],height:a[b]})})};e.prototype.renderElements=function(){var l=this,b=l.navigatorOptions,e=b.maskInside,n=l.chart,x=n.renderer,t,d={cursor:n.inverted?"ns-resize":"ew-resize"};l.navigatorGroup=t=x.g("navigator").attr({zIndex:8,visibility:"hidden"}).add();
[!e,e,!e].forEach(function(e,y){l.shades[y]=x.rect().addClass("highcharts-navigator-mask"+(1===y?"-inside":"-outside")).add(t);n.styledMode||l.shades[y].attr({fill:e?b.maskFill:"rgba(0,0,0,0)"}).css(1===y&&d)});l.outline=x.path().addClass("highcharts-navigator-outline").add(t);n.styledMode||l.outline.attr({"stroke-width":b.outlineWidth,stroke:b.outlineColor});b.handles.enabled&&[0,1].forEach(function(e){b.handles.inverted=n.inverted;l.handles[e]=x.symbol(b.handles.symbols[e],-b.handles.width/2-1,
0,b.handles.width,b.handles.height,b.handles);l.handles[e].attr({zIndex:7-e}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+["left","right"][e]).add(t);if(!n.styledMode){var y=b.handles;l.handles[e].attr({fill:y.backgroundColor,stroke:y.borderColor,"stroke-width":y.lineWidth}).css(d)}})};e.prototype.update=function(l){(this.series||[]).forEach(function(l){l.baseSeries&&delete l.baseSeries.navigatorSeries});this.destroy();v(!0,this.chart.options.navigator,this.options,l);this.init(this.chart)};
e.prototype.render=function(l,b,e,x){var y=this.chart,t=this.scrollbarHeight,K,a=this.xAxis,h=a.pointRange||0;var c=a.navigatorAxis.fake?y.xAxis[0]:a;var H=this.navigatorEnabled,p,g=this.rendered;var v=y.inverted;var u=y.xAxis[0].minRange,N=y.xAxis[0].options.maxRange;if(!this.hasDragged||k(e)){l=z(l-h/2);b=z(b+h/2);if(!F(l)||!F(b))if(g)e=0,x=n(a.width,c.width);else return;this.left=n(a.left,y.plotLeft+t+(v?y.plotWidth:0));this.size=p=K=n(a.len,(v?y.plotHeight:y.plotWidth)-2*t);y=v?t:K+2*t;e=n(e,
a.toPixels(l,!0));x=n(x,a.toPixels(b,!0));F(e)&&Infinity!==Math.abs(e)||(e=0,x=y);l=a.toValue(e,!0);b=a.toValue(x,!0);var G=Math.abs(z(b-l));G<u?this.grabbedLeft?e=a.toPixels(b-u-h,!0):this.grabbedRight&&(x=a.toPixels(l+u+h,!0)):k(N)&&z(G-h)>N&&(this.grabbedLeft?e=a.toPixels(b-N-h,!0):this.grabbedRight&&(x=a.toPixels(l+N+h,!0)));this.zoomedMax=d(Math.max(e,x),0,p);this.zoomedMin=d(this.fixedWidth?this.zoomedMax-this.fixedWidth:Math.min(e,x),0,p);this.range=this.zoomedMax-this.zoomedMin;p=Math.round(this.zoomedMax);
e=Math.round(this.zoomedMin);H&&(this.navigatorGroup.attr({visibility:"visible"}),g=g&&!this.hasDragged?"animate":"attr",this.drawMasks(e,p,v,g),this.drawOutline(e,p,v,g),this.navigatorOptions.handles.enabled&&(this.drawHandle(e,0,v,g),this.drawHandle(p,1,v,g)));this.scrollbar&&(v?(v=this.top-t,c=this.left-t+(H||!c.opposite?0:(c.titleOffset||0)+c.axisTitleMargin),t=K+2*t):(v=this.top+(H?this.height:-t),c=this.left-t),this.scrollbar.position(c,v,y,t),this.scrollbar.setRange(this.zoomedMin/(K||1),this.zoomedMax/
(K||1)));this.rendered=!0}};e.prototype.addMouseEvents=function(){var l=this,b=l.chart,e=b.container,x=[],n,t;l.mouseMoveHandler=n=function(b){l.onMouseMove(b)};l.mouseUpHandler=t=function(b){l.onMouseUp(b)};x=l.getPartsEvents("mousedown");x.push(u(b.renderTo,"mousemove",n),u(e.ownerDocument,"mouseup",t));I&&(x.push(u(b.renderTo,"touchmove",n),u(e.ownerDocument,"touchend",t)),x.concat(l.getPartsEvents("touchstart")));l.eventsToUnbind=x;l.series&&l.series[0]&&x.push(u(l.series[0].xAxis,"foundExtremes",
function(){b.navigator.modifyNavigatorAxisExtremes()}))};e.prototype.getPartsEvents=function(l){var b=this,e=[];["shades","handles"].forEach(function(x){b[x].forEach(function(n,y){e.push(u(n.element,l,function(l){b[x+"Mousedown"](l,y)}))})});return e};e.prototype.shadesMousedown=function(l,b){l=this.chart.pointer.normalize(l);var e=this.chart,x=this.xAxis,n=this.zoomedMin,y=this.left,t=this.size,d=this.range,a=l.chartX;e.inverted&&(a=l.chartY,y=this.top);if(1===b)this.grabbedCenter=a,this.fixedWidth=
d,this.dragOffset=a-n;else{l=a-y-d/2;if(0===b)l=Math.max(0,l);else if(2===b&&l+d>=t)if(l=t-d,this.reversedExtremes){l-=d;var h=this.getUnionExtremes().dataMin}else var c=this.getUnionExtremes().dataMax;l!==n&&(this.fixedWidth=d,b=x.navigatorAxis.toFixedRange(l,l+d,h,c),k(b.min)&&e.xAxis[0].setExtremes(Math.min(b.min,b.max),Math.max(b.min,b.max),!0,null,{trigger:"navigator"}))}};e.prototype.handlesMousedown=function(b,e){this.chart.pointer.normalize(b);b=this.chart;var l=b.xAxis[0],x=this.reversedExtremes;
0===e?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=x?l.min:l.max):(this.grabbedRight=!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=x?l.max:l.min);b.fixedRange=null};e.prototype.onMouseMove=function(b){var l=this,e=l.chart,x=l.left,t=l.navigatorSize,d=l.range,a=l.dragOffset,k=e.inverted;b.touches&&0===b.touches[0].pageX||(b=e.pointer.normalize(b),e=b.chartX,k&&(x=l.top,e=b.chartY),l.grabbedLeft?(l.hasDragged=!0,l.render(0,0,e-x,l.otherHandlePos)):l.grabbedRight?
(l.hasDragged=!0,l.render(0,0,l.otherHandlePos,e-x)):l.grabbedCenter&&(l.hasDragged=!0,e<a?e=a:e>t+a-d&&(e=t+a-d),l.render(0,0,e-a,e-a+d)),l.hasDragged&&l.scrollbar&&n(l.scrollbar.options.liveRedraw,q.svg&&!c&&!this.chart.isBoosting)&&(b.DOMType=b.type,setTimeout(function(){l.onMouseUp(b)},0)))};e.prototype.onMouseUp=function(b){var l=this.chart,e=this.xAxis,x=this.scrollbar,n=b.DOMEvent||b,t=l.inverted,d=this.rendered&&!this.hasDragged?"animate":"attr";if(this.hasDragged&&(!x||!x.hasDragged)||"scrollbar"===
b.trigger){x=this.getUnionExtremes();if(this.zoomedMin===this.otherHandlePos)var a=this.fixedExtreme;else if(this.zoomedMax===this.otherHandlePos)var h=this.fixedExtreme;this.zoomedMax===this.size&&(h=this.reversedExtremes?x.dataMin:x.dataMax);0===this.zoomedMin&&(a=this.reversedExtremes?x.dataMax:x.dataMin);e=e.navigatorAxis.toFixedRange(this.zoomedMin,this.zoomedMax,a,h);k(e.min)&&l.xAxis[0].setExtremes(Math.min(e.min,e.max),Math.max(e.min,e.max),!0,this.hasDragged?!1:null,{trigger:"navigator",
triggerOp:"navigator-drag",DOMEvent:n})}"mousemove"!==b.DOMType&&"touchmove"!==b.DOMType&&(this.grabbedLeft=this.grabbedRight=this.grabbedCenter=this.fixedWidth=this.fixedExtreme=this.otherHandlePos=this.hasDragged=this.dragOffset=null);this.navigatorEnabled&&F(this.zoomedMin)&&F(this.zoomedMax)&&(l=Math.round(this.zoomedMin),b=Math.round(this.zoomedMax),this.shades&&this.drawMasks(l,b,t,d),this.outline&&this.drawOutline(l,b,t,d),this.navigatorOptions.handles.enabled&&Object.keys(this.handles).length===
this.handles.length&&(this.drawHandle(l,0,t,d),this.drawHandle(b,1,t,d)))};e.prototype.removeEvents=function(){this.eventsToUnbind&&(this.eventsToUnbind.forEach(function(b){b()}),this.eventsToUnbind=void 0);this.removeBaseSeriesEvents()};e.prototype.removeBaseSeriesEvents=function(){var b=this.baseSeries||[];this.navigatorEnabled&&b[0]&&(!1!==this.navigatorOptions.adaptToUpdatedData&&b.forEach(function(b){t(b,"updatedData",this.updatedDataHandler)},this),b[0].xAxis&&t(b[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))};
e.prototype.init=function(b){var e=b.options,l=e.navigator,t=l.enabled,d=e.scrollbar,k=d.enabled;e=t?l.height:0;var h=k?d.height:0;this.handles=[];this.shades=[];this.chart=b;this.setBaseSeries();this.height=e;this.scrollbarHeight=h;this.scrollbarEnabled=k;this.navigatorEnabled=t;this.navigatorOptions=l;this.scrollbarOptions=d;this.outlineHeight=e+h;this.opposite=n(l.opposite,!(t||!b.inverted));var c=this;t=c.baseSeries;d=b.xAxis.length;k=b.yAxis.length;var H=t&&t[0]&&t[0].xAxis||b.xAxis[0]||{options:{}};
b.isDirtyBox=!0;c.navigatorEnabled?(c.xAxis=new f(b,v({breaks:H.options.breaks,ordinal:H.options.ordinal},l.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",index:d,isInternal:!0,offset:0,keepOrdinalPadding:!0,startOnTick:!1,endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},b.inverted?{offsets:[h,0,-h,0],width:e}:{offsets:[0,-h,0,h],height:e})),c.yAxis=new f(b,v(l.yAxis,{id:"navigator-y-axis",alignTicks:!1,offset:0,index:k,isInternal:!0,reversed:n(l.yAxis&&l.yAxis.reversed,
b.yAxis[0]&&b.yAxis[0].reversed,!1),zoomEnabled:!1},b.inverted?{width:e}:{height:e})),t||l.series.data?c.updateNavigatorSeries(!1):0===b.series.length&&(c.unbindRedraw=u(b,"beforeRedraw",function(){0<b.series.length&&!c.series&&(c.setBaseSeries(),c.unbindRedraw())})),c.reversedExtremes=b.inverted&&!c.xAxis.reversed||!b.inverted&&c.xAxis.reversed,c.renderElements(),c.addMouseEvents()):(c.xAxis={chart:b,navigatorAxis:{fake:!0},translate:function(e,l){var n=b.xAxis[0],t=n.getExtremes(),d=n.len-2*h,a=
x("min",n.options.min,t.dataMin);n=x("max",n.options.max,t.dataMax)-a;return l?e*n/d+a:d*(e-a)/n},toPixels:function(b){return this.translate(b)},toValue:function(b){return this.translate(b,!0)}},c.xAxis.navigatorAxis.axis=c.xAxis,c.xAxis.navigatorAxis.toFixedRange=D.AdditionsClass.prototype.toFixedRange.bind(c.xAxis.navigatorAxis));b.options.scrollbar.enabled&&(b.scrollbar=c.scrollbar=new a(b.renderer,v(b.options.scrollbar,{margin:c.navigatorEnabled?0:10,vertical:b.inverted}),b),u(c.scrollbar,"changed",
function(e){var l=c.size,x=l*this.to;l*=this.from;c.hasDragged=c.scrollbar.hasDragged;c.render(0,0,l,x);(b.options.scrollbar.liveRedraw||"mousemove"!==e.DOMType&&"touchmove"!==e.DOMType)&&setTimeout(function(){c.onMouseUp(e)})}));c.addBaseSeriesEvents();c.addChartEvents()};e.prototype.getUnionExtremes=function(b){var e=this.chart.xAxis[0],l=this.xAxis,t=l.options,d=e.options,a;b&&null===e.dataMin||(a={dataMin:n(t&&t.min,x("min",d.min,e.dataMin,l.dataMin,l.min)),dataMax:n(t&&t.max,x("max",d.max,e.dataMax,
l.dataMax,l.max))});return a};e.prototype.setBaseSeries=function(b,e){var l=this.chart,x=this.baseSeries=[];b=b||l.options&&l.options.navigator.baseSeries||(l.series.length?M(l.series,function(b){return!b.options.isInternal}).index:0);(l.series||[]).forEach(function(e,l){e.options.isInternal||!e.options.showInNavigator&&(l!==b&&e.options.id!==b||!1===e.options.showInNavigator)||x.push(e)});this.xAxis&&!this.xAxis.navigatorAxis.fake&&this.updateNavigatorSeries(!0,e)};e.prototype.updateNavigatorSeries=
function(e,x){var l=this,d=l.chart,a=l.baseSeries,c,y,h=l.navigatorOptions.series,k,H={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",yAxis:"navigator-y-axis",showInLegend:!1,stacking:void 0,isInternal:!0,states:{inactive:{opacity:1}}},g=l.series=(l.series||[]).filter(function(b){var e=b.baseSeries;return 0>a.indexOf(e)?(e&&(t(e,"updatedData",l.updatedDataHandler),delete e.navigatorSeries),b.chart&&b.destroy(),!1):!0});a&&a.length&&a.forEach(function(b){var e=
b.navigatorSeries,t=p({color:b.color,visible:b.visible},L(h)?C.navigator.series:h);e&&!1===l.navigatorOptions.adaptToUpdatedData||(H.name="Navigator "+a.length,c=b.options||{},k=c.navigatorOptions||{},y=v(c,H,t,k),y.pointRange=n(t.pointRange,k.pointRange,C.plotOptions[y.type||"line"].pointRange),t=k.data||t.data,l.hasNavigatorData=l.hasNavigatorData||!!t,y.data=t||c.data&&c.data.slice(0),e&&e.options?e.update(y,x):(b.navigatorSeries=d.initSeries(y),b.navigatorSeries.baseSeries=b,g.push(b.navigatorSeries)))});
if(h.data&&(!a||!a.length)||L(h))l.hasNavigatorData=!1,h=b(h),h.forEach(function(b,e){H.name="Navigator "+(g.length+1);y=v(C.navigator.series,{color:d.series[e]&&!d.series[e].options.isInternal&&d.series[e].color||d.options.colors[e]||d.options.colors[0]},H,b);y.data=b.data;y.data&&(l.hasNavigatorData=!0,g.push(d.initSeries(y)))});e&&this.addBaseSeriesEvents()};e.prototype.addBaseSeriesEvents=function(){var b=this,e=b.baseSeries||[];e[0]&&e[0].xAxis&&u(e[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);
e.forEach(function(e){u(e,"show",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!0,!1)});u(e,"hide",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!1,!1)});!1!==this.navigatorOptions.adaptToUpdatedData&&e.xAxis&&u(e,"updatedData",this.updatedDataHandler);u(e,"remove",function(){this.navigatorSeries&&(h(b.series,this.navigatorSeries),k(this.navigatorSeries.options)&&this.navigatorSeries.remove(!1),delete this.navigatorSeries)})},this)};e.prototype.getBaseSeriesMin=
function(b){return this.baseSeries.reduce(function(b,e){return Math.min(b,e.xData?e.xData[0]:b)},b)};e.prototype.modifyNavigatorAxisExtremes=function(){var b=this.xAxis,e;"undefined"!==typeof b.getExtremes&&(!(e=this.getUnionExtremes(!0))||e.dataMin===b.min&&e.dataMax===b.max||(b.min=e.dataMin,b.max=e.dataMax))};e.prototype.modifyBaseAxisExtremes=function(){var b=this.chart.navigator,e=this.getExtremes(),x=e.dataMin,t=e.dataMax;e=e.max-e.min;var d=b.stickToMin,a=b.stickToMax,c=n(this.options.overscroll,
0),h=b.series&&b.series[0],k=!!this.setExtremes;if(!this.eventArgs||"rangeSelectorButton"!==this.eventArgs.trigger){if(d){var H=x;var p=H+e}a&&(p=t+c,d||(H=Math.max(x,p-e,b.getBaseSeriesMin(h&&h.xData?h.xData[0]:-Number.MAX_VALUE))));k&&(d||a)&&F(H)&&(this.min=this.userMin=H,this.max=this.userMax=p)}b.stickToMin=b.stickToMax=null};e.prototype.updatedDataHandler=function(){var b=this.chart.navigator,e=this.navigatorSeries,x=b.getBaseSeriesMin(this.xData[0]);b.stickToMax=b.reversedExtremes?0===Math.round(b.zoomedMin):
Math.round(b.zoomedMax)>=Math.round(b.size);b.stickToMin=F(this.xAxis.min)&&this.xAxis.min<=x&&(!this.chart.fixedRange||!b.stickToMax);e&&!b.hasNavigatorData&&(e.options.pointStart=this.xData[0],e.setData(this.options.data,!1,null,!1))};e.prototype.addChartEvents=function(){this.eventsToUnbind||(this.eventsToUnbind=[]);this.eventsToUnbind.push(u(this.chart,"redraw",function(){var b=this.navigator,e=b&&(b.baseSeries&&b.baseSeries[0]&&b.baseSeries[0].xAxis||this.xAxis[0]);e&&b.render(e.min,e.max)}),
u(this.chart,"getMargins",function(){var b=this.navigator,e=b.opposite?"plotTop":"marginBottom";this.inverted&&(e=b.opposite?"marginRight":"plotLeft");this[e]=(this[e]||0)+(b.navigatorEnabled||!this.inverted?b.outlineHeight:0)+b.navigatorOptions.margin}))};e.prototype.destroy=function(){this.removeEvents();this.xAxis&&(h(this.chart.xAxis,this.xAxis),h(this.chart.axes,this.xAxis));this.yAxis&&(h(this.chart.yAxis,this.yAxis),h(this.chart.axes,this.yAxis));(this.series||[]).forEach(function(b){b.destroy&&
b.destroy()});"series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" ").forEach(function(b){this[b]&&this[b].destroy&&this[b].destroy();this[b]=null},this);[this.handles].forEach(function(b){G(b)},this)};return e}();q.Navigator||(q.Navigator=e,D.compose(f),u(w,"beforeShowResetZoom",function(){var b=this.options,e=b.navigator,x=b.rangeSelector;if((e&&e.enabled||x&&x.enabled)&&(!c&&"x"===b.chart.zoomType||c&&"x"===b.chart.pinchType))return!1}),
u(w,"beforeRender",function(){var b=this.options;if(b.navigator.enabled||b.scrollbar.enabled)this.scroller=this.navigator=new e(this)}),u(w,"afterSetChartSize",function(){var b=this.legend,e=this.navigator;if(e){var x=b&&b.options;var t=e.xAxis;var d=e.yAxis;var a=e.scrollbarHeight;this.inverted?(e.left=e.opposite?this.chartWidth-a-e.height:this.spacing[3]+a,e.top=this.plotTop+a):(e.left=this.plotLeft+a,e.top=e.navigatorOptions.top||this.chartHeight-e.height-a-this.spacing[2]-(this.rangeSelector&&
this.extraBottomMargin?this.rangeSelector.getHeight():0)-(x&&"bottom"===x.verticalAlign&&"proximate"!==x.layout&&x.enabled&&!x.floating?b.legendHeight+n(x.margin,10):0)-(this.titleOffset?this.titleOffset[2]:0));t&&d&&(this.inverted?t.options.left=d.options.left=e.left:t.options.top=d.options.top=e.top,t.setAxisSize(),d.setAxisSize())}}),u(w,"update",function(b){var e=b.options.navigator||{},x=b.options.scrollbar||{};this.navigator||this.scroller||!e.enabled&&!x.enabled||(v(!0,this.options.navigator,
e),v(!0,this.options.scrollbar,x),delete b.options.navigator,delete b.options.scrollbar)}),u(w,"afterUpdate",function(b){this.navigator||this.scroller||!this.options.navigator.enabled&&!this.options.scrollbar.enabled||(this.scroller=this.navigator=new e(this),n(b.redraw,!0)&&this.redraw(b.animation))}),u(w,"afterAddSeries",function(){this.navigator&&this.navigator.setBaseSeries(null,!1)}),u(E,"afterUpdate",function(){this.chart.navigator&&!this.options.isInternal&&this.chart.navigator.setBaseSeries(null,
!1)}),w.prototype.callbacks.push(function(b){var e=b.navigator;e&&b.xAxis[0]&&(b=b.xAxis[0].getExtremes(),e.render(b.min,b.max))}));q.Navigator=e;return q.Navigator});J(f,"Core/Axis/OrdinalAxis.js",[f["Core/Axis/Axis.js"],f["Core/Globals.js"],f["Series/Line/LineSeries.js"],f["Core/Utilities.js"],f["Core/Chart/Chart.js"]],function(f,B,w,r,q){var E=r.addEvent,D=r.css,m=r.defined,g=r.error,a=r.pick,A=r.timeUnits,I;(function(c){var f=function(){function c(d){this.index={};this.axis=d}c.prototype.beforeSetTickPositions=
function(){var d=this.axis,c=d.ordinal,k=[],g,h=!1,p=d.getExtremes(),u=p.min,f=p.max,m,v=d.isXAxis&&!!d.options.breaks;p=d.options.ordinal;var n=Number.MAX_VALUE,t=d.chart.options.chart.ignoreHiddenSeries,b;if(p||v){d.series.forEach(function(e,l){g=[];if(!(t&&!1===e.visible||!1===e.takeOrdinalPosition&&!v)&&(k=k.concat(e.processedXData),x=k.length,k.sort(function(b,e){return b-e}),n=Math.min(n,a(e.closestPointRange,n)),x)){for(l=0;l<x-1;)k[l]!==k[l+1]&&g.push(k[l+1]),l++;g[0]!==k[0]&&g.unshift(k[0]);
k=g}e.isSeriesBoosting&&(b=!0)});b&&(k.length=0);var x=k.length;if(2<x){var e=k[1]-k[0];for(m=x-1;m--&&!h;)k[m+1]-k[m]!==e&&(h=!0);!d.options.keepOrdinalPadding&&(k[0]-u>e||f-k[k.length-1]>e)&&(h=!0)}else d.options.overscroll&&(2===x?n=k[1]-k[0]:1===x?(n=d.options.overscroll,k=[k[0],k[0]+n]):n=c.overscrollPointsRange);h?(d.options.overscroll&&(c.overscrollPointsRange=n,k=k.concat(c.getOverscrollPositions())),c.positions=k,e=d.ordinal2lin(Math.max(u,k[0]),!0),m=Math.max(d.ordinal2lin(Math.min(f,k[k.length-
1]),!0),1),c.slope=f=(f-u)/(m-e),c.offset=u-e*f):(c.overscrollPointsRange=a(d.closestPointRange,c.overscrollPointsRange),c.positions=d.ordinal.slope=c.offset=void 0)}d.isOrdinal=p&&h;c.groupIntervalFactor=null};c.prototype.getExtendedPositions=function(){var d=this,a=d.axis,c=a.constructor.prototype,g=a.chart,h=a.series[0].currentDataGrouping,p=d.index,u=h?h.count+h.unitName:"raw",f=a.options.overscroll,m=a.getExtremes(),v;p||(p=d.index={});if(!p[u]){var n={series:[],chart:g,getExtremes:function(){return{min:m.dataMin,
max:m.dataMax+f}},options:{ordinal:!0},ordinal:{},ordinal2lin:c.ordinal2lin,val2lin:c.val2lin};n.ordinal.axis=n;a.series.forEach(function(t){v={xAxis:n,xData:t.xData.slice(),chart:g,destroyGroupedData:B.noop,getProcessedData:w.prototype.getProcessedData};v.xData=v.xData.concat(d.getOverscrollPositions());v.options={dataGrouping:h?{enabled:!0,forced:!0,approximation:"open",units:[[h.unitName,[h.count]]]}:{enabled:!1}};t.processData.apply(v);n.series.push(v)});a.ordinal.beforeSetTickPositions.apply({axis:n});
p[u]=n.ordinal.positions}return p[u]};c.prototype.getGroupIntervalFactor=function(d,a,c){c=c.processedXData;var k=c.length,h=[];var p=this.groupIntervalFactor;if(!p){for(p=0;p<k-1;p++)h[p]=c[p+1]-c[p];h.sort(function(d,a){return d-a});h=h[Math.floor(k/2)];d=Math.max(d,c[0]);a=Math.min(a,c[k-1]);this.groupIntervalFactor=p=k*h/(a-d)}return p};c.prototype.getOverscrollPositions=function(){var d=this.axis,a=d.options.overscroll,c=this.overscrollPointsRange,g=[],h=d.dataMax;if(m(c))for(g.push(h);h<=d.dataMax+
a;)h+=c,g.push(h);return g};c.prototype.postProcessTickInterval=function(d){var a=this.axis,c=this.slope;return c?a.options.breaks?a.closestPointRange||d:d/(c/a.closestPointRange):d};return c}();c.Composition=f;c.compose=function(a,d,f){a.keepProps.push("ordinal");var k=a.prototype;a.prototype.getTimeTicks=function(a,d,c,k,f,u,v){void 0===f&&(f=[]);void 0===u&&(u=0);var n=0,t,b,x={},e=[],h=-Number.MAX_VALUE,l=this.options.tickPixelInterval,y=this.chart.time,p=[];if(!this.options.ordinal&&!this.options.breaks||
!f||3>f.length||"undefined"===typeof d)return y.getTimeTicks.apply(y,arguments);var G=f.length;for(t=0;t<G;t++){var C=t&&f[t-1]>c;f[t]<d&&(n=t);if(t===G-1||f[t+1]-f[t]>5*u||C){if(f[t]>h){for(b=y.getTimeTicks(a,f[n],f[t],k);b.length&&b[0]<=h;)b.shift();b.length&&(h=b[b.length-1]);p.push(e.length);e=e.concat(b)}n=t+1}if(C)break}if(b){b=b.info;if(v&&b.unitRange<=A.hour){t=e.length-1;for(n=1;n<t;n++)if(y.dateFormat("%d",e[n])!==y.dateFormat("%d",e[n-1])){x[e[n]]="day";var z=!0}z&&(x[e[0]]="day");b.higherRanks=
x}b.segmentStarts=p;e.info=b}else g(12,!1,this.chart);if(v&&m(l)){n=p=e.length;z=[];var F;for(y=[];n--;)t=this.translate(e[n]),F&&(y[n]=F-t),z[n]=F=t;y.sort();y=y[Math.floor(y.length/2)];y<.6*l&&(y=null);n=e[p-1]>c?p-1:p;for(F=void 0;n--;)t=z[n],p=Math.abs(F-t),F&&p<.8*l&&(null===y||p<.8*y)?(x[e[n]]&&!x[e[n+1]]?(p=n+1,F=t):p=n,e.splice(p,1)):F=t}return e};k.lin2val=function(a,d){var c=this.ordinal,h=c.positions;if(h){var k=c.slope,g=c.offset;c=h.length-1;if(d)if(0>a)a=h[0];else if(a>c)a=h[c];else{c=
Math.floor(a);var v=a-c}else for(;c--;)if(d=k*c+g,a>=d){k=k*(c+1)+g;v=(a-d)/(k-d);break}return"undefined"!==typeof v&&"undefined"!==typeof h[c]?h[c]+(v?v*(h[c+1]-h[c]):0):a}return a};k.val2lin=function(a,d){var c=this.ordinal,h=c.positions;if(h){var k=h.length,g;for(g=k;g--;)if(h[g]===a){var v=g;break}for(g=k-1;g--;)if(a>h[g]||0===g){a=(a-h[g])/(h[g+1]-h[g]);v=g+a;break}d=d?v:c.slope*(v||0)+c.offset}else d=a;return d};k.ordinal2lin=k.val2lin;E(a,"afterInit",function(){this.ordinal||(this.ordinal=
new c.Composition(this))});E(a,"foundExtremes",function(){this.isXAxis&&m(this.options.overscroll)&&this.max===this.dataMax&&(!this.chart.mouseIsDown||this.isInternal)&&(!this.eventArgs||this.eventArgs&&"navigator"!==this.eventArgs.trigger)&&(this.max+=this.options.overscroll,!this.isInternal&&m(this.userMin)&&(this.min+=this.options.overscroll))});E(a,"afterSetScale",function(){this.horiz&&!this.isDirty&&(this.isDirty=this.isOrdinal&&this.chart.navigator&&!this.chart.navigator.adaptToUpdatedData)});
E(a,"initialAxisTranslation",function(){this.ordinal&&(this.ordinal.beforeSetTickPositions(),this.tickInterval=this.ordinal.postProcessTickInterval(this.tickInterval))});E(d,"pan",function(a){var d=this.xAxis[0],c=d.options.overscroll,k=a.originalEvent.chartX,g=this.options.chart&&this.options.chart.panning,f=!1;if(g&&"y"!==g.type&&d.options.ordinal&&d.series.length){var v=this.mouseDownX,n=d.getExtremes(),t=n.dataMax,b=n.min,x=n.max,e=this.hoverPoints,H=d.closestPointRange||d.ordinal&&d.ordinal.overscrollPointsRange;
v=(v-k)/(d.translationSlope*(d.ordinal.slope||H));var l={ordinal:{positions:d.ordinal.getExtendedPositions()}};H=d.lin2val;var y=d.val2lin;if(!l.ordinal.positions)f=!0;else if(1<Math.abs(v)){e&&e.forEach(function(b){b.setState()});if(0>v){e=l;var u=d.ordinal.positions?d:l}else e=d.ordinal.positions?d:l,u=l;l=u.ordinal.positions;t>l[l.length-1]&&l.push(t);this.fixedRange=x-b;v=d.navigatorAxis.toFixedRange(null,null,H.apply(e,[y.apply(e,[b,!0])+v,!0]),H.apply(u,[y.apply(u,[x,!0])+v,!0]));v.min>=Math.min(n.dataMin,
b)&&v.max<=Math.max(t,x)+c&&d.setExtremes(v.min,v.max,!0,!1,{trigger:"pan"});this.mouseDownX=k;D(this.container,{cursor:"move"})}}else f=!0;f||g&&/y/.test(g.type)?c&&(d.max=d.dataMax+c):a.preventDefault()});E(f,"updatedData",function(){var d=this.xAxis;d&&d.options.ordinal&&delete d.ordinal.index})}})(I||(I={}));I.compose(f,q,w);return I});J(f,"Core/Axis/BrokenAxis.js",[f["Core/Axis/Axis.js"],f["Series/Line/LineSeries.js"],f["Extensions/Stacking.js"],f["Core/Utilities.js"]],function(f,B,w,r){var q=
r.addEvent,E=r.find,D=r.fireEvent,m=r.isArray,g=r.isNumber,a=r.pick,A=function(){function g(a){this.hasBreaks=!1;this.axis=a}g.isInBreak=function(a,g){var c=a.repeat||Infinity,d=a.from,f=a.to-a.from;g=g>=d?(g-d)%c:c-(d-g)%c;return a.inclusive?g<=f:g<f&&0!==g};g.lin2Val=function(a){var c=this.brokenAxis;c=c&&c.breakArray;if(!c)return a;var f;for(f=0;f<c.length;f++){var d=c[f];if(d.from>=a)break;else d.to<a?a+=d.len:g.isInBreak(d,a)&&(a+=d.len)}return a};g.val2Lin=function(a){var c=this.brokenAxis;
c=c&&c.breakArray;if(!c)return a;var f=a,d;for(d=0;d<c.length;d++){var m=c[d];if(m.to<=a)f-=m.len;else if(m.from>=a)break;else if(g.isInBreak(m,a)){f-=a-m.from;break}}return f};g.prototype.findBreakAt=function(a,g){return E(g,function(c){return c.from<a&&a<c.to})};g.prototype.isInAnyBreak=function(c,f){var u=this.axis,d=u.options.breaks,m=d&&d.length,k;if(m){for(;m--;)if(g.isInBreak(d[m],c)){var G=!0;k||(k=a(d[m].showPoints,!u.isXAxis))}var h=G&&f?G&&!k:G}return h};g.prototype.setBreaks=function(c,
C){var u=this,d=u.axis,z=m(c)&&!!c.length;d.isDirty=u.hasBreaks!==z;u.hasBreaks=z;d.options.breaks=d.userOptions.breaks=c;d.forceRedraw=!0;d.series.forEach(function(a){a.isDirty=!0});z||d.val2lin!==g.val2Lin||(delete d.val2lin,delete d.lin2val);z&&(d.userOptions.ordinal=!1,d.lin2val=g.lin2Val,d.val2lin=g.val2Lin,d.setExtremes=function(a,d,c,g,m){if(u.hasBreaks){for(var k,h=this.options.breaks;k=u.findBreakAt(a,h);)a=k.to;for(;k=u.findBreakAt(d,h);)d=k.from;d<a&&(d=a)}f.prototype.setExtremes.call(this,
a,d,c,g,m)},d.setAxisTranslation=function(){f.prototype.setAxisTranslation.call(this);u.unitLength=null;if(u.hasBreaks){var c=d.options.breaks||[],m=[],h=[],p=0,z,C=d.userMin||d.min,q=d.userMax||d.max,v=a(d.pointRangePadding,0),n;c.forEach(function(b){z=b.repeat||Infinity;g.isInBreak(b,C)&&(C+=b.to%z-C%z);g.isInBreak(b,q)&&(q-=q%z-b.from%z)});c.forEach(function(a){b=a.from;for(z=a.repeat||Infinity;b-z>C;)b-=z;for(;b<C;)b+=z;for(n=b;n<q;n+=z)m.push({value:n,move:"in"}),m.push({value:n+(a.to-a.from),
move:"out",size:a.breakSize})});m.sort(function(b,e){return b.value===e.value?("in"===b.move?0:1)-("in"===e.move?0:1):b.value-e.value});var t=0;var b=C;m.forEach(function(a){t+="in"===a.move?1:-1;1===t&&"in"===a.move&&(b=a.value);0===t&&(h.push({from:b,to:a.value,len:a.value-b-(a.size||0)}),p+=a.value-b-(a.size||0))});d.breakArray=u.breakArray=h;u.unitLength=q-C-p+v;D(d,"afterBreaks");d.staticScale?d.transA=d.staticScale:u.unitLength&&(d.transA*=(q-d.min+v)/u.unitLength);v&&(d.minPixelPadding=d.transA*
d.minPointOffset);d.min=C;d.max=q}});a(C,!0)&&d.chart.redraw()};return g}();r=function(){function f(){}f.compose=function(c,f){c.keepProps.push("brokenAxis");var m=B.prototype;m.drawBreaks=function(d,c){var k=this,f=k.points,h,p,m,u;if(d&&d.brokenAxis&&d.brokenAxis.hasBreaks){var z=d.brokenAxis;c.forEach(function(c){h=z&&z.breakArray||[];p=d.isXAxis?d.min:a(k.options.threshold,d.min);f.forEach(function(n){u=a(n["stack"+c.toUpperCase()],n[c]);h.forEach(function(a){if(g(p)&&g(u)){m=!1;if(p<a.from&&
u>a.to||p>a.from&&u<a.from)m="pointBreak";else if(p<a.from&&u>a.from&&u<a.to||p>a.from&&u>a.to&&u<a.from)m="pointInBreak";m&&D(d,m,{point:n,brk:a})}})})})}};m.gappedPath=function(){var a=this.currentDataGrouping,c=a&&a.gapSize;a=this.options.gapSize;var g=this.points.slice(),f=g.length-1,h=this.yAxis,p;if(a&&0<f)for("value"!==this.options.gapUnit&&(a*=this.basePointRange),c&&c>a&&c>=this.basePointRange&&(a=c),p=void 0;f--;)p&&!1!==p.visible||(p=g[f+1]),c=g[f],!1!==p.visible&&!1!==c.visible&&(p.x-
c.x>a&&(p=(c.x+p.x)/2,g.splice(f+1,0,{isNull:!0,x:p}),h.stacking&&this.options.stacking&&(p=h.stacking.stacks[this.stackKey][p]=new w(h,h.options.stackLabels,!1,p,this.stack),p.total=0)),p=c);return this.getGraphPath(g)};q(c,"init",function(){this.brokenAxis||(this.brokenAxis=new A(this))});q(c,"afterInit",function(){"undefined"!==typeof this.brokenAxis&&this.brokenAxis.setBreaks(this.options.breaks,!1)});q(c,"afterSetTickPositions",function(){var a=this.brokenAxis;if(a&&a.hasBreaks){var c=this.tickPositions,
g=this.tickPositions.info,f=[],h;for(h=0;h<c.length;h++)a.isInAnyBreak(c[h])||f.push(c[h]);this.tickPositions=f;this.tickPositions.info=g}});q(c,"afterSetOptions",function(){this.brokenAxis&&this.brokenAxis.hasBreaks&&(this.options.ordinal=!1)});q(f,"afterGeneratePoints",function(){var a=this.options.connectNulls,c=this.points,g=this.xAxis,f=this.yAxis;if(this.isDirty)for(var h=c.length;h--;){var p=c[h],m=!(null===p.y&&!1===a)&&(g&&g.brokenAxis&&g.brokenAxis.isInAnyBreak(p.x,!0)||f&&f.brokenAxis&&
f.brokenAxis.isInAnyBreak(p.y,!0));p.visible=m?!1:!1!==p.options.visible}});q(f,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,a(this.pointArrayMap,["y"]))})};return f}();r.compose(f,B);return r});J(f,"masters/modules/broken-axis.src.js",[],function(){});J(f,"Extensions/DataGrouping.js",[f["Core/Axis/Axis.js"],f["Core/Axis/DateTimeAxis.js"],f["Core/Globals.js"],f["Series/Line/LineSeries.js"],f["Core/Options.js"],f["Core/Series/Point.js"],f["Core/Tooltip.js"],
f["Core/Utilities.js"]],function(f,B,w,r,q,E,D,m){var g=r.prototype,a=m.addEvent,A=m.arrayMax,I=m.arrayMin,c=m.correctFloat,C=m.defined,u=m.error,d=m.extend,z=m.format,k=m.isNumber,G=m.merge,h=m.pick;"";var p=w.approximations={sum:function(b){var a=b.length;if(!a&&b.hasNulls)var e=null;else if(a)for(e=0;a--;)e+=b[a];return e},average:function(b){var a=b.length;b=p.sum(b);k(b)&&a&&(b=c(b/a));return b},averages:function(){var b=[];[].forEach.call(arguments,function(a){b.push(p.average(a))});return"undefined"===
typeof b[0]?void 0:b},open:function(b){return b.length?b[0]:b.hasNulls?null:void 0},high:function(b){return b.length?A(b):b.hasNulls?null:void 0},low:function(b){return b.length?I(b):b.hasNulls?null:void 0},close:function(b){return b.length?b[b.length-1]:b.hasNulls?null:void 0},ohlc:function(b,a,e,d){b=p.open(b);a=p.high(a);e=p.low(e);d=p.close(d);if(k(b)||k(a)||k(e)||k(d))return[b,a,e,d]},range:function(b,a){b=p.low(b);a=p.high(a);if(k(b)||k(a))return[b,a];if(null===b&&null===a)return null}};m=function(b,
a,e,d){var c=this,n=c.data,x=c.options&&c.options.data,t=[],g=[],h=[],f=b.length,v=!!a,H=[],m=c.pointArrayMap,u=m&&m.length,q=["x"].concat(m||["y"]),z=0,D=0,A;d="function"===typeof d?d:p[d]?p[d]:p[c.getDGApproximation&&c.getDGApproximation()||"average"];u?m.forEach(function(){H.push([])}):H.push([]);var w=u||1;for(A=0;A<=f&&!(b[A]>=e[0]);A++);for(A;A<=f;A++){for(;"undefined"!==typeof e[z+1]&&b[A]>=e[z+1]||A===f;){var r=e[z];c.dataGroupInfo={start:c.cropStart+D,length:H[0].length};var I=d.apply(c,
H);c.pointClass&&!C(c.dataGroupInfo.options)&&(c.dataGroupInfo.options=G(c.pointClass.prototype.optionsToObject.call({series:c},c.options.data[c.cropStart+D])),q.forEach(function(b){delete c.dataGroupInfo.options[b]}));"undefined"!==typeof I&&(t.push(r),g.push(I),h.push(c.dataGroupInfo));D=A;for(r=0;r<w;r++)H[r].length=0,H[r].hasNulls=!1;z+=1;if(A===f)break}if(A===f)break;if(m)for(r=c.cropStart+A,I=n&&n[r]||c.pointClass.prototype.applyOptions.apply({series:c},[x[r]]),r=0;r<u;r++){var F=I[m[r]];k(F)?
H[r].push(F):null===F&&(H[r].hasNulls=!0)}else r=v?a[A]:null,k(r)?H[0].push(r):null===r&&(H[0].hasNulls=!0)}return{groupedXData:t,groupedYData:g,groupMap:h}};var M={approximations:p,groupData:m},L=g.processData,F=g.generatePoints,v={groupPixelWidth:2,dateTimeLabelFormats:{millisecond:["%A, %b %e, %H:%M:%S.%L","%A, %b %e, %H:%M:%S.%L","-%H:%M:%S.%L"],second:["%A, %b %e, %H:%M:%S","%A, %b %e, %H:%M:%S","-%H:%M:%S"],minute:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],hour:["%A, %b %e, %H:%M","%A, %b %e, %H:%M",
"-%H:%M"],day:["%A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],week:["Week from %A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],month:["%B %Y","%B","-%B %Y"],year:["%Y","%Y","-%Y"]}},n={line:{},spline:{},area:{},areaspline:{},arearange:{},column:{groupPixelWidth:10},columnrange:{groupPixelWidth:10},candlestick:{groupPixelWidth:10},ohlc:{groupPixelWidth:5}},t=w.defaultDataGroupingUnits=[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,
3,4,6,8,12]],["day",[1]],["week",[1]],["month",[1,3,6]],["year",null]];g.getDGApproximation=function(){return this.is("arearange")?"range":this.is("ohlc")?"ohlc":this.is("column")?"sum":"average"};g.groupData=m;g.processData=function(){var b=this.chart,a=this.options.dataGrouping,e=!1!==this.allowDG&&a&&h(a.enabled,b.options.isStock),c=this.visible||!b.options.chart.ignoreHiddenSeries,d,n=this.currentDataGrouping,k=!1;this.forceCrop=e;this.groupPixelWidth=null;this.hasProcessed=!0;e&&!this.requireSorting&&
(this.requireSorting=k=!0);e=!1===L.apply(this,arguments)||!e;k&&(this.requireSorting=!1);if(!e){this.destroyGroupedData();e=a.groupAll?this.xData:this.processedXData;var f=a.groupAll?this.yData:this.processedYData,p=b.plotSizeX;b=this.xAxis;var v=b.options.ordinal,m=this.groupPixelWidth=b.getGroupPixelWidth&&b.getGroupPixelWidth();if(m){this.isDirty=d=!0;this.points=null;k=b.getExtremes();var u=k.min;k=k.max;v=v&&b.ordinal&&b.ordinal.getGroupIntervalFactor(u,k,this)||1;m=m*(k-u)/p*v;p=b.getTimeTicks(B.AdditionsClass.prototype.normalizeTimeTickInterval(m,
a.units||t),Math.min(u,e[0]),Math.max(k,e[e.length-1]),b.options.startOfWeek,e,this.closestPointRange);f=g.groupData.apply(this,[e,f,p,a.approximation]);e=f.groupedXData;v=f.groupedYData;var q=0;if(a.smoothed&&e.length){var A=e.length-1;for(e[A]=Math.min(e[A],k);A--&&0<A;)e[A]+=m/2;e[0]=Math.max(e[0],u)}for(A=1;A<p.length;A++)p.info.segmentStarts&&-1!==p.info.segmentStarts.indexOf(A)||(q=Math.max(p[A]-p[A-1],q));u=p.info;u.gapSize=q;this.closestPointRange=p.info.totalRange;this.groupMap=f.groupMap;
if(C(e[0])&&e[0]<b.min&&c){if(!C(b.options.min)&&b.min<=b.dataMin||b.min===b.dataMin)b.min=Math.min(e[0],b.min);b.dataMin=Math.min(e[0],b.dataMin)}a.groupAll&&(a=this.cropData(e,v,b.min,b.max,1),e=a.xData,v=a.yData);this.processedXData=e;this.processedYData=v}else this.groupMap=null;this.hasGroupedData=d;this.currentDataGrouping=u;this.preventGraphAnimation=(n&&n.totalRange)!==(u&&u.totalRange)}};g.destroyGroupedData=function(){this.groupedData&&(this.groupedData.forEach(function(b,a){b&&(this.groupedData[a]=
b.destroy?b.destroy():null)},this),this.groupedData.length=0)};g.generatePoints=function(){F.apply(this);this.destroyGroupedData();this.groupedData=this.hasGroupedData?this.points:null};a(E,"update",function(){if(this.dataGroup)return u(24,!1,this.series.chart),!1});a(D,"headerFormatter",function(b){var a=this.chart,e=a.time,c=b.labelConfig,n=c.series,t=n.tooltipOptions,g=n.options.dataGrouping,h=t.xDateFormat,f=n.xAxis,p=t[(b.isFooter?"footer":"header")+"Format"];if(f&&"datetime"===f.options.type&&
g&&k(c.key)){var m=n.currentDataGrouping;g=g.dateTimeLabelFormats||v.dateTimeLabelFormats;if(m)if(t=g[m.unitName],1===m.count)h=t[0];else{h=t[1];var u=t[2]}else!h&&g&&(h=this.getXDateFormat(c,t,f));h=e.dateFormat(h,c.key);u&&(h+=e.dateFormat(u,c.key+m.totalRange-1));n.chart.styledMode&&(p=this.styledModeFormat(p));b.text=z(p,{point:d(c.point,{key:h}),series:n},a);b.preventDefault()}});a(r,"destroy",g.destroyGroupedData);a(r,"afterSetOptions",function(b){b=b.options;var a=this.type,e=this.chart.options.plotOptions,
c=q.defaultOptions.plotOptions[a].dataGrouping,d=this.useCommonDataGrouping&&v;if(n[a]||d)c||(c=G(v,n[a])),b.dataGrouping=G(d,c,e.series&&e.series.dataGrouping,e[a].dataGrouping,this.userOptions.dataGrouping)});a(f,"afterSetScale",function(){this.series.forEach(function(b){b.hasProcessed=!1})});f.prototype.getGroupPixelWidth=function(){var b=this.series,a=b.length,e,c=0,d=!1,n;for(e=a;e--;)(n=b[e].options.dataGrouping)&&(c=Math.max(c,h(n.groupPixelWidth,v.groupPixelWidth)));for(e=a;e--;)(n=b[e].options.dataGrouping)&&
b[e].hasProcessed&&(a=(b[e].processedXData||b[e].data).length,b[e].groupPixelWidth||a>this.chart.plotSizeX/c||a&&n.forced)&&(d=!0);return d?c:0};f.prototype.setDataGrouping=function(b,a){var e;a=h(a,!0);b||(b={forced:!1,units:null});if(this instanceof f)for(e=this.series.length;e--;)this.series[e].update({dataGrouping:b},!1);else this.chart.options.series.forEach(function(e){e.dataGrouping=b},!1);this.ordinal&&(this.ordinal.slope=void 0);a&&this.chart.redraw()};w.dataGrouping=M;"";return M});J(f,
"Series/OHLC/OHLCPoint.js",[f["Core/Series/Series.js"]],function(f){var B=this&&this.__extends||function(){var f=function(r,q){f=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(f,q){f.__proto__=q}||function(f,q){for(var m in q)q.hasOwnProperty(m)&&(f[m]=q[m])};return f(r,q)};return function(r,q){function w(){this.constructor=r}f(r,q);r.prototype=null===q?Object.create(q):(w.prototype=q.prototype,new w)}}();return function(f){function r(){var q=null!==f&&f.apply(this,arguments)||this;
q.close=void 0;q.high=void 0;q.low=void 0;q.open=void 0;q.options=void 0;q.plotClose=void 0;q.plotOpen=void 0;q.series=void 0;return q}B(r,f);r.prototype.getClassName=function(){return f.prototype.getClassName.call(this)+(this.open<this.close?" highcharts-point-up":" highcharts-point-down")};return r}(f.seriesTypes.column.prototype.pointClass)});J(f,"Series/OHLC/OHLCSeries.js",[f["Core/Series/Series.js"],f["Series/OHLC/OHLCPoint.js"],f["Core/Utilities.js"]],function(f,B,w){var r=this&&this.__extends||
function(){var f=function(g,a){f=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,g){a.__proto__=g}||function(a,g){for(var c in g)g.hasOwnProperty(c)&&(a[c]=g[c])};return f(g,a)};return function(g,a){function m(){this.constructor=g}f(g,a);g.prototype=null===a?Object.create(a):(m.prototype=a.prototype,new m)}}(),q=f.seriesTypes.column,E=w.extend,D=w.merge;w=function(f){function g(){var a=null!==f&&f.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;a.yData=
void 0;return a}r(g,f);g.prototype.drawPoints=function(){var a=this,g=a.chart,f=function(a,g,f){var c=a[0];a=a[1];"number"===typeof c[2]&&(c[2]=Math.max(f+g,c[2]));"number"===typeof a[2]&&(a[2]=Math.min(f-g,a[2]))};a.points.forEach(function(c){var m=c.graphic,u=!m;if("undefined"!==typeof c.plotY){m||(c.graphic=m=g.renderer.path().add(a.group));g.styledMode||m.attr(a.pointAttribs(c,c.selected&&"select"));var d=m.strokeWidth();var q=d%2/2;var k=Math.round(c.plotX)-q;var A=Math.round(c.shapeArgs.width/
2);var h=[["M",k,Math.round(c.yBottom)],["L",k,Math.round(c.plotHigh)]];if(null!==c.open){var p=Math.round(c.plotOpen)+q;h.push(["M",k,p],["L",k-A,p]);f(h,d/2,p)}null!==c.close&&(p=Math.round(c.plotClose)+q,h.push(["M",k,p],["L",k+A,p]),f(h,d/2,p));m[u?"attr":"animate"]({d:h}).addClass(c.getClassName(),!0)}})};g.prototype.init=function(){f.prototype.init.apply(this,arguments);this.options.stacking=void 0};g.prototype.pointAttribs=function(a,g){g=f.prototype.pointAttribs.call(this,a,g);var m=this.options;
delete g.fill;!a.options.color&&m.upColor&&a.open<a.close&&(g.stroke=m.upColor);return g};g.prototype.toYData=function(a){return[a.open,a.high,a.low,a.close]};g.prototype.translate=function(){var a=this,g=a.yAxis,m=!!a.modifyValue,c=["plotOpen","plotHigh","plotLow","plotClose","yBottom"];f.prototype.translate.apply(a);a.points.forEach(function(f){[f.open,f.high,f.low,f.close,f.low].forEach(function(u,d){null!==u&&(m&&(u=a.modifyValue(u)),f[c[d]]=g.toPixels(u,!0))});f.tooltipPos[1]=f.plotHigh+g.pos-
a.chart.plotTop})};g.defaultOptions=D(q.defaultOptions,{lineWidth:1,tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Open: {point.open}<br/>High: {point.high}<br/>Low: {point.low}<br/>Close: {point.close}<br/>'},threshold:null,states:{hover:{lineWidth:3}},stickyTracking:!0});return g}(q);E(w.prototype,{animate:null,directTouch:!1,pointArrayMap:["open","high","low","close"],pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"},pointValKey:"close"});
w.prototype.pointClass=B;f.registerSeriesType("ohlc",w);"";return w});J(f,"Series/Candlestick/CandlestickSeries.js",[f["Core/Series/Series.js"],f["Core/Options.js"],f["Core/Color/Palette.js"],f["Core/Utilities.js"]],function(f,B,w,r){var q=this&&this.__extends||function(){var a=function(g,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var d in c)c.hasOwnProperty(d)&&(a[d]=c[d])};return a(g,c)};return function(g,c){function f(){this.constructor=
g}a(g,c);g.prototype=null===c?Object.create(c):(f.prototype=c.prototype,new f)}}(),E=f.seriesTypes,D=E.ohlc,m=E.column.prototype,g=B.defaultOptions,a=r.merge;B=function(f){function r(){var a=null!==f&&f.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}q(r,f);r.prototype.pointAttribs=function(a,g){var c=m.pointAttribs.call(this,a,g),d=this.options,f=a.open<a.close,k=d.lineColor||this.color;c["stroke-width"]=d.lineWidth;c.fill=a.options.color||(f?d.upColor||this.color:
this.color);c.stroke=a.options.lineColor||(f?d.upLineColor||k:k);g&&(a=d.states[g],c.fill=a.color||c.fill,c.stroke=a.lineColor||c.stroke,c["stroke-width"]=a.lineWidth||c["stroke-width"]);return c};r.prototype.drawPoints=function(){var a=this,g=a.chart,f=a.yAxis.reversed;a.points.forEach(function(c){var d=c.graphic,k=!d;if("undefined"!==typeof c.plotY){d||(c.graphic=d=g.renderer.path().add(a.group));a.chart.styledMode||d.attr(a.pointAttribs(c,c.selected&&"select")).shadow(a.options.shadow);var m=d.strokeWidth()%
2/2;var h=Math.round(c.plotX)-m;var p=c.plotOpen;var u=c.plotClose;var q=Math.min(p,u);p=Math.max(p,u);var r=Math.round(c.shapeArgs.width/2);u=f?p!==c.yBottom:Math.round(q)!==Math.round(c.plotHigh);var v=f?Math.round(q)!==Math.round(c.plotHigh):p!==c.yBottom;q=Math.round(q)+m;p=Math.round(p)+m;m=[];m.push(["M",h-r,p],["L",h-r,q],["L",h+r,q],["L",h+r,p],["Z"],["M",h,q],["L",h,u?Math.round(f?c.yBottom:c.plotHigh):q],["M",h,p],["L",h,v?Math.round(f?c.plotHigh:c.yBottom):p]);d[k?"attr":"animate"]({d:m}).addClass(c.getClassName(),
!0)}})};r.defaultOptions=a(D.defaultOptions,g.plotOptions,{states:{hover:{lineWidth:2}},tooltip:g.plotOptions.ohlc.tooltip,threshold:null,lineColor:w.neutralColor100,lineWidth:1,upColor:w.backgroundColor,stickyTracking:!0});return r}(D);f.registerSeriesType("candlestick",B);"";return B});J(f,"Series/Flags/FlagsPoint.js",[f["Core/Series/Series.js"],f["Core/Utilities.js"]],function(f,B){var w=this&&this.__extends||function(){var f=function(q,r){f=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&
function(f,g){f.__proto__=g}||function(f,g){for(var a in g)g.hasOwnProperty(a)&&(f[a]=g[a])};return f(q,r)};return function(q,r){function m(){this.constructor=q}f(q,r);q.prototype=null===r?Object.create(r):(m.prototype=r.prototype,new m)}}(),r=B.isNumber;return function(f){function q(){var q=null!==f&&f.apply(this,arguments)||this;q.options=void 0;q.series=void 0;return q}w(q,f);q.prototype.isValid=function(){return r(this.y)||"undefined"===typeof this.y};return q}(f.seriesTypes.column.prototype.pointClass)});
J(f,"Mixins/OnSeries.js",[f["Series/Column/ColumnSeries.js"],f["Series/Line/LineSeries.js"],f["Core/Utilities.js"]],function(f,B,w){var r=f.prototype,q=B.prototype,E=w.defined,D=w.stableSort;return{getPlotBox:function(){return q.getPlotBox.call(this.options.onSeries&&this.chart.get(this.options.onSeries)||this)},translate:function(){r.translate.apply(this);var f=this,g=f.options,a=f.chart,q=f.points,w=q.length-1,c,C=g.onSeries;C=C&&a.get(C);g=g.onKey||"y";var u=C&&C.options.step,d=C&&C.points,z=d&&
d.length,k=a.inverted,G=f.xAxis,h=f.yAxis,p=0,B;if(C&&C.visible&&z){p=(C.pointXOffset||0)+(C.barW||0)/2;a=C.currentDataGrouping;var L=d[z-1].x+(a?a.totalRange:0);D(q,function(a,c){return a.x-c.x});for(g="plot"+g[0].toUpperCase()+g.substr(1);z--&&q[w];){var F=d[z];a=q[w];a.y=F.y;if(F.x<=a.x&&"undefined"!==typeof F[g]){if(a.x<=L&&(a.plotY=F[g],F.x<a.x&&!u&&(B=d[z+1])&&"undefined"!==typeof B[g])){var v=(a.x-F.x)/(B.x-F.x);a.plotY+=v*(B[g]-F[g]);a.y+=v*(B.y-F.y)}w--;z++;if(0>w)break}}}q.forEach(function(a,
d){a.plotX+=p;if("undefined"===typeof a.plotY||k)0<=a.plotX&&a.plotX<=G.len?k?(a.plotY=G.translate(a.x,0,1,0,1),a.plotX=E(a.y)?h.translate(a.y,0,0,0,1):0):a.plotY=(G.opposite?0:f.yAxis.len)+G.offset:a.shapeArgs={};if((c=q[d-1])&&c.plotX===a.plotX){"undefined"===typeof c.stackIndex&&(c.stackIndex=0);var b=c.stackIndex+1}a.stackIndex=b});this.onSeries=C}}});J(f,"Series/Flags/FlagsSymbols.js",[f["Core/Globals.js"],f["Core/Renderer/SVG/SVGRenderer.js"]],function(f,B){function w(f){E[f+"pin"]=function(m,
g,a,q,r){var c=r&&r.anchorX;r=r&&r.anchorY;"circle"===f&&q>a&&(m-=Math.round((q-a)/2),a=q);var w=E[f](m,g,a,q);if(c&&r){var u=c;"circle"===f?u=m+a/2:(m=w[0],a=w[1],"M"===m[0]&&"L"===a[0]&&(u=(m[1]+a[1])/2));w.push(["M",u,g>r?g:g+q],["L",c,r]);w=w.concat(E.circle(c-1,r-1,2,2))}return w}}var r=f.Renderer,q=f.VMLRenderer,E=B.prototype.symbols;E.flag=function(f,m,g,a,q){var r=q&&q.anchorX||f;q=q&&q.anchorY||m;var c=E.circle(r-1,q-1,2,2);c.push(["M",r,q],["L",f,m+a],["L",f,m],["L",f+g,m],["L",f+g,m+a],
["L",f,m+a],["Z"]);return c};w("circle");w("square");r===q&&["circlepin","flag","squarepin"].forEach(function(f){q.prototype.symbols[f]=E[f]});return E});J(f,"Series/Flags/FlagsSeries.js",[f["Core/Series/Series.js"],f["Series/Flags/FlagsPoint.js"],f["Core/Globals.js"],f["Mixins/OnSeries.js"],f["Core/Color/Palette.js"],f["Core/Renderer/SVG/SVGElement.js"],f["Core/Utilities.js"]],function(f,B,w,r,q,E,D){var m=this&&this.__extends||function(){var a=function(c,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof
Array&&function(a,c){a.__proto__=c}||function(a,c){for(var d in c)c.hasOwnProperty(d)&&(a[d]=c[d])};return a(c,d)};return function(c,d){function f(){this.constructor=c}a(c,d);c.prototype=null===d?Object.create(d):(f.prototype=d.prototype,new f)}}(),g=f.seriesTypes,a=g.column,A=g.line;g=w.noop;var I=D.addEvent,c=D.defined,C=D.extend,u=D.merge,d=D.objectEach,z=D.wrap;D=function(f){function g(){var a=null!==f&&f.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}m(g,
f);g.prototype.animate=function(a){a&&this.setClip()};g.prototype.drawPoints=function(){var a=this.points,f=this.chart,g=f.renderer,k=f.inverted,m=this.options,v=m.y,n,t=this.yAxis,b={},x=[];for(n=a.length;n--;){var e=a[n];var H=(k?e.plotY:e.plotX)>this.xAxis.len;var l=e.plotX;var y=e.stackIndex;var q=e.options.shape||m.shape;var r=e.plotY;"undefined"!==typeof r&&(r=e.plotY+v-("undefined"!==typeof y&&y*m.stackDistance));e.anchorX=y?void 0:e.plotX;var A=y?void 0:e.plotY;var O="flag"!==q;y=e.graphic;
"undefined"!==typeof r&&0<=l&&!H?(y||(y=e.graphic=g.label("",null,null,q,null,null,m.useHTML).addClass("highcharts-point").add(this.markerGroup),e.graphic.div&&(e.graphic.div.point=e),y.isNew=!0),y.attr({align:O?"center":"left",width:m.width,height:m.height,"text-align":m.textAlign}),f.styledMode||y.attr(this.pointAttribs(e)).css(u(m.style,e.style)).shadow(m.shadow),0<l&&(l-=y.strokeWidth()%2),q={y:r,anchorY:A},m.allowOverlapX&&(q.x=l,q.anchorX=e.anchorX),y.attr({text:e.options.title||m.title||"A"})[y.isNew?
"attr":"animate"](q),m.allowOverlapX||(b[e.plotX]?b[e.plotX].size=Math.max(b[e.plotX].size,y.width):b[e.plotX]={align:O?.5:0,size:y.width,target:l,anchorX:l}),e.tooltipPos=[l,r+t.pos-f.plotTop]):y&&(e.graphic=y.destroy())}m.allowOverlapX||(d(b,function(b){b.plotX=b.anchorX;x.push(b)}),w.distribute(x,k?t.len:this.xAxis.len,100),a.forEach(function(a){var e=a.graphic&&b[a.plotX];e&&(a.graphic[a.graphic.isNew?"attr":"animate"]({x:e.pos+e.align*e.size,anchorX:a.anchorX}),c(e.pos)?a.graphic.isNew=!1:(a.graphic.attr({x:-9999,
anchorX:-9999}),a.graphic.isNew=!0))}));m.useHTML&&z(this.markerGroup,"on",function(b){return E.prototype.on.apply(b.apply(this,[].slice.call(arguments,1)),[].slice.call(arguments,1))})};g.prototype.drawTracker=function(){var a=this.points;f.prototype.drawTracker.call(this);a.forEach(function(c){var d=c.graphic;d&&I(d.element,"mouseover",function(){0<c.stackIndex&&!c.raised&&(c._y=d.y,d.attr({y:c._y-8}),c.raised=!0);a.forEach(function(a){a!==c&&a.raised&&a.graphic&&(a.graphic.attr({y:a._y}),a.raised=
!1)})})})};g.prototype.pointAttribs=function(a,c){var d=this.options,f=a&&a.color||this.color,g=d.lineColor,k=a&&a.lineWidth;a=a&&a.fillColor||d.fillColor;c&&(a=d.states[c].fillColor,g=d.states[c].lineColor,k=d.states[c].lineWidth);return{fill:a||f,stroke:g||f,"stroke-width":k||d.lineWidth||0}};g.prototype.setClip=function(){A.prototype.setClip.apply(this,arguments);!1!==this.options.clip&&this.sharedClipKey&&this.markerGroup.clip(this.chart[this.sharedClipKey])};g.defaultOptions=u(a.defaultOptions,
{pointRange:0,allowOverlapX:!1,shape:"flag",stackDistance:12,textAlign:"center",tooltip:{pointFormat:"{point.text}<br/>"},threshold:null,y:-30,fillColor:q.backgroundColor,lineWidth:1,states:{hover:{lineColor:q.neutralColor100,fillColor:q.highlightColor20}},style:{fontSize:"11px",fontWeight:"bold"}});return g}(a);C(D.prototype,{allowDG:!1,buildKDTree:g,forceCrop:!0,getPlotBox:r.getPlotBox,init:A.prototype.init,invertGroups:g,noSharedTooltip:!0,pointClass:B,sorted:!1,takeOrdinalPosition:!1,trackerGroups:["markerGroup"],
translate:r.translate});f.registerSeriesType("flags",D);"";"";return D});J(f,"Extensions/RangeSelector.js",[f["Core/Axis/Axis.js"],f["Core/Chart/Chart.js"],f["Core/Globals.js"],f["Core/Options.js"],f["Core/Color/Palette.js"],f["Core/Renderer/SVG/SVGElement.js"],f["Core/Utilities.js"]],function(f,B,w,r,q,E,D){function m(a){if(-1!==a.indexOf("%L"))return"text";var c="aAdewbBmoyY".split("").some(function(b){return-1!==a.indexOf("%"+b)}),d="HkIlMS".split("").some(function(b){return-1!==a.indexOf("%"+
b)});return c&&d?"datetime-local":c?"date":d?"time":"text"}var g=r.defaultOptions,a=D.addEvent,A=D.createElement,I=D.css,c=D.defined,C=D.destroyObjectProperties,u=D.discardElement,d=D.extend,z=D.fireEvent,k=D.isNumber,G=D.merge,h=D.objectEach,p=D.pick,J=D.pInt,L=D.splat;d(g,{rangeSelector:{allButtonsEnabled:!1,buttons:void 0,buttonSpacing:5,enabled:void 0,verticalAlign:"top",buttonTheme:{width:28,height:18,padding:2,zIndex:7},floating:!1,x:0,y:0,height:void 0,inputBoxBorderColor:q.neutralColor20,
inputBoxHeight:17,inputBoxWidth:90,inputDateFormat:"%b %e, %Y",inputDateParser:void 0,inputEditDateFormat:"%Y-%m-%d",inputEnabled:!0,inputPosition:{align:"right",x:0,y:0},inputSpacing:5,selected:void 0,buttonPosition:{align:"left",x:0,y:0},inputStyle:{},labelStyle:{color:q.neutralColor60}}});g.lang=G(g.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",rangeSelectorTo:"To"});var F=function(){function v(a){this.buttons=void 0;this.buttonOptions=v.prototype.defaultButtons;this.options=void 0;this.chart=
a;this.init(a)}v.prototype.clickButton=function(d,t){var b=this.chart,n=this.buttonOptions[d],e=b.xAxis[0],g=b.scroller&&b.scroller.getUnionExtremes()||e||{},l=g.dataMin,h=g.dataMax,m=e&&Math.round(Math.min(e.max,p(h,e.max))),v=n.type;g=n._range;var q,u=n.dataGrouping;if(null!==l&&null!==h){b.fixedRange=g;u&&(this.forcedDataGrouping=!0,f.prototype.setDataGrouping.call(e||{chart:this.chart},u,!1),this.frozenStates=n.preserveDataGrouping);if("month"===v||"year"===v)if(e){v={range:n,max:m,chart:b,dataMin:l,
dataMax:h};var r=e.minFromRange.call(v);k(v.newMax)&&(m=v.newMax)}else g=n;else if(g)r=Math.max(m-g,l),m=Math.min(r+g,h);else if("ytd"===v)if(e)"undefined"===typeof h&&(l=Number.MAX_VALUE,h=Number.MIN_VALUE,b.series.forEach(function(b){b=b.xData;l=Math.min(b[0],l);h=Math.max(b[b.length-1],h)}),t=!1),m=this.getYTDExtremes(h,l,b.time.useUTC),r=q=m.min,m=m.max;else{this.deferredYTDClick=d;return}else"all"===v&&e&&(r=l,m=h);c(r)&&(r+=n._offsetMin);c(m)&&(m+=n._offsetMax);this.setSelected(d);if(e)e.setExtremes(r,
m,p(t,!0),void 0,{trigger:"rangeSelectorButton",rangeSelectorButton:n});else{var w=L(b.options.xAxis)[0];var A=w.range;w.range=g;var B=w.min;w.min=q;a(b,"load",function(){w.range=A;w.min=B})}z(this,"afterBtnClick")}};v.prototype.setSelected=function(a){this.selected=this.options.selected=a};v.prototype.init=function(c){var d=this,b=c.options.rangeSelector,f=b.buttons||d.defaultButtons.slice(),e=b.selected,g=function(){var b=d.minInput,a=d.maxInput;b&&b.blur&&z(b,"blur");a&&a.blur&&z(a,"blur")};d.chart=
c;d.options=b;d.buttons=[];d.buttonOptions=f;this.unMouseDown=a(c.container,"mousedown",g);this.unResize=a(c,"resize",g);f.forEach(d.computeButtonRange);"undefined"!==typeof e&&f[e]&&this.clickButton(e,!1);a(c,"load",function(){c.xAxis&&c.xAxis[0]&&a(c.xAxis[0],"setExtremes",function(b){this.max-this.min!==c.fixedRange&&"rangeSelectorButton"!==b.trigger&&"updatedData"!==b.trigger&&d.forcedDataGrouping&&!d.frozenStates&&this.setDataGrouping(!1,!1)})})};v.prototype.updateButtonStates=function(){var a=
this,c=this.chart,b=c.xAxis[0],d=Math.round(b.max-b.min),e=!b.hasVisibleSeries,f=c.scroller&&c.scroller.getUnionExtremes()||b,g=f.dataMin,h=f.dataMax;c=a.getYTDExtremes(h,g,c.time.useUTC);var m=c.min,v=c.max,p=a.selected,q=k(p),u=a.options.allButtonsEnabled,r=a.buttons;a.buttonOptions.forEach(function(c,f){var n=c._range,t=c.type,l=c.count||1,x=r[f],k=0,y=c._offsetMax-c._offsetMin;c=f===p;var H=n>h-g,K=n<b.minRange,w=!1,z=!1;n=n===d;("month"===t||"year"===t)&&d+36E5>=864E5*{month:28,year:365}[t]*
l-y&&d-36E5<=864E5*{month:31,year:366}[t]*l+y?n=!0:"ytd"===t?(n=v-m+y===d,w=!c):"all"===t&&(n=b.max-b.min>=h-g,z=!c&&q&&n);t=!u&&(H||K||z||e);l=c&&n||n&&!q&&!w||c&&a.frozenStates;t?k=3:l&&(q=!0,k=2);x.state!==k&&(x.setState(k),0===k&&p===f&&a.setSelected())})};v.prototype.computeButtonRange=function(a){var c=a.type,b=a.count||1,d={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5};if(d[c])a._range=d[c]*b;else if("month"===c||"year"===c)a._range=864E5*{month:30,year:365}[c]*b;a._offsetMin=
p(a.offsetMin,0);a._offsetMax=p(a.offsetMax,0);a._range+=a._offsetMax-a._offsetMin};v.prototype.getInputValue=function(a){a="min"===a?this.minInput:this.maxInput;var c=this.chart.options.rangeSelector,b=this.chart.time;return a?("text"===a.type&&c.inputDateParser||this.defaultInputDateParser)(a.value,b.useUTC,b):0};v.prototype.setInputValue=function(a,d){var b=this.options,f=this.chart.time,e="min"===a?this.minInput:this.maxInput;a="min"===a?this.minDateBox:this.maxDateBox;if(e){var g=e.getAttribute("data-hc-time");
g=c(g)?Number(g):void 0;c(d)&&(c(g)&&e.setAttribute("data-hc-time-previous",g),e.setAttribute("data-hc-time",d),g=d);e.value=f.dateFormat(this.inputTypeFormats[e.type]||b.inputEditDateFormat,g);a&&a.attr({text:f.dateFormat(b.inputDateFormat,g)})}};v.prototype.setInputExtremes=function(a,c,b){if(a="min"===a?this.minInput:this.maxInput){var d=this.inputTypeFormats[a.type],e=this.chart.time;d&&(c=e.dateFormat(d,c),a.min!==c&&(a.min=c),b=e.dateFormat(d,b),a.max!==b&&(a.max=b))}};v.prototype.showInput=
function(a){var c="min"===a?this.minDateBox:this.maxDateBox;if((a="min"===a?this.minInput:this.maxInput)&&c&&this.inputGroup){var b="text"===a.type,d=this.inputGroup,e=d.translateX;d=d.translateY;I(a,{width:b?c.width-2+"px":"auto",height:b?c.height-2+"px":"auto",border:"2px solid silver"});b?I(a,{left:e+c.x+"px",top:d+"px"}):I(a,{left:Math.min(Math.round(c.x+e-(a.offsetWidth-c.width)/2),this.chart.chartWidth-a.offsetWidth)+"px",top:d-(a.offsetHeight-c.height)/2+"px"})}};v.prototype.hideInput=function(a){(a=
"min"===a?this.minInput:this.maxInput)&&I(a,{top:"-9999em",border:0,width:"1px",height:"1px"})};v.prototype.defaultInputDateParser=function(a,c,b){var d=a.split("/").join("-").split(" ").join("T");-1===d.indexOf("T")&&(d+="T00:00");if(c)d+="Z";else{var e;if(e=w.isSafari)e=d,e=!(6<e.length&&(e.lastIndexOf("-")===e.length-6||e.lastIndexOf("+")===e.length-6));e&&(e=(new Date(d)).getTimezoneOffset()/60,d+=0>=e?"+"+w.pad(-e)+":00":"-"+w.pad(e)+":00")}d=Date.parse(d);k(d)||(a=a.split("-"),d=Date.UTC(J(a[0]),
J(a[1])-1,J(a[2])));b&&c&&(d+=b.getTimezoneOffset(d));return d};v.prototype.drawInput=function(a){function c(){var e=n.getInputValue(a),c=b.xAxis[0],d=b.scroller&&b.scroller.xAxis?b.scroller.xAxis:c,f=d.dataMin;d=d.dataMax;var g=n.maxInput,l=n.minInput;e!==Number(r.getAttribute("data-hc-time-previous"))&&k(e)&&(r.setAttribute("data-hc-time-previous",e),p&&g&&k(f)?e>Number(g.getAttribute("data-hc-time"))?e=void 0:e<f&&(e=f):l&&k(d)&&(e<Number(l.getAttribute("data-hc-time"))?e=void 0:e>d&&(e=d)),"undefined"!==
typeof e&&c.setExtremes(p?e:c.min,p?c.max:e,void 0,void 0,{trigger:"rangeSelectorInput"}))}var b=this.chart,f=this.div,e=this.inputGroup,n=this,l=b.renderer.style||{},h=b.renderer,v=b.options.rangeSelector,p="min"===a,u=h.label(g.lang[p?"rangeSelectorFrom":"rangeSelectorTo"],0).addClass("highcharts-range-label").attr({padding:2}).add(e);h=h.label("",0).addClass("highcharts-range-input").attr({padding:2,width:v.inputBoxWidth,height:v.inputBoxHeight,"text-align":"center"}).on("click",function(){n.showInput(a);
n[a+"Input"].focus()});b.styledMode||h.attr({stroke:v.inputBoxBorderColor,"stroke-width":1});h.add(e);var r=A("input",{name:a,className:"highcharts-range-selector",type:m(v.inputDateFormat||"%b %e, %Y")},void 0,f);b.styledMode||(u.css(G(l,v.labelStyle)),h.css(G({color:q.neutralColor80},l,v.inputStyle)),I(r,d({position:"absolute",border:0,boxShadow:"0 0 15px rgba(0,0,0,0.3)",width:"1px",height:"1px",padding:0,textAlign:"center",fontSize:l.fontSize,fontFamily:l.fontFamily,top:"-9999em"},v.inputStyle)));
r.onfocus=function(){n.showInput(a)};r.onblur=function(){r===w.doc.activeElement&&c();n.hideInput(a);n.setInputValue(a);r.blur()};var z=!1;r.onchange=function(){c();z||(n.hideInput(a),r.blur())};r.onkeypress=function(a){13===a.keyCode&&c()};r.onkeydown=function(){z=!0};r.onkeyup=function(){z=!1};return{dateBox:h,input:r,label:u}};v.prototype.getPosition=function(){var a=this.chart,c=a.options.rangeSelector;a="top"===c.verticalAlign?a.plotTop-a.axisOffset[0]:0;return{buttonTop:a+c.buttonPosition.y,
inputTop:a+c.inputPosition.y-10}};v.prototype.getYTDExtremes=function(a,c,b){var d=this.chart.time,e=new d.Date(a),f=d.get("FullYear",e);b=b?d.Date.UTC(f,0,1):+new d.Date(f,0,1);c=Math.max(c,b);e=e.getTime();return{max:Math.min(a||e,e),min:c}};v.prototype.render=function(a,d){var b=this.chart,f=b.renderer,e=b.container,g=b.options,l=g.rangeSelector,t=p(g.chart.style&&g.chart.style.zIndex,0)+1;g=l.inputEnabled;if(!1!==l.enabled){this.rendered||(this.group=f.g("range-selector-group").attr({zIndex:7}).add(),
this.div=A("div",void 0,{position:"relative",height:0,zIndex:t}),this.renderButtons(),g&&e.parentNode&&(e.parentNode.insertBefore(this.div,e),this.inputGroup=f.g("input-group").add(this.group),f=this.drawInput("min"),this.minDateBox=f.dateBox,this.minLabel=f.label,this.minInput=f.input,f=this.drawInput("max"),this.maxDateBox=f.dateBox,this.maxLabel=f.label,this.maxInput=f.input));if(g&&(this.setInputValue("min",a),this.setInputValue("max",d),a=b.scroller&&b.scroller.getUnionExtremes()||b.xAxis[0]||
{},c(a.dataMin)&&c(a.dataMax)&&(b=b.xAxis[0].minRange||0,this.setInputExtremes("min",a.dataMin,Math.min(a.dataMax,this.getInputValue("max"))-b),this.setInputExtremes("max",Math.max(a.dataMin,this.getInputValue("min"))+b,a.dataMax)),this.inputGroup)){var h=0;[this.minLabel,this.minDateBox,this.maxLabel,this.maxDateBox].forEach(function(a,b){a&&(a.attr({x:h}),h+=a.width+l.inputSpacing,b%2&&(h+=l.inputSpacing))})}this.alignElements();this.rendered=!0}};v.prototype.renderButtons=function(){var a=this,
c=g.lang,b=this.chart.renderer,d=this.options,e=this.buttons,f=d.buttonTheme,l=f&&f.states;this.buttonGroup=b.g("range-selector-buttons").add(this.group);this.zoomText=b.text(c.rangeSelectorZoom,0,15).add(this.buttonGroup);this.chart.styledMode||(this.zoomText.css(d.labelStyle),f["stroke-width"]=p(f["stroke-width"],0));this.buttonOptions.forEach(function(c,d){e[d]=b.button(c.text,0,0,function(b){var e=c.events&&c.events.click,f;e&&(f=e.call(c,b));!1!==f&&a.clickButton(d);a.isActive=!0},f,l&&l.hover,
l&&l.select,l&&l.disabled).attr({"text-align":"center"}).add(a.buttonGroup);c.title&&e[d].attr("title",c.title)})};v.prototype.alignElements=function(){var a=this,c=this.buttonGroup,b=this.buttons,d=this.chart,e=this.group,f=this.inputGroup,g=this.options,h=this.zoomText,k=d.options,m=k.exporting&&!1!==k.exporting.enabled&&k.navigation&&k.navigation.buttonOptions,v=d.hasLoaded?"animate":"attr";k=g.buttonPosition;var q=g.inputPosition,r=g.verticalAlign,u=function(b,e){return m&&a.titleCollision(d)&&
"top"===r&&"right"===e.align&&e.y-b.getBBox().height-12<(m.y||0)+(m.height||0)+d.spacing[0]?-40:0},w=d.plotLeft,z=w;if(e&&k&&q){var A=k.x-d.spacing[3];c&&(h&&(h[v]({x:p(w+k.x,w)}),z+=k.x+h.getBBox().width+5),this.buttonOptions.forEach(function(a,e){b[e][v]({x:z});z+=b[e].width+g.buttonSpacing}),w-=d.spacing[3],this.updateButtonStates(),h=u(c,k),"right"===k.align?A+=h-w:"center"===k.align&&(A-=w/2),c.align({y:k.y,width:c.getBBox().width,align:k.align,x:A},!0,d.spacingBox),e.placed=c.placed=d.hasLoaded);
f&&(h=u(f,q),"left"===q.align?A=w:"right"===q.align&&(A=-Math.max(d.axisOffset[1],-h)),f.align({y:q.y,width:f.getBBox().width,align:q.align,x:q.x+A-2},!0,d.spacingBox),c&&this.handleCollision(h),f.placed=d.hasLoaded);e.align({verticalAlign:r},!0,d.spacingBox);c=e.alignAttr.translateY;f=e.getBBox().height+20;h=0;"bottom"===r&&(h=(h=d.legend&&d.legend.options)&&"bottom"===h.verticalAlign&&h.enabled&&!h.floating?d.legend.legendHeight+p(h.margin,10):0,f=f+h-20,h=c-f-(g.floating?0:g.y)-(d.titleOffset?
d.titleOffset[2]:0)-10);if("top"===r)g.floating&&(h=0),d.titleOffset&&d.titleOffset[0]&&(h=d.titleOffset[0]),h+=d.margin[0]-d.spacing[0]||0;else if("middle"===r)if(q.y===k.y)h=c;else if(q.y||k.y)h=0>q.y||0>k.y?h-Math.min(q.y,k.y):c-f;e.translate(g.x,g.y+Math.floor(h));k=this.minInput;q=this.maxInput;g.inputEnabled&&k&&q&&(k.style.marginTop=e.translateY+"px",q.style.marginTop=e.translateY+"px")}};v.prototype.handleCollision=function(a){var c=this.chart,b=this.buttonGroup,d=this.inputGroup,e=this.options,
f=e.buttonPosition;e=e.inputPosition;if(d&&b){var g=d.alignAttr.translateX+d.alignOptions.x-a+d.getBBox().x+2,h=d.alignOptions.width,k=b.alignAttr.translateX+b.getBBox().x,n=b.getBBox().width+20;(e.align===f.align||k+n>g&&g+h>k&&f.y<e.y+d.getBBox().height)&&d.attr({translateX:d.alignAttr.translateX+(c.axisOffset[1]>=-a?0:-a),translateY:d.alignAttr.translateY+b.getBBox().height+10})}};v.prototype.getHeight=function(){var a=this.options,c=this.group,b=a.y,d=a.buttonPosition.y,e=a.inputPosition.y;if(a.height)return a.height;
a=c?c.getBBox(!0).height+13+b:0;c=Math.min(e,d);if(0>e&&0>d||0<e&&0<d)a+=Math.abs(c);return a};v.prototype.titleCollision=function(a){return!(a.options.title.text||a.options.subtitle.text)};v.prototype.update=function(a){var c=this.chart;G(!0,c.options.rangeSelector,a);this.destroy();this.init(c);this.render()};v.prototype.destroy=function(){var a=this,c=a.minInput,b=a.maxInput;a.unMouseDown&&a.unMouseDown();a.unResize&&a.unResize();C(a.buttons);c&&(c.onfocus=c.onblur=c.onchange=null);b&&(b.onfocus=
b.onblur=b.onchange=null);h(a,function(b,c){b&&"chart"!==c&&(b instanceof E?b.destroy():b instanceof window.HTMLElement&&u(b));b!==v.prototype[c]&&(a[c]=null)},this)};return v}();F.prototype.defaultButtons=[{type:"month",count:1,text:"1m",title:"View 1 month"},{type:"month",count:3,text:"3m",title:"View 3 months"},{type:"month",count:6,text:"6m",title:"View 6 months"},{type:"ytd",text:"YTD",title:"View year to date"},{type:"year",count:1,text:"1y",title:"View 1 year"},{type:"all",text:"All",title:"View all"}];
F.prototype.inputTypeFormats={"datetime-local":"%Y-%m-%dT%H:%M:%S",date:"%Y-%m-%d",time:"%H:%M:%S"};f.prototype.minFromRange=function(){var a=this.range,c=a.type,d=this.max,b=this.chart.time,f=function(a,e){var d="year"===c?"FullYear":"Month",f=new b.Date(a),g=b.get(d,f);b.set(d,f,g+e);g===b.get(d,f)&&b.set("Date",f,0);return f.getTime()-a};if(k(a)){var e=d-a;var g=a}else e=d+f(d,-a.count),this.chart&&(this.chart.fixedRange=d-e);var h=p(this.dataMin,Number.MIN_VALUE);k(e)||(e=h);e<=h&&(e=h,"undefined"===
typeof g&&(g=f(e,a.count)),this.newMax=Math.min(e+g,this.dataMax));k(d)||(e=void 0);return e};w.RangeSelector||(a(B,"afterGetContainer",function(){var a;if(null===(a=this.options.rangeSelector)||void 0===a?0:a.enabled)this.rangeSelector=new F(this)}),a(B,"beforeRender",function(){var a=this.axes,c=this.rangeSelector;c&&(k(c.deferredYTDClick)&&(c.clickButton(c.deferredYTDClick),delete c.deferredYTDClick),a.forEach(function(a){a.updateNames();a.setScale()}),this.getAxisMargins(),c.render(),a=c.options.verticalAlign,
c.options.floating||("bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0)))}),a(B,"update",function(a){var d=a.options.rangeSelector;a=this.rangeSelector;var f=this.extraBottomMargin,b=this.extraTopMargin;d&&d.enabled&&!c(a)&&this.options.rangeSelector&&(this.options.rangeSelector.enabled=!0,this.rangeSelector=new F(this));this.extraTopMargin=this.extraBottomMargin=!1;a&&(a.render(),d=d&&d.verticalAlign||a.options&&a.options.verticalAlign,a.options.floating||("bottom"===d?
this.extraBottomMargin=!0:"middle"!==d&&(this.extraTopMargin=!0)),this.extraBottomMargin!==f||this.extraTopMargin!==b)&&(this.isDirtyBox=!0)}),a(B,"render",function(){var a=this.rangeSelector;a&&!a.options.floating&&(a.render(),a=a.options.verticalAlign,"bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0))}),a(B,"getMargins",function(){var a=this.rangeSelector;a&&(a=a.getHeight(),this.extraTopMargin&&(this.plotTop+=a),this.extraBottomMargin&&(this.marginBottom+=a))}),B.prototype.callbacks.push(function(c){function d(){b&&
(f=c.xAxis[0].getExtremes(),g=c.legend,h=null===b||void 0===b?void 0:b.options.verticalAlign,k(f.min)&&b.render(f.min,f.max),g.display&&"top"===h&&h===g.options.verticalAlign&&(e=G(c.spacingBox),e.y="vertical"===g.options.layout?c.plotTop:e.y+b.getHeight(),g.group.placed=!1,g.align(e)))}var f,b=c.rangeSelector,g,e,h;if(b){var l=a(c.xAxis[0],"afterSetExtremes",function(a){b.render(a.min,a.max)});var m=a(c,"redraw",d);d()}a(c,"destroy",function(){b&&(m(),l())})}),w.RangeSelector=F);return w.RangeSelector});
J(f,"Core/Chart/StockChart.js",[f["Core/Axis/Axis.js"],f["Core/Chart/Chart.js"],f["Core/Globals.js"],f["Series/Line/LineSeries.js"],f["Core/Color/Palette.js"],f["Core/Series/Point.js"],f["Core/Renderer/SVG/SVGRenderer.js"],f["Core/Utilities.js"]],function(f,B,w,r,q,E,D,m){function g(a,b,c){var e=L(a)||a.nodeName,d=arguments[e?1:0],f=d,g=d.series,h=p(),k,t=v(d.navigator&&d.navigator.enabled,h.navigator.enabled,!0);d.xAxis=n(d.xAxis||{}).map(function(a,b){return F({minPadding:0,maxPadding:0,overscroll:0,
ordinal:!0,title:{text:null},labels:{overflow:"justify"},showLastLabel:!0},h.xAxis,h.xAxis&&h.xAxis[b],a,{type:"datetime",categories:null},t?{startOnTick:!1,endOnTick:!1}:null)});d.yAxis=n(d.yAxis||{}).map(function(a,b){k=v(a.opposite,!0);return F({labels:{y:-2},opposite:k,showLastLabel:!(!a.categories&&"category"!==a.type),title:{text:null}},h.yAxis,h.yAxis&&h.yAxis[b],a)});d.series=null;d=F({chart:{panning:{enabled:!0,type:"x"},pinchType:"x"},navigator:{enabled:t},scrollbar:{enabled:v(h.scrollbar.enabled,
!0)},rangeSelector:{enabled:v(h.rangeSelector.enabled,!0)},title:{text:null},tooltip:{split:v(h.tooltip.split,!0),crosshairs:!0},legend:{enabled:!1}},d,{isStock:!0});d.series=f.series=g;return e?new B(a,d,c):new B(d,b)}var a=r.prototype,A=a.init,I=a.processData,c=E.prototype.tooltipFormatter;a=m.addEvent;var C=m.arrayMax,u=m.arrayMin,d=m.clamp,z=m.defined,k=m.extend,G=m.find,h=m.format,p=m.getOptions,J=m.isNumber,L=m.isString,F=m.merge,v=m.pick,n=m.splat;a(r,"setOptions",function(a){var b;this.chart.options.isStock&&
(this.is("column")||this.is("columnrange")?b={borderWidth:0,shadow:!1}:this.is("scatter")||this.is("sma")||(b={marker:{enabled:!1,radius:2}}),b&&(a.plotOptions[this.type]=F(a.plotOptions[this.type],b)))});a(f,"autoLabelAlign",function(a){var b=this.chart,c=this.options;b=b._labelPanes=b._labelPanes||{};var e=this.options.labels;this.chart.options.isStock&&"yAxis"===this.coll&&(c=c.top+","+c.height,!b[c]&&e.enabled&&(15===e.x&&(e.x=0),"undefined"===typeof e.align&&(e.align="right"),b[c]=this,a.align=
"right",a.preventDefault()))});a(f,"destroy",function(){var a=this.chart,b=this.options&&this.options.top+","+this.options.height;b&&a._labelPanes&&a._labelPanes[b]===this&&delete a._labelPanes[b]});a(f,"getPlotLinePath",function(a){function b(a){var b="xAxis"===a?"yAxis":"xAxis";a=c.options[b];return J(a)?[f[b][a]]:L(a)?[f.get(a)]:e.map(function(a){return a[b]})}var c=this,e=this.isLinked&&!this.series?this.linkedParent.series:this.series,f=c.chart,g=f.renderer,h=c.left,k=c.top,m,t,n,q,p=[],r=[],
u=a.translatedValue,w=a.value,A=a.force;if(f.options.isStock&&!1!==a.acrossPanes&&"xAxis"===c.coll||"yAxis"===c.coll){a.preventDefault();r=b(c.coll);var B=c.isXAxis?f.yAxis:f.xAxis;B.forEach(function(a){if(z(a.options.id)?-1===a.options.id.indexOf("navigator"):1){var b=a.isXAxis?"yAxis":"xAxis";b=z(a.options[b])?f[b][a.options[b]]:f[b][0];c===b&&r.push(a)}});var C=r.length?[]:[c.isXAxis?f.yAxis[0]:f.xAxis[0]];r.forEach(function(a){-1!==C.indexOf(a)||G(C,function(b){return b.pos===a.pos&&b.len===a.len})||
C.push(a)});var D=v(u,c.translate(w,null,null,a.old));J(D)&&(c.horiz?C.forEach(function(a){var b;t=a.pos;q=t+a.len;m=n=Math.round(D+c.transB);"pass"!==A&&(m<h||m>h+c.width)&&(A?m=n=d(m,h,h+c.width):b=!0);b||p.push(["M",m,t],["L",n,q])}):C.forEach(function(a){var b;m=a.pos;n=m+a.len;t=q=Math.round(k+c.height-D);"pass"!==A&&(t<k||t>k+c.height)&&(A?t=q=d(t,k,k+c.height):b=!0);b||p.push(["M",m,t],["L",n,q])}));a.path=0<p.length?g.crispPolyLine(p,a.lineWidth||1):null}});D.prototype.crispPolyLine=function(a,
b){for(var c=0;c<a.length;c+=2){var e=a[c],d=a[c+1];e[1]===d[1]&&(e[1]=d[1]=Math.round(e[1])-b%2/2);e[2]===d[2]&&(e[2]=d[2]=Math.round(e[2])+b%2/2)}return a};a(f,"afterHideCrosshair",function(){this.crossLabel&&(this.crossLabel=this.crossLabel.hide())});a(f,"afterDrawCrosshair",function(a){var b,c;if(z(this.crosshair.label)&&this.crosshair.label.enabled&&this.cross){var d=this.chart,f=this.logarithmic,g=this.options.crosshair.label,m=this.horiz,t=this.opposite,n=this.left,p=this.top,r=this.crossLabel,
u=g.format,w="",A="inside"===this.options.tickPosition,B=!1!==this.crosshair.snap,C=0,D=a.e||this.cross&&this.cross.e,E=a.point;a=this.min;var F=this.max;f&&(a=f.lin2log(a),F=f.lin2log(F));f=m?"center":t?"right"===this.labelAlign?"right":"left":"left"===this.labelAlign?"left":"center";r||(r=this.crossLabel=d.renderer.label(null,null,null,g.shape||"callout").addClass("highcharts-crosshair-label"+(this.series[0]&&" highcharts-color-"+this.series[0].colorIndex)).attr({align:g.align||f,padding:v(g.padding,
8),r:v(g.borderRadius,3),zIndex:2}).add(this.labelGroup),d.styledMode||r.attr({fill:g.backgroundColor||this.series[0]&&this.series[0].color||q.neutralColor60,stroke:g.borderColor||"","stroke-width":g.borderWidth||0}).css(k({color:q.backgroundColor,fontWeight:"normal",fontSize:"11px",textAlign:"center"},g.style)));m?(f=B?E.plotX+n:D.chartX,p+=t?0:this.height):(f=t?this.width+n:0,p=B?E.plotY+p:D.chartY);u||g.formatter||(this.dateTime&&(w="%b %d, %Y"),u="{value"+(w?":"+w:"")+"}");w=B?E[this.isXAxis?
"x":"y"]:this.toValue(m?D.chartX:D.chartY);r.attr({text:u?h(u,{value:w},d):g.formatter.call(this,w),x:f,y:p,visibility:w<a||w>F?"hidden":"visible"});g=r.getBBox();if(J(r.y))if(m){if(A&&!t||!A&&t)p=r.y-g.height}else p=r.y-g.height/2;m?(b=n-g.x,c=n+this.width-g.x):(b="left"===this.labelAlign?n:0,c="right"===this.labelAlign?n+this.width:d.chartWidth);r.translateX<b&&(C=b-r.translateX);r.translateX+g.width>=c&&(C=-(r.translateX+g.width-c));r.attr({x:f+C,y:p,anchorX:m?f:this.opposite?0:d.chartWidth,anchorY:m?
this.opposite?d.chartHeight:0:p+g.height/2})}});r.prototype.init=function(){A.apply(this,arguments);this.setCompare(this.options.compare)};r.prototype.setCompare=function(a){this.modifyValue="value"===a||"percent"===a?function(b,c){var d=this.compareValue;return"undefined"!==typeof b&&"undefined"!==typeof d?(b="value"===a?b-d:b/d*100-(100===this.options.compareBase?0:100),c&&(c.change=b),b):0}:null;this.userOptions.compare=a;this.chart.hasRendered&&(this.isDirty=!0)};r.prototype.processData=function(a){var b,
c=-1,d=!0===this.options.compareStart?0:1;I.apply(this,arguments);if(this.xAxis&&this.processedYData){var f=this.processedXData;var g=this.processedYData;var h=g.length;this.pointArrayMap&&(c=this.pointArrayMap.indexOf(this.options.pointValKey||this.pointValKey||"y"));for(b=0;b<h-d;b++){var k=g[b]&&-1<c?g[b][c]:g[b];if(J(k)&&f[b+d]>=this.xAxis.min&&0!==k){this.compareValue=k;break}}}};a(r,"afterGetExtremes",function(a){a=a.dataExtremes;if(this.modifyValue&&a){var b=[this.modifyValue(a.dataMin),this.modifyValue(a.dataMax)];
a.dataMin=u(b);a.dataMax=C(b)}});f.prototype.setCompare=function(a,b){this.isXAxis||(this.series.forEach(function(b){b.setCompare(a)}),v(b,!0)&&this.chart.redraw())};E.prototype.tooltipFormatter=function(a){var b=this.series.chart.numberFormatter;a=a.replace("{point.change}",(0<this.change?"+":"")+b(this.change,v(this.series.tooltipOptions.changeDecimals,2)));return c.apply(this,[a])};a(r,"render",function(){var a=this.chart;if(!(a.is3d&&a.is3d()||a.polar)&&this.xAxis&&!this.xAxis.isRadial){var b=
this.yAxis.len;if(this.xAxis.axisLine){var c=a.plotTop+a.plotHeight-this.yAxis.pos-this.yAxis.len,d=Math.floor(this.xAxis.axisLine.strokeWidth()/2);0<=c&&(b-=Math.max(d-c,0))}this.clipBox||a.hasRendered?a[this.sharedClipKey]&&(a[this.sharedClipKey].animate({width:this.xAxis.len,height:b}),a[this.sharedClipKey+"m"]&&a[this.sharedClipKey+"m"].animate({width:this.xAxis.len})):(this.clipBox=F(a.clipBox),this.clipBox.width=this.xAxis.len,this.clipBox.height=b)}});a(B,"update",function(a){a=a.options;"scrollbar"in
a&&this.navigator&&(F(!0,this.options.scrollbar,a.scrollbar),this.navigator.update({},!1),delete a.scrollbar)});w.StockChart=w.stockChart=g;"";return g});J(f,"masters/modules/stock.src.js",[],function(){})});
//# sourceMappingURL=stock.js.map