/*
 Highmaps JS v8.2.2 (2020-12-12)

 Tilemap module

 (c) 2010-2019 Highsoft AS

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/tilemap",["highcharts","highcharts/modules/map"],function(l){a(l);a.Highcharts=l;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function l(a,d,f,h){a.hasOwnProperty(d)||(a[d]=h.apply(null,f))}a=a?a._modules:{};l(a,"Series/Tilemap/TilemapPoint.js",[a["Core/Series/Series.js"],a["Mixins/ColorSeries.js"],a["Core/Utilities.js"]],
function(a,d,f){var h=this&&this.__extends||function(){var a=function(c,f){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(k,b){k.__proto__=b}||function(k,b){for(var a in b)b.hasOwnProperty(a)&&(k[a]=b[a])};return a(c,f)};return function(c,f){function k(){this.constructor=c}a(c,f);c.prototype=null===f?Object.create(f):(k.prototype=f.prototype,new k)}}(),e=a.seriesTypes;a=e.line.prototype.pointClass;d=d.colorPointMixin;f=f.extend;e=function(a){function c(){var c=null!==a&&a.apply(this,
arguments)||this;c.options=void 0;c.radius=void 0;c.series=void 0;c.tileEdges=void 0;return c}h(c,a);c.prototype.haloPath=function(){return this.series.tileShape.haloPath.apply(this,arguments)};return c}(e.heatmap.prototype.pointClass);f(e.prototype,{setState:a.prototype.setState,setVisible:d.setVisible});return e});l(a,"Series/Tilemap/TilemapShapes.js",[a["Core/Series/Series.js"],a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,d,f){function h(a,b,c){a=a.options;return{xPad:(a.colsize||1)/
-b,yPad:(a.rowsize||1)/-c}}a=a.seriesTypes;var e=a.heatmap,t=a.scatter,c=f.clamp,l=f.pick;return{hexagon:{alignDataLabel:t.prototype.alignDataLabel,getSeriesPadding:function(a){return h(a,3,2)},haloPath:function(a){if(!a)return[];var b=this.tileEdges;return[["M",b.x2-a,b.y1+a],["L",b.x3+a,b.y1+a],["L",b.x4+1.5*a,b.y2],["L",b.x3+a,b.y3-a],["L",b.x2-a,b.y3-a],["L",b.x1-1.5*a,b.y2],["Z"]]},translate:function(){var a=this.options,b=this.xAxis,g=this.yAxis,f=a.pointPadding||0,r=(a.colsize||1)/3,v=(a.rowsize||
1)/2,p;this.generatePoints();this.points.forEach(function(a){var m=c(Math.floor(b.len-b.translate(a.x-2*r,0,1,0,1)),-b.len,2*b.len),k=c(Math.floor(b.len-b.translate(a.x-r,0,1,0,1)),-b.len,2*b.len),e=c(Math.floor(b.len-b.translate(a.x+r,0,1,0,1)),-b.len,2*b.len),u=c(Math.floor(b.len-b.translate(a.x+2*r,0,1,0,1)),-b.len,2*b.len),w=c(Math.floor(g.translate(a.y-v,0,1,0,1)),-g.len,2*g.len),x=c(Math.floor(g.translate(a.y,0,1,0,1)),-g.len,2*g.len),q=c(Math.floor(g.translate(a.y+v,0,1,0,1)),-g.len,2*g.len),
n=l(a.pointPadding,f),d=n*Math.abs(k-m)/Math.abs(q-x);d=b.reversed?-d:d;var h=b.reversed?-n:n;n=g.reversed?-n:n;a.x%2&&(p=p||Math.round(Math.abs(q-w)/2)*(g.reversed?-1:1),w+=p,x+=p,q+=p);a.plotX=a.clientX=(k+e)/2;a.plotY=x;m+=d+h;k+=h;e-=h;u-=d+h;w-=n;q+=n;a.tileEdges={x1:m,x2:k,x3:e,x4:u,y1:w,y2:x,y3:q};a.shapeType="path";a.shapeArgs={d:[["M",k,w],["L",e,w],["L",u,x],["L",e,q],["L",k,q],["L",m,x],["Z"]]}});this.translateColors()}},diamond:{alignDataLabel:t.prototype.alignDataLabel,getSeriesPadding:function(a){return h(a,
2,2)},haloPath:function(a){if(!a)return[];var b=this.tileEdges;return[["M",b.x2,b.y1+a],["L",b.x3+a,b.y2],["L",b.x2,b.y3-a],["L",b.x1-a,b.y2],["Z"]]},translate:function(){var a=this.options,b=this.xAxis,g=this.yAxis,f=a.pointPadding||0,e=a.colsize||1,v=(a.rowsize||1)/2,p;this.generatePoints();this.points.forEach(function(a){var k=c(Math.round(b.len-b.translate(a.x-e,0,1,0,0)),-b.len,2*b.len),d=c(Math.round(b.len-b.translate(a.x,0,1,0,0)),-b.len,2*b.len),r=c(Math.round(b.len-b.translate(a.x+e,0,1,
0,0)),-b.len,2*b.len),u=c(Math.round(g.translate(a.y-v,0,1,0,0)),-g.len,2*g.len),m=c(Math.round(g.translate(a.y,0,1,0,0)),-g.len,2*g.len),h=c(Math.round(g.translate(a.y+v,0,1,0,0)),-g.len,2*g.len),q=l(a.pointPadding,f),n=q*Math.abs(d-k)/Math.abs(h-m);n=b.reversed?-n:n;q=g.reversed?-q:q;a.x%2&&(p=Math.abs(h-u)/2*(g.reversed?-1:1),u+=p,m+=p,h+=p);a.plotX=a.clientX=d;a.plotY=m;k+=n;r-=n;u-=q;h+=q;a.tileEdges={x1:k,x2:d,x3:r,y1:u,y2:m,y3:h};a.shapeType="path";a.shapeArgs={d:[["M",d,u],["L",r,m],["L",
d,h],["L",k,m],["Z"]]}});this.translateColors()}},circle:{alignDataLabel:t.prototype.alignDataLabel,getSeriesPadding:function(a){return h(a,2,2)},haloPath:function(a){return t.prototype.pointClass.prototype.haloPath.call(this,a+(a&&this.radius))},translate:function(){var a=this.options,b=this.xAxis,f=this.yAxis,d=a.pointPadding||0,e=(a.rowsize||1)/2,v=a.colsize||1,p,m,h,t,l=!1;this.generatePoints();this.points.forEach(function(a){var g=c(Math.round(b.len-b.translate(a.x,0,1,0,0)),-b.len,2*b.len),
r=c(Math.round(f.translate(a.y,0,1,0,0)),-f.len,2*f.len),k=d,n=!1;"undefined"!==typeof a.pointPadding&&(k=a.pointPadding,l=n=!0);if(!t||l)p=Math.abs(c(Math.floor(b.len-b.translate(a.x+v,0,1,0,0)),-b.len,2*b.len)-g),m=Math.abs(c(Math.floor(f.translate(a.y+e,0,1,0,0)),-f.len,2*f.len)-r),h=Math.floor(Math.sqrt(p*p+m*m)/2),t=Math.min(p,h,m)-k,l&&!n&&(l=!1);a.x%2&&(r+=m*(f.reversed?-1:1));a.plotX=a.clientX=g;a.plotY=r;a.radius=t;a.shapeType="circle";a.shapeArgs={x:g,y:r,r:t}});this.translateColors()}},
square:{alignDataLabel:e.prototype.alignDataLabel,translate:e.prototype.translate,getSeriesPadding:d.noop,haloPath:e.prototype.pointClass.prototype.haloPath}}});l(a,"Series/Tilemap/TilemapComposition.js",[a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,d){d=d.addEvent;d(a.Axis,"afterSetAxisTranslation",function(){if(!this.recomputingForTilemap&&"colorAxis"!==this.coll){var a=this,d=a.series.map(function(d){return d.getSeriesPixelPadding&&d.getSeriesPixelPadding(a)}).reduce(function(a,c){return(a&&
a.padding)>(c&&c.padding)?a:c},void 0)||{padding:0,axisLengthFactor:1},e=Math.round(d.padding*d.axisLengthFactor);d.padding&&(a.len-=e,a.recomputingForTilemap=!0,a.setAxisTranslation(),delete a.recomputingForTilemap,a.minPixelPadding+=d.padding,a.len+=e)}})});l(a,"Series/Tilemap/TilemapSeries.js",[a["Core/Series/Series.js"],a["Core/Globals.js"],a["Series/Tilemap/TilemapPoint.js"],a["Series/Tilemap/TilemapShapes.js"],a["Core/Utilities.js"]],function(a,d,f,h,e){var l=this&&this.__extends||function(){var a=
function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),c=a.seriesTypes,y=c.column,k=c.heatmap;c=c.scatter;d=d.noop;var b=e.extend,g=e.merge;e=function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=void 0;
b.points=void 0;b.tileShape=void 0;return b}l(b,a);b.prototype.alignDataLabel=function(){return this.tileShape.alignDataLabel.apply(this,Array.prototype.slice.call(arguments))};b.prototype.drawPoints=function(){var a=this;y.prototype.drawPoints.call(this);this.points.forEach(function(b){b.graphic&&b.graphic[a.chart.styledMode?"css":"animate"](a.colorAttribs(b))})};b.prototype.getSeriesPixelPadding=function(a){var b=a.isXAxis,c=this.tileShape.getSeriesPadding(this);if(!c)return{padding:0,axisLengthFactor:1};
var d=Math.round(a.translate(b?2*c.xPad:c.yPad,0,1,0,1));a=Math.round(a.translate(b?c.xPad:0,0,1,0,1));return{padding:Math.abs(d-a)||0,axisLengthFactor:b?2:1.1}};b.prototype.setOptions=function(){var b=a.prototype.setOptions.apply(this,Array.prototype.slice.call(arguments));this.tileShape=h[b.tileShape];return b};b.prototype.translate=function(){return this.tileShape.translate.apply(this,Array.prototype.slice.call(arguments))};b.defaultOptions=g(k.defaultOptions,{marker:null,states:{hover:{halo:{enabled:!0,
size:2,opacity:.5,attributes:{zIndex:3}}}},pointPadding:2,tileShape:"hexagon"});return b}(k);b(e.prototype,{getSymbol:d,markerAttribs:c.prototype.markerAttribs,pointAttribs:y.prototype.pointAttribs,pointClass:f});a.registerSeriesType("tilemap",e);"";"";return e});l(a,"masters/modules/tilemap.src.js",[],function(){})});
//# sourceMappingURL=tilemap.js.map