/*
 Highcharts Gantt JS v8.2.2 (2020-12-12)

 Tree Grid

 (c) 2016-2019 Jon Arild Nygard

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/treegrid",["highcharts"],function(B){b(B);b.Highcharts=B;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function B(b,t,w,q){b.hasOwnProperty(t)||(b[t]=q.apply(null,w))}b=b?b._modules:{};B(b,"Gantt/Tree.js",[b["Core/Utilities.js"]],function(b){var t=b.extend,w=b.isNumber,q=b.pick,m=function(b,p){var r=b.reduce(function(d,
r){var l=q(r.parent,"");"undefined"===typeof d[l]&&(d[l]=[]);d[l].push(r);return d},{});Object.keys(r).forEach(function(d,b){var l=r[d];""!==d&&-1===p.indexOf(d)&&(l.forEach(function(d){b[""].push(d)}),delete b[d])});return r},p=function(b,m,r,d,C,l){var k=0,v=0,n=l&&l.after,a=l&&l.before;m={data:d,depth:r-1,id:b,level:r,parent:m};var g,h;"function"===typeof a&&a(m,l);a=(C[b]||[]).map(function(e){var c=p(e.id,b,r+1,e,C,l),f=e.start;e=!0===e.milestone?f:e.end;g=!w(g)||f<g?f:g;h=!w(h)||e>h?e:h;k=k+
1+c.descendants;v=Math.max(c.height+1,v);return c});d&&(d.start=q(d.start,g),d.end=q(d.end,h));t(m,{children:a,descendants:k,height:v});"function"===typeof n&&n(m,l);return m};return{getListOfParents:m,getNode:p,getTree:function(b,q){var r=b.map(function(d){return d.id});b=m(b,r);return p("",null,1,null,b,q)}}});B(b,"Core/Axis/TreeGridTick.js",[b["Core/Color/Palette.js"],b["Core/Utilities.js"]],function(b,t){var w=t.addEvent,q=t.defined,m=t.isObject,p=t.isNumber,z=t.pick,y=t.wrap,r;(function(d){function r(){this.treeGrid||
(this.treeGrid=new a(this))}function l(a,h){a=a.treeGrid;var e=!a.labelIcon,c=h.renderer,f=h.xy,u=h.options,A=u.width,g=u.height,d=f.x-A/2-u.padding;f=f.y-g/2;var k=h.collapsed?90:180,x=h.show&&p(f),n=a.labelIcon;n||(a.labelIcon=n=c.path(c.symbols[u.type](u.x,u.y,A,g)).addClass("highcharts-label-icon").add(h.group));x||n.attr({y:-9999});c.styledMode||n.attr({"stroke-width":1,fill:z(h.color,b.neutralColor60)}).css({cursor:"pointer",stroke:u.lineColor,strokeWidth:u.lineWidth});n[e?"attr":"animate"]({translateX:d,
translateY:f,rotation:k})}function k(a,h,e,c,f,u,A,d,k){var g=z(this.options&&this.options.labels,u);u=this.pos;var H=this.axis,n="treegrid"===H.options.type;a=a.apply(this,[h,e,c,f,g,A,d,k]);n&&(h=g&&m(g.symbol,!0)?g.symbol:{},g=g&&p(g.indentation)?g.indentation:0,u=(u=(H=H.treeGrid.mapOfPosToGridNode)&&H[u])&&u.depth||1,a.x+=h.width+2*h.padding+(u-1)*g);return a}function v(a){var h=this,e=h.pos,c=h.axis,f=h.label,u=c.treeGrid.mapOfPosToGridNode,A=c.options,g=z(h.options&&h.options.labels,A&&A.labels),
d=g&&m(g.symbol,!0)?g.symbol:{},k=(u=u&&u[e])&&u.depth;A="treegrid"===A.type;var n=-1<c.tickPositions.indexOf(e);e=c.chart.styledMode;A&&u&&f&&f.element&&f.addClass("highcharts-treegrid-node-level-"+k);a.apply(h,Array.prototype.slice.call(arguments,1));A&&f&&f.element&&u&&u.descendants&&0<u.descendants&&(c=c.treeGrid.isCollapsed(u),l(h,{color:!e&&f.styles&&f.styles.color||"",collapsed:c,group:f.parentGroup,options:d,renderer:f.renderer,show:n,xy:f.xy}),d="highcharts-treegrid-node-"+(c?"expanded":
"collapsed"),f.addClass("highcharts-treegrid-node-"+(c?"collapsed":"expanded")).removeClass(d),e||f.css({cursor:"pointer"}),[f,h.treeGrid.labelIcon].forEach(function(c){c&&!c.attachedTreeGridEvents&&(w(c.element,"mouseover",function(){f.addClass("highcharts-treegrid-node-active");f.renderer.styledMode||f.css({textDecoration:"underline"})}),w(c.element,"mouseout",function(){var c=q(g.style)?g.style:{};f.removeClass("highcharts-treegrid-node-active");f.renderer.styledMode||f.css({textDecoration:c.textDecoration})}),
w(c.element,"click",function(){h.treeGrid.toggleCollapse()}),c.attachedTreeGridEvents=!0)}))}var n=!1;d.compose=function(a){n||(w(a,"init",r),y(a.prototype,"getLabelPosition",k),y(a.prototype,"renderLabel",v),a.prototype.collapse=function(a){this.treeGrid.collapse(a)},a.prototype.expand=function(a){this.treeGrid.expand(a)},a.prototype.toggleCollapse=function(a){this.treeGrid.toggleCollapse(a)},n=!0)};var a=function(){function a(a){this.tick=a}a.prototype.collapse=function(a){var e=this.tick,c=e.axis,
f=c.brokenAxis;f&&c.treeGrid.mapOfPosToGridNode&&(e=c.treeGrid.collapse(c.treeGrid.mapOfPosToGridNode[e.pos]),f.setBreaks(e,z(a,!0)))};a.prototype.expand=function(a){var e=this.tick,c=e.axis,f=c.brokenAxis;f&&c.treeGrid.mapOfPosToGridNode&&(e=c.treeGrid.expand(c.treeGrid.mapOfPosToGridNode[e.pos]),f.setBreaks(e,z(a,!0)))};a.prototype.toggleCollapse=function(a){var e=this.tick,c=e.axis,f=c.brokenAxis;f&&c.treeGrid.mapOfPosToGridNode&&(e=c.treeGrid.toggleCollapse(c.treeGrid.mapOfPosToGridNode[e.pos]),
f.setBreaks(e,z(a,!0)))};return a}();d.Additions=a})(r||(r={}));return r});B(b,"Mixins/TreeSeries.js",[b["Core/Color/Color.js"],b["Core/Utilities.js"]],function(b,t){var w=t.extend,q=t.isArray,m=t.isNumber,p=t.isObject,z=t.merge,y=t.pick;return{getColor:function(r,d){var m=d.index,l=d.mapOptionsToLevel,k=d.parentColor,v=d.parentColorIndex,n=d.series,a=d.colors,g=d.siblings,h=n.points,e=n.chart.options.chart,c;if(r){h=h[r.i];r=l[r.level]||{};if(l=h&&r.colorByPoint){var f=h.index%(a?a.length:e.colorCount);
var u=a&&a[f]}if(!n.chart.styledMode){a=h&&h.options.color;e=r&&r.color;if(c=k)c=(c=r&&r.colorVariation)&&"brightness"===c.key?b.parse(k).brighten(m/g*c.to).get():k;c=y(a,e,u,c,n.color)}var A=y(h&&h.options.colorIndex,r&&r.colorIndex,f,v,d.colorIndex)}return{color:c,colorIndex:A}},getLevelOptions:function(b){var d=null;if(p(b)){d={};var r=m(b.from)?b.from:1;var l=b.levels;var k={};var v=p(b.defaults)?b.defaults:{};q(l)&&(k=l.reduce(function(d,a){if(p(a)&&m(a.level)){var g=z({},a);var h="boolean"===
typeof g.levelIsConstant?g.levelIsConstant:v.levelIsConstant;delete g.levelIsConstant;delete g.level;a=a.level+(h?0:r-1);p(d[a])?w(d[a],g):d[a]=g}return d},{}));l=m(b.to)?b.to:1;for(b=0;b<=l;b++)d[b]=z({},v,p(k[b])?k[b]:{})}return d},setTreeValues:function l(d,b){var k=b.before,v=b.idRoot,n=b.mapIdToNode[v],a=b.points[d.i],g=a&&a.options||{},h=0,e=[];w(d,{levelDynamic:d.level-(("boolean"===typeof b.levelIsConstant?b.levelIsConstant:1)?0:n.level),name:y(a&&a.name,""),visible:v===d.id||("boolean"===
typeof b.visible?b.visible:!1)});"function"===typeof k&&(d=k(d,b));d.children.forEach(function(c,f){var a=w({},b);w(a,{index:f,siblings:d.children.length,visible:d.visible});c=l(c,a);e.push(c);c.visible&&(h+=c.val)});d.visible=0<h||d.visible;k=y(g.value,h);w(d,{children:e,childrenTotal:h,isLeaf:d.visible&&!h,val:k});return d},updateRootId:function(b){if(p(b)){var d=p(b.options)?b.options:{};d=y(b.rootNode,d.rootId,"");p(b.userOptions)&&(b.userOptions.rootId=d);b.rootNode=d}return d}}});B(b,"Core/Axis/GridAxis.js",
[b["Core/Axis/Axis.js"],b["Core/Globals.js"],b["Core/Axis/Tick.js"],b["Core/Utilities.js"]],function(b,t,w,q){var m=q.addEvent,p=q.defined,z=q.erase,y=q.find,r=q.isArray,d=q.isNumber,C=q.merge,l=q.pick,k=q.timeUnits,v=q.wrap,n=t.Chart,a=function(a){var c=a.options;c.labels||(c.labels={});c.labels.align=l(c.labels.align,"center");a.categories||(c.showLastLabel=!1);a.labelRotation=0;c.labels.rotation=0};"";b.prototype.getMaxLabelDimensions=function(a,c){var f={width:0,height:0};c.forEach(function(c){c=
a[c];if(q.isObject(c,!0)){var e=q.isObject(c.label,!0)?c.label:{};c=e.getBBox?e.getBBox().height:0;e.textStr&&!d(e.textPxLength)&&(e.textPxLength=e.getBBox().width);var u=d(e.textPxLength)?Math.round(e.textPxLength):0;e.textStr&&(u=Math.round(e.getBBox().width));f.height=Math.max(c,f.height);f.width=Math.max(u,f.width)}});return f};t.dateFormats.W=function(a){a=new this.Date(a);var c=(this.get("Day",a)+6)%7,f=new this.Date(a.valueOf());this.set("Date",f,this.get("Date",a)-c+3);c=new this.Date(this.get("FullYear",
f),0,1);4!==this.get("Day",c)&&(this.set("Month",a,0),this.set("Date",a,1+(11-this.get("Day",c))%7));return(1+Math.floor((f.valueOf()-c.valueOf())/6048E5)).toString()};t.dateFormats.E=function(a){return this.dateFormat("%a",a,!0).charAt(0)};m(n,"afterSetChartSize",function(){this.axes.forEach(function(a){(a.grid&&a.grid.columns||[]).forEach(function(c){c.setAxisSize();c.setAxisTranslation()})})});m(w,"afterGetLabelPosition",function(a){var c=this.label,f=this.axis,e=f.reversed,b=f.chart,g=f.options.grid||
{},k=f.options.labels,n=k.align,x=h.Side[f.side],l=a.tickmarkOffset,E=f.tickPositions,D=this.pos-l;E=d(E[a.index+1])?E[a.index+1]-l:f.max+l;var F=f.tickSize("tick");l=F?F[0]:0;F=F?F[1]/2:0;if(!0===g.enabled){if("top"===x){g=f.top+f.offset;var G=g-l}else"bottom"===x?(G=b.chartHeight-f.bottom+f.offset,g=G+l):(g=f.top+f.len-f.translate(e?E:D),G=f.top+f.len-f.translate(e?D:E));"right"===x?(x=b.chartWidth-f.right+f.offset,e=x+l):"left"===x?(e=f.left+f.offset,x=e-l):(x=Math.round(f.left+f.translate(e?E:
D))-F,e=Math.round(f.left+f.translate(e?D:E))-F);this.slotWidth=e-x;a.pos.x="left"===n?x:"right"===n?e:x+(e-x)/2;a.pos.y=G+(g-G)/2;b=b.renderer.fontMetrics(k.style.fontSize,c.element);c=c.getBBox().height;k.useHTML?a.pos.y+=b.b+-(c/2):(c=Math.round(c/b.h),a.pos.y+=(b.b-(b.h-b.f))/2+-((c-1)*b.h/2));a.pos.x+=f.horiz&&k.x||0}});var g=function(){function a(c){this.axis=c}a.prototype.isOuterAxis=function(){var c=this.axis,a=c.grid.columnIndex,e=c.linkedParent&&c.linkedParent.grid.columns||c.grid.columns,
b=a?c.linkedParent:c,g=-1,h=0;c.chart[c.coll].forEach(function(a,f){a.side!==c.side||a.options.isInternal||(h=f,a===b&&(g=f))});return h===g&&(d(a)?e.length===a:!0)};a.prototype.renderBorder=function(c){var a=this.axis,e=a.chart.renderer,b=a.options;c=e.path(c).addClass("highcharts-axis-line").add(a.axisBorder);e.styledMode||c.attr({stroke:b.lineColor,"stroke-width":b.lineWidth,zIndex:7});return c};return a}(),h=function(){function e(){}e.compose=function(c){b.keepProps.push("grid");v(c.prototype,
"unsquish",e.wrapUnsquish);m(c,"init",e.onInit);m(c,"afterGetOffset",e.onAfterGetOffset);m(c,"afterGetTitlePosition",e.onAfterGetTitlePosition);m(c,"afterInit",e.onAfterInit);m(c,"afterRender",e.onAfterRender);m(c,"afterSetAxisTranslation",e.onAfterSetAxisTranslation);m(c,"afterSetOptions",e.onAfterSetOptions);m(c,"afterSetOptions",e.onAfterSetOptions2);m(c,"afterSetScale",e.onAfterSetScale);m(c,"afterTickSize",e.onAfterTickSize);m(c,"trimTicks",e.onTrimTicks);m(c,"destroy",e.onDestroy)};e.onAfterGetOffset=
function(){var c=this.grid;(c&&c.columns||[]).forEach(function(c){c.getOffset()})};e.onAfterGetTitlePosition=function(c){if(!0===(this.options.grid||{}).enabled){var a=this.axisTitle,b=this.height,g=this.horiz,h=this.left,d=this.offset,k=this.opposite,n=this.options.title,v=void 0===n?{}:n;n=this.top;var E=this.width,D=this.tickSize(),F=a&&a.getBBox().width,G=v.x||0,m=v.y||0,J=l(v.margin,g?5:10);a=this.chart.renderer.fontMetrics(v.style&&v.style.fontSize,a).f;D=(g?n+b:h)+(g?1:-1)*(k?-1:1)*(D?D[0]/
2:0)+(this.side===e.Side.bottom?a:0);c.titlePosition.x=g?h-F/2-J+G:D+(k?E:0)+d+G;c.titlePosition.y=g?D-(k?b:0)+(k?a:-a)/2+d+m:n-J+m}};e.onAfterInit=function(){var c=this.chart,f=this.options.grid;f=void 0===f?{}:f;var e=this.userOptions;f.enabled&&(a(this),v(this,"labelFormatter",function(c){var a=this.axis,f=this.value,e=a.tickPositions,b=(a.isLinked?a.linkedParent:a).series[0],g=f===e[0];e=f===e[e.length-1];var u=b&&y(b.options.data,function(c){return c[a.isXAxis?"x":"y"]===f});if(u&&b.is("gantt")){var d=
C(u);t.seriesTypes.gantt.prototype.pointClass.setGanttPointAliases(d)}this.isFirst=g;this.isLast=e;this.point=d;return c.call(this)}));if(f.columns)for(var g=this.grid.columns=[],h=this.grid.columnIndex=0;++h<f.columns.length;){var d=C(e,f.columns[f.columns.length-h-1],{linkedTo:0,type:"category",scrollbar:{enabled:!1}});delete d.grid.columns;d=new b(this.chart,d);d.grid.isColumn=!0;d.grid.columnIndex=h;z(c.axes,d);z(c[this.coll],d);g.push(d)}};e.onAfterRender=function(){var c,a=this.grid,b=this.options;
if(!0===(b.grid||{}).enabled){this.maxLabelDimensions=this.getMaxLabelDimensions(this.ticks,this.tickPositions);this.rightWall&&this.rightWall.destroy();if(this.grid&&this.grid.isOuterAxis()&&this.axisLine&&(b=b.lineWidth)){b=this.getLinePath(b);var d=b[0],g=b[1],h=((this.tickSize("tick")||[1])[0]-1)*(this.side===e.Side.top||this.side===e.Side.left?-1:1);"M"===d[0]&&"L"===g[0]&&(this.horiz?(d[2]+=h,g[2]+=h):(d[1]+=h,g[1]+=h));!this.horiz&&this.chart.marginRight&&(d=[d,["L",this.left,d[2]]],h=["L",
this.chart.chartWidth-this.chart.marginRight,this.toPixels(this.max+this.tickmarkOffset)],g=[["M",g[1],this.toPixels(this.max+this.tickmarkOffset)],h],this.grid.upperBorder||0===this.min%1||(this.grid.upperBorder=this.grid.renderBorder(d)),this.grid.upperBorder&&this.grid.upperBorder.animate({d:d}),this.grid.lowerBorder||0===this.max%1||(this.grid.lowerBorder=this.grid.renderBorder(g)),this.grid.lowerBorder&&this.grid.lowerBorder.animate({d:g}));this.grid.axisLineExtra?this.grid.axisLineExtra.animate({d:b}):
this.grid.axisLineExtra=this.grid.renderBorder(b);this.axisLine[this.showAxis?"show":"hide"](!0)}(a&&a.columns||[]).forEach(function(a){a.render()});!this.horiz&&this.chart.hasRendered&&(this.scrollbar||(null===(c=this.linkedParent)||void 0===c?0:c.scrollbar))&&(c=this.max,a=this.tickmarkOffset,b=this.tickPositions[this.tickPositions.length-1],g=this.tickPositions[0],this.min-g>a?this.ticks[g].label.hide():this.ticks[g].label.show(),b-c>a?this.ticks[b].label.hide():this.ticks[b].label.show(),b-c<
a&&0<b-c&&this.ticks[b].isLast?this.ticks[b].mark.hide():this.ticks[b-1].mark.show())}};e.onAfterSetAxisTranslation=function(){var a,f=this.tickPositions&&this.tickPositions.info,e=this.options,b=e.grid||{},g=this.userOptions.labels||{};this.horiz?(!0===b.enabled&&this.series.forEach(function(a){a.options.pointRange=0}),f&&e.dateTimeLabelFormats&&e.labels&&!p(g.align)&&(!1===e.dateTimeLabelFormats[f.unitName].range||1<f.count)&&(e.labels.align="left",p(g.x)||(e.labels.x=3))):"treegrid"!==this.options.type&&
(null===(a=this.grid)||void 0===a?0:a.columns)&&(this.minPointOffset=this.tickInterval)};e.onAfterSetOptions=function(a){var c=this.options;a=a.userOptions;var e=c&&q.isObject(c.grid,!0)?c.grid:{};if(!0===e.enabled){var b=C(!0,{className:"highcharts-grid-axis "+(a.className||""),dateTimeLabelFormats:{hour:{list:["%H:%M","%H"]},day:{list:["%A, %e. %B","%a, %e. %b","%E"]},week:{list:["Week %W","W%W"]},month:{list:["%B","%b","%o"]}},grid:{borderWidth:1},labels:{padding:2,style:{fontSize:"13px"}},margin:0,
title:{text:null,reserveSpace:!1,rotation:0},units:[["millisecond",[1,10,100]],["second",[1,10]],["minute",[1,5,15]],["hour",[1,6]],["day",[1]],["week",[1]],["month",[1]],["year",null]]},a);"xAxis"===this.coll&&(p(a.linkedTo)&&!p(a.tickPixelInterval)&&(b.tickPixelInterval=350),p(a.tickPixelInterval)||!p(a.linkedTo)||p(a.tickPositioner)||p(a.tickInterval)||(b.tickPositioner=function(a,c){var e=this.linkedParent&&this.linkedParent.tickPositions&&this.linkedParent.tickPositions.info;if(e){var f,g=b.units;
for(f=0;f<g.length;f++)if(g[f][0]===e.unitName){var d=f;break}if(g[d+1]){var h=g[d+1][0];var u=(g[d+1][1]||[1])[0]}else"year"===e.unitName&&(h="year",u=10*e.count);e=k[h];this.tickInterval=e*u;return this.getTimeTicks({unitRange:e,count:u,unitName:h},a,c,this.options.startOfWeek)}}));C(!0,this.options,b);this.horiz&&(c.minPadding=l(a.minPadding,0),c.maxPadding=l(a.maxPadding,0));d(c.grid.borderWidth)&&(c.tickWidth=c.lineWidth=e.borderWidth)}};e.onAfterSetOptions2=function(a){a=(a=a.userOptions)&&
a.grid||{};var c=a.columns;a.enabled&&c&&C(!0,this.options,c[c.length-1])};e.onAfterSetScale=function(){(this.grid.columns||[]).forEach(function(a){a.setScale()})};e.onAfterTickSize=function(a){var c=b.defaultLeftAxisOptions,e=this.horiz,g=this.maxLabelDimensions,d=this.options.grid;d=void 0===d?{}:d;d.enabled&&g&&(c=2*Math.abs(c.labels.x),e=e?d.cellHeight||c+g.height:c+g.width,r(a.tickSize)?a.tickSize[0]=e:a.tickSize=[e,0])};e.onDestroy=function(a){var c=this.grid;(c.columns||[]).forEach(function(c){c.destroy(a.keepEvents)});
c.columns=void 0};e.onInit=function(a){a=a.userOptions||{};var c=a.grid||{};c.enabled&&p(c.borderColor)&&(a.tickColor=a.lineColor=c.borderColor);this.grid||(this.grid=new g(this))};e.onTrimTicks=function(){var a=this.options,e=this.categories,b=this.tickPositions,g=b[0],d=b[b.length-1],h=this.linkedParent&&this.linkedParent.min||this.min,k=this.linkedParent&&this.linkedParent.max||this.max,n=this.tickInterval;!0!==(a.grid||{}).enabled||e||!this.horiz&&!this.isLinked||(g<h&&g+n>h&&!a.startOnTick&&
(b[0]=h),d>k&&d-n<k&&!a.endOnTick&&(b[b.length-1]=k))};e.wrapUnsquish=function(a){var c=this.options.grid;return!0===(void 0===c?{}:c).enabled&&this.categories?this.tickInterval:a.apply(this,Array.prototype.slice.call(arguments,1))};return e}();(function(a){a=a.Side||(a.Side={});a[a.top=0]="top";a[a.right=1]="right";a[a.bottom=2]="bottom";a[a.left=3]="left"})(h||(h={}));h.compose(b);return h});B(b,"Core/Axis/BrokenAxis.js",[b["Core/Axis/Axis.js"],b["Series/Line/LineSeries.js"],b["Extensions/Stacking.js"],
b["Core/Utilities.js"]],function(b,t,w,q){var m=q.addEvent,p=q.find,z=q.fireEvent,y=q.isArray,r=q.isNumber,d=q.pick,C=function(){function l(b){this.hasBreaks=!1;this.axis=b}l.isInBreak=function(b,d){var k=b.repeat||Infinity,a=b.from,g=b.to-b.from;d=d>=a?(d-a)%k:k-(a-d)%k;return b.inclusive?d<=g:d<g&&0!==d};l.lin2Val=function(b){var d=this.brokenAxis;d=d&&d.breakArray;if(!d)return b;var k;for(k=0;k<d.length;k++){var a=d[k];if(a.from>=b)break;else a.to<b?b+=a.len:l.isInBreak(a,b)&&(b+=a.len)}return b};
l.val2Lin=function(b){var d=this.brokenAxis;d=d&&d.breakArray;if(!d)return b;var k=b,a;for(a=0;a<d.length;a++){var g=d[a];if(g.to<=b)k-=g.len;else if(g.from>=b)break;else if(l.isInBreak(g,b)){k-=b-g.from;break}}return k};l.prototype.findBreakAt=function(b,d){return p(d,function(d){return d.from<b&&b<d.to})};l.prototype.isInAnyBreak=function(b,m){var k=this.axis,a=k.options.breaks,g=a&&a.length,h;if(g){for(;g--;)if(l.isInBreak(a[g],b)){var e=!0;h||(h=d(a[g].showPoints,!k.isXAxis))}var c=e&&m?e&&!h:
e}return c};l.prototype.setBreaks=function(k,m){var n=this,a=n.axis,g=y(k)&&!!k.length;a.isDirty=n.hasBreaks!==g;n.hasBreaks=g;a.options.breaks=a.userOptions.breaks=k;a.forceRedraw=!0;a.series.forEach(function(a){a.isDirty=!0});g||a.val2lin!==l.val2Lin||(delete a.val2lin,delete a.lin2val);g&&(a.userOptions.ordinal=!1,a.lin2val=l.lin2Val,a.val2lin=l.val2Lin,a.setExtremes=function(a,e,c,d,g){if(n.hasBreaks){for(var f,h=this.options.breaks;f=n.findBreakAt(a,h);)a=f.to;for(;f=n.findBreakAt(e,h);)e=f.from;
e<a&&(e=a)}b.prototype.setExtremes.call(this,a,e,c,d,g)},a.setAxisTranslation=function(){b.prototype.setAxisTranslation.call(this);n.unitLength=null;if(n.hasBreaks){var g=a.options.breaks||[],e=[],c=[],f=0,k,m=a.userMin||a.min,p=a.userMax||a.max,r=d(a.pointRangePadding,0),q;g.forEach(function(a){k=a.repeat||Infinity;l.isInBreak(a,m)&&(m+=a.to%k-m%k);l.isInBreak(a,p)&&(p-=p%k-a.from%k)});g.forEach(function(a){t=a.from;for(k=a.repeat||Infinity;t-k>m;)t-=k;for(;t<m;)t+=k;for(q=t;q<p;q+=k)e.push({value:q,
move:"in"}),e.push({value:q+(a.to-a.from),move:"out",size:a.breakSize})});e.sort(function(a,c){return a.value===c.value?("in"===a.move?0:1)-("in"===c.move?0:1):a.value-c.value});var x=0;var t=m;e.forEach(function(a){x+="in"===a.move?1:-1;1===x&&"in"===a.move&&(t=a.value);0===x&&(c.push({from:t,to:a.value,len:a.value-t-(a.size||0)}),f+=a.value-t-(a.size||0))});a.breakArray=n.breakArray=c;n.unitLength=p-m-f+r;z(a,"afterBreaks");a.staticScale?a.transA=a.staticScale:n.unitLength&&(a.transA*=(p-a.min+
r)/n.unitLength);r&&(a.minPixelPadding=a.transA*a.minPointOffset);a.min=m;a.max=p}});d(m,!0)&&a.chart.redraw()};return l}();q=function(){function b(){}b.compose=function(b,l){b.keepProps.push("brokenAxis");var k=t.prototype;k.drawBreaks=function(a,b){var g=this,e=g.points,c,f,k,l;if(a&&a.brokenAxis&&a.brokenAxis.hasBreaks){var m=a.brokenAxis;b.forEach(function(b){c=m&&m.breakArray||[];f=a.isXAxis?a.min:d(g.options.threshold,a.min);e.forEach(function(e){l=d(e["stack"+b.toUpperCase()],e[b]);c.forEach(function(c){if(r(f)&&
r(l)){k=!1;if(f<c.from&&l>c.to||f>c.from&&l<c.from)k="pointBreak";else if(f<c.from&&l>c.from&&l<c.to||f>c.from&&l>c.to&&l<c.from)k="pointInBreak";k&&z(a,k,{point:e,brk:c})}})})})}};k.gappedPath=function(){var a=this.currentDataGrouping,b=a&&a.gapSize;a=this.options.gapSize;var d=this.points.slice(),e=d.length-1,c=this.yAxis,f;if(a&&0<e)for("value"!==this.options.gapUnit&&(a*=this.basePointRange),b&&b>a&&b>=this.basePointRange&&(a=b),f=void 0;e--;)f&&!1!==f.visible||(f=d[e+1]),b=d[e],!1!==f.visible&&
!1!==b.visible&&(f.x-b.x>a&&(f=(b.x+f.x)/2,d.splice(e+1,0,{isNull:!0,x:f}),c.stacking&&this.options.stacking&&(f=c.stacking.stacks[this.stackKey][f]=new w(c,c.options.stackLabels,!1,f,this.stack),f.total=0)),f=b);return this.getGraphPath(d)};m(b,"init",function(){this.brokenAxis||(this.brokenAxis=new C(this))});m(b,"afterInit",function(){"undefined"!==typeof this.brokenAxis&&this.brokenAxis.setBreaks(this.options.breaks,!1)});m(b,"afterSetTickPositions",function(){var a=this.brokenAxis;if(a&&a.hasBreaks){var b=
this.tickPositions,d=this.tickPositions.info,e=[],c;for(c=0;c<b.length;c++)a.isInAnyBreak(b[c])||e.push(b[c]);this.tickPositions=e;this.tickPositions.info=d}});m(b,"afterSetOptions",function(){this.brokenAxis&&this.brokenAxis.hasBreaks&&(this.options.ordinal=!1)});m(l,"afterGeneratePoints",function(){var a=this.options.connectNulls,b=this.points,d=this.xAxis,e=this.yAxis;if(this.isDirty)for(var c=b.length;c--;){var f=b[c],k=!(null===f.y&&!1===a)&&(d&&d.brokenAxis&&d.brokenAxis.isInAnyBreak(f.x,!0)||
e&&e.brokenAxis&&e.brokenAxis.isInAnyBreak(f.y,!0));f.visible=k?!1:!1!==f.options.visible}});m(l,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,d(this.pointArrayMap,["y"]))})};return b}();q.compose(b,t);return q});B(b,"Core/Axis/TreeGridAxis.js",[b["Core/Axis/Axis.js"],b["Core/Axis/Tick.js"],b["Gantt/Tree.js"],b["Core/Axis/TreeGridTick.js"],b["Mixins/TreeSeries.js"],b["Core/Utilities.js"]],function(b,t,w,q,m,p){var z=m.getLevelOptions,y=p.addEvent,r=p.find,d=
p.fireEvent,C=p.isArray,l=p.isNumber,k=p.isObject,v=p.isString,n=p.merge,a=p.pick,g=p.wrap,h;(function(b){function c(a,b){var c=a.collapseStart||0;a=a.collapseEnd||0;a>=b&&(c-=.5);return{from:c,to:a,showPoints:!1}}function e(a,b,c){var e=[],d=[],f={},g={},h=-1,D="boolean"===typeof b?b:!1;a=w.getTree(a,{after:function(a){a=g[a.pos];var b=0,c=0;a.children.forEach(function(a){c+=(a.descendants||0)+1;b=Math.max((a.height||0)+1,b)});a.descendants=c;a.height=b;a.collapsed&&d.push(a)},before:function(a){var b=
k(a.data,!0)?a.data:{},c=v(b.name)?b.name:"",d=f[a.parent];d=k(d,!0)?g[d.pos]:null;var l=function(a){return a.name===c},m;D&&k(d,!0)&&(m=r(d.children,l))?(l=m.pos,m.nodes.push(a)):l=h++;g[l]||(g[l]=m={depth:d?d.depth+1:0,name:c,id:b.id,nodes:[a],children:[],pos:l},-1!==l&&e.push(c),k(d,!0)&&d.children.push(m));v(a.id)&&(f[a.id]=a);m&&!0===b.collapsed&&(m.collapsed=!0);a.pos=l}});g=function(a,b){var c=function(a,d,e){var f=d+(-1===d?0:b-1),g=(f-d)/2,h=d+g;a.nodes.forEach(function(a){var b=a.data;k(b,
!0)&&(b.y=d+(b.seriesIndex||0),delete b.seriesIndex);a.pos=h});e[h]=a;a.pos=h;a.tickmarkOffset=g+.5;a.collapseStart=f+.5;a.children.forEach(function(a){c(a,f+1,e);f=(a.collapseEnd||0)-.5});a.collapseEnd=f+.5;return e};return c(a["-1"],-1,{})}(g,c);return{categories:e,mapOfIdToNode:f,mapOfPosToGridNode:g,collapsedNodes:d,tree:a}}function h(a){a.target.axes.filter(function(a){return"treegrid"===a.options.type}).forEach(function(b){var c=b.options||{},d=c.labels,f=c.uniqueNames,g=0;c=c.max;if(!b.treeGrid.mapOfPosToGridNode||
b.series.some(function(a){return!a.hasRendered||a.isDirtyData||a.isDirty})){var h=b.series.reduce(function(a,b){b.visible&&((b.options.data||[]).forEach(function(c){b.options.keys&&b.options.keys.length&&(c=b.pointClass.prototype.optionsToObject.call({series:b},c),b.pointClass.setGanttPointAliases(c));k(c,!0)&&(c.seriesIndex=g,a.push(c))}),!0===f&&g++);return a},[]);if(c&&h.length<c)for(var l=h.length;l<=c;l++)h.push({name:l+"\u200b"});c=e(h,f||!1,!0===f?g:1);b.categories=c.categories;b.treeGrid.mapOfPosToGridNode=
c.mapOfPosToGridNode;b.hasNames=!0;b.treeGrid.tree=c.tree;b.series.forEach(function(a){var b=(a.options.data||[]).map(function(b){C(b)&&a.options.keys&&a.options.keys.length&&h.forEach(function(a){0<=b.indexOf(a.x)&&0<=b.indexOf(a.x2)&&(b=a)});return k(b,!0)?n(b):b});a.visible&&a.setData(b,!1)});b.treeGrid.mapOptionsToLevel=z({defaults:d,from:1,levels:d&&d.levels,to:b.treeGrid.tree&&b.treeGrid.tree.height});"beforeRender"===a.type&&(b.treeGrid.collapsedNodes=c.collapsedNodes)}})}function m(a,b){var c=
this.treeGrid.mapOptionsToLevel||{},d=this.ticks,e=d[b],f;if("treegrid"===this.options.type&&this.treeGrid.mapOfPosToGridNode){var g=this.treeGrid.mapOfPosToGridNode[b];(c=c[g.depth])&&(f={labels:c});e?(e.parameters.category=g.name,e.options=f,e.addLabel()):d[b]=new t(this,b,void 0,void 0,{category:g.name,tickmarkOffset:g.tickmarkOffset,options:f})}else a.apply(this,Array.prototype.slice.call(arguments,1))}function p(a){var b=this.options;b=(b=b&&b.labels)&&l(b.indentation)?b.indentation:0;var c=
a.apply(this,Array.prototype.slice.call(arguments,1));if("treegrid"===this.options.type&&this.treeGrid.mapOfPosToGridNode){var d=this.treeGrid.mapOfPosToGridNode[-1].height||0;c.width+=b*(d-1)}return c}function B(a,b,c){var d=this,f="treegrid"===c.type;d.treeGrid||(d.treeGrid=new I(d));f&&(y(b,"beforeRender",h),y(b,"beforeRedraw",h),y(b,"addSeries",function(a){a.options.data&&(a=e(a.options.data,c.uniqueNames||!1,1),d.treeGrid.collapsedNodes=(d.treeGrid.collapsedNodes||[]).concat(a.collapsedNodes))}),
y(d,"foundExtremes",function(){d.treeGrid.collapsedNodes&&d.treeGrid.collapsedNodes.forEach(function(a){var b=d.treeGrid.collapse(a);d.brokenAxis&&(d.brokenAxis.setBreaks(b,!1),d.treeGrid.collapsedNodes&&(d.treeGrid.collapsedNodes=d.treeGrid.collapsedNodes.filter(function(b){return a.collapseStart!==b.collapseStart||a.collapseEnd!==b.collapseEnd})))})}),y(d,"afterBreaks",function(){var a;"yAxis"===d.coll&&!d.staticScale&&(null===(a=d.chart.options.chart)||void 0===a?0:a.height)&&(d.isDirty=!0)}),
c=n({grid:{enabled:!0},labels:{align:"left",levels:[{level:void 0},{level:1,style:{fontWeight:"bold"}}],symbol:{type:"triangle",x:-5,y:-5,height:10,width:10,padding:5}},uniqueNames:!1},c,{reversed:!0,grid:{columns:void 0}}));a.apply(d,[b,c]);f&&(d.hasNames=!0,d.options.showLastLabel=!0)}function K(b){var c=this.options;"treegrid"===c.type?(this.min=a(this.userMin,c.min,this.dataMin),this.max=a(this.userMax,c.max,this.dataMax),d(this,"foundExtremes"),this.setAxisTranslation(),this.tickmarkOffset=.5,
this.tickInterval=1,this.tickPositions=this.treeGrid.mapOfPosToGridNode?this.treeGrid.getTickPositions():[]):b.apply(this,Array.prototype.slice.call(arguments,1))}var x=!1;b.compose=function(a){x||(g(a.prototype,"generateTick",m),g(a.prototype,"getMaxLabelDimensions",p),g(a.prototype,"init",B),g(a.prototype,"setTickInterval",K),q.compose(t),x=!0)};var I=function(){function a(a){this.axis=a}a.prototype.setCollapsedStatus=function(a){var b=this.axis,c=b.chart;b.series.forEach(function(b){var d=b.options.data;
if(a.id&&d){var e=c.get(a.id);b=d[b.data.indexOf(e)];e&&b&&(e.collapsed=a.collapsed,b.collapsed=a.collapsed)}})};a.prototype.collapse=function(a){var b=this.axis,d=b.options.breaks||[],e=c(a,b.max);d.push(e);a.collapsed=!0;b.treeGrid.setCollapsedStatus(a);return d};a.prototype.expand=function(a){var b=this.axis,d=b.options.breaks||[],e=c(a,b.max);a.collapsed=!1;b.treeGrid.setCollapsedStatus(a);return d.reduce(function(a,b){b.to===e.to&&b.from===e.from||a.push(b);return a},[])};a.prototype.getTickPositions=
function(){var a=this.axis,b=Math.floor(a.min/a.tickInterval)*a.tickInterval,c=Math.ceil(a.max/a.tickInterval)*a.tickInterval;return Object.keys(a.treeGrid.mapOfPosToGridNode||{}).reduce(function(d,e){e=+e;!(e>=b&&e<=c)||a.brokenAxis&&a.brokenAxis.isInAnyBreak(e)||d.push(e);return d},[])};a.prototype.isCollapsed=function(a){var b=this.axis,d=b.options.breaks||[],e=c(a,b.max);return d.some(function(a){return a.from===e.from&&a.to===e.to})};a.prototype.toggleCollapse=function(a){return this.isCollapsed(a)?
this.expand(a):this.collapse(a)};return a}();b.Additions=I})(h||(h={}));b.prototype.utils={getNode:w.getNode};h.compose(b);return h});B(b,"masters/modules/treegrid.src.js",[],function(){})});
//# sourceMappingURL=treegrid.js.map