/*
 Highcharts JS v8.2.2 (2020-12-12)

 Highcharts variwide module

 (c) 2010-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/variwide",["highcharts"],function(h){a(h);a.Highcharts=h;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function h(a,g,d,f){a.hasOwnProperty(g)||(a[g]=f.apply(null,d))}a=a?a._modules:{};h(a,"Series/Variwide/VariwidePoint.js",[a["Core/Series/Series.js"],a["Core/Utilities.js"]],function(a,g){var d=this&&this.__extends||
function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),f=g.isNumber;return function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.crosshairWidth=void 0;b.options=void 0;b.series=void 0;return b}d(b,a);b.prototype.isValid=
function(){return f(this.y)&&f(this.z)};return b}(a.seriesTypes.column.prototype.pointClass)});h(a,"Series/Variwide/VariwideComposition.js",[a["Core/Axis/Tick.js"],a["Core/Axis/Axis.js"],a["Core/Utilities.js"]],function(a,g,d){var f=d.addEvent;d=d.wrap;a.prototype.postTranslate=function(a,b,d){var c=this.axis,e=a[b]-c.pos;c.horiz||(e=c.len-e);e=c.series[0].postTranslate(d,e);c.horiz||(e=c.len-e);a[b]=c.pos+e};f(g,"afterDrawCrosshair",function(a){this.variwide&&this.cross&&this.cross.attr("stroke-width",
a.point&&a.point.crosshairWidth)});f(g,"afterRender",function(){var a=this;!this.horiz&&this.variwide&&this.chart.labelCollectors.push(function(){return a.tickPositions.filter(function(b){return a.ticks[b].label}).map(function(b,c){b=a.ticks[b].label;b.labelrank=a.zData[c];return b})})});f(a,"afterGetPosition",function(a){var b=this.axis,c=b.horiz?"x":"y";b.variwide&&(this[c+"Orig"]=a.pos[c],this.postTranslate(a.pos,c,this.pos))});d(a.prototype,"getLabelPosition",function(a,b,d,f,e,t,l,r){var c=Array.prototype.slice.call(arguments,
1),n=e?"x":"y";this.axis.variwide&&"number"===typeof this[n+"Orig"]&&(c[e?0:1]=this[n+"Orig"]);c=a.apply(this,c);this.axis.variwide&&this.axis.categories&&this.postTranslate(c,n,r);return c})});h(a,"Series/Variwide/VariwideSeries.js",[a["Core/Series/Series.js"],a["Series/Variwide/VariwidePoint.js"],a["Core/Utilities.js"]],function(a,g,d){var f=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&
(a[c]=b[c])};return a(b,c)};return function(b,c){function l(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(l.prototype=c.prototype,new l)}}(),c=a.seriesTypes.column,b=d.extend,h=d.merge,p=d.pick;d=function(b){function d(){var a=null!==b&&b.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;a.relZ=void 0;a.totalZ=void 0;a.zData=void 0;return a}f(d,b);d.prototype.processData=function(b){this.totalZ=0;this.relZ=[];a.seriesTypes.column.prototype.processData.call(this,
b);(this.xAxis.reversed?this.zData.slice().reverse():this.zData).forEach(function(a,b){this.relZ[b]=this.totalZ;this.totalZ+=a},this);this.xAxis.categories&&(this.xAxis.variwide=!0,this.xAxis.zData=this.zData)};d.prototype.postTranslate=function(a,b,c){var d=this.xAxis,k=this.relZ;a=d.reversed?k.length-a:a;var q=d.reversed?-1:1,m=d.len,f=this.totalZ;d=a/k.length*m;var l=(a+q)/k.length*m,e=p(k[a],f)/f*m;k=p(k[a+q],f)/f*m;c&&(c.crosshairWidth=k-e);return e+(b-d)*(k-e)/(l-d)};d.prototype.translate=function(){var b=
this.options.crisp,c=this.xAxis;this.options.crisp=!1;a.seriesTypes.column.prototype.translate.call(this);this.options.crisp=b;var d=this.chart.inverted,f=this.borderWidth%2/2;this.points.forEach(function(a,b){if(c.variwide){var e=this.postTranslate(b,a.shapeArgs.x,a);b=this.postTranslate(b,a.shapeArgs.x+a.shapeArgs.width)}else e=a.plotX,b=c.translate(a.x+a.z,0,0,0,1);this.options.crisp&&(e=Math.round(e)-f,b=Math.round(b)-f);a.shapeArgs.x=e;a.shapeArgs.width=Math.max(b-e,1);a.plotX=(e+b)/2;d?a.tooltipPos[1]=
c.len-a.shapeArgs.x-a.shapeArgs.width/2:a.tooltipPos[0]=a.shapeArgs.x+a.shapeArgs.width/2},this);this.options.stacking&&this.correctStackLabels()};d.prototype.correctStackLabels=function(){var a=this,b=a.options,c=a.yAxis,d,e,f,h;a.points.forEach(function(g){h=g.x;e=g.shapeArgs.width;(f=c.stacking.stacks[(a.negStacks&&g.y<(b.startFromThreshold?0:b.threshold)?"-":"")+a.stackKey])&&(d=f[h])&&!g.isNull&&d.setOffset(-(e/2)||0,e||0,void 0,void 0,g.plotX)})};d.defaultOptions=h(c.defaultOptions,{pointPadding:0,
groupPadding:0});return d}(c);b(d.prototype,{irregularWidths:!0,pointArrayMap:["y","z"],parallelArrays:["x","y","z"],pointClass:g});a.registerSeriesType("variwide",d);"";return d});h(a,"masters/modules/variwide.src.js",[],function(){})});
//# sourceMappingURL=variwide.js.map