/*
 Highcharts JS v8.2.2 (2020-12-12)

 Vector plot series module

 (c) 2010-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/vector",["highcharts"],function(e){a(e);a.Highcharts=e;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function e(a,e,g,f){a.hasOwnProperty(e)||(a[e]=f.apply(null,g))}a=a?a._modules:{};e(a,"Series/Vector/VectorSeries.js",[a["Core/Animation/AnimationUtilities.js"],a["Core/Series/Series.js"],a["Core/Globals.js"],a["Core/Utilities.js"]],
function(a,e,g,f){var k=this&&this.__extends||function(){var a=function(d,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,a){c.__proto__=a}||function(c,a){for(var b in a)a.hasOwnProperty(b)&&(c[b]=a[b])};return a(d,c)};return function(d,c){function b(){this.constructor=d}a(d,c);d.prototype=null===c?Object.create(c):(b.prototype=c.prototype,new b)}}(),l=a.animObject;a=e.seriesTypes;var m=a.line,h=a.scatter,n=f.arrayMax;a=f.extend;var p=f.merge,q=f.pick;f=function(a){function d(){var c=
null!==a&&a.apply(this,arguments)||this;c.data=void 0;c.lengthMax=void 0;c.options=void 0;c.points=void 0;return c}k(d,a);d.prototype.animate=function(a){a?this.markerGroup.attr({opacity:.01}):this.markerGroup.animate({opacity:1},l(this.options.animation))};d.prototype.arrow=function(a){a=a.length/this.lengthMax*this.options.vectorLength/20;var b={start:10*a,center:0,end:-10*a}[this.options.rotationOrigin]||0;return[["M",0,7*a+b],["L",-1.5*a,7*a+b],["L",0,10*a+b],["L",1.5*a,7*a+b],["L",0,7*a+b],["L",
0,-10*a+b]]};d.prototype.drawPoints=function(){var a=this.chart;this.points.forEach(function(b){var c=b.plotX,d=b.plotY;!1===this.options.clip||a.isInsidePlot(c,d,a.inverted)?(b.graphic||(b.graphic=this.chart.renderer.path().add(this.markerGroup).addClass("highcharts-point highcharts-color-"+q(b.colorIndex,b.series.colorIndex))),b.graphic.attr({d:this.arrow(b),translateX:c,translateY:d,rotation:b.direction}),this.chart.styledMode||b.graphic.attr(this.pointAttribs(b))):b.graphic&&(b.graphic=b.graphic.destroy())},
this)};d.prototype.pointAttribs=function(a,b){var c=this.options;a=a.color||this.color;var d=this.options.lineWidth;b&&(a=c.states[b].color||a,d=(c.states[b].lineWidth||d)+(c.states[b].lineWidthPlus||0));return{stroke:a,"stroke-width":d}};d.prototype.translate=function(){m.prototype.translate.call(this);this.lengthMax=n(this.lengthData)};d.defaultOptions=p(h.defaultOptions,{lineWidth:2,marker:null,rotationOrigin:"center",states:{hover:{lineWidthPlus:1}},tooltip:{pointFormat:"<b>[{point.x}, {point.y}]</b><br/>Length: <b>{point.length}</b><br/>Direction: <b>{point.direction}\u00b0</b><br/>"},
vectorLength:20});return d}(h);a(f.prototype,{drawGraph:g.noop,getSymbol:g.noop,markerAttribs:g.noop,parallelArrays:["x","y","length","direction"],pointArrayMap:["y","length","direction"]});e.registerSeriesType("vector",f);"";return f});e(a,"masters/modules/vector.src.js",[],function(){})});
//# sourceMappingURL=vector.js.map