/*
 Highcharts JS v8.2.2 (2020-12-12)

 Wind barb series module

 (c) 2010-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/windbarb",["highcharts"],function(l){a(l);a.Highcharts=l;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function l(a,g,e,r){a.hasOwnProperty(g)||(a[g]=r.apply(null,e))}a=a?a._modules:{};l(a,"Mixins/OnSeries.js",[a["Series/Column/ColumnSeries.js"],a["Series/Line/LineSeries.js"],a["Core/Utilities.js"]],function(a,g,e){var u=
a.prototype,c=g.prototype,v=e.defined,x=e.stableSort;return{getPlotBox:function(){return c.getPlotBox.call(this.options.onSeries&&this.chart.get(this.options.onSeries)||this)},translate:function(){u.translate.apply(this);var a=this,m=a.options,f=a.chart,c=a.points,e=c.length-1,g,n=m.onSeries;n=n&&f.get(n);m=m.onKey||"y";var B=n&&n.options.step,b=n&&n.points,k=b&&b.length,q=f.inverted,d=a.xAxis,h=a.yAxis,w=0,t;if(n&&n.visible&&k){w=(n.pointXOffset||0)+(n.barW||0)/2;f=n.currentDataGrouping;var l=b[k-
1].x+(f?f.totalRange:0);x(c,function(b,q){return b.x-q.x});for(m="plot"+m[0].toUpperCase()+m.substr(1);k--&&c[e];){var p=b[k];f=c[e];f.y=p.y;if(p.x<=f.x&&"undefined"!==typeof p[m]){if(f.x<=l&&(f.plotY=p[m],p.x<f.x&&!B&&(t=b[k+1])&&"undefined"!==typeof t[m])){var r=(f.x-p.x)/(t.x-p.x);f.plotY+=r*(t[m]-p[m]);f.y+=r*(t.y-p.y)}e--;k++;if(0>e)break}}}c.forEach(function(b,k){b.plotX+=w;if("undefined"===typeof b.plotY||q)0<=b.plotX&&b.plotX<=d.len?q?(b.plotY=d.translate(b.x,0,1,0,1),b.plotX=v(b.y)?h.translate(b.y,
0,0,0,1):0):b.plotY=(d.opposite?0:a.yAxis.len)+d.offset:b.shapeArgs={};if((g=c[k-1])&&g.plotX===b.plotX){"undefined"===typeof g.stackIndex&&(g.stackIndex=0);var f=g.stackIndex+1}b.stackIndex=f});this.onSeries=n}}});l(a,"Series/Windbarb/WindbarbPoint.js",[a["Core/Utilities.js"],a["Series/Column/ColumnSeries.js"]],function(a,g){var e=this&&this.__extends||function(){var a=function(c,e){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var f in c)c.hasOwnProperty(f)&&
(a[f]=c[f])};return a(c,e)};return function(c,e){function g(){this.constructor=c}a(c,e);c.prototype=null===e?Object.create(e):(g.prototype=e.prototype,new g)}}(),l=a.isNumber;return function(a){function c(){var c=null!==a&&a.apply(this,arguments)||this;c.beaufort=void 0;c.beaufortLevel=void 0;c.direction=void 0;c.options=void 0;c.series=void 0;return c}e(c,a);c.prototype.isValid=function(){return l(this.value)&&0<=this.value};return c}(g.prototype.pointClass)});l(a,"Series/Windbarb/WindbarbSeries.js",
[a["Core/Animation/AnimationUtilities.js"],a["Core/Series/Series.js"],a["Core/Globals.js"],a["Mixins/OnSeries.js"],a["Core/Utilities.js"],a["Series/Windbarb/WindbarbPoint.js"]],function(a,g,e,l,c,v){var r=this&&this.__extends||function(){var a=function(c,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var q in a)a.hasOwnProperty(q)&&(b[q]=a[q])};return a(c,b)};return function(c,b){function k(){this.constructor=c}a(c,b);c.prototype=null===
b?Object.create(b):(k.prototype=b.prototype,new k)}}(),u=a.animObject;a=g.seriesTypes;var m=a.column,f=a.line;a=e.noop;var y=c.extend,z=c.merge,A=c.pick;c=function(a){function c(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}r(c,a);c.registerApproximation=function(){e.approximations&&!e.approximations.windbarb&&(e.approximations.windbarb=function(a,c){var b=0,d=0,h,k=a.length;for(h=0;h<k;h++)b+=a[h]*Math.cos(c[h]*e.deg2rad),d+=a[h]*Math.sin(c[h]*
e.deg2rad);return[a.reduce(function(a,b){return a+b},0)/a.length,Math.atan2(d,b)/e.deg2rad]})};c.prototype.init=function(a,k){c.registerApproximation();f.prototype.init.call(this,a,k)};c.prototype.pointAttribs=function(a,c){var b=this.options;a=a.color||this.color;var d=this.options.lineWidth;c&&(a=b.states[c].color||a,d=(b.states[c].lineWidth||d)+(b.states[c].lineWidthPlus||0));return{stroke:a,"stroke-width":d}};c.prototype.windArrow=function(a){var c=1.943844*a.value,b=this.options.vectorLength/
20,d=-10;if(a.isNull)return[];if(0===a.beaufortLevel)return this.chart.renderer.symbols.circle(-10*b,-10*b,20*b,20*b);a=[["M",0,7*b],["L",-1.5*b,7*b],["L",0,10*b],["L",1.5*b,7*b],["L",0,7*b],["L",0,-10*b]];var h=(c-c%50)/50;if(0<h)for(;h--;)a.push(-10===d?["L",0,d*b]:["M",0,d*b],["L",5*b,d*b+2],["L",0,d*b+4]),c-=50,d+=7;h=(c-c%10)/10;if(0<h)for(;h--;)a.push(-10===d?["L",0,d*b]:["M",0,d*b],["L",7*b,d*b]),c-=10,d+=3;h=(c-c%5)/5;if(0<h)for(;h--;)a.push(-10===d?["L",0,d*b]:["M",0,d*b],["L",4*b,d*b]),
c-=5,d+=3;return a};c.prototype.translate=function(){var a=this.beaufortFloor,c=this.beaufortName;l.translate.call(this);this.points.forEach(function(b){for(var d=0;d<a.length&&!(a[d]>b.value);d++);b.beaufortLevel=d-1;b.beaufort=c[d-1]})};c.prototype.drawPoints=function(){var a=this.chart,c=this.yAxis,e=a.inverted,d=this.options.vectorLength/2;this.points.forEach(function(b){var f=b.plotX,g=b.plotY;!1===this.options.clip||a.isInsidePlot(f,0,!1)?(b.graphic||(b.graphic=this.chart.renderer.path().add(this.markerGroup).addClass("highcharts-point highcharts-color-"+
A(b.colorIndex,b.series.colorIndex))),b.graphic.attr({d:this.windArrow(b),translateX:f+this.options.xOffset,translateY:g+this.options.yOffset,rotation:b.direction}),this.chart.styledMode||b.graphic.attr(this.pointAttribs(b))):b.graphic&&(b.graphic=b.graphic.destroy());b.tooltipPos=[f+this.options.xOffset+(e&&!this.onSeries?d:0),g+this.options.yOffset-(e?0:d+c.pos-a.plotTop)]},this)};c.prototype.animate=function(a){a?this.markerGroup.attr({opacity:.01}):this.markerGroup.animate({opacity:1},u(this.options.animation))};
c.prototype.markerAttribs=function(a,c){return{}};c.prototype.getExtremes=function(){return{}};c.defaultOptions=z(m.defaultOptions,{dataGrouping:{enabled:!0,approximation:"windbarb",groupPixelWidth:30},lineWidth:2,onSeries:null,states:{hover:{lineWidthPlus:0}},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.value}</b> ({point.beaufort})<br/>'},vectorLength:20,colorKey:"value",yOffset:-20,xOffset:0});return c}(m);y(c.prototype,{pointArrayMap:["value",
"direction"],parallelArrays:["x","value","direction"],beaufortName:"Calm;Light air;Light breeze;Gentle breeze;Moderate breeze;Fresh breeze;Strong breeze;Near gale;Gale;Strong gale;Storm;Violent storm;Hurricane".split(";"),beaufortFloor:[0,.3,1.6,3.4,5.5,8,10.8,13.9,17.2,20.8,24.5,28.5,32.7],trackerGroups:["markerGroup"],getPlotBox:l.getPlotBox,invertGroups:a});c.prototype.pointClass=v;c.registerApproximation();g.registerSeriesType("windbarb",c);"";return c});l(a,"masters/modules/windbarb.src.js",
[],function(){})});
//# sourceMappingURL=windbarb.js.map