/*
 Highcharts JS v8.2.2 (2020-12-12)

 (c) 2016-2019 Highsoft AS
 Authors: Jon Arild Nygard

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/wordcloud",["highcharts"],function(l){a(l);a.Highcharts=l;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function l(a,g,h,v){a.hasOwnProperty(g)||(a[g]=v.apply(null,h))}a=a?a._modules:{};l(a,"Mixins/Polygon.js",[a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,g){var h=g.find,v=g.isArray,m=g.isNumber,q=a.deg2rad,
f=function(e,b){b=m(b)?b:14;b=Math.pow(10,b);return Math.round(e*b)/b},r=function(e,b){var c=b[0]-e[0];e=b[1]-e[1];return[[-e,c],[e,-c]]},u=function(e,b){e=e.map(function(c){return c[0]*b[0]+c[1]*b[1]});return{min:Math.min.apply(this,e),max:Math.max.apply(this,e)}},k=function(e,b){var c=e[0];e=e[1];var d=q*-b;b=Math.cos(d);d=Math.sin(d);return[f(c*b-e*d),f(c*d+e*b)]},z=function(e,b,c){e=k([e[0]-b[0],e[1]-b[1]],c);return[e[0]+b[0],e[1]+b[1]]},C=function(e){var b=e.axes;if(!v(b)){b=[];var c=c=e.concat([e[0]]);
c.reduce(function(c,A){var d=r(c,A)[0];h(b,function(c){return c[0]===d[0]&&c[1]===d[1]})||b.push(d);return A});e.axes=b}return b},l=function(e,b){e=C(e);b=C(b);return e.concat(b)};return{getBoundingBoxFromPolygon:function(e){return e.reduce(function(b,c){var d=c[0];c=c[1];b.left=Math.min(d,b.left);b.right=Math.max(d,b.right);b.bottom=Math.max(c,b.bottom);b.top=Math.min(c,b.top);return b},{left:Number.MAX_VALUE,right:-Number.MAX_VALUE,bottom:-Number.MAX_VALUE,top:Number.MAX_VALUE})},getPolygon:function(e,
b,c,d,A){var f=[e,b],B=e-c/2;e+=c/2;c=b-d/2;b+=d/2;return[[B,c],[e,c],[e,b],[B,b]].map(function(c){return z(c,f,-A)})},isPolygonsColliding:function(e,b){var c=l(e,b);return!h(c,function(c){var d=u(e,c);c=u(b,c);return!!(c.min>d.max||c.max<d.min)})},movePolygon:function(e,b,c){return c.map(function(c){return[c[0]+e,c[1]+b]})},rotate2DToOrigin:k,rotate2DToPoint:z}});l(a,"Mixins/DrawPoint.js",[],function(){var a=function(a){return"function"===typeof a},g=function(h){var g,m=this,q=m.graphic,f=h.animatableAttribs,
r=h.onComplete,u=h.css,k=h.renderer,z=null===(g=m.series)||void 0===g?void 0:g.options.animation;if(m.shouldDraw())q||(m.graphic=q=k[h.shapeType](h.shapeArgs).add(h.group)),q.css(u).attr(h.attribs).animate(f,h.isNew?!1:z,r);else if(q){var l=function(){m.graphic=q=q.destroy();a(r)&&r()};Object.keys(f).length?q.animate(f,void 0,function(){l()}):l()}};return{draw:g,drawPoint:function(a){(a.attribs=a.attribs||{})["class"]=this.getClassName();g.call(this,a)},isFn:a}});l(a,"Series/Wordcloud/WordcloudPoint.js",
[a["Mixins/DrawPoint.js"],a["Core/Series/Series.js"],a["Core/Utilities.js"]],function(a,g,h){var v=this&&this.__extends||function(){var a=function(g,f){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,f){a.__proto__=f}||function(a,f){for(var g in f)f.hasOwnProperty(g)&&(a[g]=f[g])};return a(g,f)};return function(g,f){function h(){this.constructor=g}a(g,f);g.prototype=null===f?Object.create(f):(h.prototype=f.prototype,new h)}}();h=h.extend;g=function(a){function g(){var f=null!==
a&&a.apply(this,arguments)||this;f.dimensions=void 0;f.options=void 0;f.polygon=void 0;f.rect=void 0;f.series=void 0;return f}v(g,a);g.prototype.shouldDraw=function(){return!this.isNull};g.prototype.isValid=function(){return!0};return g}(g.seriesTypes.column.prototype.pointClass);h(g.prototype,{draw:a.drawPoint,weight:1});return g});l(a,"Series/Wordcloud/WordcloudUtils.js",[a["Mixins/Polygon.js"],a["Core/Utilities.js"]],function(a,g){var h=a.isPolygonsColliding,v=a.movePolygon,m=g.extend,l=g.find,
f=g.isNumber,r=g.isObject,u=g.merge,k;(function(a){function g(c,d){return!(d.left>c.right||d.right<c.left||d.top>c.bottom||d.bottom<c.top)}function k(c,d){var a=!1,b=c.rect,f=c.polygon,p=c.lastCollidedWith,y=function(d){var a=g(b,d.rect);a&&(c.rotation%90||d.rotation%90)&&(a=h(f,d.polygon));return a};p&&((a=y(p))||delete c.lastCollidedWith);a||(a=!!l(d,function(d){var a=y(d);a&&(c.lastCollidedWith=d);return a}));return a}function e(c,d){d=4*c;var a=Math.ceil((Math.sqrt(d)-1)/2),b=2*a+1,f=Math.pow(b,
2),p=!1;--b;1E4>=c&&("boolean"===typeof p&&d>=f-b&&(p={x:a-(f-d),y:-a}),f-=b,"boolean"===typeof p&&d>=f-b&&(p={x:-a,y:-a+(f-d)}),f-=b,"boolean"===typeof p&&(p=d>=f-b?{x:-a+(f-d),y:a}:{x:a,y:a-(f-d-b)}),p.x*=5,p.y*=5);return p}function b(c,d){var a=d.width/2,b=-(d.height/2),f=d.height/2;return!(-(d.width/2)<c.left&&a>c.right&&b<c.top&&f>c.bottom)}a.isRectanglesIntersecting=g;a.intersectsAnyWord=k;a.archimedeanSpiral=function(c,d){var a=d.field;d=!1;a=a.width*a.width+a.height*a.height;var b=.8*c;1E4>=
c&&(d={x:b*Math.cos(b),y:b*Math.sin(b)},Math.min(Math.abs(d.x),Math.abs(d.y))<a||(d=!1));return d};a.squareSpiral=e;a.rectangularSpiral=function(c,a){c=e(c,a);a=a.field;c&&(c.x*=a.ratioX,c.y*=a.ratioY);return c};a.getRandomPosition=function(c){return Math.round(c*(Math.random()+.5)/2)};a.getScale=function(c,a,b){var d=2*Math.max(Math.abs(b.top),Math.abs(b.bottom));b=2*Math.max(Math.abs(b.left),Math.abs(b.right));return Math.min(0<b?1/b*c:1,0<d?1/d*a:1)};a.getPlayingField=function(c,a,b){b=b.reduce(function(c,
a){a=a.dimensions;var b=Math.max(a.width,a.height);c.maxHeight=Math.max(c.maxHeight,a.height);c.maxWidth=Math.max(c.maxWidth,a.width);c.area+=b*b;return c},{maxHeight:0,maxWidth:0,area:0});b=Math.max(b.maxHeight,b.maxWidth,.85*Math.sqrt(b.area));var d=c>a?c/a:1;c=a>c?a/c:1;return{width:b*d,height:b*c,ratioX:d,ratioY:c}};a.getRotation=function(c,a,b,e){var d=!1;f(c)&&f(a)&&f(b)&&f(e)&&0<c&&-1<a&&e>b&&(d=b+a%c*((e-b)/(c-1||1)));return d};a.getSpiral=function(c,a){var b,d=[];for(b=1;1E4>b;b++)d.push(c(b,
a));return function(c){return 1E4>=c?d[c-1]:!1}};a.outsidePlayingField=b;a.intersectionTesting=function(c,a){var d=a.placed,f=a.field,e=a.rectangle,p=a.polygon,y=a.spiral,g=1,n={x:0,y:0},h=c.rect=m({},e);c.polygon=p;for(c.rotation=a.rotation;!1!==n&&(k(c,d)||b(h,f));)n=y(g),r(n)&&(h.left=e.left+n.x,h.right=e.right+n.x,h.top=e.top+n.y,h.bottom=e.bottom+n.y,c.polygon=v(n.x,n.y,p)),g++;return n};a.extendPlayingField=function(a,b){if(r(a)&&r(b)){var c=b.bottom-b.top;var d=b.right-b.left;b=a.ratioX;var f=
a.ratioY;c=d*b>c*f?d:c;a=u(a,{width:a.width+c*b*2,height:a.height+c*f*2})}return a};a.updateFieldBoundaries=function(a,b){if(!f(a.left)||a.left>b.left)a.left=b.left;if(!f(a.right)||a.right<b.right)a.right=b.right;if(!f(a.top)||a.top>b.top)a.top=b.top;if(!f(a.bottom)||a.bottom<b.bottom)a.bottom=b.bottom;return a}})(k||(k={}));return k});l(a,"Series/Wordcloud/WordcloudSeries.js",[a["Core/Series/Series.js"],a["Core/Globals.js"],a["Series/Line/LineSeries.js"],a["Mixins/Polygon.js"],a["Core/Utilities.js"],
a["Series/Wordcloud/WordcloudPoint.js"],a["Series/Wordcloud/WordcloudUtils.js"]],function(a,g,h,l,m,q,f){var r=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),u=a.seriesTypes.column,k=g.noop,v=l.getBoundingBoxFromPolygon,
C=l.getPolygon,G=l.isPolygonsColliding,e=l.rotate2DToOrigin;l=l.rotate2DToPoint;var b=m.extend,c=m.isArray,d=m.isNumber,A=m.isObject,F=m.merge;m=function(a){function e(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}r(e,a);e.prototype.bindAxes=function(){var a={endOnTick:!1,gridLineWidth:0,lineWidth:0,maxPadding:0,startOnTick:!1,title:null,tickPositions:[]};h.prototype.bindAxes.call(this);b(this.yAxis.options,a);b(this.xAxis.options,a)};e.prototype.pointAttribs=
function(a,b){a=g.seriesTypes.column.prototype.pointAttribs.call(this,a,b);delete a.stroke;delete a["stroke-width"];return a};e.prototype.deriveFontSize=function(a,b,c){a=d(a)?a:0;b=d(b)?b:1;c=d(c)?c:1;return Math.floor(Math.max(c,a*b))};e.prototype.drawPoints=function(){var a=this,c=a.hasRendered,d=a.xAxis,e=a.yAxis,g=a.group,h=a.options,p=h.animation,l=h.allowExtendPlayingField,m=a.chart.renderer,k=m.text().add(g),q=[],r=a.placementStrategy[h.placementStrategy],u=h.rotation,B=a.points.map(function(a){return a.weight}),
z=Math.max.apply(null,B),D=a.points.concat().sort(function(a,b){return b.weight-a.weight});a.group.attr({scaleX:1,scaleY:1});D.forEach(function(c){var d=a.deriveFontSize(1/z*c.weight,h.maxFontSize,h.minFontSize);d=b({fontSize:d+"px"},h.style);k.css(d).attr({x:0,y:0,text:c.name});d=k.getBBox(!0);c.dimensions={height:d.height,width:d.width}});var w=f.getPlayingField(d.len,e.len,D);var E=f.getSpiral(a.spirals[h.spiral],{field:w});D.forEach(function(d){var e=a.deriveFontSize(1/z*d.weight,h.maxFontSize,
h.minFontSize);e=b({fontSize:e+"px"},h.style);var k=r(d,{data:D,field:w,placed:q,rotation:u}),n=b(a.pointAttribs(d,d.selected&&"select"),{align:"center","alignment-baseline":"middle",x:k.x,y:k.y,text:d.name,rotation:k.rotation}),y=C(k.x,k.y,d.dimensions.width,d.dimensions.height,k.rotation),t=v(y),x=f.intersectionTesting(d,{rectangle:t,polygon:y,field:w,placed:q,spiral:E,rotation:k.rotation});!x&&l&&(w=f.extendPlayingField(w,t),x=f.intersectionTesting(d,{rectangle:t,polygon:y,field:w,placed:q,spiral:E,
rotation:k.rotation}));A(x)?(n.x+=x.x,n.y+=x.y,t.left+=x.x,t.right+=x.x,t.top+=x.y,t.bottom+=x.y,w=f.updateFieldBoundaries(w,t),q.push(d),d.isNull=!1):d.isNull=!0;if(p){var B={x:n.x,y:n.y};c?(delete n.x,delete n.y):(n.x=0,n.y=0)}d.draw({animatableAttribs:B,attribs:n,css:e,group:g,renderer:m,shapeArgs:void 0,shapeType:"text"})});k=k.destroy();d=f.getScale(d.len,e.len,w);a.group.attr({scaleX:d,scaleY:d})};e.prototype.hasData=function(){return A(this)&&!0===this.visible&&c(this.points)&&0<this.points.length};
e.prototype.getPlotBox=function(){var a=this.chart,b=a.inverted,c=this[b?"yAxis":"xAxis"];b=this[b?"xAxis":"yAxis"];return{translateX:(c?c.left:a.plotLeft)+(c?c.len:a.plotWidth)/2,translateY:(b?b.top:a.plotTop)+(b?b.len:a.plotHeight)/2,scaleX:1,scaleY:1}};e.defaultOptions=F(u.defaultOptions,{allowExtendPlayingField:!0,animation:{duration:500},borderWidth:0,clip:!1,colorByPoint:!0,minFontSize:1,maxFontSize:25,placementStrategy:"center",rotation:{from:0,orientations:2,to:90},showInLegend:!1,spiral:"rectangular",
style:{fontFamily:"sans-serif",fontWeight:"900",whiteSpace:"nowrap"},tooltip:{followPointer:!0,pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.weight}</b><br/>'}});return e}(u);b(m.prototype,{animate:h.prototype.animate,animateDrilldown:k,animateDrillupFrom:k,pointClass:q,setClip:k,placementStrategy:{random:function(a,b){var c=b.field;b=b.rotation;return{x:f.getRandomPosition(c.width)-c.width/2,y:f.getRandomPosition(c.height)-c.height/2,rotation:f.getRotation(b.orientations,
a.index,b.from,b.to)}},center:function(a,b){b=b.rotation;return{x:0,y:0,rotation:f.getRotation(b.orientations,a.index,b.from,b.to)}}},pointArrayMap:["weight"],spirals:{archimedean:f.archimedeanSpiral,rectangular:f.rectangularSpiral,square:f.squareSpiral},utils:{extendPlayingField:f.extendPlayingField,getRotation:f.getRotation,isPolygonsColliding:G,rotate2DToOrigin:e,rotate2DToPoint:l}});a.registerSeriesType("wordcloud",m);"";return m});l(a,"masters/modules/wordcloud.src.js",[],function(){})});
//# sourceMappingURL=wordcloud.js.map