/*
 Highcharts JS v8.2.2 (2020-12-12)

 X-range series

 (c) 2010-2019 Torstein Honsi, Lars A. V. Cabrera

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/xrange",["highcharts"],function(k){a(k);a.Highcharts=k;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function k(a,g,h,b){a.hasOwnProperty(g)||(a[g]=b.apply(null,h))}a=a?a._modules:{};k(a,"Series/XRange/XRangePoint.js",[a["Core/Series/Series.js"],a["Core/Series/Point.js"]],function(a,g){var h=this&&this.__extends||
function(){var a=function(b,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,d){a.__proto__=d}||function(a,d){for(var b in d)d.hasOwnProperty(b)&&(a[b]=d[b])};return a(b,d)};return function(b,d){function m(){this.constructor=b}a(b,d);b.prototype=null===d?Object.create(d):(m.prototype=d.prototype,new m)}}();return function(a){function b(){var d=null!==a&&a.apply(this,arguments)||this;d.options=void 0;d.series=void 0;d.tooltipDateKeys=["x","x2"];return d}h(b,a);b.getColorByCategory=
function(a,b){var d=a.options.colors||a.chart.options.colors;a=b.y%(d?d.length:a.chart.options.chart.colorCount);return{colorIndex:a,color:d&&d[a]}};b.prototype.resolveColor=function(){var a=this.series;if(a.options.colorByPoint&&!this.options.color){var m=b.getColorByCategory(a,this);a.chart.styledMode||(this.color=m.color);this.options.colorIndex||(this.colorIndex=m.colorIndex)}else this.color||(this.color=a.color)};b.prototype.init=function(){g.prototype.init.apply(this,arguments);this.y||(this.y=
0);return this};b.prototype.setState=function(){g.prototype.setState.apply(this,arguments);this.series.drawPoint(this,this.series.getAnimationVerb())};b.prototype.getLabelConfig=function(){var a=g.prototype.getLabelConfig.call(this),b=this.series.yAxis.categories;a.x2=this.x2;a.yCategory=this.yCategory=b&&b[this.y];return a};b.prototype.isValid=function(){return"number"===typeof this.x&&"number"===typeof this.x2};return b}(a.seriesTypes.column.prototype.pointClass)});k(a,"Series/XRange/XRangeComposition.js",
[a["Core/Axis/Axis.js"],a["Core/Utilities.js"]],function(a,g){var h=g.addEvent,b=g.pick;h(a,"afterGetSeriesExtremes",function(){var a=this.series,d;if(this.isXAxis){var g=b(this.dataMax,-Number.MAX_VALUE);a.forEach(function(a){a.x2Data&&a.x2Data.forEach(function(a){a>g&&(g=a,d=!0)})});d&&(this.dataMax=g)}})});k(a,"Series/XRange/XRangeSeries.js",[a["Core/Series/Series.js"],a["Core/Globals.js"],a["Core/Color/Color.js"],a["Core/Utilities.js"],a["Series/XRange/XRangePoint.js"]],function(a,g,h,b,k){var d=
this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,a){c.__proto__=a}||function(c,a){for(var b in a)a.hasOwnProperty(b)&&(c[b]=a[b])};return a(b,c)};return function(b,c){function A(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(A.prototype=c.prototype,new A)}}(),m=a.seriesTypes,r=m.column,z=m.line,B=h.parse,C=r.prototype,v=b.clamp,E=b.correctFloat,F=b.defined;h=b.extend;var D=b.find,u=b.isNumber,w=b.isObject,
t=b.merge,x=b.pick;b=function(a){function b(){var c=null!==a&&a.apply(this,arguments)||this;c.data=void 0;c.options=void 0;c.points=void 0;return c}d(b,a);b.prototype.init=function(){r.prototype.init.apply(this,arguments);this.options.stacking=void 0};b.prototype.getColumnMetrics=function(){function c(){a.series.forEach(function(c){var a=c.xAxis;c.xAxis=c.yAxis;c.yAxis=a})}var a=this.chart;c();var b=C.getColumnMetrics.call(this);c();return b};b.prototype.cropData=function(c,a,b,d){a=z.prototype.cropData.call(this,
this.x2Data,a,b,d);a.xData=c.slice(a.start,a.end);return a};b.prototype.findPointIndex=function(a){var c=this.cropped,b=this.cropStart,d=this.points,e=a.id;if(e)var f=(f=D(d,function(a){return a.id===e}))?f.index:void 0;"undefined"===typeof f&&(f=(f=D(d,function(c){return c.x===a.x&&c.x2===a.x2&&!c.touched}))?f.index:void 0);c&&u(f)&&u(b)&&f>=b&&(f-=b);return f};b.prototype.translatePoint=function(a){var b,c,d=this.xAxis,e=this.yAxis,f=this.columnMetrics,n=this.options,g=n.minPointLength||0,p=(null===
(b=a.shapeArgs)||void 0===b?NaN:b.width)/2,k=this.pointXOffset=f.offset;b=a.plotX;var h=x(a.x2,a.x+(a.len||0)),l=d.translate(h,0,0,0,1);h=Math.abs(l-b);var q=this.chart.inverted,m=x(n.borderWidth,1)%2/2,r=f.offset,y=Math.round(f.width);g&&(g-=h,0>g&&(g=0),b-=g/2,l+=g/2);b=Math.max(b,-10);l=v(l,-10,d.len+10);F(a.options.pointWidth)&&(r-=(Math.ceil(a.options.pointWidth)-y)/2,y=Math.ceil(a.options.pointWidth));n.pointPlacement&&u(a.plotY)&&e.categories&&(a.plotY=e.translate(a.y,0,1,0,1,n.pointPlacement));
a.shapeArgs={x:Math.floor(Math.min(b,l))+m,y:Math.floor(a.plotY+r)+m,width:Math.round(Math.abs(l-b)),height:y,r:this.options.borderRadius};q?a.tooltipPos[1]+=k+p:a.tooltipPos[0]-=p+k-(null===(c=a.shapeArgs)||void 0===c?NaN:c.width)/2;c=a.shapeArgs.x;n=c+a.shapeArgs.width;0>c||n>d.len?(c=v(c,0,d.len),n=v(n,0,d.len),p=n-c,a.dlBox=t(a.shapeArgs,{x:c,width:n-c,centerX:p?p/2:null})):a.dlBox=null;c=a.tooltipPos;n=q?1:0;p=q?0:1;f=this.columnMetrics?this.columnMetrics.offset:-f.width/2;c[n]=q?c[n]+a.shapeArgs.width/
2:c[n]+(d.reversed?-1:0)*a.shapeArgs.width;c[p]=v(c[p]+(q?-1:1)*f,0,e.len-1);if(f=a.partialFill)w(f)&&(f=f.amount),u(f)||(f=0),e=a.shapeArgs,a.partShapeArgs={x:e.x,y:e.y,width:e.width,height:e.height,r:this.options.borderRadius},b=Math.max(Math.round(h*f+a.plotX-b),0),a.clipRectArgs={x:d.reversed?e.x+h-b:e.x,y:e.y,width:b,height:e.height}};b.prototype.translate=function(){C.translate.apply(this,arguments);this.points.forEach(function(a){this.translatePoint(a)},this)};b.prototype.drawPoint=function(a,
b){var c=this.options,d=this.chart.renderer,e=a.graphic,f=a.shapeType,g=a.shapeArgs,h=a.partShapeArgs,p=a.clipRectArgs,k=a.partialFill,m=c.stacking&&!c.borderRadius,l=a.state,q=c.states[l||"normal"]||{},r="undefined"===typeof l?"attr":b;l=this.pointAttribs(a,l);q=x(this.chart.options.chart.animation,q.animation);if(a.isNull||!1===a.visible)e&&(a.graphic=e.destroy());else{if(e)e.rect[b](g);else a.graphic=e=d.g("point").addClass(a.getClassName()).add(a.group||this.group),e.rect=d[f](t(g)).addClass(a.getClassName()).addClass("highcharts-partfill-original").add(e);
h&&(e.partRect?(e.partRect[b](t(h)),e.partialClipRect[b](t(p))):(e.partialClipRect=d.clipRect(p.x,p.y,p.width,p.height),e.partRect=d[f](h).addClass("highcharts-partfill-overlay").add(e).clip(e.partialClipRect)));this.chart.styledMode||(e.rect[b](l,q).shadow(c.shadow,null,m),h&&(w(k)||(k={}),w(c.partialFill)&&(k=t(c.partialFill,k)),a=k.fill||B(l.fill).brighten(-.3).get()||B(a.color||this.color).brighten(-.3).get(),l.fill=a,e.partRect[r](l,q).shadow(c.shadow,null,m)))}};b.prototype.drawPoints=function(){var a=
this,b=a.getAnimationVerb();a.points.forEach(function(c){a.drawPoint(c,b)})};b.prototype.getAnimationVerb=function(){return this.chart.pointCount<(this.options.animationLimit||250)?"animate":"attr"};b.defaultOptions=t(r.defaultOptions,{colorByPoint:!0,dataLabels:{formatter:function(){var a=this.point.partialFill;w(a)&&(a=a.amount);if(u(a)&&0<a)return E(100*a)+"%"},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:'<span style="font-size: 10px">{point.x} - {point.x2}</span><br/>',pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.yCategory}</b><br/>'},
borderRadius:3,pointRange:0});return b}(r);h(b.prototype,{type:"xrange",parallelArrays:["x","x2","y"],requireSorting:!1,animate:z.prototype.animate,cropShoulder:1,getExtremesFromAll:!0,autoIncrement:g.noop,buildKDTree:g.noop,pointClass:k});a.registerSeriesType("xrange",b);"";return b});k(a,"masters/modules/xrange.src.js",[],function(){})});
//# sourceMappingURL=xrange.js.map