/*
 Highcharts JS v8.2.2 (2020-12-12)

 3D features for Highcharts JS

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/highcharts-3d",["highcharts"],function(C){b(C);b.Highcharts=C;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function C(b,v,g,u){b.hasOwnProperty(v)||(b[v]=u.apply(null,g))}b=b?b._modules:{};C(b,"Extensions/Math3D.js",[b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,v){function g(d,c,a){c=0<a&&a<Number.POSITIVE_INFINITY?
a/(d.z+c.z+a):1;return{x:d.x*c,y:d.y*c}}function u(d,c,a,n){var m=c.options.chart.options3d,p=w(n,a?c.inverted:!1),e={x:c.plotWidth/2,y:c.plotHeight/2,z:m.depth/2,vd:w(m.depth,1)*w(m.viewDistance,0)},h=c.scale3d||1;n=t*m.beta*(p?-1:1);m=t*m.alpha*(p?-1:1);var q=Math.cos(m),f=Math.cos(-n),D=Math.sin(m),b=Math.sin(-n);a||(e.x+=c.plotLeft,e.y+=c.plotTop);return d.map(function(a){var c=(p?a.y:a.x)-e.x;var l=(p?a.x:a.y)-e.y;a=(a.z||0)-e.z;c={x:f*c-b*a,y:-D*b*c+q*l-f*D*a,z:q*b*c+D*l+q*f*a};l=g(c,e,e.vd);
l.x=l.x*h+e.x;l.y=l.y*h+e.y;l.z=c.z*h+e.z;return{x:p?l.y:l.x,y:p?l.x:l.y,z:l.z}})}function d(d,c){var a=c.options.chart.options3d,n=c.plotWidth/2;c=c.plotHeight/2;a=w(a.depth,1)*w(a.viewDistance,0)+a.depth;return Math.sqrt(Math.pow(n-w(d.plotX,d.x),2)+Math.pow(c-w(d.plotY,d.y),2)+Math.pow(a-w(d.plotZ,d.z),2))}function x(d){var c=0,a;for(a=0;a<d.length;a++){var n=(a+1)%d.length;c+=d[a].x*d[n].y-d[n].x*d[a].y}return c/2}function r(d,c,a){return x(u(d,c,a))}var w=v.pick,t=b.deg2rad;b.perspective3D=g;
b.perspective=u;b.pointCameraDistance=d;b.shapeArea=x;b.shapeArea3d=r;return{perspective:u,perspective3D:g,pointCameraDistance:d,shapeArea:x,shapeArea3D:r}});C(b,"Core/Renderer/SVG/SVGElement3D.js",[b["Core/Color/Color.js"],b["Core/Renderer/SVG/SVGElement.js"],b["Core/Utilities.js"]],function(b,v,g){var u=b.parse,d=g.defined,x=g.merge,r=g.objectEach,w=g.pick,t;(function(b){b.base={initArgs:function(c){var a=this,d=a.renderer,b=d[a.pathType+"Path"](c),p=b.zIndexes;a.parts.forEach(function(e){a[e]=
d.path(b[e]).attr({"class":"highcharts-3d-"+e,zIndex:p[e]||0}).add(a)});a.attr({"stroke-linejoin":"round",zIndex:p.group});a.originalDestroy=a.destroy;a.destroy=a.destroyParts;a.forcedSides=b.forcedSides},singleSetterForParts:function(c,a,d,b,p,e){var h={};b=[null,null,b||"attr",p,e];var q=d&&d.zIndexes;d?(q&&q.group&&this.attr({zIndex:q.group}),r(d,function(a,e){h[e]={};h[e][c]=a;q&&(h[e].zIndex=d.zIndexes[e]||0)}),b[1]=h):(h[c]=a,b[0]=h);return this.processParts.apply(this,b)},processParts:function(c,
a,d,b,p){var e=this;e.parts.forEach(function(h){a&&(c=w(a[h],!1));if(!1!==c)e[h][d](c,b,p)});return e},destroyParts:function(){this.processParts(null,null,"destroy");return this.originalDestroy()}};b.cuboid=x(b.base,{parts:["front","top","side"],pathType:"cuboid",attr:function(c,a,b,m){if("string"===typeof c&&"undefined"!==typeof a){var n=c;c={};c[n]=a}return c.shapeArgs||d(c.x)?this.singleSetterForParts("d",null,this.renderer[this.pathType+"Path"](c.shapeArgs||c)):v.prototype.attr.call(this,c,void 0,
b,m)},animate:function(c,a,n){if(d(c.x)&&d(c.y)){c=this.renderer[this.pathType+"Path"](c);var m=c.forcedSides;this.singleSetterForParts("d",null,c,"animate",a,n);this.attr({zIndex:c.zIndexes.group});m!==this.forcedSides&&(this.forcedSides=m,b.cuboid.fillSetter.call(this,this.fill))}else v.prototype.animate.call(this,c,a,n);return this},fillSetter:function(c){this.forcedSides=this.forcedSides||[];this.singleSetterForParts("fill",null,{front:c,top:u(c).brighten(0<=this.forcedSides.indexOf("top")?0:
.1).get(),side:u(c).brighten(0<=this.forcedSides.indexOf("side")?0:-.1).get()});this.color=this.fill=c;return this}})})(t||(t={}));return t});C(b,"Core/Renderer/SVG/SVGRenderer3D.js",[b["Core/Animation/AnimationUtilities.js"],b["Core/Color/Color.js"],b["Core/Globals.js"],b["Extensions/Math3D.js"],b["Core/Renderer/SVG/SVGElement.js"],b["Core/Renderer/SVG/SVGElement3D.js"],b["Core/Renderer/SVG/SVGRenderer.js"],b["Core/Utilities.js"]],function(b,v,g,u,d,x,r,w){function t(a,e,c,h,d,f,b,q){var k=[],l=
f-d;return f>d&&f-d>Math.PI/2+.0001?(k=k.concat(t(a,e,c,h,d,d+Math.PI/2,b,q)),k=k.concat(t(a,e,c,h,d+Math.PI/2,f,b,q))):f<d&&d-f>Math.PI/2+.0001?(k=k.concat(t(a,e,c,h,d,d-Math.PI/2,b,q)),k=k.concat(t(a,e,c,h,d-Math.PI/2,f,b,q))):[["C",a+c*Math.cos(d)-c*F*l*Math.sin(d)+b,e+h*Math.sin(d)+h*F*l*Math.cos(d)+q,a+c*Math.cos(f)+c*F*l*Math.sin(f)+b,e+h*Math.sin(f)-h*F*l*Math.cos(f)+q,a+c*Math.cos(f)+b,e+h*Math.sin(f)+q]]}var p=b.animObject,c=v.parse,a=g.charts,n=g.deg2rad,m=u.perspective,z=u.shapeArea,e=
w.defined,h=w.extend,q=w.merge,f=w.pick,D=Math.cos,H=Math.sin,K=Math.PI,F=4*(Math.sqrt(2)-1)/3/(K/2);r.prototype.elements3d=x;r.prototype.toLinePath=function(a,e){var c=[];a.forEach(function(a){c.push(["L",a.x,a.y])});a.length&&(c[0][0]="M",e&&c.push(["Z"]));return c};r.prototype.toLineSegments=function(a){var e=[],c=!0;a.forEach(function(a){e.push(c?["M",a.x,a.y]:["L",a.x,a.y]);c=!c});return e};r.prototype.face3d=function(c){var h=this,k=this.createElement("path");k.vertexes=[];k.insidePlotArea=
!1;k.enabled=!0;k.attr=function(c){if("object"===typeof c&&(e(c.enabled)||e(c.vertexes)||e(c.insidePlotArea))){this.enabled=f(c.enabled,this.enabled);this.vertexes=f(c.vertexes,this.vertexes);this.insidePlotArea=f(c.insidePlotArea,this.insidePlotArea);delete c.enabled;delete c.vertexes;delete c.insidePlotArea;var k=m(this.vertexes,a[h.chartIndex],this.insidePlotArea),l=h.toLinePath(k,!0);k=z(k);k=this.enabled&&0<k?"visible":"hidden";c.d=l;c.visibility=k}return d.prototype.attr.apply(this,arguments)};
k.animate=function(c){if("object"===typeof c&&(e(c.enabled)||e(c.vertexes)||e(c.insidePlotArea))){this.enabled=f(c.enabled,this.enabled);this.vertexes=f(c.vertexes,this.vertexes);this.insidePlotArea=f(c.insidePlotArea,this.insidePlotArea);delete c.enabled;delete c.vertexes;delete c.insidePlotArea;var k=m(this.vertexes,a[h.chartIndex],this.insidePlotArea),l=h.toLinePath(k,!0);k=z(k);k=this.enabled&&0<k?"visible":"hidden";c.d=l;this.attr("visibility",k)}return d.prototype.animate.apply(this,arguments)};
return k.attr(c)};r.prototype.polyhedron=function(a){var c=this,k=this.g(),h=k.destroy;this.styledMode||k.attr({"stroke-linejoin":"round"});k.faces=[];k.destroy=function(){for(var a=0;a<k.faces.length;a++)k.faces[a].destroy();return h.call(this)};k.attr=function(a,h,f,l){if("object"===typeof a&&e(a.faces)){for(;k.faces.length>a.faces.length;)k.faces.pop().destroy();for(;k.faces.length<a.faces.length;)k.faces.push(c.face3d().add(k));for(var b=0;b<a.faces.length;b++)c.styledMode&&delete a.faces[b].fill,
k.faces[b].attr(a.faces[b],null,f,l);delete a.faces}return d.prototype.attr.apply(this,arguments)};k.animate=function(a,e,h){if(a&&a.faces){for(;k.faces.length>a.faces.length;)k.faces.pop().destroy();for(;k.faces.length<a.faces.length;)k.faces.push(c.face3d().add(k));for(var f=0;f<a.faces.length;f++)k.faces[f].animate(a.faces[f],e,h);delete a.faces}return d.prototype.animate.apply(this,arguments)};return k.attr(a)};r.prototype.element3d=function(a,c){var e=this.g();h(e,this.elements3d[a]);e.initArgs(c);
return e};r.prototype.cuboid=function(a){return this.element3d("cuboid",a)};r.prototype.cuboidPath=function(c){function e(a){return 0===l&&1<a&&6>a?{x:G[a].x,y:G[a].y+10,z:G[a].z}:G[0].x===G[7].x&&4<=a?{x:G[a].x+10,y:G[a].y,z:G[a].z}:0===n&&2>a||5<a?{x:G[a].x,y:G[a].y,z:G[a].z+10}:G[a]}function h(a){return G[a]}var f=c.x,d=c.y,b=c.z||0,l=c.height,q=c.width,n=c.depth,y=a[this.chartIndex],A=y.options.chart.options3d.alpha,E=0,G=[{x:f,y:d,z:b},{x:f+q,y:d,z:b},{x:f+q,y:d+l,z:b},{x:f,y:d+l,z:b},{x:f,y:d+
l,z:b+n},{x:f+q,y:d+l,z:b+n},{x:f+q,y:d,z:b+n},{x:f,y:d,z:b+n}],D=[];G=m(G,y,c.insidePlotArea);var B=function(a,c,A){var f=[[],-1],d=a.map(h),k=c.map(h);a=a.map(e);c=c.map(e);0>z(d)?f=[d,0]:0>z(k)?f=[k,1]:A&&(D.push(A),f=0>z(a)?[d,0]:0>z(c)?[k,1]:[d,0]);return f};var I=B([3,2,1,0],[7,6,5,4],"front");c=I[0];var p=I[1];I=B([1,6,7,0],[4,5,2,3],"top");q=I[0];var H=I[1];I=B([1,2,5,6],[0,7,4,3],"side");B=I[0];I=I[1];1===I?E+=1E6*(y.plotWidth-f):I||(E+=1E6*f);E+=10*(!H||0<=A&&180>=A||360>A&&357.5<A?y.plotHeight-
d:10+d);1===p?E+=100*b:p||(E+=100*(1E3-b));return{front:this.toLinePath(c,!0),top:this.toLinePath(q,!0),side:this.toLinePath(B,!0),zIndexes:{group:Math.round(E)},forcedSides:D,isFront:p,isTop:H}};r.prototype.arc3d=function(a){function e(a){var c=!1,e={},f;a=q(a);for(f in a)-1!==l.indexOf(f)&&(e[f]=a[f],delete a[f],c=!0);return c?[e,a]:!1}var k=this.g(),b=k.renderer,l="x y r innerR start end depth".split(" ");a=q(a);a.alpha=(a.alpha||0)*n;a.beta=(a.beta||0)*n;k.top=b.path();k.side1=b.path();k.side2=
b.path();k.inn=b.path();k.out=b.path();k.onAdd=function(){var a=k.parentGroup,c=k.attr("class");k.top.add(k);["out","inn","side1","side2"].forEach(function(e){k[e].attr({"class":c+" highcharts-3d-side"}).add(a)})};["addClass","removeClass"].forEach(function(a){k[a]=function(){var c=arguments;["top","out","inn","side1","side2"].forEach(function(e){k[e][a].apply(k[e],c)})}});k.setPaths=function(a){var c=k.renderer.arc3dPath(a),e=100*c.zTop;k.attribs=a;k.top.attr({d:c.top,zIndex:c.zTop});k.inn.attr({d:c.inn,
zIndex:c.zInn});k.out.attr({d:c.out,zIndex:c.zOut});k.side1.attr({d:c.side1,zIndex:c.zSide1});k.side2.attr({d:c.side2,zIndex:c.zSide2});k.zIndex=e;k.attr({zIndex:e});a.center&&(k.top.setRadialReference(a.center),delete a.center)};k.setPaths(a);k.fillSetter=function(a){var e=c(a).brighten(-.1).get();this.fill=a;this.side1.attr({fill:e});this.side2.attr({fill:e});this.inn.attr({fill:e});this.out.attr({fill:e});this.top.attr({fill:a});return this};["opacity","translateX","translateY","visibility"].forEach(function(a){k[a+
"Setter"]=function(a,c){k[c]=a;["out","inn","side1","side2","top"].forEach(function(e){k[e].attr(c,a)})}});k.attr=function(a){var c;if("object"===typeof a&&(c=e(a))){var f=c[0];arguments[0]=c[1];h(k.attribs,f);k.setPaths(k.attribs)}return d.prototype.attr.apply(k,arguments)};k.animate=function(a,c,h){var b=this.attribs,l="data-"+Math.random().toString(26).substring(2,9);delete a.center;delete a.z;delete a.alpha;delete a.beta;var A=p(f(c,this.renderer.globalAnimation));if(A.duration){c=e(a);k[l]=0;
a[l]=1;k[l+"Setter"]=g.noop;if(c){var E=c[0];A.step=function(a,c){function e(a){return b[a]+(f(E[a],b[a])-b[a])*c.pos}c.prop===l&&c.elem.setPaths(q(b,{x:e("x"),y:e("y"),r:e("r"),innerR:e("innerR"),start:e("start"),end:e("end"),depth:e("depth")}))}}c=A}return d.prototype.animate.call(this,a,c,h)};k.destroy=function(){this.top.destroy();this.out.destroy();this.inn.destroy();this.side1.destroy();this.side2.destroy();return d.prototype.destroy.call(this)};k.hide=function(){this.top.hide();this.out.hide();
this.inn.hide();this.side1.hide();this.side2.hide()};k.show=function(a){this.top.show(a);this.out.show(a);this.inn.show(a);this.side1.show(a);this.side2.show(a)};return k};r.prototype.arc3dPath=function(a){function c(a){a%=2*Math.PI;a>Math.PI&&(a=2*Math.PI-a);return a}var e=a.x,f=a.y,d=a.start,h=a.end-.00001,b=a.r,q=a.innerR||0,l=a.depth||0,y=a.alpha,A=a.beta,E=Math.cos(d),n=Math.sin(d);a=Math.cos(h);var p=Math.sin(h),B=b*Math.cos(A);b*=Math.cos(y);var m=q*Math.cos(A),J=q*Math.cos(y);q=l*Math.sin(A);
var r=l*Math.sin(y);l=[["M",e+B*E,f+b*n]];l=l.concat(t(e,f,B,b,d,h,0,0));l.push(["L",e+m*a,f+J*p]);l=l.concat(t(e,f,m,J,h,d,0,0));l.push(["Z"]);var z=0<A?Math.PI/2:0;A=0<y?0:Math.PI/2;z=d>-z?d:h>-z?-z:d;var g=h<K-A?h:d<K-A?K-A:h,F=2*K-A;y=[["M",e+B*D(z),f+b*H(z)]];y=y.concat(t(e,f,B,b,z,g,0,0));h>F&&d<F?(y.push(["L",e+B*D(g)+q,f+b*H(g)+r]),y=y.concat(t(e,f,B,b,g,F,q,r)),y.push(["L",e+B*D(F),f+b*H(F)]),y=y.concat(t(e,f,B,b,F,h,0,0)),y.push(["L",e+B*D(h)+q,f+b*H(h)+r]),y=y.concat(t(e,f,B,b,h,F,q,r)),
y.push(["L",e+B*D(F),f+b*H(F)]),y=y.concat(t(e,f,B,b,F,g,0,0))):h>K-A&&d<K-A&&(y.push(["L",e+B*Math.cos(g)+q,f+b*Math.sin(g)+r]),y=y.concat(t(e,f,B,b,g,h,q,r)),y.push(["L",e+B*Math.cos(h),f+b*Math.sin(h)]),y=y.concat(t(e,f,B,b,h,g,0,0)));y.push(["L",e+B*Math.cos(g)+q,f+b*Math.sin(g)+r]);y=y.concat(t(e,f,B,b,g,z,q,r));y.push(["Z"]);A=[["M",e+m*E,f+J*n]];A=A.concat(t(e,f,m,J,d,h,0,0));A.push(["L",e+m*Math.cos(h)+q,f+J*Math.sin(h)+r]);A=A.concat(t(e,f,m,J,h,d,q,r));A.push(["Z"]);E=[["M",e+B*E,f+b*n],
["L",e+B*E+q,f+b*n+r],["L",e+m*E+q,f+J*n+r],["L",e+m*E,f+J*n],["Z"]];e=[["M",e+B*a,f+b*p],["L",e+B*a+q,f+b*p+r],["L",e+m*a+q,f+J*p+r],["L",e+m*a,f+J*p],["Z"]];p=Math.atan2(r,-q);f=Math.abs(h+p);a=Math.abs(d+p);d=Math.abs((d+h)/2+p);f=c(f);a=c(a);d=c(d);d*=1E5;h=1E5*a;f*=1E5;return{top:l,zTop:1E5*Math.PI+1,out:y,zOut:Math.max(d,h,f),inn:A,zInn:Math.max(d,h,f),side1:E,zSide1:.99*f,side2:e,zSide2:.99*h}};return r});C(b,"Core/Axis/Tick3D.js",[b["Core/Utilities.js"]],function(b){var v=b.addEvent,g=b.extend,
u=b.wrap;return function(){function d(){}d.compose=function(b){v(b,"afterGetLabelPosition",d.onAfterGetLabelPosition);u(b.prototype,"getMarkPath",d.wrapGetMarkPath)};d.onAfterGetLabelPosition=function(b){var d=this.axis.axis3D;d&&g(b.pos,d.fix3dPosition(b.pos))};d.wrapGetMarkPath=function(b){var d=this.axis.axis3D,g=b.apply(this,[].slice.call(arguments,1));if(d){var t=g[0],p=g[1];if("M"===t[0]&&"L"===p[0])return d=[d.fix3dPosition({x:t[1],y:t[2],z:0}),d.fix3dPosition({x:p[1],y:p[2],z:0})],this.axis.chart.renderer.toLineSegments(d)}return g};
return d}()});C(b,"Core/Axis/Axis3D.js",[b["Core/Globals.js"],b["Extensions/Math3D.js"],b["Core/Axis/Tick.js"],b["Core/Axis/Tick3D.js"],b["Core/Utilities.js"]],function(b,v,g,u,d){var x=v.perspective,r=v.perspective3D,w=v.shapeArea,t=d.addEvent,p=d.merge,c=d.pick,a=d.wrap,n=b.deg2rad,m=function(){function a(a){this.axis=a}a.prototype.fix3dPosition=function(a,b){var e=this.axis,f=e.chart;if("colorAxis"===e.coll||!f.chart3d||!f.is3d())return a;var d=n*f.options.chart.options3d.alpha,h=n*f.options.chart.options3d.beta,
p=c(b&&e.options.title.position3d,e.options.labels.position3d);b=c(b&&e.options.title.skew3d,e.options.labels.skew3d);var m=f.chart3d.frame3d,l=f.plotLeft,g=f.plotWidth+l,k=f.plotTop,r=f.plotHeight+k;f=!1;var z=0,t=0,u={x:0,y:1,z:0};a=e.axis3D.swapZ({x:a.x,y:a.y,z:0});if(e.isZAxis)if(e.opposite){if(null===m.axes.z.top)return{};t=a.y-k;a.x=m.axes.z.top.x;a.y=m.axes.z.top.y;l=m.axes.z.top.xDir;f=!m.top.frontFacing}else{if(null===m.axes.z.bottom)return{};t=a.y-r;a.x=m.axes.z.bottom.x;a.y=m.axes.z.bottom.y;
l=m.axes.z.bottom.xDir;f=!m.bottom.frontFacing}else if(e.horiz)if(e.opposite){if(null===m.axes.x.top)return{};t=a.y-k;a.y=m.axes.x.top.y;a.z=m.axes.x.top.z;l=m.axes.x.top.xDir;f=!m.top.frontFacing}else{if(null===m.axes.x.bottom)return{};t=a.y-r;a.y=m.axes.x.bottom.y;a.z=m.axes.x.bottom.z;l=m.axes.x.bottom.xDir;f=!m.bottom.frontFacing}else if(e.opposite){if(null===m.axes.y.right)return{};z=a.x-g;a.x=m.axes.y.right.x;a.z=m.axes.y.right.z;l=m.axes.y.right.xDir;l={x:l.z,y:l.y,z:-l.x}}else{if(null===m.axes.y.left)return{};
z=a.x-l;a.x=m.axes.y.left.x;a.z=m.axes.y.left.z;l=m.axes.y.left.xDir}"chart"!==p&&("flap"===p?e.horiz?(h=Math.sin(d),d=Math.cos(d),e.opposite&&(h=-h),f&&(h=-h),u={x:l.z*h,y:d,z:-l.x*h}):l={x:Math.cos(h),y:0,z:Math.sin(h)}:"ortho"===p?e.horiz?(u=Math.cos(d),p=Math.sin(h)*u,d=-Math.sin(d),h=-u*Math.cos(h),u={x:l.y*h-l.z*d,y:l.z*p-l.x*h,z:l.x*d-l.y*p},d=1/Math.sqrt(u.x*u.x+u.y*u.y+u.z*u.z),f&&(d=-d),u={x:d*u.x,y:d*u.y,z:d*u.z}):l={x:Math.cos(h),y:0,z:Math.sin(h)}:e.horiz?u={x:Math.sin(h)*Math.sin(d),
y:Math.cos(d),z:-Math.cos(h)*Math.sin(d)}:l={x:Math.cos(h),y:0,z:Math.sin(h)});a.x+=z*l.x+t*u.x;a.y+=z*l.y+t*u.y;a.z+=z*l.z+t*u.z;f=x([a],e.chart)[0];b&&(0>w(x([a,{x:a.x+l.x,y:a.y+l.y,z:a.z+l.z},{x:a.x+u.x,y:a.y+u.y,z:a.z+u.z}],e.chart))&&(l={x:-l.x,y:-l.y,z:-l.z}),a=x([{x:a.x,y:a.y,z:a.z},{x:a.x+l.x,y:a.y+l.y,z:a.z+l.z},{x:a.x+u.x,y:a.y+u.y,z:a.z+u.z}],e.chart),f.matrix=[a[1].x-a[0].x,a[1].y-a[0].y,a[2].x-a[0].x,a[2].y-a[0].y,f.x,f.y],f.matrix[4]-=f.x*f.matrix[0]+f.y*f.matrix[2],f.matrix[5]-=f.x*
f.matrix[1]+f.y*f.matrix[3]);return f};a.prototype.swapZ=function(a,c){var e=this.axis;return e.isZAxis?(c=c?0:e.chart.plotLeft,{x:c+a.z,y:a.y,z:a.x-c}):a};return a}();return function(){function d(){}d.compose=function(c){p(!0,c.defaultOptions,d.defaultOptions);c.keepProps.push("axis3D");t(c,"init",d.onInit);t(c,"afterSetOptions",d.onAfterSetOptions);t(c,"drawCrosshair",d.onDrawCrosshair);t(c,"destroy",d.onDestroy);c=c.prototype;a(c,"getLinePath",d.wrapGetLinePath);a(c,"getPlotBandPath",d.wrapGetPlotBandPath);
a(c,"getPlotLinePath",d.wrapGetPlotLinePath);a(c,"getSlotWidth",d.wrapGetSlotWidth);a(c,"getTitlePosition",d.wrapGetTitlePosition);u.compose(g)};d.onAfterSetOptions=function(){var a=this.chart,d=this.options;a.is3d&&a.is3d()&&"colorAxis"!==this.coll&&(d.tickWidth=c(d.tickWidth,0),d.gridLineWidth=c(d.gridLineWidth,1))};d.onDestroy=function(){["backFrame","bottomFrame","sideFrame"].forEach(function(a){this[a]&&(this[a]=this[a].destroy())},this)};d.onDrawCrosshair=function(a){this.chart.is3d()&&"colorAxis"!==
this.coll&&a.point&&(a.point.crosshairPos=this.isXAxis?a.point.axisXpos:this.len-a.point.axisYpos)};d.onInit=function(){this.axis3D||(this.axis3D=new m(this))};d.wrapGetLinePath=function(a){return this.chart.is3d()&&"colorAxis"!==this.coll?[]:a.apply(this,[].slice.call(arguments,1))};d.wrapGetPlotBandPath=function(a){if(!this.chart.is3d()||"colorAxis"===this.coll)return a.apply(this,[].slice.call(arguments,1));var c=arguments,d=c[2],f=[];c=this.getPlotLinePath({value:c[1]});d=this.getPlotLinePath({value:d});
if(c&&d)for(var e=0;e<c.length;e+=2){var b=c[e],m=c[e+1],n=d[e],l=d[e+1];"M"===b[0]&&"L"===m[0]&&"M"===n[0]&&"L"===l[0]&&f.push(b,m,l,["L",n[1],n[2]],["Z"])}return f};d.wrapGetPlotLinePath=function(a){var c=this.axis3D,d=this.chart,e=a.apply(this,[].slice.call(arguments,1));if("colorAxis"===this.coll||!d.chart3d||!d.is3d()||null===e)return e;var b=d.options.chart.options3d,m=this.isZAxis?d.plotWidth:b.depth;b=d.chart3d.frame3d;var n=e[0],p=e[1];e=[];"M"===n[0]&&"L"===p[0]&&(c=[c.swapZ({x:n[1],y:n[2],
z:0}),c.swapZ({x:n[1],y:n[2],z:m}),c.swapZ({x:p[1],y:p[2],z:0}),c.swapZ({x:p[1],y:p[2],z:m})],this.horiz?(this.isZAxis?(b.left.visible&&e.push(c[0],c[2]),b.right.visible&&e.push(c[1],c[3])):(b.front.visible&&e.push(c[0],c[2]),b.back.visible&&e.push(c[1],c[3])),b.top.visible&&e.push(c[0],c[1]),b.bottom.visible&&e.push(c[2],c[3])):(b.front.visible&&e.push(c[0],c[2]),b.back.visible&&e.push(c[1],c[3]),b.left.visible&&e.push(c[0],c[1]),b.right.visible&&e.push(c[2],c[3])),e=x(e,this.chart,!1));return d.renderer.toLineSegments(e)};
d.wrapGetSlotWidth=function(a,d){var e=this.chart,b=this.ticks,h=this.gridGroup;if(this.categories&&e.frameShapes&&e.is3d()&&h&&d&&d.label){h=h.element.childNodes[0].getBBox();var m=e.frameShapes.left.getBBox(),n=e.options.chart.options3d;e={x:e.plotWidth/2,y:e.plotHeight/2,z:n.depth/2,vd:c(n.depth,1)*c(n.viewDistance,0)};var p,l;n=d.pos;var g=b[n-1];b=b[n+1];0!==n&&g&&g.label&&g.label.xy&&(p=r({x:g.label.xy.x,y:g.label.xy.y,z:null},e,e.vd));b&&b.label&&b.label.xy&&(l=r({x:b.label.xy.x,y:b.label.xy.y,
z:null},e,e.vd));b={x:d.label.xy.x,y:d.label.xy.y,z:null};b=r(b,e,e.vd);return Math.abs(p?b.x-p.x:l?l.x-b.x:h.x-m.x)}return a.apply(this,[].slice.call(arguments,1))};d.wrapGetTitlePosition=function(a){var c=a.apply(this,[].slice.call(arguments,1));return this.axis3D?this.axis3D.fix3dPosition(c,!0):c};d.defaultOptions={labels:{position3d:"offset",skew3d:!1},title:{position3d:null,skew3d:null}};return d}()});C(b,"Core/Axis/ZAxis.js",[b["Core/Axis/Axis.js"],b["Core/Utilities.js"]],function(b,v){var g=
this&&this.__extends||function(){var d=function(c,a){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var d in c)c.hasOwnProperty(d)&&(a[d]=c[d])};return d(c,a)};return function(c,a){function b(){this.constructor=c}d(c,a);c.prototype=null===a?Object.create(a):(b.prototype=a.prototype,new b)}}(),u=v.addEvent,d=v.merge,x=v.pick,r=v.splat,w=function(){function d(){}d.compose=function(c){u(c,"afterGetAxes",d.onAfterGetAxes);c=c.prototype;c.addZAxis=
d.wrapAddZAxis;c.collectionsWithInit.zAxis=[c.addZAxis];c.collectionsWithUpdate.push("zAxis")};d.onAfterGetAxes=function(){var c=this,a=this.options;a=a.zAxis=r(a.zAxis||{});c.is3d()&&(c.zAxis=[],a.forEach(function(a,d){a.index=d;a.isX=!0;c.addZAxis(a).setScale()}))};d.wrapAddZAxis=function(c){return new t(this,c)};return d}(),t=function(b){function c(a,c){a=b.call(this,a,c)||this;a.isZAxis=!0;return a}g(c,b);c.prototype.getSeriesExtremes=function(){var a=this,c=a.chart;a.hasVisibleSeries=!1;a.dataMin=
a.dataMax=a.ignoreMinPadding=a.ignoreMaxPadding=void 0;a.stacking&&a.stacking.buildStacks();a.series.forEach(function(d){!d.visible&&c.options.chart&&c.options.chart.ignoreHiddenSeries||(a.hasVisibleSeries=!0,d=d.zData,d.length&&(a.dataMin=Math.min(x(a.dataMin,d[0]),Math.min.apply(null,d)),a.dataMax=Math.max(x(a.dataMax,d[0]),Math.max.apply(null,d))))})};c.prototype.setAxisSize=function(){var a=this.chart;b.prototype.setAxisSize.call(this);this.width=this.len=a.options.chart&&a.options.chart.options3d&&
a.options.chart.options3d.depth||0;this.right=a.chartWidth-this.width-this.left};c.prototype.setOptions=function(a){a=d({offset:0,lineWidth:0},a);b.prototype.setOptions.call(this,a);this.coll="zAxis"};c.ZChartComposition=w;return c}(b);return t});C(b,"Core/Chart/Chart3D.js",[b["Core/Axis/Axis.js"],b["Core/Axis/Axis3D.js"],b["Core/Chart/Chart.js"],b["Core/Animation/Fx.js"],b["Core/Globals.js"],b["Extensions/Math3D.js"],b["Core/Options.js"],b["Core/Utilities.js"],b["Core/Axis/ZAxis.js"]],function(b,
v,g,u,d,x,r,w,t){var p=x.perspective,c=x.shapeArea3D,a=r.defaultOptions,n=w.addEvent,m=w.isArray,z=w.merge,e=w.pick,h=w.wrap,q;(function(b){function f(a){this.is3d()&&"scatter"===a.options.type&&(a.options.type="scatter3d")}function q(){if(this.chart3d&&this.is3d()){var a=this.renderer,c=this.options.chart.options3d,b=this.chart3d.get3dFrame(),e=this.plotLeft,f=this.plotLeft+this.plotWidth,h=this.plotTop,l=this.plotTop+this.plotHeight;c=c.depth;var m=e-(b.left.visible?b.left.size:0),k=f+(b.right.visible?
b.right.size:0),n=h-(b.top.visible?b.top.size:0),p=l+(b.bottom.visible?b.bottom.size:0),q=0-(b.front.visible?b.front.size:0),g=c+(b.back.visible?b.back.size:0),r=this.hasRendered?"animate":"attr";this.chart3d.frame3d=b;this.frameShapes||(this.frameShapes={bottom:a.polyhedron().add(),top:a.polyhedron().add(),left:a.polyhedron().add(),right:a.polyhedron().add(),back:a.polyhedron().add(),front:a.polyhedron().add()});this.frameShapes.bottom[r]({"class":"highcharts-3d-frame highcharts-3d-frame-bottom",
zIndex:b.bottom.frontFacing?-1E3:1E3,faces:[{fill:d.color(b.bottom.color).brighten(.1).get(),vertexes:[{x:m,y:p,z:q},{x:k,y:p,z:q},{x:k,y:p,z:g},{x:m,y:p,z:g}],enabled:b.bottom.visible},{fill:d.color(b.bottom.color).brighten(.1).get(),vertexes:[{x:e,y:l,z:c},{x:f,y:l,z:c},{x:f,y:l,z:0},{x:e,y:l,z:0}],enabled:b.bottom.visible},{fill:d.color(b.bottom.color).brighten(-.1).get(),vertexes:[{x:m,y:p,z:q},{x:m,y:p,z:g},{x:e,y:l,z:c},{x:e,y:l,z:0}],enabled:b.bottom.visible&&!b.left.visible},{fill:d.color(b.bottom.color).brighten(-.1).get(),
vertexes:[{x:k,y:p,z:g},{x:k,y:p,z:q},{x:f,y:l,z:0},{x:f,y:l,z:c}],enabled:b.bottom.visible&&!b.right.visible},{fill:d.color(b.bottom.color).get(),vertexes:[{x:k,y:p,z:q},{x:m,y:p,z:q},{x:e,y:l,z:0},{x:f,y:l,z:0}],enabled:b.bottom.visible&&!b.front.visible},{fill:d.color(b.bottom.color).get(),vertexes:[{x:m,y:p,z:g},{x:k,y:p,z:g},{x:f,y:l,z:c},{x:e,y:l,z:c}],enabled:b.bottom.visible&&!b.back.visible}]});this.frameShapes.top[r]({"class":"highcharts-3d-frame highcharts-3d-frame-top",zIndex:b.top.frontFacing?
-1E3:1E3,faces:[{fill:d.color(b.top.color).brighten(.1).get(),vertexes:[{x:m,y:n,z:g},{x:k,y:n,z:g},{x:k,y:n,z:q},{x:m,y:n,z:q}],enabled:b.top.visible},{fill:d.color(b.top.color).brighten(.1).get(),vertexes:[{x:e,y:h,z:0},{x:f,y:h,z:0},{x:f,y:h,z:c},{x:e,y:h,z:c}],enabled:b.top.visible},{fill:d.color(b.top.color).brighten(-.1).get(),vertexes:[{x:m,y:n,z:g},{x:m,y:n,z:q},{x:e,y:h,z:0},{x:e,y:h,z:c}],enabled:b.top.visible&&!b.left.visible},{fill:d.color(b.top.color).brighten(-.1).get(),vertexes:[{x:k,
y:n,z:q},{x:k,y:n,z:g},{x:f,y:h,z:c},{x:f,y:h,z:0}],enabled:b.top.visible&&!b.right.visible},{fill:d.color(b.top.color).get(),vertexes:[{x:m,y:n,z:q},{x:k,y:n,z:q},{x:f,y:h,z:0},{x:e,y:h,z:0}],enabled:b.top.visible&&!b.front.visible},{fill:d.color(b.top.color).get(),vertexes:[{x:k,y:n,z:g},{x:m,y:n,z:g},{x:e,y:h,z:c},{x:f,y:h,z:c}],enabled:b.top.visible&&!b.back.visible}]});this.frameShapes.left[r]({"class":"highcharts-3d-frame highcharts-3d-frame-left",zIndex:b.left.frontFacing?-1E3:1E3,faces:[{fill:d.color(b.left.color).brighten(.1).get(),
vertexes:[{x:m,y:p,z:q},{x:e,y:l,z:0},{x:e,y:l,z:c},{x:m,y:p,z:g}],enabled:b.left.visible&&!b.bottom.visible},{fill:d.color(b.left.color).brighten(.1).get(),vertexes:[{x:m,y:n,z:g},{x:e,y:h,z:c},{x:e,y:h,z:0},{x:m,y:n,z:q}],enabled:b.left.visible&&!b.top.visible},{fill:d.color(b.left.color).brighten(-.1).get(),vertexes:[{x:m,y:p,z:g},{x:m,y:n,z:g},{x:m,y:n,z:q},{x:m,y:p,z:q}],enabled:b.left.visible},{fill:d.color(b.left.color).brighten(-.1).get(),vertexes:[{x:e,y:h,z:c},{x:e,y:l,z:c},{x:e,y:l,z:0},
{x:e,y:h,z:0}],enabled:b.left.visible},{fill:d.color(b.left.color).get(),vertexes:[{x:m,y:p,z:q},{x:m,y:n,z:q},{x:e,y:h,z:0},{x:e,y:l,z:0}],enabled:b.left.visible&&!b.front.visible},{fill:d.color(b.left.color).get(),vertexes:[{x:m,y:n,z:g},{x:m,y:p,z:g},{x:e,y:l,z:c},{x:e,y:h,z:c}],enabled:b.left.visible&&!b.back.visible}]});this.frameShapes.right[r]({"class":"highcharts-3d-frame highcharts-3d-frame-right",zIndex:b.right.frontFacing?-1E3:1E3,faces:[{fill:d.color(b.right.color).brighten(.1).get(),
vertexes:[{x:k,y:p,z:g},{x:f,y:l,z:c},{x:f,y:l,z:0},{x:k,y:p,z:q}],enabled:b.right.visible&&!b.bottom.visible},{fill:d.color(b.right.color).brighten(.1).get(),vertexes:[{x:k,y:n,z:q},{x:f,y:h,z:0},{x:f,y:h,z:c},{x:k,y:n,z:g}],enabled:b.right.visible&&!b.top.visible},{fill:d.color(b.right.color).brighten(-.1).get(),vertexes:[{x:f,y:h,z:0},{x:f,y:l,z:0},{x:f,y:l,z:c},{x:f,y:h,z:c}],enabled:b.right.visible},{fill:d.color(b.right.color).brighten(-.1).get(),vertexes:[{x:k,y:p,z:q},{x:k,y:n,z:q},{x:k,y:n,
z:g},{x:k,y:p,z:g}],enabled:b.right.visible},{fill:d.color(b.right.color).get(),vertexes:[{x:k,y:n,z:q},{x:k,y:p,z:q},{x:f,y:l,z:0},{x:f,y:h,z:0}],enabled:b.right.visible&&!b.front.visible},{fill:d.color(b.right.color).get(),vertexes:[{x:k,y:p,z:g},{x:k,y:n,z:g},{x:f,y:h,z:c},{x:f,y:l,z:c}],enabled:b.right.visible&&!b.back.visible}]});this.frameShapes.back[r]({"class":"highcharts-3d-frame highcharts-3d-frame-back",zIndex:b.back.frontFacing?-1E3:1E3,faces:[{fill:d.color(b.back.color).brighten(.1).get(),
vertexes:[{x:k,y:p,z:g},{x:m,y:p,z:g},{x:e,y:l,z:c},{x:f,y:l,z:c}],enabled:b.back.visible&&!b.bottom.visible},{fill:d.color(b.back.color).brighten(.1).get(),vertexes:[{x:m,y:n,z:g},{x:k,y:n,z:g},{x:f,y:h,z:c},{x:e,y:h,z:c}],enabled:b.back.visible&&!b.top.visible},{fill:d.color(b.back.color).brighten(-.1).get(),vertexes:[{x:m,y:p,z:g},{x:m,y:n,z:g},{x:e,y:h,z:c},{x:e,y:l,z:c}],enabled:b.back.visible&&!b.left.visible},{fill:d.color(b.back.color).brighten(-.1).get(),vertexes:[{x:k,y:n,z:g},{x:k,y:p,
z:g},{x:f,y:l,z:c},{x:f,y:h,z:c}],enabled:b.back.visible&&!b.right.visible},{fill:d.color(b.back.color).get(),vertexes:[{x:e,y:h,z:c},{x:f,y:h,z:c},{x:f,y:l,z:c},{x:e,y:l,z:c}],enabled:b.back.visible},{fill:d.color(b.back.color).get(),vertexes:[{x:m,y:p,z:g},{x:k,y:p,z:g},{x:k,y:n,z:g},{x:m,y:n,z:g}],enabled:b.back.visible}]});this.frameShapes.front[r]({"class":"highcharts-3d-frame highcharts-3d-frame-front",zIndex:b.front.frontFacing?-1E3:1E3,faces:[{fill:d.color(b.front.color).brighten(.1).get(),
vertexes:[{x:m,y:p,z:q},{x:k,y:p,z:q},{x:f,y:l,z:0},{x:e,y:l,z:0}],enabled:b.front.visible&&!b.bottom.visible},{fill:d.color(b.front.color).brighten(.1).get(),vertexes:[{x:k,y:n,z:q},{x:m,y:n,z:q},{x:e,y:h,z:0},{x:f,y:h,z:0}],enabled:b.front.visible&&!b.top.visible},{fill:d.color(b.front.color).brighten(-.1).get(),vertexes:[{x:m,y:n,z:q},{x:m,y:p,z:q},{x:e,y:l,z:0},{x:e,y:h,z:0}],enabled:b.front.visible&&!b.left.visible},{fill:d.color(b.front.color).brighten(-.1).get(),vertexes:[{x:k,y:p,z:q},{x:k,
y:n,z:q},{x:f,y:h,z:0},{x:f,y:l,z:0}],enabled:b.front.visible&&!b.right.visible},{fill:d.color(b.front.color).get(),vertexes:[{x:f,y:h,z:0},{x:e,y:h,z:0},{x:e,y:l,z:0},{x:f,y:l,z:0}],enabled:b.front.visible},{fill:d.color(b.front.color).get(),vertexes:[{x:k,y:p,z:q},{x:m,y:p,z:q},{x:m,y:n,z:q},{x:k,y:n,z:q}],enabled:b.front.visible}]})}}function g(){this.styledMode&&(this.renderer.definition({tagName:"style",textContent:".highcharts-3d-top{filter: url(#highcharts-brighter)}\n.highcharts-3d-side{filter: url(#highcharts-darker)}\n"}),
[{name:"darker",slope:.6},{name:"brighter",slope:1.4}].forEach(function(a){this.renderer.definition({tagName:"filter",id:"highcharts-"+a.name,children:[{tagName:"feComponentTransfer",children:[{tagName:"feFuncR",type:"linear",slope:a.slope},{tagName:"feFuncG",type:"linear",slope:a.slope},{tagName:"feFuncB",type:"linear",slope:a.slope}]}]})},this))}function r(){var a=this.options;this.is3d()&&(a.series||[]).forEach(function(c){"scatter"===(c.type||a.chart.type||a.chart.defaultSeriesType)&&(c.type=
"scatter3d")})}function l(){var a=this.options.chart.options3d;if(this.chart3d&&this.is3d()){a&&(a.alpha=a.alpha%360+(0<=a.alpha?0:360),a.beta=a.beta%360+(0<=a.beta?0:360));var c=this.inverted,b=this.clipBox,d=this.margin;b[c?"y":"x"]=-(d[3]||0);b[c?"x":"y"]=-(d[0]||0);b[c?"height":"width"]=this.chartWidth+(d[3]||0)+(d[1]||0);b[c?"width":"height"]=this.chartHeight+(d[0]||0)+(d[2]||0);this.scale3d=1;!0===a.fitToPlot&&(this.scale3d=this.chart3d.getScale(a.depth));this.chart3d.frame3d=this.chart3d.get3dFrame()}}
function t(){this.is3d()&&(this.isDirtyBox=!0)}function k(){this.chart3d&&this.is3d()&&(this.chart3d.frame3d=this.chart3d.get3dFrame())}function u(){this.chart3d||(this.chart3d=new L(this))}function w(a){return this.is3d()||a.apply(this,[].slice.call(arguments,1))}function x(a){var c=this.series.length;if(this.is3d())for(;c--;)a=this.series[c],a.translate(),a.render();else a.call(this)}function v(a){a.apply(this,[].slice.call(arguments,1));this.is3d()&&(this.container.className+=" highcharts-3d-chart")}
var L=function(){function a(a){this.frame3d=void 0;this.chart=a}a.prototype.get3dFrame=function(){var a=this.chart,b=a.options.chart.options3d,d=b.frame,f=a.plotLeft,h=a.plotLeft+a.plotWidth,l=a.plotTop,m=a.plotTop+a.plotHeight,k=b.depth,n=function(b){b=c(b,a);return.5<b?1:-.5>b?-1:0},q=n([{x:f,y:m,z:k},{x:h,y:m,z:k},{x:h,y:m,z:0},{x:f,y:m,z:0}]),g=n([{x:f,y:l,z:0},{x:h,y:l,z:0},{x:h,y:l,z:k},{x:f,y:l,z:k}]),r=n([{x:f,y:l,z:0},{x:f,y:l,z:k},{x:f,y:m,z:k},{x:f,y:m,z:0}]),t=n([{x:h,y:l,z:k},{x:h,y:l,
z:0},{x:h,y:m,z:0},{x:h,y:m,z:k}]),u=n([{x:f,y:m,z:0},{x:h,y:m,z:0},{x:h,y:l,z:0},{x:f,y:l,z:0}]);n=n([{x:f,y:l,z:k},{x:h,y:l,z:k},{x:h,y:m,z:k},{x:f,y:m,z:k}]);var H=!1,z=!1,D=!1,w=!1;[].concat(a.xAxis,a.yAxis,a.zAxis).forEach(function(a){a&&(a.horiz?a.opposite?z=!0:H=!0:a.opposite?w=!0:D=!0)});var x=function(a,c,b){for(var d=["size","color","visible"],f={},h=0;h<d.length;h++)for(var l=d[h],m=0;m<a.length;m++)if("object"===typeof a[m]){var k=a[m][l];if("undefined"!==typeof k&&null!==k){f[l]=k;break}}a=
b;!0===f.visible||!1===f.visible?a=f.visible:"auto"===f.visible&&(a=0<c);return{size:e(f.size,1),color:e(f.color,"none"),frontFacing:0<c,visible:a}};d={axes:{},bottom:x([d.bottom,d.top,d],q,H),top:x([d.top,d.bottom,d],g,z),left:x([d.left,d.right,d.side,d],r,D),right:x([d.right,d.left,d.side,d],t,w),back:x([d.back,d.front,d],n,!0),front:x([d.front,d.back,d],u,!1)};"auto"===b.axisLabelPosition?(t=function(a,c){return a.visible!==c.visible||a.visible&&c.visible&&a.frontFacing!==c.frontFacing},b=[],t(d.left,
d.front)&&b.push({y:(l+m)/2,x:f,z:0,xDir:{x:1,y:0,z:0}}),t(d.left,d.back)&&b.push({y:(l+m)/2,x:f,z:k,xDir:{x:0,y:0,z:-1}}),t(d.right,d.front)&&b.push({y:(l+m)/2,x:h,z:0,xDir:{x:0,y:0,z:1}}),t(d.right,d.back)&&b.push({y:(l+m)/2,x:h,z:k,xDir:{x:-1,y:0,z:0}}),q=[],t(d.bottom,d.front)&&q.push({x:(f+h)/2,y:m,z:0,xDir:{x:1,y:0,z:0}}),t(d.bottom,d.back)&&q.push({x:(f+h)/2,y:m,z:k,xDir:{x:-1,y:0,z:0}}),g=[],t(d.top,d.front)&&g.push({x:(f+h)/2,y:l,z:0,xDir:{x:1,y:0,z:0}}),t(d.top,d.back)&&g.push({x:(f+h)/
2,y:l,z:k,xDir:{x:-1,y:0,z:0}}),r=[],t(d.bottom,d.left)&&r.push({z:(0+k)/2,y:m,x:f,xDir:{x:0,y:0,z:-1}}),t(d.bottom,d.right)&&r.push({z:(0+k)/2,y:m,x:h,xDir:{x:0,y:0,z:1}}),m=[],t(d.top,d.left)&&m.push({z:(0+k)/2,y:l,x:f,xDir:{x:0,y:0,z:-1}}),t(d.top,d.right)&&m.push({z:(0+k)/2,y:l,x:h,xDir:{x:0,y:0,z:1}}),f=function(c,b,d){if(0===c.length)return null;if(1===c.length)return c[0];for(var e=0,f=p(c,a,!1),h=1;h<f.length;h++)d*f[h][b]>d*f[e][b]?e=h:d*f[h][b]===d*f[e][b]&&f[h].z<f[e].z&&(e=h);return c[e]},
d.axes={y:{left:f(b,"x",-1),right:f(b,"x",1)},x:{top:f(g,"y",-1),bottom:f(q,"y",1)},z:{top:f(m,"y",-1),bottom:f(r,"y",1)}}):d.axes={y:{left:{x:f,z:0,xDir:{x:1,y:0,z:0}},right:{x:h,z:0,xDir:{x:0,y:0,z:1}}},x:{top:{y:l,z:0,xDir:{x:1,y:0,z:0}},bottom:{y:m,z:0,xDir:{x:1,y:0,z:0}}},z:{top:{x:D?h:f,y:l,xDir:D?{x:0,y:0,z:1}:{x:0,y:0,z:-1}},bottom:{x:D?h:f,y:m,xDir:D?{x:0,y:0,z:1}:{x:0,y:0,z:-1}}}};return d};a.prototype.getScale=function(a){var c=this.chart,b=c.plotLeft,d=c.plotWidth+b,e=c.plotTop,f=c.plotHeight+
e,h=b+c.plotWidth/2,m=e+c.plotHeight/2,l=Number.MAX_VALUE,k=-Number.MAX_VALUE,n=Number.MAX_VALUE,q=-Number.MAX_VALUE,g=1;var r=[{x:b,y:e,z:0},{x:b,y:e,z:a}];[0,1].forEach(function(a){r.push({x:d,y:r[a].y,z:r[a].z})});[0,1,2,3].forEach(function(a){r.push({x:r[a].x,y:f,z:r[a].z})});r=p(r,c,!1);r.forEach(function(a){l=Math.min(l,a.x);k=Math.max(k,a.x);n=Math.min(n,a.y);q=Math.max(q,a.y)});b>l&&(g=Math.min(g,1-Math.abs((b+h)/(l+h))%1));d<k&&(g=Math.min(g,(d-h)/(k-h)));e>n&&(g=0>n?Math.min(g,(e+m)/(-n+
e+m)):Math.min(g,1-(e+m)/(n+m)%1));f<q&&(g=Math.min(g,Math.abs((f-m)/(q-m))));return g};return a}();b.Composition=L;b.defaultOptions={chart:{options3d:{enabled:!1,alpha:0,beta:0,depth:100,fitToPlot:!0,viewDistance:25,axisLabelPosition:null,frame:{visible:"default",size:1,bottom:{},top:{},left:{},right:{},back:{},front:{}}}}};b.compose=function(c,e){var p=c.prototype;e=e.prototype;p.is3d=function(){return this.options.chart.options3d&&this.options.chart.options3d.enabled};p.propsRequireDirtyBox.push("chart.options3d");
p.propsRequireUpdateSeries.push("chart.options3d");e.matrixSetter=function(){if(1>this.pos&&(m(this.start)||m(this.end))){var a=this.start||[1,0,0,1,0,0],c=this.end||[1,0,0,1,0,0];var b=[];for(var d=0;6>d;d++)b.push(this.pos*c[d]+(1-this.pos)*a[d])}else b=this.end;this.elem.attr(this.prop,b,null,!0)};z(!0,a,b.defaultOptions);n(c,"init",u);n(c,"addSeries",f);n(c,"afterDrawChartBox",q);n(c,"afterGetContainer",g);n(c,"afterInit",r);n(c,"afterSetChartSize",l);n(c,"beforeRedraw",t);n(c,"beforeRender",
k);h(d.Chart.prototype,"isInsidePlot",w);h(c,"renderSeries",x);h(c,"setClassName",v)}})(q||(q={}));q.compose(g,u);t.ZChartComposition.compose(g);v.compose(b);"";return q});C(b,"Core/Series/Series3D.js",[b["Series/Line/LineSeries.js"],b["Extensions/Math3D.js"],b["Core/Utilities.js"]],function(b,v,g){var u=this&&this.__extends||function(){var b=function(c,a){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=
c[b])};return b(c,a)};return function(c,a){function d(){this.constructor=c}b(c,a);c.prototype=null===a?Object.create(a):(d.prototype=a.prototype,new d)}}(),d=v.perspective;v=g.addEvent;var x=g.extend,r=g.merge,w=g.pick,t=g.isNumber;g=function(g){function c(){return null!==g&&g.apply(this,arguments)||this}u(c,g);c.prototype.translate=function(){g.prototype.translate.apply(this,arguments);this.chart.is3d()&&this.translate3dPoints()};c.prototype.translate3dPoints=function(){var a=this.options,c=this.chart,
b=w(this.zAxis,c.options.zAxis[0]),g=[],e,h=[];this.zPadding=(a.stacking?t(a.stack)?a.stack:0:this.index||0)*(a.depth||0+(a.groupZPadding||1));for(e=0;e<this.data.length;e++){a=this.data[e];if(b&&b.translate){var q=b.logarithmic&&b.val2lin?b.val2lin(a.z):a.z;a.plotZ=b.translate(q);a.isInside=a.isInside?q>=b.min&&q<=b.max:!1}else a.plotZ=this.zPadding;a.axisXpos=a.plotX;a.axisYpos=a.plotY;a.axisZpos=a.plotZ;g.push({x:a.plotX,y:a.plotY,z:a.plotZ});h.push(a.plotX||0)}this.rawPointsX=h;c=d(g,c,!0);for(e=
0;e<this.data.length;e++)a=this.data[e],b=c[e],a.plotX=b.x,a.plotY=b.y,a.plotZ=b.z};c.defaultOptions=r(b.defaultOptions);return c}(b);v(b,"afterTranslate",function(){this.chart.is3d()&&this.translate3dPoints()});x(b.prototype,{translate3dPoints:g.prototype.translate3dPoints});return g});C(b,"Series/Column3D/Column3DComposition.js",[b["Core/Series/Series.js"],b["Series/Column/ColumnSeries.js"],b["Core/Globals.js"],b["Series/Line/LineSeries.js"],b["Extensions/Math3D.js"],b["Extensions/Stacking.js"],
b["Core/Utilities.js"]],function(b,v,g,u,d,x,r){function w(a,c){var b=a.series,d={},e,h=1;b.forEach(function(a){e=z(a.options.stack,c?0:b.length-1-a.index);d[e]?d[e].series.push(a):(d[e]={series:[a],position:h},h++)});d.totalStacks=h+1;return d}function t(a){var c=a.apply(this,[].slice.call(arguments,1));this.chart.is3d&&this.chart.is3d()&&(c.stroke=this.options.edgeColor||c.fill,c["stroke-width"]=z(this.options.edgeWidth,1));return c}function p(a,c,b){var d=this.chart.is3d&&this.chart.is3d();d&&
(this.options.inactiveOtherPoints=!0);a.call(this,c,b);d&&(this.options.inactiveOtherPoints=!1)}function c(a){for(var c=[],b=1;b<arguments.length;b++)c[b-1]=arguments[b];return this.series.chart.is3d()?this.graphic&&"g"!==this.graphic.element.nodeName:a.apply(this,c)}var a=v.prototype,n=g.svg,m=d.perspective;g=r.addEvent;var z=r.pick;r=r.wrap;r(a,"translate",function(a){a.apply(this,[].slice.call(arguments,1));this.chart.is3d()&&this.translate3dShapes()});r(u.prototype,"justifyDataLabel",function(a){return arguments[2].outside3dPlot?
!1:a.apply(this,[].slice.call(arguments,1))});a.translate3dPoints=function(){};a.translate3dShapes=function(){var a=this,c=a.chart,b=a.options,d=b.depth,n=(b.stacking?b.stack||0:a.index)*(d+(b.groupZPadding||1)),g=a.borderWidth%2?.5:0,p;c.inverted&&!a.yAxis.reversed&&(g*=-1);!1!==b.grouping&&(n=0);n+=b.groupZPadding||1;a.data.forEach(function(b){b.outside3dPlot=null;if(null!==b.y){var e=b.shapeArgs,f=b.tooltipPos,h;[["x","width"],["y","height"]].forEach(function(c){h=e[c[0]]-g;0>h&&(e[c[1]]+=e[c[0]]+
g,e[c[0]]=-g,h=0);h+e[c[1]]>a[c[0]+"Axis"].len&&0!==e[c[1]]&&(e[c[1]]=a[c[0]+"Axis"].len-e[c[0]]);if(0!==e[c[1]]&&(e[c[0]]>=a[c[0]+"Axis"].len||e[c[0]]+e[c[1]]<=g)){for(var d in e)e[d]=0;b.outside3dPlot=!0}});"rect"===b.shapeType&&(b.shapeType="cuboid");e.z=n;e.depth=d;e.insidePlotArea=!0;p={x:e.x+e.width/2,y:e.y,z:n+d/2};c.inverted&&(p.x=e.height,p.y=b.clientX);b.plot3d=m([p],c,!0,!1)[0];f=m([{x:f[0],y:f[1],z:n+d/2}],c,!0,!1)[0];b.tooltipPos=[f.x,f.y]}});a.z=n};r(a,"animate",function(a){if(this.chart.is3d()){var c=
arguments[1],b=this.yAxis,d=this,e=this.yAxis.reversed;n&&(c?d.data.forEach(function(a){null!==a.y&&(a.height=a.shapeArgs.height,a.shapey=a.shapeArgs.y,a.shapeArgs.height=1,e||(a.shapeArgs.y=a.stackY?a.plotY+b.translate(a.stackY):a.plotY+(a.negative?-a.height:a.height)))}):(d.data.forEach(function(a){null!==a.y&&(a.shapeArgs.height=a.height,a.shapeArgs.y=a.shapey,a.graphic&&a.graphic.animate(a.shapeArgs,d.options.animation))}),this.drawDataLabels()))}else a.apply(this,[].slice.call(arguments,1))});
r(a,"plotGroup",function(a,c,b,d,m,n){"dataLabelsGroup"!==c&&this.chart.is3d()&&(this[c]&&delete this[c],n&&(this.chart.columnGroup||(this.chart.columnGroup=this.chart.renderer.g("columnGroup").add(n)),this[c]=this.chart.columnGroup,this.chart.columnGroup.attr(this.getPlotBox()),this[c].survive=!0,"group"===c||"markerGroup"===c))&&(arguments[3]="visible");return a.apply(this,Array.prototype.slice.call(arguments,1))});r(a,"setVisible",function(a,c){var b=this,d;b.chart.is3d()&&b.data.forEach(function(a){d=
(a.visible=a.options.visible=c="undefined"===typeof c?!z(b.visible,a.visible):c)?"visible":"hidden";b.options.data[b.data.indexOf(a)]=a.options;a.graphic&&a.graphic.attr({visibility:d})});a.apply(this,Array.prototype.slice.call(arguments,1))});g(v,"afterInit",function(){if(this.chart.is3d()){var a=this.options,c=a.grouping,b=a.stacking,d=z(this.yAxis.options.reversedStacks,!0),m=0;if("undefined"===typeof c||c){c=w(this.chart,b);m=a.stack||0;for(b=0;b<c[m].series.length&&c[m].series[b]!==this;b++);
m=10*(c.totalStacks-c[m].position)+(d?b:-b);this.xAxis.reversed||(m=10*c.totalStacks-m)}a.depth=a.depth||25;this.z=this.z||0;a.zIndex=m}});r(a,"pointAttribs",t);r(a,"setState",p);r(a.pointClass.prototype,"hasNewShapeType",c);b.seriesTypes.columnRange&&(g=b.seriesTypes.columnrange.prototype,r(g,"pointAttribs",t),r(g,"setState",p),r(g.pointClass.prototype,"hasNewShapeType",c),g.plotGroup=a.plotGroup,g.setVisible=a.setVisible);r(u.prototype,"alignDataLabel",function(a,c,b,d,n){var e=this.chart;d.outside3dPlot=
c.outside3dPlot;if(e.is3d()&&this.is("column")){var f=this.options,h=z(d.inside,!!this.options.stacking),l=e.options.chart.options3d,g=c.pointWidth/2||0;f={x:n.x+g,y:n.y,z:this.z+f.depth/2};e.inverted&&(h&&(n.width=0,f.x+=c.shapeArgs.height/2),90<=l.alpha&&270>=l.alpha&&(f.y+=c.shapeArgs.width));f=m([f],e,!0,!1)[0];n.x=f.x-g;n.y=c.outside3dPlot?-9E9:f.y}a.apply(this,[].slice.call(arguments,1))});r(x.prototype,"getStackBox",function(a,c,d,f,n,g,p,r){var e=a.apply(this,[].slice.call(arguments,1));if(c.is3d()&&
d.base){var h=+d.base.split(",")[0],k=c.series[h];h=c.options.chart.options3d;k&&k instanceof b.seriesTypes.column&&(k={x:e.x+(c.inverted?p:g/2),y:e.y,z:k.options.depth/2},c.inverted&&(e.width=0,90<=h.alpha&&270>=h.alpha&&(k.y+=g)),k=m([k],c,!0,!1)[0],e.x=k.x-g/2,e.y=k.y)}return e});"";return v});C(b,"Series/Pie3D/Pie3DPoint.js",[b["Core/Series/Series.js"]],function(b){var v=this&&this.__extends||function(){var b=function(d,g){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,d){b.__proto__=
d}||function(b,d){for(var g in d)d.hasOwnProperty(g)&&(b[g]=d[g])};return b(d,g)};return function(d,g){function r(){this.constructor=d}b(d,g);d.prototype=null===g?Object.create(g):(r.prototype=g.prototype,new r)}}();b=b.seriesTypes.pie.prototype.pointClass;var g=b.prototype.haloPath;return function(b){function d(){var d=null!==b&&b.apply(this,arguments)||this;d.series=void 0;return d}v(d,b);d.prototype.haloPath=function(){return this.series.chart.is3d()?[]:g.apply(this,arguments)};return d}(b)});
C(b,"Series/Pie3D/Pie3DSeries.js",[b["Core/Series/Series.js"],b["Core/Globals.js"],b["Series/Pie3D/Pie3DPoint.js"],b["Core/Utilities.js"]],function(b,v,g,u){var d=this&&this.__extends||function(){var b=function(d,c){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return b(d,c)};return function(d,c){function a(){this.constructor=d}b(d,c);d.prototype=null===c?Object.create(c):(a.prototype=c.prototype,
new a)}}(),x=v.deg2rad,r=v.svg;v=u.extend;var w=u.pick;b=function(b){function g(){return null!==b&&b.apply(this,arguments)||this}d(g,b);g.prototype.addPoint=function(){b.prototype.addPoint.apply(this,arguments);this.chart.is3d()&&this.update(this.userOptions,!0)};g.prototype.animate=function(c){if(this.chart.is3d()){var a=this.options.animation;var d=this.center;var g=this.group,p=this.markerGroup;r&&(!0===a&&(a={}),c?(g.oldtranslateX=w(g.oldtranslateX,g.translateX),g.oldtranslateY=w(g.oldtranslateY,
g.translateY),d={translateX:d[0],translateY:d[1],scaleX:.001,scaleY:.001},g.attr(d),p&&(p.attrSetters=g.attrSetters,p.attr(d))):(d={translateX:g.oldtranslateX,translateY:g.oldtranslateY,scaleX:1,scaleY:1},g.animate(d,a),p&&p.animate(d,a)))}else b.prototype.animate.apply(this,arguments)};g.prototype.drawDataLabels=function(){if(this.chart.is3d()){var c=this.chart.options.chart.options3d;this.data.forEach(function(a){var b=a.shapeArgs,d=b.r,g=(b.start+b.end)/2;a=a.labelPosition;var e=a.connectorPosition,
h=-d*(1-Math.cos((b.alpha||c.alpha)*x))*Math.sin(g),p=d*(Math.cos((b.beta||c.beta)*x)-1)*Math.cos(g);[a.natural,e.breakAt,e.touchingSliceAt].forEach(function(a){a.x+=p;a.y+=h})})}b.prototype.drawDataLabels.apply(this,arguments)};g.prototype.pointAttribs=function(c){var a=b.prototype.pointAttribs.apply(this,arguments),d=this.options;this.chart.is3d()&&!this.chart.styledMode&&(a.stroke=d.edgeColor||c.color||this.color,a["stroke-width"]=w(d.edgeWidth,1));return a};g.prototype.translate=function(){b.prototype.translate.apply(this,
arguments);if(this.chart.is3d()){var c=this,a=c.options,d=a.depth||0,g=c.chart.options.chart.options3d,p=g.alpha,e=g.beta,h=a.stacking?(a.stack||0)*d:c._i*d;h+=d/2;!1!==a.grouping&&(h=0);c.data.forEach(function(b){var f=b.shapeArgs;b.shapeType="arc3d";f.z=h;f.depth=.75*d;f.alpha=p;f.beta=e;f.center=c.center;f=(f.end+f.start)/2;b.slicedTranslation={translateX:Math.round(Math.cos(f)*a.slicedOffset*Math.cos(p*x)),translateY:Math.round(Math.sin(f)*a.slicedOffset*Math.cos(p*x))}})}};return g}(b.seriesTypes.pie);
v(b,{pointClass:g});"";return b});C(b,"Series/Pie3D/Pie3DComposition.js",[b["Core/Series/Series.js"],b["Series/Pie3D/Pie3DPoint.js"],b["Series/Pie3D/Pie3DSeries.js"]],function(b,v,g){b.seriesTypes.pie.prototype.pointClass.prototype.haloPath=v.prototype.haloPath;b.seriesTypes.pie=g});C(b,"Series/Scatter3D/Scatter3DPoint.js",[b["Series/Scatter/ScatterSeries.js"]],function(b){var v=this&&this.__extends||function(){var b=function(g,d){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,
d){b.__proto__=d}||function(b,d){for(var g in d)d.hasOwnProperty(g)&&(b[g]=d[g])};return b(g,d)};return function(g,d){function u(){this.constructor=g}b(g,d);g.prototype=null===d?Object.create(d):(u.prototype=d.prototype,new u)}}();return function(b){function g(){var d=null!==b&&b.apply(this,arguments)||this;d.options=void 0;d.series=void 0;return d}v(g,b);g.prototype.applyOptions=function(){b.prototype.applyOptions.apply(this,arguments);"undefined"===typeof this.z&&(this.z=0);return this};return g}(b.prototype.pointClass)});
C(b,"Series/Scatter3D/Scatter3DSeries.js",[b["Core/Series/Series.js"],b["Series/Scatter3D/Scatter3DPoint.js"],b["Series/Scatter/ScatterSeries.js"],b["Extensions/Math3D.js"],b["Core/Utilities.js"]],function(b,v,g,u,d){var x=this&&this.__extends||function(){var b=function(d,c){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return b(d,c)};return function(d,c){function a(){this.constructor=d}b(d,c);
d.prototype=null===c?Object.create(c):(a.prototype=c.prototype,new a)}}(),r=u.pointCameraDistance;u=d.extend;var w=d.merge;d=function(b){function d(){var c=null!==b&&b.apply(this,arguments)||this;c.data=void 0;c.options=void 0;c.points=void 0;return c}x(d,b);d.prototype.pointAttribs=function(c){var a=b.prototype.pointAttribs.apply(this,arguments);this.chart.is3d()&&c&&(a.zIndex=r(c,this.chart));return a};d.defaultOptions=w(g.defaultOptions,{tooltip:{pointFormat:"x: <b>{point.x}</b><br/>y: <b>{point.y}</b><br/>z: <b>{point.z}</b><br/>"}});
return d}(g);u(d.prototype,{axisTypes:["xAxis","yAxis","zAxis"],directTouch:!0,parallelArrays:["x","y","z"],pointArrayMap:["x","y","z"],pointClass:v});b.registerSeriesType("scatter3d",d);"";return d});C(b,"Series/Area3DSeries.js",[b["Series/Line/LineSeries.js"],b["Core/Series/Series.js"],b["Extensions/Math3D.js"],b["Core/Utilities.js"]],function(b,v,g,u){var d=g.perspective,x=u.pick;g=u.wrap;g(v.seriesTypes.area.prototype,"getGraphPath",function(g){var r=g.apply(this,[].slice.call(arguments,1));if(!this.chart.is3d())return r;
var t=b.prototype.getGraphPath,p=this.options;var c=[];var a=[],n,m=x(p.connectNulls,"percent"===p.stacking),u=Math.round(this.yAxis.getThreshold(p.threshold));if(this.rawPointsX)for(n=0;n<this.points.length;n++)c.push({x:this.rawPointsX[n],y:p.stacking?this.points[n].yBottom:u,z:this.zPadding});this.chart.options&&this.chart.options.chart&&(p=this.chart.options.chart.options3d,c=d(c,this.chart,!0).map(function(a){return{plotX:a.x,plotY:a.y,plotZ:a.z}}),this.group&&p&&p.depth&&p.beta&&(this.markerGroup&&
(this.markerGroup.add(this.group),this.markerGroup.attr({translateX:0,translateY:0})),this.group.attr({zIndex:Math.max(1,270<p.beta||90>p.beta?p.depth-Math.round(this.zPadding||0):Math.round(this.zPadding||0))})));c.reversed=!0;c=t.call(this,c,!0,!0);c[0]&&"M"===c[0][0]&&(c[0]=["L",c[0][1],c[0][2]]);this.areaPath&&(c=this.areaPath.splice(0,this.areaPath.length/2).concat(c),c.xMap=this.areaPath.xMap,this.areaPath=c,t.call(this,a,!1,m));return r})});C(b,"masters/highcharts-3d.src.js",[],function(){})});
//# sourceMappingURL=highcharts-3d.js.map