/*
 Highcharts JS v8.2.2 (2020-12-12)

 (c) 2009-2018 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(e){"object"===typeof module&&module.exports?(e["default"]=e,module.exports=e):"function"===typeof define&&define.amd?define("highcharts/highcharts-more",["highcharts"],function(z){e(z);e.Highcharts=z;return e}):e("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(e){function z(e,d,f,c){e.hasOwnProperty(d)||(e[d]=c.apply(null,f))}e=e?e._modules:{};z(e,"Extensions/Pane.js",[e["Core/Chart/Chart.js"],e["Core/Globals.js"],e["Core/Color/Palette.js"],e["Core/Pointer.js"],e["Core/Utilities.js"],
e["Mixins/CenteredSeries.js"]],function(e,d,f,c,a,r){function k(b,a,h){return Math.sqrt(Math.pow(b-h[0],2)+Math.pow(a-h[1],2))<=h[2]/2}var v=a.addEvent,p=a.extend,w=a.merge,b=a.pick,h=a.splat;e.prototype.collectionsWithUpdate.push("pane");a=function(){function b(b,a){this.options=this.chart=this.center=this.background=void 0;this.coll="pane";this.defaultOptions={center:["50%","50%"],size:"85%",innerSize:"0%",startAngle:0};this.defaultBackgroundOptions={shape:"circle",borderWidth:1,borderColor:f.neutralColor20,
backgroundColor:{linearGradient:{x1:0,y1:0,x2:0,y2:1},stops:[[0,f.backgroundColor],[1,f.neutralColor10]]},from:-Number.MAX_VALUE,innerRadius:0,to:Number.MAX_VALUE,outerRadius:"105%"};this.init(b,a)}b.prototype.init=function(b,a){this.chart=a;this.background=[];a.pane.push(this);this.setOptions(b)};b.prototype.setOptions=function(b){this.options=w(this.defaultOptions,this.chart.angular?{background:{}}:void 0,b)};b.prototype.render=function(){var b=this.options,a=this.options.background,l=this.chart.renderer;
this.group||(this.group=l.g("pane-group").attr({zIndex:b.zIndex||0}).add());this.updateCenter();if(a)for(a=h(a),b=Math.max(a.length,this.background.length||0),l=0;l<b;l++)a[l]&&this.axis?this.renderBackground(w(this.defaultBackgroundOptions,a[l]),l):this.background[l]&&(this.background[l]=this.background[l].destroy(),this.background.splice(l,1))};b.prototype.renderBackground=function(b,a){var h="animate",l={"class":"highcharts-pane "+(b.className||"")};this.chart.styledMode||p(l,{fill:b.backgroundColor,
stroke:b.borderColor,"stroke-width":b.borderWidth});this.background[a]||(this.background[a]=this.chart.renderer.path().add(this.group),h="attr");this.background[a][h]({d:this.axis.getPlotBandPath(b.from,b.to,b)}).attr(l)};b.prototype.updateCenter=function(b){this.center=(b||this.axis||{}).center=r.getCenter.call(this)};b.prototype.update=function(b,a){w(!0,this.options,b);w(!0,this.chart.options.pane,b);this.setOptions(this.options);this.render();this.chart.axes.forEach(function(b){b.pane===this&&
(b.pane=null,b.update({},a))},this)};return b}();e.prototype.getHoverPane=function(b){var a=this,h;b&&a.pane.forEach(function(l){var d=b.chartX-a.plotLeft,c=b.chartY-a.plotTop;k(a.inverted?c:d,a.inverted?d:c,l.center)&&(h=l)});return h};v(e,"afterIsInsidePlot",function(b){this.polar&&(b.isInsidePlot=this.pane.some(function(a){return k(b.x,b.y,a.center)}))});v(c,"beforeGetHoverData",function(a){var h=this.chart;h.polar?(h.hoverPane=h.getHoverPane(a),a.filter=function(l){return l.visible&&!(!a.shared&&
l.directTouch)&&b(l.options.enableMouseTracking,!0)&&(!h.hoverPane||l.xAxis.pane===h.hoverPane)}):h.hoverPane=void 0});v(c,"afterGetHoverData",function(b){var a=this.chart;b.hoverPoint&&b.hoverPoint.plotX&&b.hoverPoint.plotY&&a.hoverPane&&!k(b.hoverPoint.plotX,b.hoverPoint.plotY,a.hoverPane.center)&&(b.hoverPoint=void 0)});d.Pane=a;return d.Pane});z(e,"Core/Axis/HiddenAxis.js",[],function(){return function(){function e(){}e.init=function(d){d.getOffset=function(){};d.redraw=function(){this.isDirty=
!1};d.render=function(){this.isDirty=!1};d.createLabelCollector=function(){return function(){}};d.setScale=function(){};d.setCategories=function(){};d.setTitle=function(){};d.isHidden=!0};return e}()});z(e,"Core/Axis/RadialAxis.js",[e["Core/Axis/Axis.js"],e["Core/Axis/Tick.js"],e["Core/Axis/HiddenAxis.js"],e["Core/Utilities.js"]],function(e,d,f,c){var a=c.addEvent,r=c.correctFloat,k=c.defined,v=c.extend,p=c.fireEvent,w=c.merge,b=c.pick,h=c.relativeLength,l=c.wrap;c=function(){function d(){}d.init=
function(a){var l=e.prototype;a.setOptions=function(b){b=this.options=w(a.constructor.defaultOptions,this.defaultPolarOptions,b);b.plotBands||(b.plotBands=[]);p(this,"afterSetOptions")};a.getOffset=function(){l.getOffset.call(this);this.chart.axisOffset[this.side]=0};a.getLinePath=function(a,h,l){a=this.pane.center;var m=this.chart,t=b(h,a[2]/2-this.offset);"undefined"===typeof l&&(l=this.horiz?0:this.center&&-this.center[3]/2);l&&(t+=l);this.isCircular||"undefined"!==typeof h?(h=this.chart.renderer.symbols.arc(this.left+
a[0],this.top+a[1],t,t,{start:this.startAngleRad,end:this.endAngleRad,open:!0,innerR:0}),h.xBounds=[this.left+a[0]],h.yBounds=[this.top+a[1]-t]):(h=this.postTranslate(this.angleRad,t),h=[["M",this.center[0]+m.plotLeft,this.center[1]+m.plotTop],["L",h.x,h.y]]);return h};a.setAxisTranslation=function(){l.setAxisTranslation.call(this);this.center&&(this.transA=this.isCircular?(this.endAngleRad-this.startAngleRad)/(this.max-this.min||1):(this.center[2]-this.center[3])/2/(this.max-this.min||1),this.minPixelPadding=
this.isXAxis?this.transA*this.minPointOffset:0)};a.beforeSetTickPositions=function(){this.autoConnect=this.isCircular&&"undefined"===typeof b(this.userMax,this.options.max)&&r(this.endAngleRad-this.startAngleRad)===r(2*Math.PI);!this.isCircular&&this.chart.inverted&&this.max++;this.autoConnect&&(this.max+=this.categories&&1||this.pointRange||this.closestPointRange||0)};a.setAxisSize=function(){l.setAxisSize.call(this);if(this.isRadial){this.pane.updateCenter(this);var a=this.center=v([],this.pane.center);
if(this.isCircular)this.sector=this.endAngleRad-this.startAngleRad;else{var h=this.postTranslate(this.angleRad,a[3]/2);a[0]=h.x-this.chart.plotLeft;a[1]=h.y-this.chart.plotTop}this.len=this.width=this.height=(a[2]-a[3])*b(this.sector,1)/2}};a.getPosition=function(a,h){a=this.translate(a);return this.postTranslate(this.isCircular?a:this.angleRad,b(this.isCircular?h:0>a?0:a,this.center[2]/2)-this.offset)};a.postTranslate=function(b,a){var h=this.chart,m=this.center;b=this.startAngleRad+b;return{x:h.plotLeft+
m[0]+Math.cos(b)*a,y:h.plotTop+m[1]+Math.sin(b)*a}};a.getPlotBandPath=function(a,h,l){var m=function(g){if("string"===typeof g){var t=parseInt(g,10);n.test(g)&&(t=t*q/100);return t}return g},t=this.center,g=this.startAngleRad,q=t[2]/2,x=Math.min(this.offset,0),n=/%$/;var C=this.isCircular;var D=b(m(l.outerRadius),q),J=m(l.innerRadius);m=b(m(l.thickness),10);if("polygon"===this.options.gridLineInterpolation)x=this.getPlotLinePath({value:a}).concat(this.getPlotLinePath({value:h,reverse:!0}));else{a=
Math.max(a,this.min);h=Math.min(h,this.max);a=this.translate(a);h=this.translate(h);C||(D=a||0,J=h||0);if("circle"!==l.shape&&C)l=g+(a||0),g+=h||0;else{l=-Math.PI/2;g=1.5*Math.PI;var d=!0}D-=x;x=this.chart.renderer.symbols.arc(this.left+t[0],this.top+t[1],D,D,{start:Math.min(l,g),end:Math.max(l,g),innerR:b(J,D-(m-x)),open:d});C&&(C=(g+l)/2,d=this.left+t[0]+t[2]/2*Math.cos(C),x.xBounds=C>-Math.PI/2&&C<Math.PI/2?[d,this.chart.plotWidth]:[0,d],x.yBounds=[this.top+t[1]+t[2]/2*Math.sin(C)],x.yBounds[0]+=
C>-Math.PI&&0>C||C>Math.PI?-10:10)}return x};a.getCrosshairPosition=function(b,a,h){var m=b.value,t=this.pane.center;if(this.isCircular){if(k(m))b.point&&(g=b.point.shapeArgs||{},g.start&&(m=this.chart.inverted?this.translate(b.point.rectPlotY,!0):b.point.x));else{var g=b.chartX||0;var q=b.chartY||0;m=this.translate(Math.atan2(q-h,g-a)-this.startAngleRad,!0)}b=this.getPosition(m);g=b.x;q=b.y}else k(m)||(g=b.chartX,q=b.chartY),k(g)&&k(q)&&(h=t[1]+this.chart.plotTop,m=this.translate(Math.min(Math.sqrt(Math.pow(g-
a,2)+Math.pow(q-h,2)),t[2]/2)-t[3]/2,!0));return[m,g||0,q||0]};a.getPlotLinePath=function(b){var a=this,l=a.pane.center,m=a.chart,t=m.inverted,g=b.value,q=b.reverse,x=a.getPosition(g),n=a.pane.options.background?a.pane.options.background[0]||a.pane.options.background:{},C=n.innerRadius||"0%",D=n.outerRadius||"100%";n=l[0]+m.plotLeft;var d=l[1]+m.plotTop,c=x.x,k=x.y,f=a.height;x=l[3]/2;var e;b.isCrosshair&&(k=this.getCrosshairPosition(b,n,d),g=k[0],c=k[1],k=k[2]);if(a.isCircular)g=Math.sqrt(Math.pow(c-
n,2)+Math.pow(k-d,2)),q="string"===typeof C?h(C,1):C/g,m="string"===typeof D?h(D,1):D/g,l&&x&&(g=x/g,q<g&&(q=g),m<g&&(m=g)),l=[["M",n+q*(c-n),d-q*(d-k)],["L",c-(1-m)*(c-n),k+(1-m)*(d-k)]];else if((g=a.translate(g))&&(0>g||g>f)&&(g=0),"circle"===a.options.gridLineInterpolation)l=a.getLinePath(0,g,x);else if(l=[],m[t?"yAxis":"xAxis"].forEach(function(g){g.pane===a.pane&&(e=g)}),e)for(n=e.tickPositions,e.autoConnect&&(n=n.concat([n[0]])),q&&(n=n.slice().reverse()),g&&(g+=x),c=0;c<n.length;c++)d=e.getPosition(n[c],
g),l.push(c?["L",d.x,d.y]:["M",d.x,d.y]);return l};a.getTitlePosition=function(){var b=this.center,a=this.chart,h=this.options.title;return{x:a.plotLeft+b[0]+(h.x||0),y:a.plotTop+b[1]-{high:.5,middle:.25,low:0}[h.align]*b[2]+(h.y||0)}};a.createLabelCollector=function(){var b=this;return function(){if(b.isRadial&&b.tickPositions&&!0!==b.options.labels.allowOverlap)return b.tickPositions.map(function(a){return b.ticks[a]&&b.ticks[a].label}).filter(function(b){return!!b})}}};d.compose=function(c,k){a(c,
"init",function(b){var a=this.chart,h=a.inverted,m=a.angular,t=a.polar,g=this.isXAxis,q=this.coll,x=m&&g,n,C=a.options;b=b.userOptions.pane||0;b=this.pane=a.pane&&a.pane[b];if("colorAxis"===q)this.isRadial=!1;else{if(m){if(x?f.init(this):d.init(this),n=!g)this.defaultPolarOptions=d.defaultRadialGaugeOptions}else t&&(d.init(this),this.defaultPolarOptions=(n=this.horiz)?d.defaultCircularOptions:w("xAxis"===q?c.defaultOptions:c.defaultYAxisOptions,d.defaultRadialOptions),h&&"yAxis"===q&&(this.defaultPolarOptions.stackLabels=
c.defaultYAxisOptions.stackLabels));m||t?(this.isRadial=!0,C.chart.zoomType=null,this.labelCollector||(this.labelCollector=this.createLabelCollector()),this.labelCollector&&a.labelCollectors.push(this.labelCollector)):this.isRadial=!1;b&&n&&(b.axis=this);this.isCircular=n}});a(c,"afterInit",function(){var a=this.chart,h=this.options,l=this.pane,m=l&&l.options;a.angular&&this.isXAxis||!l||!a.angular&&!a.polar||(this.angleRad=(h.angle||0)*Math.PI/180,this.startAngleRad=(m.startAngle-90)*Math.PI/180,
this.endAngleRad=(b(m.endAngle,m.startAngle+360)-90)*Math.PI/180,this.offset=h.offset||0)});a(c,"autoLabelAlign",function(b){this.isRadial&&(b.align=void 0,b.preventDefault())});a(c,"destroy",function(){if(this.chart&&this.chart.labelCollectors){var b=this.labelCollector?this.chart.labelCollectors.indexOf(this.labelCollector):-1;0<=b&&this.chart.labelCollectors.splice(b,1)}});a(c,"initialAxisTranslation",function(){this.isRadial&&this.beforeSetTickPositions()});a(k,"afterGetPosition",function(b){this.axis.getPosition&&
v(b.pos,this.axis.getPosition(this.pos))});a(k,"afterGetLabelPosition",function(a){var l=this.axis,d=this.label;if(d){var m=d.getBBox(),t=l.options.labels,g=t.y,q=20,x=t.align,n=(l.translate(this.pos)+l.startAngleRad+Math.PI/2)/Math.PI*180%360,C=Math.round(n),D="end",c=0>C?C+360:C,k=c,f=0,e=0,v=null===t.y?.3*-m.height:0;if(l.isRadial){var w=l.getPosition(this.pos,l.center[2]/2+h(b(t.distance,-25),l.center[2]/2,-l.center[2]/2));"auto"===t.rotation?d.attr({rotation:n}):null===g&&(g=l.chart.renderer.fontMetrics(d.styles&&
d.styles.fontSize).b-m.height/2);null===x&&(l.isCircular?(m.width>l.len*l.tickInterval/(l.max-l.min)&&(q=0),x=n>q&&n<180-q?"left":n>180+q&&n<360-q?"right":"center"):x="center",d.attr({align:x}));if("auto"===x&&2===l.tickPositions.length&&l.isCircular){90<c&&180>c?c=180-c:270<c&&360>=c&&(c=540-c);180<k&&360>=k&&(k=360-k);if(l.pane.options.startAngle===C||l.pane.options.startAngle===C+360||l.pane.options.startAngle===C-360)D="start";x=-90<=C&&90>=C||-360<=C&&-270>=C||270<=C&&360>=C?"start"===D?"right":
"left":"start"===D?"left":"right";70<k&&110>k&&(x="center");15>c||180<=c&&195>c?f=.3*m.height:15<=c&&35>=c?f="start"===D?0:.75*m.height:195<=c&&215>=c?f="start"===D?.75*m.height:0:35<c&&90>=c?f="start"===D?.25*-m.height:m.height:215<c&&270>=c&&(f="start"===D?m.height:.25*-m.height);15>k?e="start"===D?.15*-m.height:.15*m.height:165<k&&180>=k&&(e="start"===D?.15*m.height:.15*-m.height);d.attr({align:x});d.translate(e,f+v)}a.pos.x=w.x+t.x;a.pos.y=w.y+g}}});l(k.prototype,"getMarkPath",function(b,a,h,
m,t,g,q){var x=this.axis;x.isRadial?(b=x.getPosition(this.pos,x.center[2]/2+m),a=["M",a,h,"L",b.x,b.y]):a=b.call(this,a,h,m,t,g,q);return a})};d.defaultCircularOptions={gridLineWidth:1,labels:{align:null,distance:15,x:0,y:null,style:{textOverflow:"none"}},maxPadding:0,minPadding:0,showLastLabel:!1,tickLength:0};d.defaultRadialGaugeOptions={labels:{align:"center",x:0,y:null},minorGridLineWidth:0,minorTickInterval:"auto",minorTickLength:10,minorTickPosition:"inside",minorTickWidth:1,tickLength:10,tickPosition:"inside",
tickWidth:2,title:{rotation:0},zIndex:2};d.defaultRadialOptions={gridLineInterpolation:"circle",gridLineWidth:1,labels:{align:"right",x:-3,y:-2},showLastLabel:!1,title:{x:4,text:null,rotation:90}};return d}();c.compose(e,d);return c});z(e,"Series/AreaRange/AreaRangePoint.js",[e["Series/Area/AreaSeries.js"],e["Core/Series/Point.js"],e["Core/Utilities.js"]],function(e,d,f){var c=this&&this.__extends||function(){var a=function(d,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,
a){b.__proto__=a}||function(b,a){for(var h in a)a.hasOwnProperty(h)&&(b[h]=a[h])};return a(d,c)};return function(d,c){function b(){this.constructor=d}a(d,c);d.prototype=null===c?Object.create(c):(b.prototype=c.prototype,new b)}}(),a=d.prototype,r=f.defined,k=f.isNumber;return function(d){function f(){var a=null!==d&&d.apply(this,arguments)||this;a.high=void 0;a.low=void 0;a.options=void 0;a.plotHigh=void 0;a.plotLow=void 0;a.plotHighX=void 0;a.plotLowX=void 0;a.plotX=void 0;a.series=void 0;return a}
c(f,d);f.prototype.setState=function(){var d=this.state,b=this.series,h=b.chart.polar;r(this.plotHigh)||(this.plotHigh=b.yAxis.toPixels(this.high,!0));r(this.plotLow)||(this.plotLow=this.plotY=b.yAxis.toPixels(this.low,!0));b.stateMarkerGraphic&&(b.lowerStateMarkerGraphic=b.stateMarkerGraphic,b.stateMarkerGraphic=b.upperStateMarkerGraphic);this.graphic=this.upperGraphic;this.plotY=this.plotHigh;h&&(this.plotX=this.plotHighX);a.setState.apply(this,arguments);this.state=d;this.plotY=this.plotLow;this.graphic=
this.lowerGraphic;h&&(this.plotX=this.plotLowX);b.stateMarkerGraphic&&(b.upperStateMarkerGraphic=b.stateMarkerGraphic,b.stateMarkerGraphic=b.lowerStateMarkerGraphic,b.lowerStateMarkerGraphic=void 0);a.setState.apply(this,arguments)};f.prototype.haloPath=function(){var d=this.series.chart.polar,b=[];this.plotY=this.plotLow;d&&(this.plotX=this.plotLowX);this.isInside&&(b=a.haloPath.apply(this,arguments));this.plotY=this.plotHigh;d&&(this.plotX=this.plotHighX);this.isTopInside&&(b=b.concat(a.haloPath.apply(this,
arguments)));return b};f.prototype.destroyElements=function(){["lowerGraphic","upperGraphic"].forEach(function(a){this[a]&&(this[a]=this[a].destroy())},this);this.graphic=null;return a.destroyElements.apply(this,arguments)};f.prototype.isValid=function(){return k(this.low)&&k(this.high)};return f}(e.prototype.pointClass)});z(e,"Series/AreaRange/AreaRangeSeries.js",[e["Series/AreaRange/AreaRangePoint.js"],e["Series/Area/AreaSeries.js"],e["Core/Series/Series.js"],e["Series/Column/ColumnSeries.js"],
e["Core/Globals.js"],e["Series/Line/LineSeries.js"],e["Core/Utilities.js"]],function(e,d,f,c,a,r,k){var v=this&&this.__extends||function(){var b=function(a,m){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,g){b.__proto__=g}||function(b,g){for(var q in g)g.hasOwnProperty(q)&&(b[q]=g[q])};return b(a,m)};return function(a,m){function t(){this.constructor=a}b(a,m);a.prototype=null===m?Object.create(m):(t.prototype=m.prototype,new t)}}(),p=d.prototype,w=c.prototype,b=a.noop,h=r.prototype,
l=k.defined,u=k.extend,A=k.isArray,H=k.pick,M=k.merge;c=function(a){function c(){var m=null!==a&&a.apply(this,arguments)||this;m.data=void 0;m.options=void 0;m.points=void 0;m.lowerStateMarkerGraphic=void 0;m.xAxis=void 0;m.setStackedPoints=b;return m}v(c,a);c.prototype.toYData=function(b){return[b.low,b.high]};c.prototype.highToXY=function(b){var a=this.chart,g=this.xAxis.postTranslate(b.rectPlotX,this.yAxis.len-b.plotHigh);b.plotHighX=g.x-a.plotLeft;b.plotHigh=g.y-a.plotTop;b.plotLowX=b.plotX};
c.prototype.translate=function(){var b=this,a=b.yAxis,g=!!b.modifyValue;p.translate.apply(b);b.points.forEach(function(q){var t=q.high,n=q.plotY;q.isNull?q.plotY=null:(q.plotLow=n,q.plotHigh=a.translate(g?b.modifyValue(t,q):t,0,1,0,1),g&&(q.yBottom=q.plotHigh))});this.chart.polar&&this.points.forEach(function(g){b.highToXY(g);g.tooltipPos=[(g.plotHighX+g.plotLowX)/2,(g.plotHigh+g.plotLow)/2]})};c.prototype.getGraphPath=function(b){var a=[],g=[],q,x=p.getGraphPath;var n=this.options;var m=this.chart.polar,
h=m&&!1!==n.connectEnds,l=n.connectNulls,d=n.step;b=b||this.points;for(q=b.length;q--;){var c=b[q];var k=m?{plotX:c.rectPlotX,plotY:c.yBottom,doCurve:!1}:{plotX:c.plotX,plotY:c.plotY,doCurve:!1};c.isNull||h||l||b[q+1]&&!b[q+1].isNull||g.push(k);var f={polarPlotY:c.polarPlotY,rectPlotX:c.rectPlotX,yBottom:c.yBottom,plotX:H(c.plotHighX,c.plotX),plotY:c.plotHigh,isNull:c.isNull};g.push(f);a.push(f);c.isNull||h||l||b[q-1]&&!b[q-1].isNull||g.push(k)}b=x.call(this,b);d&&(!0===d&&(d="left"),n.step={left:"right",
center:"center",right:"left"}[d]);a=x.call(this,a);g=x.call(this,g);n.step=d;n=[].concat(b,a);!this.chart.polar&&g[0]&&"M"===g[0][0]&&(g[0]=["L",g[0][1],g[0][2]]);this.graphPath=n;this.areaPath=b.concat(g);n.isArea=!0;n.xMap=b.xMap;this.areaPath.xMap=b.xMap;return n};c.prototype.drawDataLabels=function(){var b=this.points,a=b.length,g,q=[],x=this.options.dataLabels,n,C=this.chart.inverted;if(A(x)){var l=x[0]||{enabled:!1};var c=x[1]||{enabled:!1}}else l=u({},x),l.x=x.xHigh,l.y=x.yHigh,c=u({},x),c.x=
x.xLow,c.y=x.yLow;if(l.enabled||this._hasPointLabels){for(g=a;g--;)if(n=b[g]){var d=l.inside?n.plotHigh<n.plotLow:n.plotHigh>n.plotLow;n.y=n.high;n._plotY=n.plotY;n.plotY=n.plotHigh;q[g]=n.dataLabel;n.dataLabel=n.dataLabelUpper;n.below=d;C?l.align||(l.align=d?"right":"left"):l.verticalAlign||(l.verticalAlign=d?"top":"bottom")}this.options.dataLabels=l;h.drawDataLabels&&h.drawDataLabels.apply(this,arguments);for(g=a;g--;)if(n=b[g])n.dataLabelUpper=n.dataLabel,n.dataLabel=q[g],delete n.dataLabels,n.y=
n.low,n.plotY=n._plotY}if(c.enabled||this._hasPointLabels){for(g=a;g--;)if(n=b[g])d=c.inside?n.plotHigh<n.plotLow:n.plotHigh>n.plotLow,n.below=!d,C?c.align||(c.align=d?"left":"right"):c.verticalAlign||(c.verticalAlign=d?"bottom":"top");this.options.dataLabels=c;h.drawDataLabels&&h.drawDataLabels.apply(this,arguments)}if(l.enabled)for(g=a;g--;)if(n=b[g])n.dataLabels=[n.dataLabelUpper,n.dataLabel].filter(function(g){return!!g});this.options.dataLabels=x};c.prototype.alignDataLabel=function(){w.alignDataLabel.apply(this,
arguments)};c.prototype.drawPoints=function(){var b=this.points.length,a;h.drawPoints.apply(this,arguments);for(a=0;a<b;){var g=this.points[a];g.origProps={plotY:g.plotY,plotX:g.plotX,isInside:g.isInside,negative:g.negative,zone:g.zone,y:g.y};g.lowerGraphic=g.graphic;g.graphic=g.upperGraphic;g.plotY=g.plotHigh;l(g.plotHighX)&&(g.plotX=g.plotHighX);g.y=g.high;g.negative=g.high<(this.options.threshold||0);g.zone=this.zones.length&&g.getZone();this.chart.polar||(g.isInside=g.isTopInside="undefined"!==
typeof g.plotY&&0<=g.plotY&&g.plotY<=this.yAxis.len&&0<=g.plotX&&g.plotX<=this.xAxis.len);a++}h.drawPoints.apply(this,arguments);for(a=0;a<b;)g=this.points[a],g.upperGraphic=g.graphic,g.graphic=g.lowerGraphic,u(g,g.origProps),delete g.origProps,a++};c.defaultOptions=M(d.defaultOptions,{lineWidth:1,threshold:null,tooltip:{pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},trackByArea:!0,dataLabels:{align:void 0,verticalAlign:void 0,
xLow:0,xHigh:0,yLow:0,yHigh:0}});return c}(d);u(c.prototype,{pointArrayMap:["low","high"],pointValKey:"low",deferTranslatePolar:!0,pointClass:e});f.registerSeriesType("arearange",c);"";return c});z(e,"Series/AreaSplineRange/AreaSplineRangeSeries.js",[e["Core/Series/Series.js"],e["Series/AreaRange/AreaRangeSeries.js"],e["Core/Utilities.js"]],function(e,d,f){var c=this&&this.__extends||function(){var a=function(c,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=
b}||function(a,b){for(var h in b)b.hasOwnProperty(h)&&(a[h]=b[h])};return a(c,d)};return function(c,d){function k(){this.constructor=c}a(c,d);c.prototype=null===d?Object.create(d):(k.prototype=d.prototype,new k)}}(),a=f.merge;f=f.extend;var r=function(k){function f(){var a=null!==k&&k.apply(this,arguments)||this;a.options=void 0;a.data=void 0;a.points=void 0;return a}c(f,k);f.defaultOptions=a(d.defaultOptions);return f}(d);f(r.prototype,{getPointSpline:e.seriesTypes.spline.prototype.getPointSpline});
e.registerSeriesType("areasplinerange",r);"";return r});z(e,"Series/ColumnRange/ColumnRangePoint.js",[e["Core/Series/Series.js"],e["Core/Utilities.js"]],function(e,d){var f=this&&this.__extends||function(){var a=function(c,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var d in c)c.hasOwnProperty(d)&&(a[d]=c[d])};return a(c,d)};return function(c,d){function f(){this.constructor=c}a(c,d);c.prototype=null===d?Object.create(d):(f.prototype=
d.prototype,new f)}}(),c=e.seriesTypes;e=c.column.prototype.pointClass;d=d.extend;c=function(a){function c(){var c=null!==a&&a.apply(this,arguments)||this;c.series=void 0;c.options=void 0;c.barX=void 0;c.pointWidth=void 0;c.shapeArgs=void 0;c.shapeType=void 0;return c}f(c,a);return c}(c.arearange.prototype.pointClass);d(c.prototype,{setState:e.prototype.setState});return c});z(e,"Series/ColumnRange/ColumnRangeSeries.js",[e["Series/ColumnRange/ColumnRangePoint.js"],e["Core/Series/Series.js"],e["Core/Globals.js"],
e["Core/Utilities.js"]],function(e,d,f,c){var a=this&&this.__extends||function(){var b=function(a,c){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return b(a,c)};return function(a,c){function d(){this.constructor=a}b(a,c);a.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),r=d.seriesTypes,k=r.arearange,v=r.column,p=v.prototype,w=k.prototype;f=f.noop;var b=c.clamp,h=c.merge,
l=c.pick;c=c.extend;var u={pointRange:null,marker:null,states:{hover:{halo:!1}}};r=function(c){function d(){var b=null!==c&&c.apply(this,arguments)||this;b.data=void 0;b.points=void 0;b.options=void 0;return b}a(d,c);d.prototype.setOptions=function(){h(!0,arguments[0],{stacking:void 0});return w.setOptions.apply(this,arguments)};d.prototype.translate=function(){var a=this,c=a.yAxis,d=a.xAxis,h=d.startAngleRad,t,g=a.chart,q=a.xAxis.isRadial,x=Math.max(g.chartWidth,g.chartHeight)+999,n;p.translate.apply(a);
a.points.forEach(function(m){var C=m.shapeArgs,f=a.options.minPointLength;m.plotHigh=n=b(c.translate(m.high,0,1,0,1),-x,x);m.plotLow=b(m.plotY,-x,x);var k=n;var e=l(m.rectPlotY,m.plotY)-n;Math.abs(e)<f?(f-=e,e+=f,k-=f/2):0>e&&(e*=-1,k-=e);q?(t=m.barX+h,m.shapeType="arc",m.shapeArgs=a.polarArc(k+e,k,t,t+m.pointWidth)):(C.height=e,C.y=k,m.tooltipPos=g.inverted?[c.len+c.pos-g.plotLeft-k-e/2,d.len+d.pos-g.plotTop-C.x-C.width/2,e]:[d.left-g.plotLeft+C.x+C.width/2,c.pos-g.plotTop+k+e/2,e])})};d.prototype.crispCol=
function(){return p.crispCol.apply(this,arguments)};d.prototype.drawPoints=function(){return p.drawPoints.apply(this,arguments)};d.prototype.drawTracker=function(){return p.drawTracker.apply(this,arguments)};d.prototype.getColumnMetrics=function(){return p.getColumnMetrics.apply(this,arguments)};d.prototype.pointAttribs=function(){return p.pointAttribs.apply(this,arguments)};d.prototype.adjustForMissingColumns=function(){return p.adjustForMissingColumns.apply(this,arguments)};d.prototype.animate=
function(){return p.animate.apply(this,arguments)};d.prototype.translate3dPoints=function(){return p.translate3dPoints.apply(this,arguments)};d.prototype.translate3dShapes=function(){return p.translate3dShapes.apply(this,arguments)};d.defaultOptions=h(v.defaultOptions,k.defaultOptions,u);return d}(k);c(r.prototype,{directTouch:!0,trackerGroups:["group","dataLabelsGroup"],drawGraph:f,getSymbol:f,polarArc:function(){return p.polarArc.apply(this,arguments)},pointClass:e});d.registerSeriesType("columnrange",
r);"";return r});z(e,"Series/ColumnPyramid/ColumnPyramidSeries.js",[e["Core/Series/Series.js"],e["Series/Column/ColumnSeries.js"],e["Core/Utilities.js"]],function(e,d,f){var c=this&&this.__extends||function(){var a=function(c,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return a(c,b)};return function(c,b){function d(){this.constructor=c}a(c,b);c.prototype=null===b?Object.create(b):(d.prototype=
b.prototype,new d)}}(),a=d.prototype,r=f.clamp,k=f.merge,v=f.pick;f=function(f){function e(){var b=null!==f&&f.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}c(e,f);e.prototype.translate=function(){var b=this,c=b.chart,d=b.options,f=b.dense=2>b.closestPointRange*b.xAxis.transA;f=b.borderWidth=v(d.borderWidth,f?0:1);var e=b.yAxis,k=d.threshold,p=b.translatedThreshold=e.getThreshold(k),w=v(d.minPointLength,5),y=b.getColumnMetrics(),m=y.width,t=b.barW=Math.max(m,
1+2*f),g=b.pointXOffset=y.offset;c.inverted&&(p-=.5);d.pointPadding&&(t=Math.ceil(t));a.translate.apply(b);b.points.forEach(function(a){var q=v(a.yBottom,p),n=999+Math.abs(q),l=r(a.plotY,-n,e.len+n);n=a.plotX+g;var h=t/2,f=Math.min(l,q);q=Math.max(l,q)-f;var u;a.barX=n;a.pointWidth=m;a.tooltipPos=c.inverted?[e.len+e.pos-c.plotLeft-l,b.xAxis.len-n-h,q]:[n+h,l+e.pos-c.plotTop,q];l=k+(a.total||a.y);"percent"===d.stacking&&(l=k+(0>a.y)?-100:100);l=e.toPixels(l,!0);var G=(u=c.plotHeight-l-(c.plotHeight-
p))?h*(f-l)/u:0;var y=u?h*(f+q-l)/u:0;u=n-G+h;G=n+G+h;var A=n+y+h;y=n-y+h;var K=f-w;var I=f+q;0>a.y&&(K=f,I=f+q+w);c.inverted&&(A=c.plotWidth-f,u=l-(c.plotWidth-p),G=h*(l-A)/u,y=h*(l-(A-q))/u,u=n+h+G,G=u-2*G,A=n-y+h,y=n+y+h,K=f,I=f+q-w,0>a.y&&(I=f+q+w));a.shapeType="path";a.shapeArgs={x:u,y:K,width:G-u,height:q,d:[["M",u,K],["L",G,K],["L",A,I],["L",y,I],["Z"]]}})};e.defaultOptions=k(d.defaultOptions,{});return e}(d);e.registerSeriesType("columnpyramid",f);"";return f});z(e,"Series/Gauge/GaugePoint.js",
[e["Core/Series/Series.js"]],function(e){var d=this&&this.__extends||function(){var d=function(c,a){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var d in c)c.hasOwnProperty(d)&&(a[d]=c[d])};return d(c,a)};return function(c,a){function f(){this.constructor=c}d(c,a);c.prototype=null===a?Object.create(a):(f.prototype=a.prototype,new f)}}();return function(f){function c(){var a=null!==f&&f.apply(this,arguments)||this;a.options=void 0;a.series=
void 0;a.shapeArgs=void 0;return a}d(c,f);c.prototype.setState=function(a){this.state=a};return c}(e.seriesTypes.line.prototype.pointClass)});z(e,"Series/Gauge/GaugeSeries.js",[e["Core/Series/Series.js"],e["Series/Gauge/GaugePoint.js"],e["Core/Globals.js"],e["Core/Color/Palette.js"],e["Core/Utilities.js"]],function(e,d,f,c,a){var r=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&
(a[c]=b[c])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),k=e.seriesTypes,v=k.column,p=k.line;f=f.noop;var w=a.clamp,b=a.isNumber;k=a.extend;var h=a.merge,l=a.pick,u=a.pInt;a=function(a){function d(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.points=void 0;b.options=void 0;b.yAxis=void 0;return b}r(d,a);d.prototype.translate=function(){var a=this.yAxis,c=this.options,d=a.center;
this.generatePoints();this.points.forEach(function(m){var t=h(c.dial,m.dial),g=u(l(t.radius,"80%"))*d[2]/200,q=u(l(t.baseLength,"70%"))*g/100,x=u(l(t.rearLength,"10%"))*g/100,n=t.baseWidth||3,C=t.topWidth||1,f=c.overshoot,e=a.startAngleRad+a.translate(m.y,null,null,null,!0);if(b(f)||!1===c.wrap)f=b(f)?f/180*Math.PI:0,e=w(e,a.startAngleRad-f,a.endAngleRad+f);e=180*e/Math.PI;m.shapeType="path";m.shapeArgs={d:t.path||[["M",-x,-n/2],["L",q,-n/2],["L",g,-C/2],["L",g,C/2],["L",q,n/2],["L",-x,n/2],["Z"]],
translateX:d[0],translateY:d[1],rotation:e};m.plotX=d[0];m.plotY=d[1]})};d.prototype.drawPoints=function(){var a=this,b=a.chart,d=a.yAxis.center,m=a.pivot,t=a.options,g=t.pivot,q=b.renderer;a.points.forEach(function(g){var d=g.graphic,x=g.shapeArgs,l=x.d,m=h(t.dial,g.dial);d?(d.animate(x),x.d=l):g.graphic=q[g.shapeType](x).attr({rotation:x.rotation,zIndex:1}).addClass("highcharts-dial").add(a.group);if(!b.styledMode)g.graphic[d?"animate":"attr"]({stroke:m.borderColor||"none","stroke-width":m.borderWidth||
0,fill:m.backgroundColor||c.neutralColor100})});m?m.animate({translateX:d[0],translateY:d[1]}):(a.pivot=q.circle(0,0,l(g.radius,5)).attr({zIndex:2}).addClass("highcharts-pivot").translate(d[0],d[1]).add(a.group),b.styledMode||a.pivot.attr({"stroke-width":g.borderWidth||0,stroke:g.borderColor||c.neutralColor20,fill:g.backgroundColor||c.neutralColor100}))};d.prototype.animate=function(a){var b=this;a||b.points.forEach(function(a){var c=a.graphic;c&&(c.attr({rotation:180*b.yAxis.startAngleRad/Math.PI}),
c.animate({rotation:a.shapeArgs.rotation},b.options.animation))})};d.prototype.render=function(){this.group=this.plotGroup("group","series",this.visible?"visible":"hidden",this.options.zIndex,this.chart.seriesGroup);p.prototype.render.call(this);this.group.clip(this.chart.clipRect)};d.prototype.setData=function(a,b){p.prototype.setData.call(this,a,!1);this.processData();this.generatePoints();l(b,!0)&&this.chart.redraw()};d.prototype.hasData=function(){return!!this.points.length};d.defaultOptions=
h(p.defaultOptions,{dataLabels:{borderColor:c.neutralColor20,borderRadius:3,borderWidth:1,crop:!1,defer:!1,enabled:!0,verticalAlign:"top",y:15,zIndex:2},dial:{},pivot:{},tooltip:{headerFormat:""},showInLegend:!1});return d}(p);k(a.prototype,{angular:!0,directTouch:!0,drawGraph:f,drawTracker:v.prototype.drawTracker,fixedBox:!0,forceDL:!0,noSharedTooltip:!0,pointClass:d,trackerGroups:["group","dataLabelsGroup"]});e.registerSeriesType("gauge",a);"";return a});z(e,"Series/BoxPlot/BoxPlotSeries.js",[e["Core/Series/Series.js"],
e["Series/Column/ColumnSeries.js"],e["Core/Globals.js"],e["Core/Color/Palette.js"],e["Core/Utilities.js"]],function(e,d,f,c,a){var r=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}();f=f.noop;var k=a.extend,
v=a.merge,p=a.pick;a=function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}r(b,a);b.prototype.pointAttribs=function(){return{}};b.prototype.translate=function(){var b=this.yAxis,c=this.pointArrayMap;a.prototype.translate.apply(this);this.points.forEach(function(a){c.forEach(function(c){null!==a[c]&&(a[c+"Plot"]=b.translate(a[c],0,1,0,1))});a.plotHigh=a.highPlot})};b.prototype.drawPoints=function(){var a=this,b=a.options,c=a.chart,
d=c.renderer,f,e,k,v,m,t,g=0,q,x,n,C,D=!1!==a.doQuartiles,J,r=a.options.whiskerLength;a.points.forEach(function(h){var l=h.graphic,u=l?"animate":"attr",y=h.shapeArgs,w={},G={},L={},A={},B=h.color||a.color;"undefined"!==typeof h.plotY&&(q=Math.round(y.width),x=Math.floor(y.x),n=x+q,C=Math.round(q/2),f=Math.floor(D?h.q1Plot:h.lowPlot),e=Math.floor(D?h.q3Plot:h.lowPlot),k=Math.floor(h.highPlot),v=Math.floor(h.lowPlot),l||(h.graphic=l=d.g("point").add(a.group),h.stem=d.path().addClass("highcharts-boxplot-stem").add(l),
r&&(h.whiskers=d.path().addClass("highcharts-boxplot-whisker").add(l)),D&&(h.box=d.path(void 0).addClass("highcharts-boxplot-box").add(l)),h.medianShape=d.path(void 0).addClass("highcharts-boxplot-median").add(l)),c.styledMode||(G.stroke=h.stemColor||b.stemColor||B,G["stroke-width"]=p(h.stemWidth,b.stemWidth,b.lineWidth),G.dashstyle=h.stemDashStyle||b.stemDashStyle||b.dashStyle,h.stem.attr(G),r&&(L.stroke=h.whiskerColor||b.whiskerColor||B,L["stroke-width"]=p(h.whiskerWidth,b.whiskerWidth,b.lineWidth),
L.dashstyle=h.whiskerDashStyle||b.whiskerDashStyle||b.dashStyle,h.whiskers.attr(L)),D&&(w.fill=h.fillColor||b.fillColor||B,w.stroke=b.lineColor||B,w["stroke-width"]=b.lineWidth||0,w.dashstyle=h.boxDashStyle||b.boxDashStyle||b.dashStyle,h.box.attr(w)),A.stroke=h.medianColor||b.medianColor||B,A["stroke-width"]=p(h.medianWidth,b.medianWidth,b.lineWidth),A.dashstyle=h.medianDashStyle||b.medianDashStyle||b.dashStyle,h.medianShape.attr(A)),t=h.stem.strokeWidth()%2/2,g=x+C+t,l=[["M",g,e],["L",g,k],["M",
g,f],["L",g,v]],h.stem[u]({d:l}),D&&(t=h.box.strokeWidth()%2/2,f=Math.floor(f)+t,e=Math.floor(e)+t,x+=t,n+=t,l=[["M",x,e],["L",x,f],["L",n,f],["L",n,e],["L",x,e],["Z"]],h.box[u]({d:l})),r&&(t=h.whiskers.strokeWidth()%2/2,k+=t,v+=t,J=/%$/.test(r)?C*parseFloat(r)/100:r/2,l=[["M",g-J,k],["L",g+J,k],["M",g-J,v],["L",g+J,v]],h.whiskers[u]({d:l})),m=Math.round(h.medianPlot),t=h.medianShape.strokeWidth()%2/2,m+=t,l=[["M",x,m],["L",n,m]],h.medianShape[u]({d:l}))})};b.prototype.toYData=function(a){return[a.low,
a.q1,a.median,a.q3,a.high]};b.defaultOptions=v(d.defaultOptions,{threshold:null,tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Maximum: {point.high}<br/>Upper quartile: {point.q3}<br/>Median: {point.median}<br/>Lower quartile: {point.q1}<br/>Minimum: {point.low}<br/>'},whiskerLength:"50%",fillColor:c.backgroundColor,lineWidth:1,medianWidth:2,whiskerWidth:2});return b}(d);k(a.prototype,{pointArrayMap:["low","q1","median","q3","high"],pointValKey:"high",
drawDataLabels:f,setStackedPoints:f});e.registerSeriesType("boxplot",a);"";return a});z(e,"Series/ErrorBar/ErrorBarSeries.js",[e["Core/Series/Series.js"],e["Series/BoxPlot/BoxPlotSeries.js"],e["Series/Column/ColumnSeries.js"],e["Core/Color/Palette.js"],e["Core/Utilities.js"]],function(e,d,f,c,a){var r=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};
return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),k=e.seriesTypes.arearange,v=a.merge;a=a.extend;var p=function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}r(b,a);b.prototype.getColumnMetrics=function(){return this.linkedParent&&this.linkedParent.columnMetrics||f.prototype.getColumnMetrics.call(this)};b.prototype.drawDataLabels=
function(){var a=this.pointValKey;k&&(k.prototype.drawDataLabels.call(this),this.data.forEach(function(b){b.y=b[a]}))};b.prototype.toYData=function(a){return[a.low,a.high]};b.defaultOptions=v(d.defaultOptions,{color:c.neutralColor100,grouping:!1,linkedTo:":previous",tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},whiskerWidth:null});return b}(d);a(p.prototype,{pointArrayMap:["low","high"],pointValKey:"high",doQuartiles:!1});
e.registerSeriesType("errorbar",p);"";return p});z(e,"Core/Axis/WaterfallAxis.js",[e["Extensions/Stacking.js"],e["Core/Utilities.js"]],function(e,d){var f=d.addEvent,c=d.objectEach,a;(function(a){function d(){var a=this.waterfall.stacks;a&&(a.changed=!1,delete a.alreadyChanged)}function v(){var a=this.options.stackLabels;a&&a.enabled&&this.waterfall.stacks&&this.waterfall.renderStackTotals()}function r(){for(var a=this.axes,b=this.series,c=b.length;c--;)b[c].options.stacking&&(a.forEach(function(a){a.isXAxis||
(a.waterfall.stacks.changed=!0)}),c=0)}function w(){this.waterfall||(this.waterfall=new b(this))}var b=function(){function a(a){this.axis=a;this.stacks={changed:!1}}a.prototype.renderStackTotals=function(){var a=this.axis,b=a.waterfall.stacks,d=a.stacking&&a.stacking.stackTotalGroup,h=new e(a,a.options.stackLabels,!1,0,void 0);this.dummyStackItem=h;c(b,function(a){c(a,function(a){h.total=a.stackTotal;a.label&&(h.label=a.label);e.prototype.render.call(h,d);a.label=h.label;delete h.label})});h.total=
null};return a}();a.Composition=b;a.compose=function(a,b){f(a,"init",w);f(a,"afterBuildStacks",d);f(a,"afterRender",v);f(b,"beforeRedraw",r)}})(a||(a={}));return a});z(e,"Series/Waterfall/WaterfallPoint.js",[e["Series/Column/ColumnSeries.js"],e["Core/Series/Point.js"],e["Core/Utilities.js"]],function(e,d,f){var c=this&&this.__extends||function(){var a=function(c,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&
(a[b]=c[b])};return a(c,d)};return function(c,d){function f(){this.constructor=c}a(c,d);c.prototype=null===d?Object.create(d):(f.prototype=d.prototype,new f)}}(),a=f.isNumber;return function(f){function e(){var a=null!==f&&f.apply(this,arguments)||this;a.options=void 0;a.series=void 0;return a}c(e,f);e.prototype.getClassName=function(){var a=d.prototype.getClassName.call(this);this.isSum?a+=" highcharts-sum":this.isIntermediateSum&&(a+=" highcharts-intermediate-sum");return a};e.prototype.isValid=
function(){return a(this.y)||this.isSum||!!this.isIntermediateSum};return e}(e.prototype.pointClass)});z(e,"Series/Waterfall/WaterfallSeries.js",[e["Core/Series/Series.js"],e["Core/Chart/Chart.js"],e["Core/Globals.js"],e["Core/Color/Palette.js"],e["Core/Utilities.js"],e["Core/Axis/WaterfallAxis.js"],e["Series/Waterfall/WaterfallPoint.js"]],function(e,d,f,c,a,r,k){var v=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=
b}||function(a,b){for(var g in b)b.hasOwnProperty(g)&&(a[g]=b[g])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),p=e.seriesTypes,w=p.column,b=p.line,h=a.arrayMax,l=a.arrayMin,u=a.correctFloat;p=a.extend;var A=a.merge,B=a.objectEach,z=a.pick;a=function(a){function d(){var b=null!==a&&a.apply(this,arguments)||this;b.chart=void 0;b.data=void 0;b.options=void 0;b.points=void 0;b.stackedYNeg=void 0;b.stackedYPos=
void 0;b.stackKey=void 0;b.xData=void 0;b.yAxis=void 0;b.yData=void 0;return b}v(d,a);d.prototype.generatePoints=function(){var a;w.prototype.generatePoints.apply(this);var b=0;for(a=this.points.length;b<a;b++){var g=this.points[b];var q=this.processedYData[b];if(g.isIntermediateSum||g.isSum)g.y=u(q)}};d.prototype.translate=function(){var a=this.options,b=this.yAxis,g,q=z(a.minPointLength,5),c=q/2,d=a.threshold,h=a.stacking,f=b.waterfall.stacks[this.stackKey];w.prototype.translate.apply(this);var e=
g=d;var l=this.points;var k=0;for(a=l.length;k<a;k++){var r=l[k];var v=this.processedYData[k];var u=r.shapeArgs;var p=[0,v];var y=r.y;if(h){if(f){p=f[k];if("overlap"===h){var A=p.stackState[p.stateIndex--];A=0<=y?A:A-y;Object.hasOwnProperty.call(p,"absolutePos")&&delete p.absolutePos;Object.hasOwnProperty.call(p,"absoluteNeg")&&delete p.absoluteNeg}else 0<=y?(A=p.threshold+p.posTotal,p.posTotal-=y):(A=p.threshold+p.negTotal,p.negTotal-=y,A-=y),!p.posTotal&&Object.hasOwnProperty.call(p,"absolutePos")&&
(p.posTotal=p.absolutePos,delete p.absolutePos),!p.negTotal&&Object.hasOwnProperty.call(p,"absoluteNeg")&&(p.negTotal=p.absoluteNeg,delete p.absoluteNeg);r.isSum||(p.connectorThreshold=p.threshold+p.stackTotal);b.reversed?(v=0<=y?A-y:A+y,y=A):(v=A,y=A-y);r.below=v<=z(d,0);u.y=b.translate(v,0,1,0,1);u.height=Math.abs(u.y-b.translate(y,0,1,0,1))}if(y=b.waterfall.dummyStackItem)y.x=k,y.label=f[k].label,y.setOffset(this.pointXOffset||0,this.barW||0,this.stackedYNeg[k],this.stackedYPos[k])}else A=Math.max(e,
e+y)+p[0],u.y=b.translate(A,0,1,0,1),r.isSum?(u.y=b.translate(p[1],0,1,0,1),u.height=Math.min(b.translate(p[0],0,1,0,1),b.len)-u.y):r.isIntermediateSum?(0<=y?(v=p[1]+g,y=g):(v=g,y=p[1]+g),b.reversed&&(v^=y,y^=v,v^=y),u.y=b.translate(v,0,1,0,1),u.height=Math.abs(u.y-Math.min(b.translate(y,0,1,0,1),b.len)),g+=p[1]):(u.height=0<v?b.translate(e,0,1,0,1)-u.y:b.translate(e,0,1,0,1)-b.translate(e-v,0,1,0,1),e+=v,r.below=e<z(d,0)),0>u.height&&(u.y+=u.height,u.height*=-1);r.plotY=u.y=Math.round(u.y)-this.borderWidth%
2/2;u.height=Math.max(Math.round(u.height),.001);r.yBottom=u.y+u.height;u.height<=q&&!r.isNull?(u.height=q,u.y-=c,r.plotY=u.y,r.minPointLengthOffset=0>r.y?-c:c):(r.isNull&&(u.width=0),r.minPointLengthOffset=0);u=r.plotY+(r.negative?u.height:0);this.chart.inverted?r.tooltipPos[0]=b.len-u:r.tooltipPos[1]=u}};d.prototype.processData=function(a){var c=this.options,g=this.yData,q=c.data,d=g.length,n=c.threshold||0,h,e,f,l,m;for(m=e=h=f=l=0;m<d;m++){var k=g[m];var r=q&&q[m]?q[m]:{};"sum"===k||r.isSum?g[m]=
u(e):"intermediateSum"===k||r.isIntermediateSum?(g[m]=u(h),h=0):(e+=k,h+=k);f=Math.min(e,f);l=Math.max(e,l)}b.prototype.processData.call(this,a);c.stacking||(this.dataMin=f+n,this.dataMax=l)};d.prototype.toYData=function(a){return a.isSum?"sum":a.isIntermediateSum?"intermediateSum":a.y};d.prototype.updateParallelArrays=function(a,c){b.prototype.updateParallelArrays.call(this,a,c);if("sum"===this.yData[0]||"intermediateSum"===this.yData[0])this.yData[0]=null};d.prototype.pointAttribs=function(a,b){var g=
this.options.upColor;g&&!a.options.color&&(a.color=0<a.y?g:null);a=w.prototype.pointAttribs.call(this,a,b);delete a.dashstyle;return a};d.prototype.getGraphPath=function(){return[["M",0,0]]};d.prototype.getCrispPath=function(){var a=this.data,b=this.yAxis,g=a.length,c=Math.round(this.graph.strokeWidth())%2/2,d=Math.round(this.borderWidth)%2/2,n=this.xAxis.reversed,h=this.yAxis.reversed,e=this.options.stacking,f=[],l;for(l=1;l<g;l++){var k=a[l].shapeArgs;var u=a[l-1];var r=a[l-1].shapeArgs;var p=b.waterfall.stacks[this.stackKey];
var v=0<u.y?-r.height:0;p&&r&&k&&(p=p[l-1],e?(p=p.connectorThreshold,v=Math.round(b.translate(p,0,1,0,1)+(h?v:0))-c):v=r.y+u.minPointLengthOffset+d-c,f.push(["M",(r.x||0)+(n?0:r.width||0),v],["L",(k.x||0)+(n?k.width||0:0),v]));!e&&f.length&&r&&(0>u.y&&!h||0<u.y&&h)&&(f[f.length-2][2]+=r.height,f[f.length-1][2]+=r.height)}return f};d.prototype.drawGraph=function(){b.prototype.drawGraph.call(this);this.graph.attr({d:this.getCrispPath()})};d.prototype.setStackedPoints=function(){function a(a,b,g,c){if(H)for(g;g<
H;g++)w.stackState[g]+=c;else w.stackState[0]=a,H=w.stackState.length;w.stackState.push(w.stackState[H-1]+b)}var b=this.options,g=this.yAxis.waterfall.stacks,c=b.threshold,d=c||0,n=d,h=this.stackKey,f=this.xData,e=f.length,l,k,r;this.yAxis.stacking.usePercentage=!1;var u=k=r=d;if(this.visible||!this.chart.options.chart.ignoreHiddenSeries){var p=g.changed;(l=g.alreadyChanged)&&0>l.indexOf(h)&&(p=!0);g[h]||(g[h]={});l=g[h];for(var v=0;v<e;v++){var y=f[v];if(!l[y]||p)l[y]={negTotal:0,posTotal:0,stackTotal:0,
threshold:0,stateIndex:0,stackState:[],label:p&&l[y]?l[y].label:void 0};var w=l[y];var A=this.yData[v];0<=A?w.posTotal+=A:w.negTotal+=A;var B=b.data[v];y=w.absolutePos=w.posTotal;var z=w.absoluteNeg=w.negTotal;w.stackTotal=y+z;var H=w.stackState.length;B&&B.isIntermediateSum?(a(r,k,0,r),r=k,k=c,d^=n,n^=d,d^=n):B&&B.isSum?(a(c,u,H),d=c):(a(d,A,0,u),B&&(u+=A,k+=A));w.stateIndex++;w.threshold=d;d+=w.stackTotal}g.changed=!1;g.alreadyChanged||(g.alreadyChanged=[]);g.alreadyChanged.push(h)}};d.prototype.getExtremes=
function(){var a=this.options.stacking;if(a){var b=this.yAxis;b=b.waterfall.stacks;var g=this.stackedYNeg=[];var c=this.stackedYPos=[];"overlap"===a?B(b[this.stackKey],function(a){g.push(l(a.stackState));c.push(h(a.stackState))}):B(b[this.stackKey],function(a){g.push(a.negTotal+a.threshold);c.push(a.posTotal+a.threshold)});return{dataMin:l(g),dataMax:h(c)}}return{dataMin:this.dataMin,dataMax:this.dataMax}};d.defaultOptions=A(w.defaultOptions,{dataLabels:{inside:!0},lineWidth:1,lineColor:c.neutralColor80,
dashStyle:"Dot",borderColor:c.neutralColor80,states:{hover:{lineWidthPlus:0}}});return d}(w);p(a.prototype,{pointValKey:"y",showLine:!0,pointClass:k});e.registerSeriesType("waterfall",a);r.compose(f.Axis,d);"";return a});z(e,"Series/Polygon/PolygonSeries.js",[e["Core/Series/Series.js"],e["Core/Globals.js"],e["Mixins/LegendSymbol.js"],e["Core/Utilities.js"]],function(e,d,f,c){var a=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,
b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),r=e.seriesTypes,k=r.area,v=r.line,p=r.scatter;d=d.noop;r=c.extend;var w=c.merge;c=function(b){function c(){var a=null!==b&&b.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}a(c,b);c.prototype.getGraphPath=function(){for(var a=v.prototype.getGraphPath.call(this),
b=a.length+1;b--;)(b===a.length||"M"===a[b][0])&&0<b&&a.splice(b,0,["Z"]);return this.areaPath=a};c.prototype.drawGraph=function(){this.options.fillColor=this.color;k.prototype.drawGraph.call(this)};c.defaultOptions=w(p.defaultOptions,{marker:{enabled:!1,states:{hover:{enabled:!1}}},stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:""},trackByArea:!0});return c}(p);r(c.prototype,{type:"polygon",drawLegendSymbol:f.drawRectangle,drawTracker:v.prototype.drawTracker,setStackedPoints:d});e.registerSeriesType("polygon",
c);"";return c});z(e,"Series/Bubble/BubblePoint.js",[e["Core/Series/Series.js"],e["Core/Series/Point.js"],e["Core/Utilities.js"]],function(e,d,f){var c=this&&this.__extends||function(){var a=function(c,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var d in c)c.hasOwnProperty(d)&&(a[d]=c[d])};return a(c,d)};return function(c,d){function e(){this.constructor=c}a(c,d);c.prototype=null===d?Object.create(d):(e.prototype=d.prototype,new e)}}();
f=f.extend;e=function(a){function e(){var c=null!==a&&a.apply(this,arguments)||this;c.options=void 0;c.series=void 0;return c}c(e,a);e.prototype.haloPath=function(a){return d.prototype.haloPath.call(this,0===a?0:(this.marker?this.marker.radius||0:0)+a)};return e}(e.seriesTypes.scatter.prototype.pointClass);f(e.prototype,{ttBelow:!1});return e});z(e,"Series/Bubble/BubbleLegend.js",[e["Core/Chart/Chart.js"],e["Core/Color/Color.js"],e["Core/Globals.js"],e["Core/Legend.js"],e["Series/Line/LineSeries.js"],
e["Core/Color/Palette.js"],e["Core/Utilities.js"]],function(e,d,f,c,a,r,k){var v=d.parse,p=f.noop;d=k.addEvent;var w=k.arrayMax,b=k.arrayMin,h=k.isNumber,l=k.merge,u=k.objectEach,A=k.pick,B=k.setOptions,z=k.stableSort,F=k.wrap;"";B({legend:{bubbleLegend:{borderColor:void 0,borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,connectorColor:void 0,connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,align:"right",style:{fontSize:10,
color:void 0},x:0,y:0},maxSize:60,minSize:10,legendIndex:0,ranges:{value:void 0,borderColor:void 0,color:void 0,connectorColor:void 0},sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}}});B=function(){function a(a,b){this.options=this.symbols=this.visible=this.ranges=this.movementX=this.maxLabel=this.legendSymbol=this.legendItemWidth=this.legendItemHeight=this.legendItem=this.legendGroup=this.legend=this.fontMetrics=this.chart=void 0;this.setState=p;this.init(a,b)}a.prototype.init=function(a,
b){this.options=a;this.visible=!0;this.chart=b.chart;this.legend=b};a.prototype.addToLegend=function(a){a.splice(this.options.legendIndex,0,this)};a.prototype.drawLegendSymbol=function(a){var b=this.chart,g=this.options,c=A(a.options.itemDistance,20),d=g.ranges;var n=g.connectorDistance;this.fontMetrics=b.renderer.fontMetrics(g.labels.style.fontSize.toString()+"px");d&&d.length&&h(d[0].value)?(z(d,function(a,b){return b.value-a.value}),this.ranges=d,this.setOptions(),this.render(),b=this.getMaxLabelSize(),
d=this.ranges[0].radius,a=2*d,n=n-d+b.width,n=0<n?n:0,this.maxLabel=b,this.movementX="left"===g.labels.align?n:0,this.legendItemWidth=a+n+c,this.legendItemHeight=a+this.fontMetrics.h/2):a.options.bubbleLegend.autoRanges=!0};a.prototype.setOptions=function(){var a=this.ranges,b=this.options,c=this.chart.series[b.seriesIndex],d=this.legend.baseline,e={"z-index":b.zIndex,"stroke-width":b.borderWidth},n={"z-index":b.zIndex,"stroke-width":b.connectorWidth},f=this.getLabelStyles(),h=c.options.marker.fillOpacity,
k=this.chart.styledMode;a.forEach(function(g,q){k||(e.stroke=A(g.borderColor,b.borderColor,c.color),e.fill=A(g.color,b.color,1!==h?v(c.color).setOpacity(h).get("rgba"):c.color),n.stroke=A(g.connectorColor,b.connectorColor,c.color));a[q].radius=this.getRangeRadius(g.value);a[q]=l(a[q],{center:a[0].radius-a[q].radius+d});k||l(!0,a[q],{bubbleStyle:l(!1,e),connectorStyle:l(!1,n),labelStyle:f})},this)};a.prototype.getLabelStyles=function(){var a=this.options,b={},c="left"===a.labels.align,d=this.legend.options.rtl;
u(a.labels.style,function(a,c){"color"!==c&&"fontSize"!==c&&"z-index"!==c&&(b[c]=a)});return l(!1,b,{"font-size":a.labels.style.fontSize,fill:A(a.labels.style.color,r.neutralColor100),"z-index":a.zIndex,align:d||c?"right":"left"})};a.prototype.getRangeRadius=function(a){var b=this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,b.ranges[b.ranges.length-1].value,b.ranges[0].value,b.minSize,b.maxSize,a)};a.prototype.render=function(){var a=this.chart.renderer,b=this.options.zThreshold;
this.symbols||(this.symbols={connectors:[],bubbleItems:[],labels:[]});this.legendSymbol=a.g("bubble-legend");this.legendItem=a.g("bubble-legend-item");this.legendSymbol.translateX=0;this.legendSymbol.translateY=0;this.ranges.forEach(function(a){a.value>=b&&this.renderRange(a)},this);this.legendSymbol.add(this.legendItem);this.legendItem.add(this.legendGroup);this.hideOverlappingLabels()};a.prototype.renderRange=function(a){var b=this.options,c=b.labels,d=this.chart.renderer,e=this.symbols,n=e.labels,
f=a.center,h=Math.abs(a.radius),l=b.connectorDistance||0,k=c.align,m=c.style.fontSize;l=this.legend.options.rtl||"left"===k?-l:l;c=b.connectorWidth;var r=this.ranges[0].radius||0,p=f-h-b.borderWidth/2+c/2;m=m/2-(this.fontMetrics.h-m)/2;var u=d.styledMode;"center"===k&&(l=0,b.connectorDistance=0,a.labelStyle.align="center");k=p+b.labels.y;var v=r+l+b.labels.x;e.bubbleItems.push(d.circle(r,f+((p%1?1:.5)-(c%2?0:.5)),h).attr(u?{}:a.bubbleStyle).addClass((u?"highcharts-color-"+this.options.seriesIndex+
" ":"")+"highcharts-bubble-legend-symbol "+(b.className||"")).add(this.legendSymbol));e.connectors.push(d.path(d.crispLine([["M",r,p],["L",r+l,p]],b.connectorWidth)).attr(u?{}:a.connectorStyle).addClass((u?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+(b.connectorClassName||"")).add(this.legendSymbol));a=d.text(this.formatLabel(a),v,k+m).attr(u?{}:a.labelStyle).addClass("highcharts-bubble-legend-labels "+(b.labels.className||"")).add(this.legendSymbol);
n.push(a);a.placed=!0;a.alignAttr={x:v,y:k+m}};a.prototype.getMaxLabelSize=function(){var a,b;this.symbols.labels.forEach(function(c){b=c.getBBox(!0);a=a?b.width>a.width?b:a:b});return a||{}};a.prototype.formatLabel=function(a){var b=this.options,c=b.labels.formatter;b=b.labels.format;var d=this.chart.numberFormatter;return b?k.format(b,a):c?c.call(a):d(a.value,1)};a.prototype.hideOverlappingLabels=function(){var a=this.chart,b=this.symbols;!this.options.labels.allowOverlap&&b&&(a.hideOverlappingLabels(b.labels),
b.labels.forEach(function(a,c){a.newOpacity?a.newOpacity!==a.oldOpacity&&b.connectors[c].show():b.connectors[c].hide()}))};a.prototype.getRanges=function(){var a=this.legend.bubbleLegend,c=a.options.ranges,g,d=Number.MAX_VALUE,e=-Number.MAX_VALUE;a.chart.series.forEach(function(a){a.isBubble&&!a.ignoreSeries&&(g=a.zData.filter(h),g.length&&(d=A(a.options.zMin,Math.min(d,Math.max(b(g),!1===a.options.displayNegative?a.options.zThreshold:-Number.MAX_VALUE))),e=A(a.options.zMax,Math.max(e,w(g)))))});
var n=d===e?[{value:e}]:[{value:d},{value:(d+e)/2},{value:e,autoRanges:!0}];c.length&&c[0].radius&&n.reverse();n.forEach(function(a,b){c&&c[b]&&(n[b]=l(!1,c[b],a))});return n};a.prototype.predictBubbleSizes=function(){var a=this.chart,b=this.fontMetrics,c=a.legend.options,d="horizontal"===c.layout,e=d?a.legend.lastLineHeight:0,n=a.plotSizeX,f=a.plotSizeY,h=a.series[this.options.seriesIndex];a=Math.ceil(h.minPxSize);var l=Math.ceil(h.maxPxSize);h=h.options.maxSize;var k=Math.min(f,n);if(c.floating||
!/%$/.test(h))b=l;else if(h=parseFloat(h),b=(k+e-b.h/2)*h/100/(h/100+1),d&&f-b>=n||!d&&n-b>=f)b=l;return[a,Math.ceil(b)]};a.prototype.updateRanges=function(a,b){var c=this.legend.options.bubbleLegend;c.minSize=a;c.maxSize=b;c.ranges=this.getRanges()};a.prototype.correctSizes=function(){var a=this.legend,b=this.chart.series[this.options.seriesIndex];1<Math.abs(Math.ceil(b.maxPxSize)-this.options.maxSize)&&(this.updateRanges(this.options.minSize,b.maxPxSize),a.render())};return a}();d(c,"afterGetAllItems",
function(a){var b=this.bubbleLegend,c=this.options,d=c.bubbleLegend,q=this.chart.getVisibleBubbleSeriesIndex();b&&b.ranges&&b.ranges.length&&(d.ranges.length&&(d.autoRanges=!!d.ranges[0].autoRanges),this.destroyItem(b));0<=q&&c.enabled&&d.enabled&&(d.seriesIndex=q,this.bubbleLegend=new f.BubbleLegend(d,this),this.bubbleLegend.addToLegend(a.allItems))});e.prototype.getVisibleBubbleSeriesIndex=function(){for(var a=this.series,b=0;b<a.length;){if(a[b]&&a[b].isBubble&&a[b].visible&&a[b].zData.length)return b;
b++}return-1};c.prototype.getLinesHeights=function(){var a=this.allItems,b=[],c=a.length,d,q=0;for(d=0;d<c;d++)if(a[d].legendItemHeight&&(a[d].itemHeight=a[d].legendItemHeight),a[d]===a[c-1]||a[d+1]&&a[d]._legendItemPos[1]!==a[d+1]._legendItemPos[1]){b.push({height:0});var e=b[b.length-1];for(q;q<=d;q++)a[q].itemHeight>e.height&&(e.height=a[q].itemHeight);e.step=d}return b};c.prototype.retranslateItems=function(a){var b,c,d,q=this.options.rtl,e=0;this.allItems.forEach(function(g,h){b=g.legendGroup.translateX;
c=g._legendItemPos[1];if((d=g.movementX)||q&&g.ranges)d=q?b-g.options.maxSize/2:b+d,g.legendGroup.attr({translateX:d});h>a[e].step&&e++;g.legendGroup.attr({translateY:Math.round(c+a[e].height/2)});g._legendItemPos[1]=c+a[e].height/2})};d(a,"legendItemClick",function(){var a=this.chart,b=this.visible,c=this.chart.legend;c&&c.bubbleLegend&&(this.visible=!b,this.ignoreSeries=b,a=0<=a.getVisibleBubbleSeriesIndex(),c.bubbleLegend.visible!==a&&(c.update({bubbleLegend:{enabled:a}}),c.bubbleLegend.visible=
a),this.visible=b)});F(e.prototype,"drawChartBox",function(a,b,c){var d=this.legend,q=0<=this.getVisibleBubbleSeriesIndex();if(d&&d.options.enabled&&d.bubbleLegend&&d.options.bubbleLegend.autoRanges&&q){var e=d.bubbleLegend.options;q=d.bubbleLegend.predictBubbleSizes();d.bubbleLegend.updateRanges(q[0],q[1]);e.placed||(d.group.placed=!1,d.allItems.forEach(function(a){a.legendGroup.translateY=null}));d.render();this.getMargins();this.axes.forEach(function(a){a.visible&&a.render();e.placed||(a.setScale(),
a.updateNames(),u(a.ticks,function(a){a.isNew=!0;a.isNewLabel=!0}))});e.placed=!0;this.getMargins();a.call(this,b,c);d.bubbleLegend.correctSizes();d.retranslateItems(d.getLinesHeights())}else a.call(this,b,c),d&&d.options.enabled&&d.bubbleLegend&&(d.render(),d.retranslateItems(d.getLinesHeights()))});f.BubbleLegend=B;return f.BubbleLegend});z(e,"Series/Bubble/BubbleSeries.js",[e["Core/Axis/Axis.js"],e["Core/Series/Series.js"],e["Series/Bubble/BubblePoint.js"],e["Core/Color/Color.js"],e["Core/Globals.js"],
e["Series/Line/LineSeries.js"],e["Core/Utilities.js"]],function(e,d,f,c,a,r,k){var v=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),p=d.seriesTypes,w=p.column,b=p.scatter,h=c.parse;c=a.noop;var l=
k.arrayMax,u=k.arrayMin,A=k.clamp,B=k.extend,z=k.isNumber,F=k.merge,y=k.pick,m=k.pInt;k=function(a){function c(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.maxPxSize=void 0;b.minPxSize=void 0;b.options=void 0;b.points=void 0;b.radii=void 0;b.yData=void 0;b.zData=void 0;return b}v(c,a);c.prototype.animate=function(a){!a&&this.points.length<this.options.animationLimit&&this.points.forEach(function(a){var b=a.graphic;b&&b.width&&(this.hasRendered||b.attr({x:a.plotX,y:a.plotY,width:1,
height:1}),b.animate(this.markerAttribs(a),this.options.animation))},this)};c.prototype.getRadii=function(a,b,c){var d=this.zData,g=this.yData,q=c.minPxSize,e=c.maxPxSize,h=[];var n=0;for(c=d.length;n<c;n++){var f=d[n];h.push(this.getRadius(a,b,q,e,f,g[n]))}this.radii=h};c.prototype.getRadius=function(a,b,c,d,g,e){var q=this.options,h="width"!==q.sizeBy,n=q.zThreshold,f=b-a,l=.5;if(null===e||null===g)return null;if(z(g)){q.sizeByAbsoluteValue&&(g=Math.abs(g-n),f=Math.max(b-n,Math.abs(a-n)),a=0);if(g<
a)return c/2-1;0<f&&(l=(g-a)/f)}h&&0<=l&&(l=Math.sqrt(l));return Math.ceil(c+l*(d-c))/2};c.prototype.hasData=function(){return!!this.processedXData.length};c.prototype.pointAttribs=function(a,b){var c=this.options.marker.fillOpacity;a=r.prototype.pointAttribs.call(this,a,b);1!==c&&(a.fill=h(a.fill).setOpacity(c).get("rgba"));return a};c.prototype.translate=function(){var b,c=this.data,d=this.radii;a.prototype.translate.call(this);for(b=c.length;b--;){var g=c[b];var e=d?d[b]:0;z(e)&&e>=this.minPxSize/
2?(g.marker=B(g.marker,{radius:e,width:2*e,height:2*e}),g.dlBox={x:g.plotX-e,y:g.plotY-e,width:2*e,height:2*e}):g.shapeArgs=g.plotY=g.dlBox=void 0}};c.defaultOptions=F(b.defaultOptions,{dataLabels:{formatter:function(){return this.point.z},inside:!0,verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},
turboThreshold:0,zThreshold:0,zoneAxis:"z"});return c}(b);B(k.prototype,{alignDataLabel:w.prototype.alignDataLabel,applyZones:c,bubblePadding:!0,buildKDTree:c,directTouch:!0,isBubble:!0,pointArrayMap:["y","z"],pointClass:f,parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",zoneAxis:"z"});e.prototype.beforePadding=function(){var a=this,b=this.len,c=this.chart,d=0,e=b,h=this.isXAxis,f=h?"xData":"yData",k=this.min,r={},p=Math.min(c.plotWidth,c.plotHeight),v=Number.MAX_VALUE,
w=-Number.MAX_VALUE,B=this.max-k,I=b/B,H=[];this.series.forEach(function(b){var d=b.options;!b.bubblePadding||!b.visible&&c.options.chart.ignoreHiddenSeries||(a.allowZoomOutside=!0,H.push(b),h&&(["minSize","maxSize"].forEach(function(a){var b=d[a],c=/%$/.test(b);b=m(b);r[a]=c?p*b/100:b}),b.minPxSize=r.minSize,b.maxPxSize=Math.max(r.maxSize,r.minSize),b=b.zData.filter(z),b.length&&(v=y(d.zMin,A(u(b),!1===d.displayNegative?d.zThreshold:-Number.MAX_VALUE,v)),w=y(d.zMax,Math.max(w,l(b))))))});H.forEach(function(b){var c=
b[f],g=c.length;h&&b.getRadii(v,w,b);if(0<B)for(;g--;)if(z(c[g])&&a.dataMin<=c[g]&&c[g]<=a.max){var q=b.radii?b.radii[g]:0;d=Math.min((c[g]-k)*I-q,d);e=Math.max((c[g]-k)*I+q,e)}});H.length&&0<B&&!this.logarithmic&&(e-=b,I*=(b+Math.max(0,d)-Math.min(e,b))/b,[["min","userMin",d],["max","userMax",e]].forEach(function(b){"undefined"===typeof y(a.options[b[0]],a[b[1]])&&(a[b[0]]+=b[2]/I)}))};d.registerSeriesType("bubble",k);"";"";return k});z(e,"Series/PackedBubble/PackedBubblePoint.js",[e["Core/Series/Series.js"],
e["Core/Chart/Chart.js"],e["Core/Series/Point.js"]],function(e,d,f){var c=this&&this.__extends||function(){var a=function(c,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var d in c)c.hasOwnProperty(d)&&(a[d]=c[d])};return a(c,d)};return function(c,d){function e(){this.constructor=c}a(c,d);c.prototype=null===d?Object.create(d):(e.prototype=d.prototype,new e)}}();return function(a){function e(){var c=null!==a&&a.apply(this,arguments)||this;
c.degree=NaN;c.mass=NaN;c.radius=NaN;c.options=void 0;c.series=void 0;c.value=null;return c}c(e,a);e.prototype.destroy=function(){this.series.layout&&this.series.layout.removeElementFromCollection(this,this.series.layout.nodes);return f.prototype.destroy.apply(this,arguments)};e.prototype.firePointEvent=function(){var a=this.series.options;if(this.isParentNode&&a.parentNode){var c=a.allowPointSelect;a.allowPointSelect=a.parentNode.allowPointSelect;f.prototype.firePointEvent.apply(this,arguments);
a.allowPointSelect=c}else f.prototype.firePointEvent.apply(this,arguments)};e.prototype.select=function(){var a=this.series.chart;this.isParentNode?(a.getSelectedPoints=a.getSelectedParentNodes,f.prototype.select.apply(this,arguments),a.getSelectedPoints=d.prototype.getSelectedPoints):f.prototype.select.apply(this,arguments)};return e}(e.seriesTypes.bubble.prototype.pointClass)});z(e,"Series/Networkgraph/DraggableNodes.js",[e["Core/Chart/Chart.js"],e["Core/Globals.js"],e["Core/Utilities.js"]],function(e,
d,f){var c=f.addEvent;d.dragNodesMixin={onMouseDown:function(a,c){c=this.chart.pointer.normalize(c);a.fixedPosition={chartX:c.chartX,chartY:c.chartY,plotX:a.plotX,plotY:a.plotY};a.inDragMode=!0},onMouseMove:function(a,c){if(a.fixedPosition&&a.inDragMode){var d=this.chart;c=d.pointer.normalize(c);var e=a.fixedPosition.chartX-c.chartX,f=a.fixedPosition.chartY-c.chartY;c=d.graphLayoutsLookup;if(5<Math.abs(e)||5<Math.abs(f))e=a.fixedPosition.plotX-e,f=a.fixedPosition.plotY-f,d.isInsidePlot(e,f)&&(a.plotX=
e,a.plotY=f,a.hasDragged=!0,this.redrawHalo(a),c.forEach(function(a){a.restartSimulation()}))}},onMouseUp:function(a,c){a.fixedPosition&&(a.hasDragged&&(this.layout.enableSimulation?this.layout.start():this.chart.redraw()),a.inDragMode=a.hasDragged=!1,this.options.fixedDraggable||delete a.fixedPosition)},redrawHalo:function(a){a&&this.halo&&this.halo.attr({d:a.haloPath(this.options.states.hover.halo.size)})}};c(e,"load",function(){var a=this,d,e,f;a.container&&(d=c(a.container,"mousedown",function(d){var k=
a.hoverPoint;k&&k.series&&k.series.hasDraggableNodes&&k.series.options.draggable&&(k.series.onMouseDown(k,d),e=c(a.container,"mousemove",function(a){return k&&k.series&&k.series.onMouseMove(k,a)}),f=c(a.container.ownerDocument,"mouseup",function(a){e();f();return k&&k.series&&k.series.onMouseUp(k,a)}))}));c(a,"destroy",function(){d()})})});z(e,"Series/Networkgraph/Integrations.js",[e["Core/Globals.js"]],function(e){e.networkgraphIntegrations={verlet:{attractiveForceFunction:function(d,e){return(e-
d)/d},repulsiveForceFunction:function(d,e){return(e-d)/d*(e>d?1:0)},barycenter:function(){var d=this.options.gravitationalConstant,e=this.barycenter.xFactor,c=this.barycenter.yFactor;e=(e-(this.box.left+this.box.width)/2)*d;c=(c-(this.box.top+this.box.height)/2)*d;this.nodes.forEach(function(a){a.fixedPosition||(a.plotX-=e/a.mass/a.degree,a.plotY-=c/a.mass/a.degree)})},repulsive:function(d,e,c){e=e*this.diffTemperature/d.mass/d.degree;d.fixedPosition||(d.plotX+=c.x*e,d.plotY+=c.y*e)},attractive:function(d,
e,c){var a=d.getMass(),f=-c.x*e*this.diffTemperature;e=-c.y*e*this.diffTemperature;d.fromNode.fixedPosition||(d.fromNode.plotX-=f*a.fromNode/d.fromNode.degree,d.fromNode.plotY-=e*a.fromNode/d.fromNode.degree);d.toNode.fixedPosition||(d.toNode.plotX+=f*a.toNode/d.toNode.degree,d.toNode.plotY+=e*a.toNode/d.toNode.degree)},integrate:function(d,e){var c=-d.options.friction,a=d.options.maxSpeed,f=(e.plotX+e.dispX-e.prevX)*c;c*=e.plotY+e.dispY-e.prevY;var k=Math.abs,v=k(f)/(f||1);k=k(c)/(c||1);f=v*Math.min(a,
Math.abs(f));c=k*Math.min(a,Math.abs(c));e.prevX=e.plotX+e.dispX;e.prevY=e.plotY+e.dispY;e.plotX+=f;e.plotY+=c;e.temperature=d.vectorLength({x:f,y:c})},getK:function(d){return Math.pow(d.box.width*d.box.height/d.nodes.length,.5)}},euler:{attractiveForceFunction:function(d,e){return d*d/e},repulsiveForceFunction:function(d,e){return e*e/d},barycenter:function(){var d=this.options.gravitationalConstant,e=this.barycenter.xFactor,c=this.barycenter.yFactor;this.nodes.forEach(function(a){if(!a.fixedPosition){var f=
a.getDegree();f*=1+f/2;a.dispX+=(e-a.plotX)*d*f/a.degree;a.dispY+=(c-a.plotY)*d*f/a.degree}})},repulsive:function(d,e,c,a){d.dispX+=c.x/a*e/d.degree;d.dispY+=c.y/a*e/d.degree},attractive:function(d,e,c,a){var f=d.getMass(),k=c.x/a*e;e*=c.y/a;d.fromNode.fixedPosition||(d.fromNode.dispX-=k*f.fromNode/d.fromNode.degree,d.fromNode.dispY-=e*f.fromNode/d.fromNode.degree);d.toNode.fixedPosition||(d.toNode.dispX+=k*f.toNode/d.toNode.degree,d.toNode.dispY+=e*f.toNode/d.toNode.degree)},integrate:function(d,
e){e.dispX+=e.dispX*d.options.friction;e.dispY+=e.dispY*d.options.friction;var c=e.temperature=d.vectorLength({x:e.dispX,y:e.dispY});0!==c&&(e.plotX+=e.dispX/c*Math.min(Math.abs(e.dispX),d.temperature),e.plotY+=e.dispY/c*Math.min(Math.abs(e.dispY),d.temperature))},getK:function(d){return Math.pow(d.box.width*d.box.height/d.nodes.length,.3)}}}});z(e,"Series/Networkgraph/QuadTree.js",[e["Core/Globals.js"],e["Core/Utilities.js"]],function(e,d){d=d.extend;var f=e.QuadTreeNode=function(c){this.box=c;this.boxSize=
Math.min(c.width,c.height);this.nodes=[];this.body=this.isInternal=!1;this.isEmpty=!0};d(f.prototype,{insert:function(c,a){this.isInternal?this.nodes[this.getBoxPosition(c)].insert(c,a-1):(this.isEmpty=!1,this.body?a?(this.isInternal=!0,this.divideBox(),!0!==this.body&&(this.nodes[this.getBoxPosition(this.body)].insert(this.body,a-1),this.body=!0),this.nodes[this.getBoxPosition(c)].insert(c,a-1)):(a=new f({top:c.plotX,left:c.plotY,width:.1,height:.1}),a.body=c,a.isInternal=!1,this.nodes.push(a)):
(this.isInternal=!1,this.body=c))},updateMassAndCenter:function(){var c=0,a=0,d=0;this.isInternal?(this.nodes.forEach(function(e){e.isEmpty||(c+=e.mass,a+=e.plotX*e.mass,d+=e.plotY*e.mass)}),a/=c,d/=c):this.body&&(c=this.body.mass,a=this.body.plotX,d=this.body.plotY);this.mass=c;this.plotX=a;this.plotY=d},divideBox:function(){var c=this.box.width/2,a=this.box.height/2;this.nodes[0]=new f({left:this.box.left,top:this.box.top,width:c,height:a});this.nodes[1]=new f({left:this.box.left+c,top:this.box.top,
width:c,height:a});this.nodes[2]=new f({left:this.box.left+c,top:this.box.top+a,width:c,height:a});this.nodes[3]=new f({left:this.box.left,top:this.box.top+a,width:c,height:a})},getBoxPosition:function(c){var a=c.plotY<this.box.top+this.box.height/2;return c.plotX<this.box.left+this.box.width/2?a?0:3:a?1:2}});e=e.QuadTree=function(c,a,d,e){this.box={left:c,top:a,width:d,height:e};this.maxDepth=25;this.root=new f(this.box,"0");this.root.isInternal=!0;this.root.isRoot=!0;this.root.divideBox()};d(e.prototype,
{insertNodes:function(c){c.forEach(function(a){this.root.insert(a,this.maxDepth)},this)},visitNodeRecursive:function(c,a,d){var e;c||(c=this.root);c===this.root&&a&&(e=a(c));!1!==e&&(c.nodes.forEach(function(c){if(c.isInternal){a&&(e=a(c));if(!1===e)return;this.visitNodeRecursive(c,a,d)}else c.body&&a&&a(c.body);d&&d(c)},this),c===this.root&&d&&d(c))},calculateMassAndCenter:function(){this.visitNodeRecursive(null,null,function(c){c.updateMassAndCenter()})}})});z(e,"Series/Networkgraph/Layouts.js",
[e["Core/Chart/Chart.js"],e["Core/Animation/AnimationUtilities.js"],e["Core/Globals.js"],e["Core/Utilities.js"]],function(e,d,f,c){var a=d.setAnimation;d=c.addEvent;var r=c.clamp,k=c.defined,v=c.extend,p=c.isFunction,w=c.pick;f.layouts={"reingold-fruchterman":function(){}};v(f.layouts["reingold-fruchterman"].prototype,{init:function(a){this.options=a;this.nodes=[];this.links=[];this.series=[];this.box={x:0,y:0,width:0,height:0};this.setInitialRendering(!0);this.integration=f.networkgraphIntegrations[a.integration];
this.enableSimulation=a.enableSimulation;this.attractiveForce=w(a.attractiveForce,this.integration.attractiveForceFunction);this.repulsiveForce=w(a.repulsiveForce,this.integration.repulsiveForceFunction);this.approximation=a.approximation},updateSimulation:function(a){this.enableSimulation=w(a,this.options.enableSimulation)},start:function(){var a=this.series,c=this.options;this.currentStep=0;this.forces=a[0]&&a[0].forces||[];this.chart=a[0]&&a[0].chart;this.initialRendering&&(this.initPositions(),
a.forEach(function(a){a.finishedAnimating=!0;a.render()}));this.setK();this.resetSimulation(c);this.enableSimulation&&this.step()},step:function(){var a=this,c=this.series;a.currentStep++;"barnes-hut"===a.approximation&&(a.createQuadTree(),a.quadTree.calculateMassAndCenter());a.forces.forEach(function(b){a[b+"Forces"](a.temperature)});a.applyLimits(a.temperature);a.temperature=a.coolDown(a.startTemperature,a.diffTemperature,a.currentStep);a.prevSystemTemperature=a.systemTemperature;a.systemTemperature=
a.getSystemTemperature();a.enableSimulation&&(c.forEach(function(a){a.chart&&a.render()}),a.maxIterations--&&isFinite(a.temperature)&&!a.isStable()?(a.simulation&&f.win.cancelAnimationFrame(a.simulation),a.simulation=f.win.requestAnimationFrame(function(){a.step()})):a.simulation=!1)},stop:function(){this.simulation&&f.win.cancelAnimationFrame(this.simulation)},setArea:function(a,c,d,e){this.box={left:a,top:c,width:d,height:e}},setK:function(){this.k=this.options.linkLength||this.integration.getK(this)},
addElementsToCollection:function(a,c){a.forEach(function(a){-1===c.indexOf(a)&&c.push(a)})},removeElementFromCollection:function(a,c){a=c.indexOf(a);-1!==a&&c.splice(a,1)},clear:function(){this.nodes.length=0;this.links.length=0;this.series.length=0;this.resetSimulation()},resetSimulation:function(){this.forcedStop=!1;this.systemTemperature=0;this.setMaxIterations();this.setTemperature();this.setDiffTemperature()},restartSimulation:function(){this.simulation?this.resetSimulation():(this.setInitialRendering(!1),
this.enableSimulation?this.start():this.setMaxIterations(1),this.chart&&this.chart.redraw(),this.setInitialRendering(!0))},setMaxIterations:function(a){this.maxIterations=w(a,this.options.maxIterations)},setTemperature:function(){this.temperature=this.startTemperature=Math.sqrt(this.nodes.length)},setDiffTemperature:function(){this.diffTemperature=this.startTemperature/(this.options.maxIterations+1)},setInitialRendering:function(a){this.initialRendering=a},createQuadTree:function(){this.quadTree=
new f.QuadTree(this.box.left,this.box.top,this.box.width,this.box.height);this.quadTree.insertNodes(this.nodes)},initPositions:function(){var a=this.options.initialPositions;p(a)?(a.call(this),this.nodes.forEach(function(a){k(a.prevX)||(a.prevX=a.plotX);k(a.prevY)||(a.prevY=a.plotY);a.dispX=0;a.dispY=0})):"circle"===a?this.setCircularPositions():this.setRandomPositions()},setCircularPositions:function(){function a(b){b.linksFrom.forEach(function(b){p[b.toNode.id]||(p[b.toNode.id]=!0,k.push(b.toNode),
a(b.toNode))})}var c=this.box,d=this.nodes,e=2*Math.PI/(d.length+1),f=d.filter(function(a){return 0===a.linksTo.length}),k=[],p={},v=this.options.initialPositionRadius;f.forEach(function(b){k.push(b);a(b)});k.length?d.forEach(function(a){-1===k.indexOf(a)&&k.push(a)}):k=d;k.forEach(function(a,b){a.plotX=a.prevX=w(a.plotX,c.width/2+v*Math.cos(b*e));a.plotY=a.prevY=w(a.plotY,c.height/2+v*Math.sin(b*e));a.dispX=0;a.dispY=0})},setRandomPositions:function(){function a(a){a=a*a/Math.PI;return a-=Math.floor(a)}
var c=this.box,d=this.nodes,e=d.length+1;d.forEach(function(b,d){b.plotX=b.prevX=w(b.plotX,c.width*a(d));b.plotY=b.prevY=w(b.plotY,c.height*a(e+d));b.dispX=0;b.dispY=0})},force:function(a){this.integration[a].apply(this,Array.prototype.slice.call(arguments,1))},barycenterForces:function(){this.getBarycenter();this.force("barycenter")},getBarycenter:function(){var a=0,c=0,d=0;this.nodes.forEach(function(b){c+=b.plotX*b.mass;d+=b.plotY*b.mass;a+=b.mass});return this.barycenter={x:c,y:d,xFactor:c/a,
yFactor:d/a}},barnesHutApproximation:function(a,c){var b=this.getDistXY(a,c),d=this.vectorLength(b);if(a!==c&&0!==d)if(c.isInternal)if(c.boxSize/d<this.options.theta&&0!==d){var e=this.repulsiveForce(d,this.k);this.force("repulsive",a,e*c.mass,b,d);var h=!1}else h=!0;else e=this.repulsiveForce(d,this.k),this.force("repulsive",a,e*c.mass,b,d);return h},repulsiveForces:function(){var a=this;"barnes-hut"===a.approximation?a.nodes.forEach(function(b){a.quadTree.visitNodeRecursive(null,function(c){return a.barnesHutApproximation(b,
c)})}):a.nodes.forEach(function(b){a.nodes.forEach(function(c){if(b!==c&&!b.fixedPosition){var d=a.getDistXY(b,c);var e=a.vectorLength(d);if(0!==e){var h=a.repulsiveForce(e,a.k);a.force("repulsive",b,h*c.mass,d,e)}}})})},attractiveForces:function(){var a=this,c,d,e;a.links.forEach(function(b){b.fromNode&&b.toNode&&(c=a.getDistXY(b.fromNode,b.toNode),d=a.vectorLength(c),0!==d&&(e=a.attractiveForce(d,a.k),a.force("attractive",b,e,c,d)))})},applyLimits:function(){var a=this;a.nodes.forEach(function(b){b.fixedPosition||
(a.integration.integrate(a,b),a.applyLimitBox(b,a.box),b.dispX=0,b.dispY=0)})},applyLimitBox:function(a,c){var b=a.radius;a.plotX=r(a.plotX,c.left+b,c.width-b);a.plotY=r(a.plotY,c.top+b,c.height-b)},coolDown:function(a,c,d){return a-c*d},isStable:function(){return.00001>Math.abs(this.systemTemperature-this.prevSystemTemperature)||0>=this.temperature},getSystemTemperature:function(){return this.nodes.reduce(function(a,c){return a+c.temperature},0)},vectorLength:function(a){return Math.sqrt(a.x*a.x+
a.y*a.y)},getDistR:function(a,c){a=this.getDistXY(a,c);return this.vectorLength(a)},getDistXY:function(a,c){var b=a.plotX-c.plotX;a=a.plotY-c.plotY;return{x:b,y:a,absX:Math.abs(b),absY:Math.abs(a)}}});d(e,"predraw",function(){this.graphLayoutsLookup&&this.graphLayoutsLookup.forEach(function(a){a.stop()})});d(e,"render",function(){function b(a){a.maxIterations--&&isFinite(a.temperature)&&!a.isStable()&&!a.enableSimulation&&(a.beforeStep&&a.beforeStep(),a.step(),d=!1,c=!0)}var c=!1;if(this.graphLayoutsLookup){a(!1,
this);for(this.graphLayoutsLookup.forEach(function(a){a.start()});!d;){var d=!0;this.graphLayoutsLookup.forEach(b)}c&&this.series.forEach(function(a){a&&a.layout&&a.render()})}});d(e,"beforePrint",function(){this.graphLayoutsLookup&&(this.graphLayoutsLookup.forEach(function(a){a.updateSimulation(!1)}),this.redraw())});d(e,"afterPrint",function(){this.graphLayoutsLookup&&this.graphLayoutsLookup.forEach(function(a){a.updateSimulation()});this.redraw()})});z(e,"Series/PackedBubble/PackedBubbleComposition.js",
[e["Core/Chart/Chart.js"],e["Core/Globals.js"],e["Core/Utilities.js"]],function(e,d,f){var c=d.layouts["reingold-fruchterman"],a=f.addEvent,r=f.extendClass,k=f.pick;e.prototype.getSelectedParentNodes=function(){var a=[];this.series.forEach(function(c){c.parentNode&&c.parentNode.selected&&a.push(c.parentNode)});return a};d.networkgraphIntegrations.packedbubble={repulsiveForceFunction:function(a,c,d,b){return Math.min(a,(d.marker.radius+b.marker.radius)/2)},barycenter:function(){var a=this,c=a.options.gravitationalConstant,
d=a.box,b=a.nodes,e,f;b.forEach(function(h){a.options.splitSeries&&!h.isParentNode?(e=h.series.parentNode.plotX,f=h.series.parentNode.plotY):(e=d.width/2,f=d.height/2);h.fixedPosition||(h.plotX-=(h.plotX-e)*c/(h.mass*Math.sqrt(b.length)),h.plotY-=(h.plotY-f)*c/(h.mass*Math.sqrt(b.length)))})},repulsive:function(a,c,d,b){var e=c*this.diffTemperature/a.mass/a.degree;c=d.x*e;d=d.y*e;a.fixedPosition||(a.plotX+=c,a.plotY+=d);b.fixedPosition||(b.plotX-=c,b.plotY-=d)},integrate:d.networkgraphIntegrations.verlet.integrate,
getK:d.noop};d.layouts.packedbubble=r(c,{beforeStep:function(){this.options.marker&&this.series.forEach(function(a){a&&a.calculateParentRadius()})},setCircularPositions:function(){var a=this,c=a.box,d=a.nodes,b=2*Math.PI/(d.length+1),e,f,r=a.options.initialPositionRadius;d.forEach(function(d,h){a.options.splitSeries&&!d.isParentNode?(e=d.series.parentNode.plotX,f=d.series.parentNode.plotY):(e=c.width/2,f=c.height/2);d.plotX=d.prevX=k(d.plotX,e+r*Math.cos(d.index||h*b));d.plotY=d.prevY=k(d.plotY,f+
r*Math.sin(d.index||h*b));d.dispX=0;d.dispY=0})},repulsiveForces:function(){var a=this,c,d,b,e=a.options.bubblePadding;a.nodes.forEach(function(f){f.degree=f.mass;f.neighbours=0;a.nodes.forEach(function(h){c=0;f===h||f.fixedPosition||!a.options.seriesInteraction&&f.series!==h.series||(b=a.getDistXY(f,h),d=a.vectorLength(b)-(f.marker.radius+h.marker.radius+e),0>d&&(f.degree+=.01,f.neighbours++,c=a.repulsiveForce(-d/Math.sqrt(f.neighbours),a.k,f,h)),a.force("repulsive",f,c*h.mass,b,h,d))})})},applyLimitBox:function(a){if(this.options.splitSeries&&
!a.isParentNode&&this.options.parentNodeLimit){var d=this.getDistXY(a,a.series.parentNode);var e=a.series.parentNodeRadius-a.marker.radius-this.vectorLength(d);0>e&&e>-2*a.marker.radius&&(a.plotX-=.01*d.x,a.plotY-=.01*d.y)}c.prototype.applyLimitBox.apply(this,arguments)}});a(e,"beforeRedraw",function(){this.allDataPoints&&delete this.allDataPoints})});z(e,"Series/PackedBubble/PackedBubbleSeries.js",[e["Core/Series/Series.js"],e["Core/Color/Color.js"],e["Core/Globals.js"],e["Series/PackedBubble/PackedBubblePoint.js"],
e["Core/Utilities.js"]],function(e,d,f,c,a){var r=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),k=e.seriesTypes,v=k.bubble,p=k.line,w=d.parse,b=a.addEvent,h=a.clamp,l=a.defined,u=a.extend,A=a.fireEvent,
z=a.isArray,B=a.isNumber,F=a.merge,y=a.pick,m=f.dragNodesMixin;d=function(a){function c(){var b=null!==a&&a.apply(this,arguments)||this;b.chart=void 0;b.data=void 0;b.layout=void 0;b.options=void 0;b.points=void 0;b.xData=void 0;return b}r(c,a);c.prototype.accumulateAllPoints=function(a){var b=a.chart,c=[],d,e;for(d=0;d<b.series.length;d++)if(a=b.series[d],a.is("packedbubble")&&a.visible||!b.options.chart.ignoreHiddenSeries)for(e=0;e<a.yData.length;e++)c.push([null,null,a.yData[e],a.index,e,{id:e,
marker:{radius:0}}]);return c};c.prototype.addLayout=function(){var a=this.options.layoutAlgorithm,b=this.chart.graphLayoutsStorage,c=this.chart.graphLayoutsLookup,d=this.chart.options.chart;b||(this.chart.graphLayoutsStorage=b={},this.chart.graphLayoutsLookup=c=[]);var e=b[a.type];e||(a.enableSimulation=l(d.forExport)?!d.forExport:a.enableSimulation,b[a.type]=e=new f.layouts[a.type],e.init(a),c.splice(e.index,0,e));this.layout=e;this.points.forEach(function(a){a.mass=2;a.degree=1;a.collisionNmb=
1});e.setArea(0,0,this.chart.plotWidth,this.chart.plotHeight);e.addElementsToCollection([this],e.series);e.addElementsToCollection(this.points,e.nodes)};c.prototype.addSeriesLayout=function(){var a=this.options.layoutAlgorithm,b=this.chart.graphLayoutsStorage,c=this.chart.graphLayoutsLookup,d=F(a,a.parentNodeOptions,{enableSimulation:this.layout.options.enableSimulation});var e=b[a.type+"-series"];e||(b[a.type+"-series"]=e=new f.layouts[a.type],e.init(d),c.splice(e.index,0,e));this.parentNodeLayout=
e;this.createParentNodes()};c.prototype.calculateParentRadius=function(){var a=this.seriesBox();this.parentNodeRadius=h(Math.sqrt(2*this.parentNodeMass/Math.PI)+20,20,a?Math.max(Math.sqrt(Math.pow(a.width,2)+Math.pow(a.height,2))/2+20,20):Math.sqrt(2*this.parentNodeMass/Math.PI)+20);this.parentNode&&(this.parentNode.marker.radius=this.parentNode.radius=this.parentNodeRadius)};c.prototype.calculateZExtremes=function(){var a=this.options.zMin,b=this.options.zMax,c=Infinity,d=-Infinity;if(a&&b)return[a,
b];this.chart.series.forEach(function(a){a.yData.forEach(function(a){l(a)&&(a>d&&(d=a),a<c&&(c=a))})});a=y(a,c);b=y(b,d);return[a,b]};c.prototype.checkOverlap=function(a,b){var c=a[0]-b[0],d=a[1]-b[1];return-.001>Math.sqrt(c*c+d*d)-Math.abs(a[2]+b[2])};c.prototype.createParentNodes=function(){var a=this,b=a.chart,c=a.parentNodeLayout,d,e=a.parentNode,g=a.pointClass;a.parentNodeMass=0;a.points.forEach(function(b){a.parentNodeMass+=Math.PI*Math.pow(b.marker.radius,2)});a.calculateParentRadius();c.nodes.forEach(function(b){b.seriesIndex===
a.index&&(d=!0)});c.setArea(0,0,b.plotWidth,b.plotHeight);d||(e||(e=(new g).init(this,{mass:a.parentNodeRadius/2,marker:{radius:a.parentNodeRadius},dataLabels:{inside:!1},dataLabelOnNull:!0,degree:a.parentNodeRadius,isParentNode:!0,seriesIndex:a.index})),a.parentNode&&(e.plotX=a.parentNode.plotX,e.plotY=a.parentNode.plotY),a.parentNode=e,c.addElementsToCollection([a],c.series),c.addElementsToCollection([e],c.nodes))};c.prototype.deferLayout=function(){var a=this.options.layoutAlgorithm;this.visible&&
(this.addLayout(),a.splitSeries&&this.addSeriesLayout())};c.prototype.destroy=function(){this.chart.graphLayoutsLookup&&this.chart.graphLayoutsLookup.forEach(function(a){a.removeElementFromCollection(this,a.series)},this);this.parentNode&&this.parentNodeLayout&&(this.parentNodeLayout.removeElementFromCollection(this.parentNode,this.parentNodeLayout.nodes),this.parentNode.dataLabel&&(this.parentNode.dataLabel=this.parentNode.dataLabel.destroy()));p.prototype.destroy.apply(this,arguments)};c.prototype.drawDataLabels=
function(){var a=this.options.dataLabels.textPath,b=this.points;p.prototype.drawDataLabels.apply(this,arguments);this.parentNode&&(this.parentNode.formatPrefix="parentNode",this.points=[this.parentNode],this.options.dataLabels.textPath=this.options.dataLabels.parentNodeTextPath,p.prototype.drawDataLabels.apply(this,arguments),this.points=b,this.options.dataLabels.textPath=a)};c.prototype.drawGraph=function(){if(this.layout&&this.layout.options.splitSeries){var a=this.chart,b=this.layout.options.parentNodeOptions.marker;
b={fill:b.fillColor||w(this.color).brighten(.4).get(),opacity:b.fillOpacity,stroke:b.lineColor||this.color,"stroke-width":b.lineWidth};var c=this.visible?"inherit":"hidden";this.parentNodesGroup||(this.parentNodesGroup=this.plotGroup("parentNodesGroup","parentNode",c,.1,a.seriesGroup),this.group.attr({zIndex:2}));this.calculateParentRadius();c=F({x:this.parentNode.plotX-this.parentNodeRadius,y:this.parentNode.plotY-this.parentNodeRadius,width:2*this.parentNodeRadius,height:2*this.parentNodeRadius},
b);this.parentNode.graphic||(this.graph=this.parentNode.graphic=a.renderer.symbol(b.symbol).add(this.parentNodesGroup));this.parentNode.graphic.attr(c)}};c.prototype.drawTracker=function(){var b=this.parentNode;a.prototype.drawTracker.call(this);if(b){var c=z(b.dataLabels)?b.dataLabels:b.dataLabel?[b.dataLabel]:[];b.graphic&&(b.graphic.element.point=b);c.forEach(function(a){a.div?a.div.point=b:a.element.point=b})}};c.prototype.getPointRadius=function(){var a=this,b=a.chart,c=a.options,d=c.useSimulation,
e=Math.min(b.plotWidth,b.plotHeight),g={},f=[],k=b.allDataPoints,l,t,m,p;["minSize","maxSize"].forEach(function(a){var b=parseInt(c[a],10),d=/%$/.test(c[a]);g[a]=d?e*b/100:b*Math.sqrt(k.length)});b.minRadius=l=g.minSize/Math.sqrt(k.length);b.maxRadius=t=g.maxSize/Math.sqrt(k.length);var r=d?a.calculateZExtremes():[l,t];(k||[]).forEach(function(b,c){m=d?h(b[2],r[0],r[1]):b[2];p=a.getRadius(r[0],r[1],l,t,m);0===p&&(p=null);k[c][2]=p;f.push(p)});a.radii=f};c.prototype.init=function(){p.prototype.init.apply(this,
arguments);this.eventsToUnbind.push(b(this,"updatedData",function(){this.chart.series.forEach(function(a){a.type===this.type&&(a.isDirty=!0)},this)}));return this};c.prototype.onMouseUp=function(a){if(a.fixedPosition&&!a.removed){var b,c,d=this.layout,e=this.parentNodeLayout;e&&d.options.dragBetweenSeries&&e.nodes.forEach(function(e){a&&a.marker&&e!==a.series.parentNode&&(b=d.getDistXY(a,e),c=d.vectorLength(b)-e.marker.radius-a.marker.radius,0>c&&(e.series.addPoint(F(a.options,{plotX:a.plotX,plotY:a.plotY}),
!1),d.removeElementFromCollection(a,d.nodes),a.remove()))});m.onMouseUp.apply(this,arguments)}};c.prototype.placeBubbles=function(a){var b=this.checkOverlap,c=this.positionBubble,d=[],e=1,g=0,f=0;var h=[];var q;a=a.sort(function(a,b){return b[2]-a[2]});if(a.length){d.push([[0,0,a[0][2],a[0][3],a[0][4]]]);if(1<a.length)for(d.push([[0,0-a[1][2]-a[0][2],a[1][2],a[1][3],a[1][4]]]),q=2;q<a.length;q++)a[q][2]=a[q][2]||1,h=c(d[e][g],d[e-1][f],a[q]),b(h,d[e][0])?(d.push([]),f=0,d[e+1].push(c(d[e][g],d[e][0],
a[q])),e++,g=0):1<e&&d[e-1][f+1]&&b(h,d[e-1][f+1])?(f++,d[e].push(c(d[e][g],d[e-1][f],a[q])),g++):(g++,d[e].push(h));this.chart.stages=d;this.chart.rawPositions=[].concat.apply([],d);this.resizeRadius();h=this.chart.rawPositions}return h};c.prototype.positionBubble=function(a,b,c){var d=Math.sqrt,e=Math.asin,g=Math.acos,f=Math.pow,h=Math.abs;d=d(f(a[0]-b[0],2)+f(a[1]-b[1],2));g=g((f(d,2)+f(c[2]+b[2],2)-f(c[2]+a[2],2))/(2*(c[2]+b[2])*d));e=e(h(a[0]-b[0])/d);a=(0>a[1]-b[1]?0:Math.PI)+g+e*(0>(a[0]-b[0])*
(a[1]-b[1])?1:-1);return[b[0]+(b[2]+c[2])*Math.sin(a),b[1]-(b[2]+c[2])*Math.cos(a),c[2],c[3],c[4]]};c.prototype.render=function(){var a=[];p.prototype.render.apply(this,arguments);this.options.dataLabels.allowOverlap||(this.data.forEach(function(b){z(b.dataLabels)&&b.dataLabels.forEach(function(b){a.push(b)})}),this.options.useSimulation&&this.chart.hideOverlappingLabels(a))};c.prototype.resizeRadius=function(){var a=this.chart,b=a.rawPositions,c=Math.min,d=Math.max,e=a.plotLeft,g=a.plotTop,f=a.plotHeight,
h=a.plotWidth,k,l,t;var m=k=Number.POSITIVE_INFINITY;var p=l=Number.NEGATIVE_INFINITY;for(t=0;t<b.length;t++){var r=b[t][2];m=c(m,b[t][0]-r);p=d(p,b[t][0]+r);k=c(k,b[t][1]-r);l=d(l,b[t][1]+r)}t=[p-m,l-k];c=c.apply([],[(h-e)/t[0],(f-g)/t[1]]);if(1e-10<Math.abs(c-1)){for(t=0;t<b.length;t++)b[t][2]*=c;this.placeBubbles(b)}else a.diffY=f/2+g-k-(l-k)/2,a.diffX=h/2+e-m-(p-m)/2};c.prototype.seriesBox=function(){var a=this.chart,b=Math.max,c=Math.min,d,e=[a.plotLeft,a.plotLeft+a.plotWidth,a.plotTop,a.plotTop+
a.plotHeight];this.data.forEach(function(a){l(a.plotX)&&l(a.plotY)&&a.marker.radius&&(d=a.marker.radius,e[0]=c(e[0],a.plotX-d),e[1]=b(e[1],a.plotX+d),e[2]=c(e[2],a.plotY-d),e[3]=b(e[3],a.plotY+d))});return B(e.width/e.height)?e:null};c.prototype.setVisible=function(){var a=this;p.prototype.setVisible.apply(a,arguments);a.parentNodeLayout&&a.graph?a.visible?(a.graph.show(),a.parentNode.dataLabel&&a.parentNode.dataLabel.show()):(a.graph.hide(),a.parentNodeLayout.removeElementFromCollection(a.parentNode,
a.parentNodeLayout.nodes),a.parentNode.dataLabel&&a.parentNode.dataLabel.hide()):a.layout&&(a.visible?a.layout.addElementsToCollection(a.points,a.layout.nodes):a.points.forEach(function(b){a.layout.removeElementFromCollection(b,a.layout.nodes)}))};c.prototype.translate=function(){var a=this.chart,b=this.data,c=this.index,d,e=this.options.useSimulation;this.processedXData=this.xData;this.generatePoints();l(a.allDataPoints)||(a.allDataPoints=this.accumulateAllPoints(this),this.getPointRadius());if(e)var g=
a.allDataPoints;else g=this.placeBubbles(a.allDataPoints),this.options.draggable=!1;for(d=0;d<g.length;d++)if(g[d][3]===c){var f=b[g[d][4]];var h=g[d][2];e||(f.plotX=g[d][0]-a.plotLeft+a.diffX,f.plotY=g[d][1]-a.plotTop+a.diffY);f.marker=u(f.marker,{radius:h,width:2*h,height:2*h});f.radius=h}e&&this.deferLayout();A(this,"afterTranslate")};c.defaultOptions=F(v.defaultOptions,{minSize:"10%",maxSize:"50%",sizeBy:"area",zoneAxis:"y",crisp:!1,tooltip:{pointFormat:"Value: {point.value}"},draggable:!0,useSimulation:!0,
parentNode:{allowPointSelect:!1},dataLabels:{formatter:function(){return this.point.value},parentNodeFormatter:function(){return this.name},parentNodeTextPath:{enabled:!0},padding:0,style:{transition:"opacity 2000ms"}},layoutAlgorithm:{initialPositions:"circle",initialPositionRadius:20,bubblePadding:5,parentNodeLimit:!1,seriesInteraction:!0,dragBetweenSeries:!1,parentNodeOptions:{maxIterations:400,gravitationalConstant:.03,maxSpeed:50,initialPositionRadius:100,seriesInteraction:!0,marker:{fillColor:null,
fillOpacity:1,lineWidth:1,lineColor:null,symbol:"circle"}},enableSimulation:!0,type:"packedbubble",integration:"packedbubble",maxIterations:1E3,splitSeries:!1,maxSpeed:5,gravitationalConstant:.01,friction:-.981}});return c}(v);u(d.prototype,{alignDataLabel:p.prototype.alignDataLabel,axisTypes:[],directTouch:!0,forces:["barycenter","repulsive"],hasDraggableNodes:!0,isCartesian:!1,noSharedTooltip:!0,onMouseDown:m.onMouseDown,onMouseMove:m.onMouseMove,pointArrayMap:["value"],pointClass:c,pointValKey:"value",
redrawHalo:m.redrawHalo,requireSorting:!1,searchPoint:f.noop,trackerGroups:["group","dataLabelsGroup","parentNodesGroup"]});e.registerSeriesType("packedbubble",d);"";"";return d});z(e,"Extensions/Polar.js",[e["Core/Animation/AnimationUtilities.js"],e["Core/Series/Series.js"],e["Core/Chart/Chart.js"],e["Core/Globals.js"],e["Series/Line/LineSeries.js"],e["Extensions/Pane.js"],e["Core/Pointer.js"],e["Core/Renderer/SVG/SVGRenderer.js"],e["Core/Utilities.js"]],function(e,d,f,c,a,r,k,v,p){var w=e.animObject;
d=d.seriesTypes;var b=p.addEvent,h=p.defined,l=p.find,u=p.isNumber,A=p.pick,z=p.splat,B=p.uniqueKey;e=p.wrap;var F=a.prototype;k=k.prototype;F.searchPointByAngle=function(a){var b=this.chart,c=this.xAxis.pane.center;return this.searchKDTree({clientX:180+-180/Math.PI*Math.atan2(a.chartX-c[0]-b.plotLeft,a.chartY-c[1]-b.plotTop)})};F.getConnectors=function(a,b,c,d){var e=d?1:0;var g=0<=b&&b<=a.length-1?b:0>b?a.length-1+b:0;b=0>g-1?a.length-(1+e):g-1;e=g+1>a.length-1?e:g+1;var f=a[b];e=a[e];var h=f.plotX;
f=f.plotY;var k=e.plotX;var l=e.plotY;e=a[g].plotX;g=a[g].plotY;h=(1.5*e+h)/2.5;f=(1.5*g+f)/2.5;k=(1.5*e+k)/2.5;var t=(1.5*g+l)/2.5;l=Math.sqrt(Math.pow(h-e,2)+Math.pow(f-g,2));var q=Math.sqrt(Math.pow(k-e,2)+Math.pow(t-g,2));h=Math.atan2(f-g,h-e);t=Math.PI/2+(h+Math.atan2(t-g,k-e))/2;Math.abs(h-t)>Math.PI/2&&(t-=Math.PI);h=e+Math.cos(t)*l;f=g+Math.sin(t)*l;k=e+Math.cos(Math.PI+t)*q;t=g+Math.sin(Math.PI+t)*q;e={rightContX:k,rightContY:t,leftContX:h,leftContY:f,plotX:e,plotY:g};c&&(e.prevPointCont=
this.getConnectors(a,b,!1,d));return e};F.toXY=function(a){var b=this.chart,c=this.xAxis;var d=this.yAxis;var e=a.plotX,f=a.plotY,h=a.series,k=b.inverted,l=a.y,t=k?e:d.len-f;k&&h&&!h.isRadialBar&&(a.plotY=f="number"===typeof l?d.translate(l)||0:0);a.rectPlotX=e;a.rectPlotY=f;d.center&&(t+=d.center[3]/2);d=k?d.postTranslate(f,t):c.postTranslate(e,t);a.plotX=a.polarPlotX=d.x-b.plotLeft;a.plotY=a.polarPlotY=d.y-b.plotTop;this.kdByAngle?(b=(e/Math.PI*180+c.pane.options.startAngle)%360,0>b&&(b+=360),a.clientX=
b):a.clientX=a.plotX};d.spline&&(e(d.spline.prototype,"getPointSpline",function(a,b,c,d){this.chart.polar?d?(a=this.getConnectors(b,d,!0,this.connectEnds),a=["C",a.prevPointCont.rightContX,a.prevPointCont.rightContY,a.leftContX,a.leftContY,a.plotX,a.plotY]):a=["M",c.plotX,c.plotY]:a=a.call(this,b,c,d);return a}),d.areasplinerange&&(d.areasplinerange.prototype.getPointSpline=d.spline.prototype.getPointSpline));b(a,"afterTranslate",function(){var a=this.chart;if(a.polar&&this.xAxis){(this.kdByAngle=
a.tooltip&&a.tooltip.shared)?this.searchPoint=this.searchPointByAngle:this.options.findNearestPointBy="xy";if(!this.preventPostTranslate)for(var d=this.points,e=d.length;e--;)this.toXY(d[e]),!a.hasParallelCoordinates&&!this.yAxis.reversed&&d[e].y<this.yAxis.min&&(d[e].isNull=!0);this.hasClipCircleSetter||(this.hasClipCircleSetter=!!this.eventsToUnbind.push(b(this,"afterRender",function(){if(a.polar){var b=this.yAxis.pane.center;this.clipCircle?this.clipCircle.animate({x:b[0],y:b[1],r:b[2]/2,innerR:b[3]/
2}):this.clipCircle=a.renderer.clipCircle(b[0],b[1],b[2]/2,b[3]/2);this.group.clip(this.clipCircle);this.setClip=c.noop}})))}},{order:2});e(F,"getGraphPath",function(a,b){var c=this,d;if(this.chart.polar){b=b||this.points;for(d=0;d<b.length;d++)if(!b[d].isNull){var e=d;break}if(!1!==this.options.connectEnds&&"undefined"!==typeof e){this.connectEnds=!0;b.splice(b.length,0,b[e]);var g=!0}b.forEach(function(a){"undefined"===typeof a.polarPlotY&&c.toXY(a)})}d=a.apply(this,[].slice.call(arguments,1));
g&&b.pop();return d});var y=function(a,b){var d=this,e=this.chart,g=this.options.animation,f=this.group,h=this.markerGroup,k=this.xAxis.center,l=e.plotLeft,t=e.plotTop,m,p,r,u;if(e.polar)if(d.isRadialBar)b||(d.startAngleRad=A(d.translatedThreshold,d.xAxis.startAngleRad),c.seriesTypes.pie.prototype.animate.call(d,b));else{if(e.renderer.isSVG)if(g=w(g),d.is("column")){if(!b){var v=k[3]/2;d.points.forEach(function(a){m=a.graphic;r=(p=a.shapeArgs)&&p.r;u=p&&p.innerR;m&&p&&(m.attr({r:v,innerR:v}),m.animate({r:r,
innerR:u},d.options.animation))})}}else b?(a={translateX:k[0]+l,translateY:k[1]+t,scaleX:.001,scaleY:.001},f.attr(a),h&&h.attr(a)):(a={translateX:l,translateY:t,scaleX:1,scaleY:1},f.animate(a,g),h&&h.animate(a,g))}else a.call(this,b)};e(F,"animate",y);if(d.column){var m=d.arearange.prototype;d=d.column.prototype;d.polarArc=function(a,b,c,d){var e=this.xAxis.center,g=this.yAxis.len,f=e[3]/2;b=g-b+f;a=g-A(a,g)+f;this.yAxis.reversed&&(0>b&&(b=f),0>a&&(a=f));return{x:e[0],y:e[1],r:b,innerR:a,start:c,
end:d}};e(d,"animate",y);e(d,"translate",function(a){var b=this.options,c=b.stacking,d=this.chart,e=this.xAxis,f=this.yAxis,k=f.reversed,l=f.center,m=e.startAngleRad,t=e.endAngleRad-m;this.preventPostTranslate=!0;a.call(this);if(e.isRadial){a=this.points;e=a.length;var r=f.translate(f.min);var v=f.translate(f.max);b=b.threshold||0;if(d.inverted&&u(b)){var w=f.translate(b);h(w)&&(0>w?w=0:w>t&&(w=t),this.translatedThreshold=w+m)}for(;e--;){b=a[e];var y=b.barX;var A=b.x;var z=b.y;b.shapeType="arc";if(d.inverted){b.plotY=
f.translate(z);if(c&&f.stacking){if(z=f.stacking.stacks[(0>z?"-":"")+this.stackKey],this.visible&&z&&z[A]&&!b.isNull){var B=z[A].points[this.getStackIndicator(void 0,A,this.index).key];var E=f.translate(B[0]);B=f.translate(B[1]);h(E)&&(E=p.clamp(E,0,t))}}else E=w,B=b.plotY;E>B&&(B=[E,E=B][0]);if(!k)if(E<r)E=r;else if(B>v)B=v;else{if(B<r||E>v)E=B=0}else if(B>r)B=r;else if(E<v)E=v;else if(E>r||B<v)E=B=t;f.min>f.max&&(E=B=k?t:0);E+=m;B+=m;l&&(b.barX=y+=l[3]/2);A=Math.max(y,0);z=Math.max(y+b.pointWidth,
0);b.shapeArgs={x:l&&l[0],y:l&&l[1],r:z,innerR:A,start:E,end:B};b.opacity=E===B?0:void 0;b.plotY=(h(this.translatedThreshold)&&(E<this.translatedThreshold?E:B))-m}else E=y+m,b.shapeArgs=this.polarArc(b.yBottom,b.plotY,E,E+b.pointWidth);this.toXY(b);d.inverted?(y=f.postTranslate(b.rectPlotY,y+b.pointWidth/2),b.tooltipPos=[y.x-d.plotLeft,y.y-d.plotTop]):b.tooltipPos=[b.plotX,b.plotY];l&&(b.ttBelow=b.plotY>l[1])}}});d.findAlignments=function(a,b){null===b.align&&(b.align=20<a&&160>a?"left":200<a&&340>
a?"right":"center");null===b.verticalAlign&&(b.verticalAlign=45>a||315<a?"bottom":135<a&&225>a?"top":"middle");return b};m&&(m.findAlignments=d.findAlignments);e(d,"alignDataLabel",function(a,b,c,d,e,f){var g=this.chart,h=A(d.inside,!!this.options.stacking);g.polar?(a=b.rectPlotX/Math.PI*180,g.inverted?(this.forceDL=g.isInsidePlot(b.plotX,Math.round(b.plotY),!1),h&&b.shapeArgs?(e=b.shapeArgs,e=this.yAxis.postTranslate((e.start+e.end)/2-this.xAxis.startAngleRad,b.barX+b.pointWidth/2),e={x:e.x-g.plotLeft,
y:e.y-g.plotTop}):b.tooltipPos&&(e={x:b.tooltipPos[0],y:b.tooltipPos[1]}),d.align=A(d.align,"center"),d.verticalAlign=A(d.verticalAlign,"middle")):this.findAlignments&&(d=this.findAlignments(a,d)),F.alignDataLabel.call(this,b,c,d,e,f),this.isRadialBar&&b.shapeArgs&&b.shapeArgs.start===b.shapeArgs.end&&c.hide(!0)):a.call(this,b,c,d,e,f)})}e(k,"getCoordinates",function(a,b){var c=this.chart,d={xAxis:[],yAxis:[]};c.polar?c.axes.forEach(function(a){var e=a.isXAxis,f=a.center;if("colorAxis"!==a.coll){var g=
b.chartX-f[0]-c.plotLeft;f=b.chartY-f[1]-c.plotTop;d[e?"xAxis":"yAxis"].push({axis:a,value:a.translate(e?Math.PI-Math.atan2(g,f):Math.sqrt(Math.pow(g,2)+Math.pow(f,2)),!0)})}}):d=a.call(this,b);return d});v.prototype.clipCircle=function(a,b,c,d){var e=B(),f=this.createElement("clipPath").attr({id:e}).add(this.defs);a=d?this.arc(a,b,c,d,0,2*Math.PI).add(f):this.circle(a,b,c).add(f);a.id=e;a.clipPath=f;return a};b(f,"getAxes",function(){this.pane||(this.pane=[]);z(this.options.pane).forEach(function(a){new r(a,
this)},this)});b(f,"afterDrawChartBox",function(){this.pane.forEach(function(a){a.render()})});b(a,"afterInit",function(){var a=this.chart;a.inverted&&a.polar&&(this.isRadialSeries=!0,this.is("column")&&(this.isRadialBar=!0))});e(f.prototype,"get",function(a,b){return l(this.pane,function(a){return a.options.id===b})||a.call(this,b)})});z(e,"masters/highcharts-more.src.js",[],function(){})});
//# sourceMappingURL=highcharts-more.js.map