/*
 Highstock JS v8.2.2 (2020-12-12)

 Indicator series type for Highstock

 (c) 2010-2019 Daniel Studencki

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/acceleration-bands",["highcharts","highcharts/modules/stock"],function(d){a(d);a.Highcharts=d;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function d(a,h,g,d){a.hasOwnProperty(h)||(a[h]=d.apply(null,g))}a=a?a._modules:{};d(a,"Mixins/MultipleLines.js",[a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,h){var g=
h.defined,d=h.error,n=h.merge,m=a.seriesTypes.sma;return{pointArrayMap:["top","bottom"],pointValKey:"top",linesApiNames:["bottomLine"],getTranslatedLinesNames:function(l){var a=[];(this.pointArrayMap||[]).forEach(function(b){b!==l&&a.push("plot"+b.charAt(0).toUpperCase()+b.slice(1))});return a},toYData:function(l){var a=[];(this.pointArrayMap||[]).forEach(function(b){a.push(l[b])});return a},translate:function(){var a=this,d=a.pointArrayMap,b=[],f;b=a.getTranslatedLinesNames();m.prototype.translate.apply(a,
arguments);a.points.forEach(function(c){d.forEach(function(l,v){f=c[l];null!==f&&(c[b[v]]=a.yAxis.toPixels(f,!0))})})},drawGraph:function(){var a=this,h=a.linesApiNames,b=a.points,f=b.length,c=a.options,A=a.graph,v={options:{gapSize:c.gapSize}},u=[],t;a.getTranslatedLinesNames(a.pointValKey).forEach(function(a,c){for(u[c]=[];f--;)t=b[f],u[c].push({x:t.x,plotX:t.plotX,plotY:t[a],isNull:!g(t[a])});f=b.length});h.forEach(function(b,f){u[f]?(a.points=u[f],c[b]?a.options=n(c[b].styles,v):d('Error: "There is no '+
b+' in DOCS options declared. Check if linesApiNames are consistent with your DOCS line names." at mixin/multiple-line.js:34'),a.graph=a["graph"+b],m.prototype.drawGraph.call(a),a["graph"+b]=a.graph):d('Error: "'+b+" doesn't have equivalent in pointArrayMap. To many elements in linesApiNames relative to pointArrayMap.\"")});a.points=b;a.options=c;a.graph=A;m.prototype.drawGraph.call(a)}}});d(a,"Stock/Indicators/ABands/ABandsIndicator.js",[a["Core/Series/Series.js"],a["Mixins/MultipleLines.js"],a["Core/Utilities.js"]],
function(a,d,g){var h=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),n=a.seriesTypes.sma,m=g.correctFloat,l=g.extend,z=g.merge;g=function(a){function b(){var c=null!==a&&a.apply(this,arguments)||this;
c.data=void 0;c.options=void 0;c.points=void 0;return c}h(b,a);b.prototype.getValues=function(c,b){var d=b.period,g=b.factor;b=b.index;var h=c.xData,f=(c=c.yData)?c.length:0,l=[],n=[],w=[],x=[],y=[],e;if(!(f<d)){for(e=0;e<=f;e++){if(e<f){var k=c[e][2];var p=c[e][1];var r=g;k=m(p-k)/(m(p+k)/2)*1E3*r;l.push(c[e][1]*m(1+2*k));n.push(c[e][2]*m(1-2*k))}if(e>=d){k=h.slice(e-d,e);var q=c.slice(e-d,e);r=a.prototype.getValues.call(this,{xData:k,yData:l.slice(e-d,e)},{period:d});p=a.prototype.getValues.call(this,
{xData:k,yData:n.slice(e-d,e)},{period:d});q=a.prototype.getValues.call(this,{xData:k,yData:q},{period:d,index:b});k=q.xData[0];r=r.yData[0];p=p.yData[0];q=q.yData[0];w.push([k,r,q,p]);x.push(k);y.push([r,q,p])}}return{values:w,xData:x,yData:y}}};b.defaultOptions=z(n.defaultOptions,{params:{period:20,factor:.001,index:3},lineWidth:1,topLine:{styles:{lineWidth:1}},bottomLine:{styles:{lineWidth:1}},dataGrouping:{approximation:"averages"}});return b}(n);l(g.prototype,{drawGraph:d.drawGraph,getTranslatedLinesNames:d.getTranslatedLinesNames,
linesApiNames:["topLine","bottomLine"],nameBase:"Acceleration Bands",nameComponents:["period","factor"],pointArrayMap:["top","middle","bottom"],pointValKey:"middle",toYData:d.toYData,translate:d.translate});a.registerSeriesType("abands",g);"";return g});d(a,"masters/indicators/acceleration-bands.src.js",[],function(){})});
//# sourceMappingURL=acceleration-bands.js.map