/*
 Highstock JS v8.2.2 (2020-12-12)

 All technical indicators for Highstock

 (c) 2010-2019 Pawel Fus

 License: www.highcharts.com/license
*/
(function(f){"object"===typeof module&&module.exports?(f["default"]=f,module.exports=f):"function"===typeof define&&define.amd?define("highcharts/indicators/indicators-all",["highcharts","highcharts/modules/stock"],function(w){f(w);f.Highcharts=w;return f}):f("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(f){function w(h,d,g,f){h.hasOwnProperty(d)||(h[d]=f.apply(null,g))}f=f?f._modules:{};w(f,"Mixins/IndicatorRequired.js",[f["Core/Utilities.js"]],function(h){var d=h.error;return{isParentLoaded:function(g,
h,f,q,p){if(g)return q?q(g):!0;d(p||this.generateMessage(f,h));return!1},generateMessage:function(d,h){return'Error: "'+d+'" indicator type requires "'+h+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+d}}});w(f,"Stock/Indicators/SMA/SMAComposition.js",[f["Core/Series/Series.js"],f["Core/Utilities.js"]],function(h,d){var g=h.seriesTypes;h=g.line;var f=g.ohlc.prototype;g=d.addEvent;var l=d.extend;g(h,"init",function(d){d=d.options;d.useOhlcData&&"highcharts-navigator-series"!==
d.id&&l(this,{pointValKey:f.pointValKey,keys:f.keys,pointArrayMap:f.pointArrayMap,toYData:f.toYData})});g(h,"afterSetOptions",function(d){d=d.options;var g=d.dataGrouping;g&&d.useOhlcData&&"highcharts-navigator-series"!==d.id&&(g.approximation="ohlc")})});w(f,"Stock/Indicators/SMA/SMAIndicator.js",[f["Core/Series/Series.js"],f["Mixins/IndicatorRequired.js"],f["Core/Utilities.js"]],function(h,d,g){var f=this&&this.__extends||function(){var a=function(c,k){a=Object.setPrototypeOf||{__proto__:[]}instanceof
Array&&function(a,c){a.__proto__=c}||function(a,c){for(var k in c)c.hasOwnProperty(k)&&(a[k]=c[k])};return a(c,k)};return function(c,k){function b(){this.constructor=c}a(c,k);c.prototype=null===k?Object.create(k):(b.prototype=k.prototype,new b)}}(),l=h.seriesTypes.line,q=g.addEvent,p=g.error,m=g.extend,e=g.isArray,b=g.merge,a=g.pick,c=g.splat,k=d.generateMessage;d=function(y){function v(){var a=null!==y&&y.apply(this,arguments)||this;a.data=void 0;a.dataEventsToUnbind=void 0;a.linkedParent=void 0;
a.options=void 0;a.points=void 0;return a}f(v,y);v.prototype.destroy=function(){this.dataEventsToUnbind.forEach(function(a){a()});y.prototype.destroy.apply(this,arguments)};v.prototype.getName=function(){var c=this.name,k=[];c||((this.nameComponents||[]).forEach(function(c,b){k.push(this.options.params[c]+a(this.nameSuffixes[b],""))},this),c=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+k.join(", ")+")":""));return c};v.prototype.getValues=function(a,c){var k=c.period,b=a.xData;
a=a.yData;var y=a.length,v=0,A=0,m=[],d=[],g=[],K=-1;if(!(b.length<k)){for(e(a[0])&&(K=c.index?c.index:0);v<k-1;)A+=0>K?a[v]:a[v][K],v++;for(c=v;c<y;c++){A+=0>K?a[c]:a[c][K];var f=[b[c],A/k];m.push(f);d.push(f[0]);g.push(f[1]);A-=0>K?a[c-v]:a[c-v][K]}return{values:m,xData:d,yData:g}}};v.prototype.init=function(a,b){function e(){var a=v.points||[],k=(v.xData||[]).length,b=v.getValues(v.linkedParent,v.options.params)||{values:[],xData:[],yData:[]},e=[],y=!0;if(k&&!v.hasGroupedData&&v.visible&&v.points)if(v.cropped){if(v.xAxis){var n=
v.xAxis.min;var A=v.xAxis.max}k=v.cropData(b.xData,b.yData,n,A);for(n=0;n<k.xData.length;n++)e.push([k.xData[n]].concat(c(k.yData[n])));k=b.xData.indexOf(v.xData[0]);n=b.xData.indexOf(v.xData[v.xData.length-1]);-1===k&&n===b.xData.length-2&&e[0][0]===a[0].x&&e.shift();v.updateData(e)}else b.xData.length!==k-1&&b.xData.length!==k+1&&(y=!1,v.updateData(b.values));y&&(v.xData=b.xData,v.yData=b.yData,v.options.data=b.values);!1===v.bindTo.series&&(delete v.processedXData,v.isDirty=!0,v.redraw());v.isDirtyData=
!1}var v=this,n=v.requireIndicators();if(!n.allLoaded)return p(k(v.type,n.needed));y.prototype.init.call(v,a,b);a.linkSeries();v.dataEventsToUnbind=[];if(!v.linkedParent)return p("Series "+v.options.linkedTo+" not found! Check `linkedTo`.",!1,a);v.dataEventsToUnbind.push(q(v.bindTo.series?v.linkedParent:v.linkedParent.xAxis,v.bindTo.eventName,e));if("init"===v.calculateOn)e();else var A=q(v.chart,v.calculateOn,function(){e();A()})};v.prototype.processData=function(){var a=this.options.compareToMain,
c=this.linkedParent;y.prototype.processData.apply(this,arguments);c&&c.compareValue&&a&&(this.compareValue=c.compareValue)};v.prototype.requireIndicators=function(){var a={allLoaded:!0};this.requiredIndicators.forEach(function(c){h.seriesTypes[c]?h.seriesTypes[c].prototype.requireIndicators():(a.allLoaded=!1,a.needed=c)});return a};v.defaultOptions=b(l.defaultOptions,{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,period:14}});return v}(l);m(d.prototype,{bindTo:{series:!0,
eventName:"updatedData"},calculateOn:"init",hasDerivedData:!0,nameComponents:["period"],nameSuffixes:[],requiredIndicators:[],useCommonDataGrouping:!0});h.registerSeriesType("sma",d);"";return d});w(f,"Stock/Indicators/AD/ADIndicator.js",[f["Core/Series/Series.js"],f["Core/Utilities.js"]],function(f,d){var g=this&&this.__extends||function(){var m=function(e,b){m=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var k in c)c.hasOwnProperty(k)&&(a[k]=
c[k])};return m(e,b)};return function(e,b){function a(){this.constructor=e}m(e,b);e.prototype=null===b?Object.create(b):(a.prototype=b.prototype,new a)}}(),h=f.seriesTypes.sma,l=d.error,q=d.extend,p=d.merge;d=function(m){function e(){var b=null!==m&&m.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}g(e,m);e.populateAverage=function(b,a,c,k,e){e=a[k][1];var y=a[k][2];a=a[k][3];c=c[k];return[b[k],a===e&&a===y||e===y?0:(2*a-y-e)/(e-y)*c]};e.prototype.getValues=function(b,
a){var c=a.period,k=b.xData,y=b.yData,v=a.volumeSeriesID,A=b.chart.get(v);a=A&&A.yData;var m=y?y.length:0,d=[],t=[],n=[];if(!(k.length<=c&&m&&4!==y[0].length)){if(A){for(v=c;v<m;v++)b=d.length,A=e.populateAverage(k,y,a,v,c),0<b&&(A[1]+=d[b-1][1]),d.push(A),t.push(A[0]),n.push(A[1]);return{values:d,xData:t,yData:n}}l("Series "+v+" not found! Check `volumeSeriesID`.",!0,b.chart)}};e.defaultOptions=p(h.defaultOptions,{params:{volumeSeriesID:"volume"}});return e}(h);q(d.prototype,{nameComponents:!1,nameBase:"Accumulation/Distribution"});
f.registerSeriesType("ad",d);"";return d});w(f,"Stock/Indicators/AO/AOIndicator.js",[f["Core/Series/Series.js"],f["Core/Globals.js"],f["Core/Utilities.js"]],function(f,d,g){var h=this&&this.__extends||function(){var a=function(c,k){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var k in c)c.hasOwnProperty(k)&&(a[k]=c[k])};return a(c,k)};return function(c,k){function b(){this.constructor=c}a(c,k);c.prototype=null===k?Object.create(k):(b.prototype=
k.prototype,new b)}}(),l=f.seriesTypes,q=l.sma;l=l.column;d=d.noop;var p=g.extend,m=g.merge,e=g.correctFloat,b=g.isArray;g=function(a){function c(){var c=null!==a&&a.apply(this,arguments)||this;c.data=void 0;c.options=void 0;c.points=void 0;return c}h(c,a);c.prototype.drawGraph=function(){var a=this.options,c=this.points,b=a.greaterBarColor;a=a.lowerBarColor;var e=c[0];if(!this.userOptions.color&&e)for(e.color=b,e=1;e<c.length;e++)c[e].color=c[e].y>c[e-1].y?b:c[e].y<c[e-1].y?a:c[e-1].color};c.prototype.getValues=
function(c){var a=c.xData||[];c=c.yData||[];var k=c.length,A=[],m=[],d=[],t=0,n=0,x;if(!(34>=a.length)&&b(c[0])&&4===c[0].length){for(x=0;33>x;x++){var r=(c[x][1]+c[x][2])/2;29<=x&&(t=e(t+r));n=e(n+r)}for(x=33;x<k;x++){r=(c[x][1]+c[x][2])/2;t=e(t+r);n=e(n+r);r=t/5;var g=n/34;r=e(r-g);A.push([a[x],r]);m.push(a[x]);d.push(r);r=x+1-5;g=x+1-34;t=e(t-(c[r][1]+c[r][2])/2);n=e(n-(c[g][1]+c[g][2])/2)}return{values:A,xData:m,yData:d}}};c.defaultOptions=m(q.defaultOptions,{greaterBarColor:"#06B535",lowerBarColor:"#F21313",
threshold:0,groupPadding:.2,pointPadding:.2,crisp:!1,states:{hover:{halo:{size:0}}}});return c}(q);p(g.prototype,{nameBase:"AO",nameComponents:!1,markerAttribs:d,getColumnMetrics:l.prototype.getColumnMetrics,crispCol:l.prototype.crispCol,translate:l.prototype.translate,drawPoints:l.prototype.drawPoints});f.registerSeriesType("ao",g);"";return g});w(f,"Mixins/MultipleLines.js",[f["Core/Globals.js"],f["Core/Utilities.js"]],function(f,d){var g=d.defined,h=d.error,l=d.merge,q=f.seriesTypes.sma;return{pointArrayMap:["top",
"bottom"],pointValKey:"top",linesApiNames:["bottomLine"],getTranslatedLinesNames:function(d){var m=[];(this.pointArrayMap||[]).forEach(function(e){e!==d&&m.push("plot"+e.charAt(0).toUpperCase()+e.slice(1))});return m},toYData:function(d){var m=[];(this.pointArrayMap||[]).forEach(function(e){m.push(d[e])});return m},translate:function(){var d=this,m=d.pointArrayMap,e=[],b;e=d.getTranslatedLinesNames();q.prototype.translate.apply(d,arguments);d.points.forEach(function(a){m.forEach(function(c,k){b=a[c];
null!==b&&(a[e[k]]=d.yAxis.toPixels(b,!0))})})},drawGraph:function(){var d=this,m=d.linesApiNames,e=d.points,b=e.length,a=d.options,c=d.graph,k={options:{gapSize:a.gapSize}},y=[],v;d.getTranslatedLinesNames(d.pointValKey).forEach(function(c,a){for(y[a]=[];b--;)v=e[b],y[a].push({x:v.x,plotX:v.plotX,plotY:v[c],isNull:!g(v[c])});b=e.length});m.forEach(function(c,b){y[b]?(d.points=y[b],a[c]?d.options=l(a[c].styles,k):h('Error: "There is no '+c+' in DOCS options declared. Check if linesApiNames are consistent with your DOCS line names." at mixin/multiple-line.js:34'),
d.graph=d["graph"+c],q.prototype.drawGraph.call(d),d["graph"+c]=d.graph):h('Error: "'+c+" doesn't have equivalent in pointArrayMap. To many elements in linesApiNames relative to pointArrayMap.\"")});d.points=e;d.options=a;d.graph=c;q.prototype.drawGraph.call(d)}}});w(f,"Stock/Indicators/Aroon/AroonIndicator.js",[f["Core/Series/Series.js"],f["Mixins/MultipleLines.js"],f["Core/Utilities.js"]],function(f,d,g){function h(b,a){var c=b[0],k=0,e;for(e=1;e<b.length;e++)if("max"===a&&b[e]>=c||"min"===a&&b[e]<=
c)c=b[e],k=e;return k}var l=this&&this.__extends||function(){var b=function(a,c){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,a){c.__proto__=a}||function(c,a){for(var k in a)a.hasOwnProperty(k)&&(c[k]=a[k])};return b(a,c)};return function(a,c){function k(){this.constructor=a}b(a,c);a.prototype=null===c?Object.create(c):(k.prototype=c.prototype,new k)}}(),q=f.seriesTypes.sma,p=g.extend,m=g.merge,e=g.pick;g=function(b){function a(){var c=null!==b&&b.apply(this,arguments)||this;
c.data=void 0;c.options=void 0;c.points=void 0;return c}l(a,b);a.prototype.getValues=function(c,a){a=a.period;var k=c.xData,b=(c=c.yData)?c.length:0,d=[],m=[],g=[],t;for(t=a-1;t<b;t++){var n=c.slice(t-a+1,t+2);var x=h(n.map(function(c){return e(c[2],c)}),"min");n=h(n.map(function(c){return e(c[1],c)}),"max");n=n/a*100;x=x/a*100;k[t+1]&&(d.push([k[t+1],n,x]),m.push(k[t+1]),g.push([n,x]))}return{values:d,xData:m,yData:g}};a.defaultOptions=m(q.defaultOptions,{params:{period:25},marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Aroon Up: {point.y}<br/>Aroon Down: {point.aroonDown}<br/>'},
aroonDown:{styles:{lineWidth:1,lineColor:void 0}},dataGrouping:{approximation:"averages"}});return a}(q);p(g.prototype,{linesApiNames:["aroonDown"],nameBase:"Aroon",pointArrayMap:["y","aroonDown"],pointValKey:"y",drawGraph:d.drawGraph,getTranslatedLinesNames:d.getTranslatedLinesNames,toYData:d.toYData,translate:d.translate});f.registerSeriesType("aroon",g);"";return g});w(f,"Stock/Indicators/AroonOscillator/AroonOscillatorIndicator.js",[f["Core/Series/Series.js"],f["Mixins/MultipleLines.js"],f["Mixins/IndicatorRequired.js"],
f["Core/Utilities.js"]],function(f,d,g,u){var h=this&&this.__extends||function(){var b=function(a,c){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,a){c.__proto__=a}||function(c,a){for(var k in a)a.hasOwnProperty(k)&&(c[k]=a[k])};return b(a,c)};return function(a,c){function k(){this.constructor=a}b(a,c);a.prototype=null===c?Object.create(c):(k.prototype=c.prototype,new k)}}(),q=f.seriesTypes.aroon,p=u.extend,m=u.merge,e=f.seriesTypes.aroon;u=function(b){function a(){var c=null!==
b&&b.apply(this,arguments)||this;c.data=void 0;c.options=void 0;c.points=void 0;return c}h(a,b);a.prototype.getValues=function(c,a){var k=[],b=[],d=[];c=e.prototype.getValues.call(this,c,a);for(a=0;a<c.yData.length;a++){var m=c.yData[a][0];var g=c.yData[a][1];m-=g;k.push([c.xData[a],m]);b.push(c.xData[a]);d.push(m)}return{values:k,xData:b,yData:d}};a.prototype.init=function(){var c=arguments,a=this;g.isParentLoaded(e,"aroon",a.type,function(k){k.prototype.init.apply(a,c)})};a.defaultOptions=m(q.defaultOptions,
{params:{period:25},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b>: {point.y}'}});return a}(q);p(u.prototype,m(d,{nameBase:"Aroon Oscillator",pointArrayMap:["y"],pointValKey:"y",linesApiNames:[]}));f.registerSeriesType("aroonoscillator",u);"";return u});w(f,"Stock/Indicators/ATR/ATRIndicator.js",[f["Core/Series/Series.js"],f["Core/Utilities.js"]],function(f,d){function g(d,e){return Math.max(d[1]-d[2],"undefined"===typeof e?0:Math.abs(d[1]-e[3]),"undefined"===
typeof e?0:Math.abs(d[2]-e[3]))}var h=this&&this.__extends||function(){var d=function(e,b){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var k in c)c.hasOwnProperty(k)&&(a[k]=c[k])};return d(e,b)};return function(e,b){function a(){this.constructor=e}d(e,b);e.prototype=null===b?Object.create(b):(a.prototype=b.prototype,new a)}}(),l=f.seriesTypes.sma,q=d.isArray,p=d.merge;d=function(d){function e(){var b=null!==d&&d.apply(this,arguments)||this;
b.data=void 0;b.points=void 0;b.options=void 0;return b}h(e,d);e.prototype.getValues=function(b,a){a=a.period;var c=b.xData,k=(b=b.yData)?b.length:0,e=1,v=0,d=0,m=[],f=[],t=[],n;var x=[[c[0],b[0]]];if(!(c.length<=a)&&q(b[0])&&4===b[0].length){for(n=1;n<=k;n++)if(x.push([c[n],b[n]]),a<e){var r=a;var L=c[n-1],h=g(b[n-1],b[n-2]);r=[L,(v*(r-1)+h)/r];v=r[1];m.push(r);f.push(r[0]);t.push(r[1])}else a===e?(v=d/(n-1),m.push([c[n-1],v]),f.push(c[n-1]),t.push(v)):d+=g(b[n-1],b[n-2]),e++;return{values:m,xData:f,
yData:t}}};e.defaultOptions=p(l.defaultOptions,{params:{period:14}});return e}(l);f.registerSeriesType("atr",d);"";return d});w(f,"Stock/Indicators/BB/BBIndicator.js",[f["Core/Series/Series.js"],f["Mixins/MultipleLines.js"],f["Core/Utilities.js"]],function(f,d,g){var h=this&&this.__extends||function(){var e=function(b,a){e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,a){c.__proto__=a}||function(c,a){for(var b in a)a.hasOwnProperty(b)&&(c[b]=a[b])};return e(b,a)};return function(b,
a){function c(){this.constructor=b}e(b,a);b.prototype=null===a?Object.create(a):(c.prototype=a.prototype,new c)}}(),l=f.seriesTypes.sma,q=g.extend,p=g.isArray,m=g.merge;g=function(e){function b(){var a=null!==e&&e.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}h(b,e);b.prototype.init=function(){f.seriesTypes.sma.prototype.init.apply(this,arguments);this.options=m({topLine:{styles:{lineColor:this.color}},bottomLine:{styles:{lineColor:this.color}}},this.options)};
b.prototype.getValues=function(a,c){var b=c.period,e=c.standardDeviation,v=a.xData,d=(a=a.yData)?a.length:0,m=[],g=[],t=[],n;if(!(v.length<b)){var x=p(a[0]);for(n=b;n<=d;n++){var r=v.slice(n-b,n);var L=a.slice(n-b,n);var h=f.seriesTypes.sma.prototype.getValues.call(this,{xData:r,yData:L},c);r=h.xData[0];h=h.yData[0];for(var u=0,z=L.length,l=0;l<z;l++){var q=(x?L[l][c.index]:L[l])-h;u+=q*q}q=Math.sqrt(u/(z-1));L=h+e*q;q=h-e*q;m.push([r,L,h,q]);g.push(r);t.push([L,h,q])}return{values:m,xData:g,yData:t}}};
b.defaultOptions=m(l.defaultOptions,{params:{period:20,standardDeviation:2,index:3},bottomLine:{styles:{lineWidth:1,lineColor:void 0}},topLine:{styles:{lineWidth:1,lineColor:void 0}},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Top: {point.top}<br/>Middle: {point.middle}<br/>Bottom: {point.bottom}<br/>'},marker:{enabled:!1},dataGrouping:{approximation:"averages"}});return b}(l);q(g.prototype,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",
nameComponents:["period","standardDeviation"],linesApiNames:["topLine","bottomLine"],drawGraph:d.drawGraph,getTranslatedLinesNames:d.getTranslatedLinesNames,translate:d.translate,toYData:d.toYData});f.registerSeriesType("bb",g);"";return g});w(f,"Stock/Indicators/CCI/CCIIndicator.js",[f["Core/Series/Series.js"],f["Core/Utilities.js"]],function(f,d){function g(d){return d.reduce(function(e,b){return e+b},0)}var h=this&&this.__extends||function(){var d=function(e,b){d=Object.setPrototypeOf||{__proto__:[]}instanceof
Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return d(e,b)};return function(e,b){function a(){this.constructor=e}d(e,b);e.prototype=null===b?Object.create(b):(a.prototype=b.prototype,new a)}}(),l=f.seriesTypes.sma,q=d.isArray,p=d.merge;d=function(d){function e(){var b=null!==d&&d.apply(this,arguments)||this;b.data=void 0;b.points=void 0;b.options=void 0;return b}h(e,d);e.prototype.getValues=function(b,a){a=a.period;var c=b.xData,k=(b=b.yData)?
b.length:0,e=[],v=1,d=[],m=[],f=[];if(!(c.length<=a)&&q(b[0])&&4===b[0].length){for(;v<a;){var t=b[v-1];e.push((t[1]+t[2]+t[3])/3);v++}for(v=a;v<=k;v++){t=b[v-1];t=(t[1]+t[2]+t[3])/3;var n=e.push(t);var x=e.slice(n-a);n=g(x)/a;var r,L=x.length,h=0;for(r=0;r<L;r++)h+=Math.abs(n-x[r]);x=h/a;t=(t-n)/(.015*x);d.push([c[v-1],t]);m.push(c[v-1]);f.push(t)}return{values:d,xData:m,yData:f}}};e.defaultOptions=p(l.defaultOptions,{params:{period:14}});return e}(l);f.registerSeriesType("cci",d);"";return d});
w(f,"Stock/Indicators/CMF/CMFIndicator.js",[f["Core/Series/Series.js"],f["Core/Utilities.js"]],function(f,d){var g=this&&this.__extends||function(){var d=function(g,m){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(e,b){e.__proto__=b}||function(e,b){for(var a in b)b.hasOwnProperty(a)&&(e[a]=b[a])};return d(g,m)};return function(g,m){function e(){this.constructor=g}d(g,m);g.prototype=null===m?Object.create(m):(e.prototype=m.prototype,new e)}}(),h=f.seriesTypes.sma,l=d.merge;d=function(d){function f(){var m=
null!==d&&d.apply(this,arguments)||this;m.data=void 0;m.options=void 0;m.points=void 0;m.volumeSeries=void 0;m.linkedParent=void 0;m.yData=void 0;m.nameBase="Chaikin Money Flow";return m}g(f,d);f.prototype.isValid=function(){var d=this.chart,e=this.options,b=this.linkedParent;d=this.volumeSeries||(this.volumeSeries=d.get(e.params.volumeSeriesID));var a=b&&b.yData&&4===b.yData[0].length;return!!(b&&d&&b.xData&&b.xData.length>=e.params.period&&d.xData&&d.xData.length>=e.params.period&&a)};f.prototype.getValues=
function(d,e){if(this.isValid())return this.getMoneyFlow(d.xData,d.yData,this.volumeSeries.yData,e.period)};f.prototype.getMoneyFlow=function(d,e,b,a){function c(a,c){var b=a[1],k=a[2];a=a[3];return null!==c&&null!==b&&null!==k&&null!==a&&b!==k?(a-k-(b-a))/(b-k)*c:(x=n,null)}var k=e.length,y=[],v=0,A=0,m=[],g=[],t=[],n,x=-1;if(0<a&&a<=k){for(n=0;n<a;n++)y[n]=c(e[n],b[n]),v+=b[n],A+=y[n];m.push(d[n-1]);g.push(n-x>=a&&0!==v?A/v:null);for(t.push([m[0],g[0]]);n<k;n++){y[n]=c(e[n],b[n]);v-=b[n-a];v+=b[n];
A-=y[n-a];A+=y[n];var r=[d[n],n-x>=a?A/v:null];m.push(r[0]);g.push(r[1]);t.push([r[0],r[1]])}}return{values:t,xData:m,yData:g}};f.defaultOptions=l(h.defaultOptions,{params:{period:14,volumeSeriesID:"volume"}});return f}(h);f.registerSeriesType("cmf",d);"";return d});w(f,"Stock/Indicators/DPO/DPOIndicator.js",[f["Core/Series/Series.js"],f["Core/Utilities.js"]],function(f,d){function g(b,a,c,k,y){a=e(a[c][k],a[c]);return y?m(b-a):m(b+a)}var h=this&&this.__extends||function(){var b=function(a,c){b=Object.setPrototypeOf||
{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return b(a,c)};return function(a,c){function k(){this.constructor=a}b(a,c);a.prototype=null===c?Object.create(c):(k.prototype=c.prototype,new k)}}(),l=f.seriesTypes.sma,q=d.extend,p=d.merge,m=d.correctFloat,e=d.pick;d=function(b){function a(){var a=null!==b&&b.apply(this,arguments)||this;a.options=void 0;a.data=void 0;a.points=void 0;return a}h(a,b);a.prototype.getValues=function(a,
b){var c=b.period;b=b.index;var k=c+Math.floor(c/2+1),d=a.xData||[];a=a.yData||[];var m=a.length,f=[],t=[],n=[],x=0,r,h;if(!(d.length<=k)){for(r=0;r<c-1;r++)x=g(x,a,r,b);for(h=0;h<=m-k;h++){var l=h+c-1;r=h+k-1;x=g(x,a,l,b);l=e(a[r][b],a[r]);l-=x/c;x=g(x,a,h,b,!0);f.push([d[r],l]);t.push(d[r]);n.push(l)}return{values:f,xData:t,yData:n}}};a.defaultOptions=p(l.defaultOptions,{params:{period:21}});return a}(l);q(d.prototype,{nameBase:"DPO"});f.registerSeriesType("dpo",d);"";return d});w(f,"Stock/Indicators/EMA/EMAIndicator.js",
[f["Core/Series/Series.js"],f["Core/Utilities.js"]],function(f,d){var g=this&&this.__extends||function(){var d=function(e,b){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return d(e,b)};return function(e,b){function a(){this.constructor=e}d(e,b);e.prototype=null===b?Object.create(b):(a.prototype=b.prototype,new a)}}(),h=f.seriesTypes.sma,l=d.correctFloat,q=d.isArray,p=d.merge;d=function(d){function e(){var b=
null!==d&&d.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}g(e,d);e.prototype.accumulatePeriodPoints=function(b,a,c){for(var k=0,e=0,d;e<b;)d=0>a?c[e]:c[e][a],k+=d,e++;return k};e.prototype.calculateEma=function(b,a,c,k,e,d,A){b=b[c-1];a=0>d?a[c-1]:a[c-1][d];k="undefined"===typeof e?A:l(a*k+e*(1-k));return[b,k]};e.prototype.getValues=function(b,a){var c=a.period,k=b.xData,e=(b=b.yData)?b.length:0,d=2/(c+1),A=[],m=[],g=[],t=-1;if(!(e<c)){q(b[0])&&(t=a.index?a.index:
0);a=this.accumulatePeriodPoints(c,t,b);for(a/=c;c<e+1;c++){var n=this.calculateEma(k,b,c,d,n,t,a);A.push(n);m.push(n[0]);g.push(n[1]);n=n[1]}return{values:A,xData:m,yData:g}}};e.defaultOptions=p(h.defaultOptions,{params:{index:3,period:9}});return e}(h);f.registerSeriesType("ema",d);"";return d});w(f,"Stock/Indicators/Chaikin/ChaikinIndicator.js",[f["Core/Series/Series.js"],f["Mixins/IndicatorRequired.js"],f["Core/Utilities.js"]],function(f,d,g){var h=this&&this.__extends||function(){var a=function(c,
b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(c,b)};return function(c,b){function k(){this.constructor=c}a(c,b);c.prototype=null===b?Object.create(b):(k.prototype=b.prototype,new k)}}(),l=f.seriesTypes,q=l.ad,p=l.ema,m=g.correctFloat;l=g.extend;var e=g.merge,b=g.error;g=function(a){function c(){var c=null!==a&&a.apply(this,arguments)||this;c.data=void 0;c.options=void 0;c.points=void 0;
return c}h(c,a);c.prototype.init=function(){var a=arguments,c=this;d.isParentLoaded(p,"ema",c.type,function(b){b.prototype.init.apply(c,a)})};c.prototype.getValues=function(a,c){var k=c.periods,e=c.period,d=[],y=[],t=[],n;if(2!==k.length||k[1]<=k[0])b('Error: "Chaikin requires two periods. Notice, first period should be lower than the second one."');else if(c=q.prototype.getValues.call(this,a,{volumeSeriesID:c.volumeSeriesID,period:e}))if(a=p.prototype.getValues.call(this,c,{period:k[0]}),c=p.prototype.getValues.call(this,
c,{period:k[1]}),a&&c){k=k[1]-k[0];for(n=0;n<c.yData.length;n++)e=m(a.yData[n+k]-c.yData[n]),d.push([c.xData[n],e]),y.push(c.xData[n]),t.push(e);return{values:d,xData:y,yData:t}}};c.defaultOptions=e(p.defaultOptions,{params:{volumeSeriesID:"volume",periods:[3,10]}});return c}(p);l(g.prototype,{nameBase:"Chaikin Osc",nameComponents:["periods"]});f.registerSeriesType("chaikin",g);"";return g});w(f,"Stock/Indicators/DEMA/DEMAIndicator.js",[f["Core/Series/Series.js"],f["Mixins/IndicatorRequired.js"],
f["Core/Utilities.js"]],function(f,d,g){var h=this&&this.__extends||function(){var e=function(b,a){e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return e(b,a)};return function(b,a){function c(){this.constructor=b}e(b,a);b.prototype=null===a?Object.create(a):(c.prototype=a.prototype,new c)}}(),l=f.seriesTypes.ema,q=g.correctFloat,p=g.isArray,m=g.merge;g=function(e){function b(){var a=null!==e&&e.apply(this,
arguments)||this;a.EMApercent=void 0;a.data=void 0;a.options=void 0;a.points=void 0;return a}h(b,e);b.prototype.init=function(){var a=arguments,c=this;d.isParentLoaded(l,"ema",c.type,function(b){b.prototype.init.apply(c,a)})};b.prototype.getEMA=function(a,c,b,e,d,m){return l.prototype.calculateEma(m||[],a,"undefined"===typeof d?1:d,this.EMApercent,c,"undefined"===typeof e?-1:e,b)};b.prototype.getValues=function(a,c){var b=c.period,e=2*b,d=a.xData,m=(a=a.yData)?a.length:0,f=-1,g=[],t=[],n=[],x=0,r=
[],h;this.EMApercent=2/(b+1);if(!(m<2*b-1)){p(a[0])&&(f=c.index?c.index:0);c=l.prototype.accumulatePeriodPoints(b,f,a);var u=c/b;c=0;for(h=b;h<m+2;h++){h<m+1&&(x=this.getEMA(a,E,u,f,h)[1],r.push(x));var E=x;if(h<e)c+=x;else{h===e&&(u=c/b);x=r[h-b-1];var z=this.getEMA([x],z,u)[1];var F=[d[h-2],q(2*x-z)];g.push(F);t.push(F[0]);n.push(F[1])}}return{values:g,xData:t,yData:n}}};b.defaultOptions=m(l.defaultOptions);return b}(l);f.registerSeriesType("dema",g);"";return g});w(f,"Stock/Indicators/TEMA/TEMAIndicator.js",
[f["Core/Series/Series.js"],f["Mixins/IndicatorRequired.js"],f["Core/Utilities.js"]],function(f,d,g){var h=this&&this.__extends||function(){var e=function(b,a){e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return e(b,a)};return function(b,a){function c(){this.constructor=b}e(b,a);b.prototype=null===a?Object.create(a):(c.prototype=a.prototype,new c)}}(),l=f.seriesTypes.ema,q=g.correctFloat,p=g.isArray,
m=g.merge;g=function(e){function b(){var a=null!==e&&e.apply(this,arguments)||this;a.EMApercent=void 0;a.data=void 0;a.options=void 0;a.points=void 0;return a}h(b,e);b.prototype.init=function(){var a=arguments,c=this;d.isParentLoaded(l,"ema",c.type,function(b){b.prototype.init.apply(c,a)})};b.prototype.getEMA=function(a,c,b,e,d,m){return l.prototype.calculateEma(m||[],a,"undefined"===typeof d?1:d,this.EMApercent,c,"undefined"===typeof e?-1:e,b)};b.prototype.getTemaPoint=function(a,c,b,e){return[a[e-
3],q(3*b.level1-3*b.level2+b.level3)]};b.prototype.getValues=function(a,c){var b=c.period,e=2*b,d=3*b,m=a.xData,f=(a=a.yData)?a.length:0,g=-1,t=[],n=[],x=[],r=[],h=[],u,q,z={};this.EMApercent=2/(b+1);if(!(f<3*b-2)){p(a[0])&&(g=c.index?c.index:0);c=l.prototype.accumulatePeriodPoints(b,g,a);var F=c/b;c=0;for(u=b;u<f+3;u++){u<f+1&&(z.level1=this.getEMA(a,R,F,g,u)[1],r.push(z.level1));var R=z.level1;if(u<e)c+=z.level1;else{u===e&&(F=c/b,c=0);z.level1=r[u-b-1];z.level2=this.getEMA([z.level1],B,F)[1];h.push(z.level2);
var B=z.level2;if(u<d)c+=z.level2;else{u===d&&(F=c/b);u===f+1&&(z.level1=r[u-b-1],z.level2=this.getEMA([z.level1],B,F)[1],h.push(z.level2));z.level1=r[u-b-2];z.level2=h[u-2*b-1];z.level3=this.getEMA([z.level2],z.prevLevel3,F)[1];if(q=this.getTemaPoint(m,d,z,u))t.push(q),n.push(q[0]),x.push(q[1]);z.prevLevel3=z.level3}}}return{values:t,xData:n,yData:x}}};b.defaultOptions=m(l.defaultOptions);return b}(l);f.registerSeriesType("tema",g);"";return g});w(f,"Stock/Indicators/TRIX/TRIXIndicator.js",[f["Core/Series/Series.js"],
f["Mixins/IndicatorRequired.js"],f["Core/Utilities.js"]],function(f,d,g){var h=this&&this.__extends||function(){var d=function(e,b){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return d(e,b)};return function(e,b){function a(){this.constructor=e}d(e,b);e.prototype=null===b?Object.create(b):(a.prototype=b.prototype,new a)}}(),l=f.seriesTypes.tema,q=g.correctFloat,p=g.merge;g=function(m){function e(){var b=
null!==m&&m.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}h(e,m);e.prototype.init=function(){var b=arguments,a=this;d.isParentLoaded(f.seriesTypes.tema,"tema",a.type,function(c){c.prototype.init.apply(a,b)})};e.prototype.getTemaPoint=function(b,a,c,k){if(k>a)var e=[b[k-3],0!==c.prevLevel3?q(c.level3-c.prevLevel3)/c.prevLevel3*100:null];return e};e.defaultOptions=p(l.defaultOptions);return e}(l);f.registerSeriesType("trix",g);"";return g});w(f,"Stock/Indicators/APO/APOIndicator.js",
[f["Core/Series/Series.js"],f["Mixins/IndicatorRequired.js"],f["Core/Utilities.js"]],function(f,d,g){var h=this&&this.__extends||function(){var e=function(b,a){e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return e(b,a)};return function(b,a){function c(){this.constructor=b}e(b,a);b.prototype=null===a?Object.create(a):(c.prototype=a.prototype,new c)}}(),l=f.seriesTypes.ema,q=g.extend,p=g.merge,m=
g.error;g=function(e){function b(){var a=null!==e&&e.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}h(b,e);b.prototype.getValues=function(a,c){var b=c.periods,e=c.index;c=[];var d=[],f=[],g;if(2!==b.length||b[1]<=b[0])m('Error: "APO requires two periods. Notice, first period should be lower than the second one."');else{var h=l.prototype.getValues.call(this,a,{index:e,period:b[0]});a=l.prototype.getValues.call(this,a,{index:e,period:b[1]});if(h&&a){b=b[1]-b[0];
for(g=0;g<a.yData.length;g++)e=h.yData[g+b]-a.yData[g],c.push([a.xData[g],e]),d.push(a.xData[g]),f.push(e);return{values:c,xData:d,yData:f}}}};b.prototype.init=function(){var a=arguments,c=this;d.isParentLoaded(l,"ema",c.type,function(b){b.prototype.init.apply(c,a)})};b.defaultOptions=p(l.defaultOptions,{params:{periods:[10,20]}});return b}(l);q(g.prototype,{nameBase:"APO",nameComponents:["periods"]});f.registerSeriesType("apo",g);"";return g});w(f,"Stock/Indicators/IKH/IKHIndicator.js",[f["Core/Series/Series.js"],
f["Core/Color/Color.js"],f["Core/Globals.js"],f["Core/Utilities.js"]],function(f,d,g,u){function h(a){return a.reduce(function(a,c){return Math.max(a,c[1])},-Infinity)}function q(a){return a.reduce(function(a,c){return Math.min(a,c[2])},Infinity)}function p(a){return{high:h(a),low:q(a)}}function m(a){var c,b,k,e,d;a.series.forEach(function(a){if(a.xData)for(e=a.xData,d=b=a.xIncrement?1:e.length-1;0<d;d--)if(k=e[d]-e[d-1],"undefined"===typeof c||k<c)c=k});return c}function e(a,c,b,k){if(a&&c&&b&&k){var e=
c.plotX-a.plotX;c=c.plotY-a.plotY;var d=k.plotX-b.plotX;k=k.plotY-b.plotY;var n=a.plotX-b.plotX,v=a.plotY-b.plotY;b=(-c*n+e*v)/(-d*c+e*k);d=(d*v-k*n)/(-d*c+e*k);if(0<=b&&1>=b&&0<=d&&1>=d)return{plotX:a.plotX+d*e,plotY:a.plotY+d*c}}return!1}function b(a){var c=a.indicator;c.points=a.points;c.nextPoints=a.nextPoints;c.color=a.color;c.options=A(a.options.senkouSpan.styles,a.gap);c.graph=a.graph;c.fillGraph=!0;f.seriesTypes.sma.prototype.drawGraph.call(c)}var a=this&&this.__extends||function(){var a=
function(c,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(c,b)};return function(c,b){function k(){this.constructor=c}a(c,b);c.prototype=null===b?Object.create(b):(k.prototype=b.prototype,new k)}}(),c=f.seriesTypes.sma,k=d.parse,y=u.defined;d=u.extend;var v=u.isArray,A=u.merge,K=u.objectEach;g.approximations["ichimoku-averages"]=function(){var a=[],c;[].forEach.call(arguments,function(b,
k){a.push(g.approximations.average(b));c=!c&&"undefined"===typeof a[k]});return c?void 0:a};u=function(d){function g(){var a=null!==d&&d.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;a.graphCollection=void 0;a.graphsenkouSpan=void 0;a.ikhMap=void 0;a.nextPoints=void 0;return a}a(g,d);g.prototype.init=function(){f.seriesTypes.sma.prototype.init.apply(this,arguments);this.options=A({tenkanLine:{styles:{lineColor:this.color}},kijunLine:{styles:{lineColor:this.color}},chikouLine:{styles:{lineColor:this.color}},
senkouSpanA:{styles:{lineColor:this.color,fill:k(this.color).setOpacity(.5).get()}},senkouSpanB:{styles:{lineColor:this.color,fill:k(this.color).setOpacity(.5).get()}},senkouSpan:{styles:{fill:k(this.color).setOpacity(.2).get()}}},this.options)};g.prototype.toYData=function(a){return[a.tenkanSen,a.kijunSen,a.chikouSpan,a.senkouSpanA,a.senkouSpanB]};g.prototype.translate=function(){var a=this;f.seriesTypes.sma.prototype.translate.apply(a);a.points.forEach(function(c){a.pointArrayMap.forEach(function(b){y(c[b])&&
(c["plot"+b]=a.yAxis.toPixels(c[b],!0),c.plotY=c["plot"+b],c.tooltipPos=[c.plotX,c["plot"+b]],c.isNull=!1)})})};g.prototype.drawGraph=function(){var a=this,c=a.points,k=c.length,d=a.options,v=a.graph,g=a.color,m={options:{gapSize:d.gapSize}},t=a.pointArrayMap.length,h=[[],[],[],[],[],[]],l={tenkanLine:h[0],kijunLine:h[1],chikouLine:h[2],senkouSpanA:h[3],senkouSpanB:h[4],senkouSpan:h[5]},u=[],p=a.options.senkouSpan,q=p.color||p.styles.fill,M=p.negativeColor,w=[[],[]],O=[[],[]],P=0,G,Q,N;for(a.ikhMap=
l;k--;){var C=c[k];for(G=0;G<t;G++)p=a.pointArrayMap[G],y(C[p])&&h[G].push({plotX:C.plotX,plotY:C["plot"+p],isNull:!1});M&&k!==c.length-1&&(p=l.senkouSpanB.length-1,C=e(l.senkouSpanA[p-1],l.senkouSpanA[p],l.senkouSpanB[p-1],l.senkouSpanB[p]),G={plotX:C.plotX,plotY:C.plotY,isNull:!1,intersectPoint:!0},C&&(l.senkouSpanA.splice(p,0,G),l.senkouSpanB.splice(p,0,G),u.push(p)))}K(l,function(c,b){d[b]&&"senkouSpan"!==b&&(a.points=h[P],a.options=A(d[b].styles,m),a.graph=a["graph"+b],a.fillGraph=!1,a.color=
g,f.seriesTypes.sma.prototype.drawGraph.call(a),a["graph"+b]=a.graph);P++});a.graphCollection&&a.graphCollection.forEach(function(c){a[c].destroy();delete a[c]});a.graphCollection=[];if(M&&l.senkouSpanA[0]&&l.senkouSpanB[0]){u.unshift(0);u.push(l.senkouSpanA.length-1);for(t=0;t<u.length-1;t++){p=u[t];C=u[t+1];k=l.senkouSpanB.slice(p,C+1);p=l.senkouSpanA.slice(p,C+1);if(1<=Math.floor(k.length/2))if(C=Math.floor(k.length/2),k[C].plotY===p[C].plotY){for(N=G=C=0;N<k.length;N++)C+=k[N].plotY,G+=p[N].plotY;
C=C>G?0:1}else C=k[C].plotY>p[C].plotY?0:1;else C=k[0].plotY>p[0].plotY?0:1;w[C]=w[C].concat(k);O[C]=O[C].concat(p)}["graphsenkouSpanColor","graphsenkouSpanNegativeColor"].forEach(function(c,k){w[k].length&&O[k].length&&(Q=0===k?q:M,b({indicator:a,points:w[k],nextPoints:O[k],color:Q,options:d,gap:m,graph:a[c]}),a[c]=a.graph,a.graphCollection.push(c))})}else b({indicator:a,points:l.senkouSpanB,nextPoints:l.senkouSpanA,color:q,options:d,gap:m,graph:a.graphsenkouSpan}),a.graphsenkouSpan=a.graph;delete a.nextPoints;
delete a.fillGraph;a.points=c;a.options=d;a.graph=v};g.prototype.getGraphPath=function(a){var c=[],b;a=a||this.points;if(this.fillGraph&&this.nextPoints){if((b=f.seriesTypes.sma.prototype.getGraphPath.call(this,this.nextPoints))&&b.length){b[0][0]="L";c=f.seriesTypes.sma.prototype.getGraphPath.call(this,a);b=b.slice(0,c.length);for(var k=b.length-1;0<=k;k--)c.push(b[k])}}else c=f.seriesTypes.sma.prototype.getGraphPath.apply(this,arguments);return c};g.prototype.getValues=function(a,c){var b=c.period,
k=c.periodTenkan;c=c.periodSenkouSpanB;var e=a.xData,d=a.yData,f=d&&d.length||0;a=m(a.xAxis);var y=[],n=[],g;if(!(e.length<=b)&&v(d[0])&&4===d[0].length){var A=e[0]-b*a;for(g=0;g<b;g++)n.push(A+g*a);for(g=0;g<f;g++){if(g>=k){var t=d.slice(g-k,g);t=p(t);t=(t.high+t.low)/2}if(g>=b){var h=d.slice(g-b,g);h=p(h);h=(h.high+h.low)/2;var x=(t+h)/2}if(g>=c){var l=d.slice(g-c,g);l=p(l);l=(l.high+l.low)/2}A=d[g][3];var u=e[g];"undefined"===typeof y[g]&&(y[g]=[]);"undefined"===typeof y[g+b]&&(y[g+b]=[]);y[g+
b][0]=t;y[g+b][1]=h;y[g+b][2]=void 0;y[g][2]=A;g<=b&&(y[g+b][3]=void 0,y[g+b][4]=void 0);"undefined"===typeof y[g+2*b]&&(y[g+2*b]=[]);y[g+2*b][3]=x;y[g+2*b][4]=l;n.push(u)}for(g=1;g<=b;g++)n.push(u+g*a);return{values:y,xData:n,yData:y}}};g.defaultOptions=A(c.defaultOptions,{params:{period:26,periodTenkan:9,periodSenkouSpanB:52},marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>TENKAN SEN: {point.tenkanSen:.3f}<br/>KIJUN SEN: {point.kijunSen:.3f}<br/>CHIKOU SPAN: {point.chikouSpan:.3f}<br/>SENKOU SPAN A: {point.senkouSpanA:.3f}<br/>SENKOU SPAN B: {point.senkouSpanB:.3f}<br/>'},
tenkanLine:{styles:{lineWidth:1,lineColor:void 0}},kijunLine:{styles:{lineWidth:1,lineColor:void 0}},chikouLine:{styles:{lineWidth:1,lineColor:void 0}},senkouSpanA:{styles:{lineWidth:1,lineColor:void 0}},senkouSpanB:{styles:{lineWidth:1,lineColor:void 0}},senkouSpan:{styles:{fill:"rgba(255, 0, 0, 0.5)"}},dataGrouping:{approximation:"ichimoku-averages"}});return g}(c);d(u.prototype,{pointArrayMap:["tenkanSen","kijunSen","chikouSpan","senkouSpanA","senkouSpanB"],pointValKey:"tenkanSen",nameComponents:["periodSenkouSpanB",
"period","periodTenkan"]});f.registerSeriesType("ikh",u);"";return u});w(f,"Stock/Indicators/KeltnerChannels/KeltnerChannelsIndicator.js",[f["Core/Series/Series.js"],f["Mixins/MultipleLines.js"],f["Core/Utilities.js"]],function(f,d,g){var h=this&&this.__extends||function(){var e=function(b,a){e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return e(b,a)};return function(b,a){function c(){this.constructor=
b}e(b,a);b.prototype=null===a?Object.create(a):(c.prototype=a.prototype,new c)}}(),l=f.seriesTypes.sma,q=g.correctFloat,p=g.extend,m=g.merge;g=function(e){function b(){var a=null!==e&&e.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}h(b,e);b.prototype.init=function(){f.seriesTypes.sma.prototype.init.apply(this,arguments);this.options=m({topLine:{styles:{lineColor:this.color}},bottomLine:{styles:{lineColor:this.color}}},this.options)};b.prototype.getValues=function(a,
c){var b=c.period,e=c.periodATR,d=c.multiplierATR,g=a.yData;g=g?g.length:0;var m=[];c=f.seriesTypes.ema.prototype.getValues(a,{period:b,index:c.index});var h=f.seriesTypes.atr.prototype.getValues(a,{period:e}),t=[],n=[],x;if(!(g<b)){for(x=b;x<=g;x++){var r=c.values[x-b];var l=h.values[x-e];var p=r[0];a=q(r[1]+d*l[1]);l=q(r[1]-d*l[1]);r=r[1];m.push([p,a,r,l]);t.push(p);n.push([a,r,l])}return{values:m,xData:t,yData:n}}};b.defaultOptions=m(l.defaultOptions,{params:{period:20,periodATR:10,multiplierATR:2},
bottomLine:{styles:{lineWidth:1,lineColor:void 0}},topLine:{styles:{lineWidth:1,lineColor:void 0}},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Upper Channel: {point.top}<br/>EMA({series.options.params.period}): {point.middle}<br/>Lower Channel: {point.bottom}<br/>'},marker:{enabled:!1},dataGrouping:{approximation:"averages"},lineWidth:1});return b}(l);p(g.prototype,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameBase:"Keltner Channels",
nameComponents:["period","periodATR","multiplierATR"],linesApiNames:["topLine","bottomLine"],requiredIndicators:["ema","atr"],drawGraph:d.drawGraph,getTranslatedLinesNames:d.getTranslatedLinesNames,translate:d.translate,toYData:d.toYData});f.registerSeriesType("keltnerchannels",g);"";return g});w(f,"Stock/Indicators/MACD/MACDIndicator.js",[f["Core/Series/Series.js"],f["Core/Globals.js"],f["Core/Utilities.js"]],function(f,d,g){var h=this&&this.__extends||function(){var a=function(c,b){a=Object.setPrototypeOf||
{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(c,b)};return function(c,b){function k(){this.constructor=c}a(c,b);c.prototype=null===b?Object.create(b):(k.prototype=b.prototype,new k)}}(),l=f.seriesTypes.sma,q=d.noop,p=g.extend,m=g.correctFloat,e=g.defined,b=g.merge;g=function(a){function c(){var c=null!==a&&a.apply(this,arguments)||this;c.data=void 0;c.options=void 0;c.points=void 0;c.currentLineZone=void 0;c.graphmacd=
void 0;c.graphsignal=void 0;c.macdZones=void 0;c.signalZones=void 0;return c}h(c,a);c.prototype.init=function(){f.seriesTypes.sma.prototype.init.apply(this,arguments);this.options&&(this.options=b({signalLine:{styles:{lineColor:this.color}},macdLine:{styles:{color:this.color}}},this.options),this.macdZones={zones:this.options.macdLine.zones,startIndex:0},this.signalZones={zones:this.macdZones.zones.concat(this.options.signalLine.zones),startIndex:this.macdZones.zones.length},this.resetZones=!0)};
c.prototype.toYData=function(a){return[a.y,a.signal,a.MACD]};c.prototype.translate=function(){var a=this,c=["plotSignal","plotMACD"];d.seriesTypes.column.prototype.translate.apply(a);a.points.forEach(function(b){[b.signal,b.MACD].forEach(function(k,e){null!==k&&(b[c[e]]=a.yAxis.toPixels(k,!0))})})};c.prototype.destroy=function(){this.graph=null;this.graphmacd=this.graphmacd&&this.graphmacd.destroy();this.graphsignal=this.graphsignal&&this.graphsignal.destroy();f.seriesTypes.sma.prototype.destroy.apply(this,
arguments)};c.prototype.drawGraph=function(){for(var a=this,c=a.points,d=c.length,g=a.options,m=a.zones,h={options:{gapSize:g.gapSize}},t=[[],[]],n;d--;)n=c[d],e(n.plotMACD)&&t[0].push({plotX:n.plotX,plotY:n.plotMACD,isNull:!e(n.plotMACD)}),e(n.plotSignal)&&t[1].push({plotX:n.plotX,plotY:n.plotSignal,isNull:!e(n.plotMACD)});["macd","signal"].forEach(function(c,e){a.points=t[e];a.options=b(g[c+"Line"].styles,h);a.graph=a["graph"+c];a.currentLineZone=c+"Zones";a.zones=a[a.currentLineZone].zones;f.seriesTypes.sma.prototype.drawGraph.call(a);
a["graph"+c]=a.graph});a.points=c;a.options=g;a.zones=m;a.currentLineZone=null};c.prototype.getZonesGraphs=function(a){var c=f.seriesTypes.sma.prototype.getZonesGraphs.call(this,a),b=c;this.currentLineZone&&(b=c.splice(this[this.currentLineZone].startIndex+1),b.length?b.splice(0,0,a[0]):b=[a[0]]);return b};c.prototype.applyZones=function(){var a=this.zones;this.zones=this.signalZones.zones;f.seriesTypes.sma.prototype.applyZones.call(this);this.graphmacd&&this.options.macdLine.zones.length&&this.graphmacd.hide();
this.zones=a};c.prototype.getValues=function(a,c){var b=0,k=[],d=[],g=[];if(!(a.xData.length<c.longPeriod+c.signalPeriod)){var y=f.seriesTypes.ema.prototype.getValues(a,{period:c.shortPeriod});var n=f.seriesTypes.ema.prototype.getValues(a,{period:c.longPeriod});y=y.values;n=n.values;for(a=1;a<=y.length;a++)e(n[a-1])&&e(n[a-1][1])&&e(y[a+c.shortPeriod+1])&&e(y[a+c.shortPeriod+1][0])&&k.push([y[a+c.shortPeriod+1][0],0,null,y[a+c.shortPeriod+1][1]-n[a-1][1]]);for(a=0;a<k.length;a++)d.push(k[a][0]),g.push([0,
null,k[a][3]]);c=f.seriesTypes.ema.prototype.getValues({xData:d,yData:g},{period:c.signalPeriod,index:2});c=c.values;for(a=0;a<k.length;a++)k[a][0]>=c[0][0]&&(k[a][2]=c[b][1],g[a]=[0,c[b][1],k[a][3]],null===k[a][3]?(k[a][1]=0,g[a][0]=0):(k[a][1]=m(k[a][3]-c[b][1]),g[a][0]=m(k[a][3]-c[b][1])),b++);return{values:k,xData:d,yData:g}}};c.defaultOptions=b(l.defaultOptions,{params:{shortPeriod:12,longPeriod:26,signalPeriod:9,period:26},signalLine:{zones:[],styles:{lineWidth:1,lineColor:void 0}},macdLine:{zones:[],
styles:{lineWidth:1,lineColor:void 0}},threshold:0,groupPadding:.1,pointPadding:.1,crisp:!1,states:{hover:{halo:{size:0}}},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Value: {point.MACD}<br/>Signal: {point.signal}<br/>Histogram: {point.y}<br/>'},dataGrouping:{approximation:"averages"},minPointLength:0});return c}(l);p(g.prototype,{nameComponents:["longPeriod","shortPeriod","signalPeriod"],requiredIndicators:["ema"],pointArrayMap:["y","signal","MACD"],
parallelArrays:["x","y","signal","MACD"],pointValKey:"y",markerAttribs:q,getColumnMetrics:d.seriesTypes.column.prototype.getColumnMetrics,crispCol:d.seriesTypes.column.prototype.crispCol,drawPoints:d.seriesTypes.column.prototype.drawPoints});f.registerSeriesType("macd",g);"";return g});w(f,"Stock/Indicators/MFI/MFIIndicator.js",[f["Core/Series/Series.js"],f["Core/Utilities.js"]],function(f,d){function g(a){return a.reduce(function(a,b){return a+b})}function h(a){return(a[1]+a[2]+a[3])/3}var l=this&&
this.__extends||function(){var a=function(c,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(c,b)};return function(c,b){function e(){this.constructor=c}a(c,b);c.prototype=null===b?Object.create(b):(e.prototype=b.prototype,new e)}}(),q=f.seriesTypes.sma,p=d.extend,m=d.merge,e=d.error,b=d.isArray;d=function(a){function c(){var c=null!==a&&a.apply(this,arguments)||this;c.data=void 0;c.options=
void 0;c.points=void 0;return c}l(c,a);c.prototype.getValues=function(a,c){var k=c.period,d=a.xData,f=a.yData,m=f?f.length:0,y=c.decimals,n=1,x=a.chart.get(c.volumeSeriesID),r=x&&x.yData,l=[],p=[],u=[],q=[],F=[];if(!x)e("Series "+c.volumeSeriesID+" not found! Check `volumeSeriesID`.",!0,a.chart);else if(!(d.length<=k)&&b(f[0])&&4===f[0].length&&r){for(a=h(f[n]);n<k+1;)c=a,a=h(f[n]),c=a>=c,x=a*r[n],q.push(c?x:0),F.push(c?0:x),n++;for(k=n-1;k<m;k++)k>n-1&&(q.shift(),F.shift(),c=a,a=h(f[k]),c=a>c,x=
a*r[k],q.push(c?x:0),F.push(c?0:x)),c=g(F),x=g(q),c=x/c,c=parseFloat((100-100/(1+c)).toFixed(y)),l.push([d[k],c]),p.push(d[k]),u.push(c);return{values:l,xData:p,yData:u}}};c.defaultOptions=m(q.defaultOptions,{params:{period:14,volumeSeriesID:"volume",decimals:4}});return c}(q);p(d.prototype,{nameBase:"Money Flow Index"});f.registerSeriesType("mfi",d);"";return d});w(f,"Stock/Indicators/Momentum/MomentumIndicator.js",[f["Core/Series/Series.js"],f["Core/Utilities.js"]],function(f,d){function g(e,b,
a,c,k){a=a[c-1][3]-a[c-k-1][3];b=b[c-1];e.shift();return[b,a]}var h=this&&this.__extends||function(){var e=function(b,a){e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return e(b,a)};return function(b,a){function c(){this.constructor=b}e(b,a);b.prototype=null===a?Object.create(a):(c.prototype=a.prototype,new c)}}(),l=f.seriesTypes.sma,q=d.extend,p=d.isArray,m=d.merge;d=function(e){function b(){var a=
null!==e&&e.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}h(b,e);b.prototype.getValues=function(a,c){c=c.period;var b=a.xData,e=(a=a.yData)?a.length:0,d=b[0],f=[],m=[],h=[];if(!(b.length<=c)&&p(a[0])){var t=a[0][3];t=[[d,t]];for(d=c+1;d<e;d++){var n=g(t,b,a,d,c,void 0);f.push(n);m.push(n[0]);h.push(n[1])}n=g(t,b,a,d,c,void 0);f.push(n);m.push(n[0]);h.push(n[1]);return{values:f,xData:m,yData:h}}};b.defaultOptions=m(l.defaultOptions,{params:{period:14}});return b}(l);
q(d.prototype,{nameBase:"Momentum"});f.registerSeriesType("momentum",d);"";return d});w(f,"Stock/Indicators/NATR/NATRIndicator.js",[f["Core/Series/Series.js"],f["Core/Utilities.js"]],function(f,d){var g=this&&this.__extends||function(){var d=function(g,e){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return d(g,e)};return function(g,e){function b(){this.constructor=g}d(g,e);g.prototype=null===e?
Object.create(e):(b.prototype=e.prototype,new b)}}(),h=f.seriesTypes.atr,l=d.merge;d=d.extend;var q=function(d){function f(){var e=null!==d&&d.apply(this,arguments)||this;e.data=void 0;e.points=void 0;e.options=void 0;return e}g(f,d);f.prototype.getValues=function(e,b){var a=h.prototype.getValues.apply(this,arguments),c=a.values.length,k=b.period-1,d=e.yData,g=0;if(a){for(;g<c;g++)a.yData[g]=a.values[g][1]/d[k][3]*100,a.values[g][1]=a.yData[g],k++;return a}};f.defaultOptions=l(h.defaultOptions,{tooltip:{valueSuffix:"%"}});
return f}(h);d(q.prototype,{requiredIndicators:["atr"]});f.registerSeriesType("natr",q);"";return q});w(f,"Stock/Indicators/PivotPoints/PivotPointsPoint.js",[f["Core/Series/Series.js"]],function(f){function d(d,g){var h=d.series.pointArrayMap,l=h.length;for(f.seriesTypes.sma.prototype.pointClass.prototype[g].call(d);l--;)g="dataLabel"+h[l],d[g]&&d[g].element&&d[g].destroy(),d[g]=null}var g=this&&this.__extends||function(){var d=function(g,f){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&
function(d,g){d.__proto__=g}||function(d,g){for(var e in g)g.hasOwnProperty(e)&&(d[e]=g[e])};return d(g,f)};return function(g,f){function h(){this.constructor=g}d(g,f);g.prototype=null===f?Object.create(f):(h.prototype=f.prototype,new h)}}();return function(f){function h(){var d=null!==f&&f.apply(this,arguments)||this;d.P=void 0;d.pivotLine=void 0;d.series=void 0;return d}g(h,f);h.prototype.destroyElements=function(){d(this,"destroyElements")};h.prototype.destroy=function(){d(this,"destroyElements")};
return h}(f.seriesTypes.sma.prototype.pointClass)});w(f,"Stock/Indicators/PivotPoints/PivotPointsIndicator.js",[f["Core/Series/Series.js"],f["Stock/Indicators/PivotPoints/PivotPointsPoint.js"],f["Core/Utilities.js"]],function(f,d,g){var h=this&&this.__extends||function(){var b=function(a,c){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return b(a,c)};return function(a,c){function e(){this.constructor=
a}b(a,c);a.prototype=null===c?Object.create(c):(e.prototype=c.prototype,new e)}}(),l=f.seriesTypes.sma,q=g.merge,p=g.extend,m=g.defined,e=g.isArray;g=function(b){function a(){var a=null!==b&&b.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;a.endPoint=void 0;a.plotEndPoint=void 0;return a}h(a,b);a.prototype.toYData=function(a){return[a.P]};a.prototype.translate=function(){var a=this;f.seriesTypes.sma.prototype.translate.apply(a);a.points.forEach(function(c){a.pointArrayMap.forEach(function(b){m(c[b])&&
(c["plot"+b]=a.yAxis.toPixels(c[b],!0))})});a.plotEndPoint=a.xAxis.toPixels(a.endPoint,!0)};a.prototype.getGraphPath=function(a){for(var c=this,b=a.length,e=[[],[],[],[],[],[],[],[],[]],d=[],g=c.plotEndPoint,h=c.pointArrayMap.length,t,n,x;b--;){n=a[b];for(x=0;x<h;x++)t=c.pointArrayMap[x],m(n[t])&&e[x].push({plotX:n.plotX,plotY:n["plot"+t],isNull:!1},{plotX:g,plotY:n["plot"+t],isNull:!1},{plotX:g,plotY:null,isNull:!0});g=n.plotX}e.forEach(function(a){d=d.concat(f.seriesTypes.sma.prototype.getGraphPath.call(c,
a))});return d};a.prototype.drawDataLabels=function(){var a=this,b=a.pointArrayMap,e,d,g;if(a.options.dataLabels.enabled){var m=a.points.length;b.concat([!1]).forEach(function(c,k){for(g=m;g--;)d=a.points[g],c?(d.y=d[c],d.pivotLine=c,d.plotY=d["plot"+c],e=d["dataLabel"+c],k&&(d["dataLabel"+b[k-1]]=d.dataLabel),d.dataLabels||(d.dataLabels=[]),d.dataLabels[0]=d.dataLabel=e=e&&e.element?e:null):d["dataLabel"+b[k-1]]=d.dataLabel;f.seriesTypes.sma.prototype.drawDataLabels.apply(a,arguments)})}};a.prototype.getValues=
function(a,b){var c=b.period,d=a.xData,k=(a=a.yData)?a.length:0;b=this[b.algorithm+"Placement"];var g=[],f=[],m=[],n;if(!(d.length<c)&&e(a[0])&&4===a[0].length){for(n=c+1;n<=k+c;n+=c){var h=d.slice(n-c-1,n);var r=a.slice(n-c-1,n);var l=h.length;var p=h[l-1];r=this.getPivotAndHLC(r);r=b(r);r=g.push([p].concat(r));f.push(p);m.push(g[r-1].slice(1))}this.endPoint=h[0]+(p-h[0])/l*c;return{values:g,xData:f,yData:m}}};a.prototype.getPivotAndHLC=function(a){var c=-Infinity,b=Infinity,e=a[a.length-1][3];a.forEach(function(a){c=
Math.max(c,a[1]);b=Math.min(b,a[2])});return[(c+b+e)/3,c,b,e]};a.prototype.standardPlacement=function(a){var c=a[1]-a[2];return[null,null,a[0]+c,2*a[0]-a[2],a[0],2*a[0]-a[1],a[0]-c,null,null]};a.prototype.camarillaPlacement=function(a){var c=a[1]-a[2];return[a[3]+1.5*c,a[3]+1.25*c,a[3]+1.1666*c,a[3]+1.0833*c,a[0],a[3]-1.0833*c,a[3]-1.1666*c,a[3]-1.25*c,a[3]-1.5*c]};a.prototype.fibonacciPlacement=function(a){var c=a[1]-a[2];return[null,a[0]+c,a[0]+.618*c,a[0]+.382*c,a[0],a[0]-.382*c,a[0]-.618*c,a[0]-
c,null]};a.defaultOptions=q(l.defaultOptions,{params:{period:28,algorithm:"standard"},marker:{enabled:!1},enableMouseTracking:!1,dataLabels:{enabled:!0,format:"{point.pivotLine}"},dataGrouping:{approximation:"averages"}});return a}(l);p(g.prototype,{nameBase:"Pivot Points",pointArrayMap:"R4 R3 R2 R1 P S1 S2 S3 S4".split(" "),pointValKey:"P",pointClass:d});f.registerSeriesType("pivotpoints",g);"";return g});w(f,"Stock/Indicators/PPO/PPOIndicator.js",[f["Core/Series/Series.js"],f["Mixins/IndicatorRequired.js"],
f["Core/Utilities.js"]],function(f,d,g){var h=this&&this.__extends||function(){var b=function(a,c){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return b(a,c)};return function(a,c){function e(){this.constructor=a}b(a,c);a.prototype=null===c?Object.create(c):(e.prototype=c.prototype,new e)}}(),l=f.seriesTypes.ema,q=g.correctFloat,p=g.extend,m=g.merge,e=g.error;g=function(b){function a(){var a=null!==
b&&b.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}h(a,b);a.prototype.init=function(){var a=arguments,b=this;d.isParentLoaded(l,"ema",b.type,function(c){c.prototype.init.apply(b,a)})};a.prototype.getValues=function(a,b){var c=b.periods,d=b.index;b=[];var k=[],g=[],f;if(2!==c.length||c[1]<=c[0])e('Error: "PPO requires two periods. Notice, first period should be lower than the second one."');else{var m=l.prototype.getValues.call(this,a,{index:d,period:c[0]});a=
l.prototype.getValues.call(this,a,{index:d,period:c[1]});if(m&&a){c=c[1]-c[0];for(f=0;f<a.yData.length;f++)d=q((m.yData[f+c]-a.yData[f])/a.yData[f]*100),b.push([a.xData[f],d]),k.push(a.xData[f]),g.push(d);return{values:b,xData:k,yData:g}}}};a.defaultOptions=m(l.defaultOptions,{params:{periods:[12,26]}});return a}(l);p(g.prototype,{nameBase:"PPO",nameComponents:["periods"]});f.registerSeriesType("ppo",g);"";return g});w(f,"Mixins/ReduceArray.js",[],function(){return{minInArray:function(f,d){return f.reduce(function(g,
f){return Math.min(g,f[d])},Number.MAX_VALUE)},maxInArray:function(f,d){return f.reduce(function(g,f){return Math.max(g,f[d])},-Number.MAX_VALUE)},getArrayExtremes:function(f,d,g){return f.reduce(function(f,h){return[Math.min(f[0],h[d]),Math.max(f[1],h[g])]},[Number.MAX_VALUE,-Number.MAX_VALUE])}}});w(f,"Stock/Indicators/PC/PCIndicator.js",[f["Core/Series/Series.js"],f["Core/Color/Palette.js"],f["Mixins/MultipleLines.js"],f["Mixins/ReduceArray.js"],f["Core/Utilities.js"]],function(f,d,g,u,l){var h=
this&&this.__extends||function(){var b=function(a,c){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return b(a,c)};return function(a,c){function e(){this.constructor=a}b(a,c);a.prototype=null===c?Object.create(c):(e.prototype=c.prototype,new e)}}(),p=f.seriesTypes.sma,m=l.merge;l=l.extend;var e=u.getArrayExtremes;u=function(b){function a(){var a=null!==b&&b.apply(this,arguments)||this;a.data=void 0;
a.options=void 0;a.points=void 0;return a}h(a,b);a.prototype.getValues=function(a,b){b=b.period;var c=a.xData,d=(a=a.yData)?a.length:0,k=[],g=[],f=[],m;if(!(d<b)){for(m=b;m<=d;m++){var n=c[m-1];var h=a.slice(m-b,m);var r=e(h,2,1);h=r[1];var l=r[0];r=(h+l)/2;k.push([n,h,r,l]);g.push(n);f.push([h,r,l])}return{values:k,xData:g,yData:f}}};a.defaultOptions=m(p.defaultOptions,{params:{period:20},lineWidth:1,topLine:{styles:{lineColor:d.colors[2],lineWidth:1}},bottomLine:{styles:{lineColor:d.colors[8],lineWidth:1}},
dataGrouping:{approximation:"averages"}});return a}(p);l(u.prototype,{getTranslatedLinesNames:g.getTranslatedLinesNames,drawGraph:g.drawGraph,toYData:g.toYData,pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameBase:"Price Channel",nameComponents:["period"],linesApiNames:["topLine","bottomLine"],translate:g.translate});f.registerSeriesType("pc",u);"";return u});w(f,"Stock/Indicators/PriceEnvelopes/PriceEnvelopesIndicator.js",[f["Core/Series/Series.js"],f["Core/Utilities.js"]],function(f,
d){var g=this&&this.__extends||function(){var d=function(e,b){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return d(e,b)};return function(e,b){function a(){this.constructor=e}d(e,b);e.prototype=null===b?Object.create(b):(a.prototype=b.prototype,new a)}}(),h=f.seriesTypes.sma,l=d.extend,q=d.isArray,p=d.merge;d=function(d){function e(){var b=null!==d&&d.apply(this,arguments)||this;b.data=void 0;
b.options=void 0;b.points=void 0;return b}g(e,d);e.prototype.init=function(){f.seriesTypes.sma.prototype.init.apply(this,arguments);this.options=p({topLine:{styles:{lineColor:this.color}},bottomLine:{styles:{lineColor:this.color}}},this.options)};e.prototype.toYData=function(b){return[b.top,b.middle,b.bottom]};e.prototype.translate=function(){var b=this,a=["plotTop","plotMiddle","plotBottom"];f.seriesTypes.sma.prototype.translate.apply(b);b.points.forEach(function(c){[c.top,c.middle,c.bottom].forEach(function(e,
d){null!==e&&(c[a[d]]=b.yAxis.toPixels(e,!0))})})};e.prototype.drawGraph=function(){for(var b=this,a=b.points,c=a.length,e=b.options,d=b.graph,g={options:{gapSize:e.gapSize}},m=[[],[]],h;c--;)h=a[c],m[0].push({plotX:h.plotX,plotY:h.plotTop,isNull:h.isNull}),m[1].push({plotX:h.plotX,plotY:h.plotBottom,isNull:h.isNull});["topLine","bottomLine"].forEach(function(a,c){b.points=m[c];b.options=p(e[a].styles,g);b.graph=b["graph"+a];f.seriesTypes.sma.prototype.drawGraph.call(b);b["graph"+a]=b.graph});b.points=
a;b.options=e;b.graph=d;f.seriesTypes.sma.prototype.drawGraph.call(b)};e.prototype.getValues=function(b,a){var c=a.period,e=a.topBand,d=a.bottomBand,g=b.xData,m=(b=b.yData)?b.length:0,h=[],l=[],t=[],n;if(!(g.length<c)&&q(b[0])&&4===b[0].length){for(n=c;n<=m;n++){var x=g.slice(n-c,n);var r=b.slice(n-c,n);r=f.seriesTypes.sma.prototype.getValues.call(this,{xData:x,yData:r},a);x=r.xData[0];r=r.yData[0];var p=r*(1+e);var u=r*(1-d);h.push([x,p,r,u]);l.push(x);t.push([p,r,u])}return{values:h,xData:l,yData:t}}};
e.defaultOptions=p(h.defaultOptions,{marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Top: {point.top}<br/>Middle: {point.middle}<br/>Bottom: {point.bottom}<br/>'},params:{period:20,topBand:.1,bottomBand:.1},bottomLine:{styles:{lineWidth:1,lineColor:void 0}},topLine:{styles:{lineWidth:1}},dataGrouping:{approximation:"averages"}});return e}(h);l(d.prototype,{nameComponents:["period","topBand","bottomBand"],nameBase:"Price envelopes",
pointArrayMap:["top","middle","bottom"],parallelArrays:["x","y","top","bottom"],pointValKey:"middle"});f.registerSeriesType("priceenvelopes",d);"";return d});w(f,"Stock/Indicators/PSAR/PSARIndicator.js",[f["Core/Series/Series.js"],f["Core/Utilities.js"]],function(f,d){var g=this&&this.__extends||function(){var d=function(f,e){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return d(f,e)};return function(f,
e){function b(){this.constructor=f}d(f,e);f.prototype=null===e?Object.create(e):(b.prototype=e.prototype,new b)}}(),h=f.seriesTypes.sma,l=d.merge;d=d.extend;var q=function(d){function f(){var e=null!==d&&d.apply(this,arguments)||this;e.data=void 0;e.points=void 0;e.options=void 0;return e}g(f,d);f.prototype.getValues=function(e,b){var a=e.xData;e=e.yData;var c=e[0][1],d=b.maxAccelerationFactor,f=b.increment,g=b.initialAccelerationFactor,m=e[0][2],h=b.decimals,l=b.index,t=[],n=[],x=[],r=1,p;if(!(l>=
e.length)){for(p=0;p<l;p++)c=Math.max(e[p][1],c),m=Math.min(e[p][2],parseFloat(m.toFixed(h)));var q=e[p][1]>m?1:-1;b=b.initialAccelerationFactor;var u=b*(c-m);t.push([a[l],m]);n.push(a[l]);x.push(parseFloat(m.toFixed(h)));for(p=l+1;p<e.length;p++){l=e[p-1][2];var z=e[p-2][2];var F=e[p-1][1];var w=e[p-2][1];var B=e[p][1];var D=e[p][2];null!==z&&null!==w&&null!==l&&null!==F&&null!==B&&null!==D&&(m=q===r?1===q?m+u<Math.min(z,l)?m+u:Math.min(z,l):m+u>Math.max(w,F)?m+u:Math.max(w,F):c,l=1===q?B>c?B:c:
D<c?D:c,B=1===r&&D>m||-1===r&&B>m?1:-1,r=B,u=l,D=f,z=d,F=g,b=r===q?1===r&&u>c?b===z?z:parseFloat((b+D).toFixed(2)):-1===r&&u<c?b===z?z:parseFloat((b+D).toFixed(2)):b:F,c=l-m,u=b*c,t.push([a[p],parseFloat(m.toFixed(h))]),n.push(a[p]),x.push(parseFloat(m.toFixed(h))),r=q,q=B,c=l)}return{values:t,xData:n,yData:x}}};f.defaultOptions=l(h.defaultOptions,{lineWidth:0,marker:{enabled:!0},states:{hover:{lineWidthPlus:0}},params:{initialAccelerationFactor:.02,maxAccelerationFactor:.2,increment:.02,index:2,
decimals:4}});return f}(h);d(q.prototype,{nameComponents:!1});f.registerSeriesType("psar",q);"";return q});w(f,"Stock/Indicators/ROC/ROCIndicator.js",[f["Core/Series/Series.js"],f["Core/Utilities.js"]],function(f,d){var g=this&&this.__extends||function(){var d=function(e,b){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return d(e,b)};return function(e,b){function a(){this.constructor=e}d(e,b);e.prototype=
null===b?Object.create(b):(a.prototype=b.prototype,new a)}}(),h=f.seriesTypes.sma,l=d.isArray,q=d.merge;d=d.extend;var p=function(d){function e(){var b=null!==d&&d.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}g(e,d);e.prototype.getValues=function(b,a){var c=a.period,e=b.xData,d=(b=b.yData)?b.length:0,f=[],g=[],m=[],h=-1;if(!(e.length<=c)){l(b[0])&&(h=a.index);for(a=c;a<d;a++){var t=0>h?(t=b[a-c])?(b[a]-t)/t*100:null:(t=b[a-c][h])?(b[a][h]-t)/t*100:null;t=[e[a],
t];f.push(t);g.push(t[0]);m.push(t[1])}return{values:f,xData:g,yData:m}}};e.defaultOptions=q(h.defaultOptions,{params:{index:3,period:9}});return e}(h);d(p.prototype,{nameBase:"Rate of Change"});f.registerSeriesType("roc",p);"";return p});w(f,"Stock/Indicators/RSI/RSIIndicator.js",[f["Core/Series/Series.js"],f["Core/Utilities.js"]],function(f,d){var g=this&&this.__extends||function(){var d=function(f,e){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,
a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return d(f,e)};return function(f,e){function b(){this.constructor=f}d(f,e);f.prototype=null===e?Object.create(e):(b.prototype=e.prototype,new b)}}(),h=f.seriesTypes.sma,l=d.isArray,q=d.merge;d=function(d){function f(){var e=null!==d&&d.apply(this,arguments)||this;e.data=void 0;e.points=void 0;e.options=void 0;return e}g(f,d);f.prototype.getValues=function(e,b){var a=b.period,c=e.xData,d=(e=e.yData)?e.length:0;b=b.decimals;var f=1,g=[],m=[],h=[],
p=0,t=0,n;if(!(c.length<a)&&l(e[0])&&4===e[0].length){for(;f<a;){var x=parseFloat((e[f][3]-e[f-1][3]).toFixed(b));0<x?p+=x:t+=Math.abs(x);f++}var r=parseFloat((p/(a-1)).toFixed(b));for(n=parseFloat((t/(a-1)).toFixed(b));f<d;f++)x=parseFloat((e[f][3]-e[f-1][3]).toFixed(b)),0<x?(p=x,t=0):(p=0,t=Math.abs(x)),r=parseFloat(((r*(a-1)+p)/a).toFixed(b)),n=parseFloat(((n*(a-1)+t)/a).toFixed(b)),p=0===n?100:0===r?0:parseFloat((100-100/(1+r/n)).toFixed(b)),g.push([c[f],p]),m.push(c[f]),h.push(p);return{values:g,
xData:m,yData:h}}};f.defaultOptions=q(h.defaultOptions,{params:{period:14,decimals:4}});return f}(h);f.registerSeriesType("rsi",d);"";return d});w(f,"Stock/Indicators/Stochastic/StochasticIndicator.js",[f["Core/Series/Series.js"],f["Mixins/MultipleLines.js"],f["Mixins/ReduceArray.js"],f["Core/Utilities.js"]],function(f,d,g,u){var h=this&&this.__extends||function(){var b=function(a,c){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&
(a[b]=c[b])};return b(a,c)};return function(a,c){function e(){this.constructor=a}b(a,c);a.prototype=null===c?Object.create(c):(e.prototype=c.prototype,new e)}}(),q=f.seriesTypes.sma,p=u.extend,m=u.isArray,e=u.merge;u=function(b){function a(){var a=null!==b&&b.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}h(a,b);a.prototype.init=function(){f.seriesTypes.sma.prototype.init.apply(this,arguments);this.options=e({smoothedLine:{styles:{lineColor:this.color}}},this.options)};
a.prototype.getValues=function(a,b){var c=b.periods[0];b=b.periods[1];var e=a.xData,d=(a=a.yData)?a.length:0,k=[],h=[],t=[],n=null,l;if(!(d<c)&&m(a[0])&&4===a[0].length){for(l=c-1;l<d;l++){var r=a.slice(l-c+1,l+1);var p=g.getArrayExtremes(r,2,1);var q=p[0];r=a[l][3]-q;q=p[1]-q;r=r/q*100;h.push(e[l]);t.push([r,null]);l>=c-1+(b-1)&&(n=f.seriesTypes.sma.prototype.getValues.call(this,{xData:h.slice(-b),yData:t.slice(-b)},{period:b}),n=n.yData[0]);k.push([e[l],r,n]);t[t.length-1][1]=n}return{values:k,
xData:h,yData:t}}};a.defaultOptions=e(q.defaultOptions,{params:{periods:[14,3]},marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>%K: {point.y}<br/>%D: {point.smoothed}<br/>'},smoothedLine:{styles:{lineWidth:1,lineColor:void 0}},dataGrouping:{approximation:"averages"}});return a}(q);p(u.prototype,{nameComponents:["periods"],nameBase:"Stochastic",pointArrayMap:["y","smoothed"],parallelArrays:["x","y","smoothed"],pointValKey:"y",linesApiNames:["smoothedLine"],
drawGraph:d.drawGraph,getTranslatedLinesNames:d.getTranslatedLinesNames,translate:d.translate,toYData:d.toYData});f.registerSeriesType("stochastic",u);"";return u});w(f,"Stock/Indicators/SlowStochastic/SlowStochasticIndicator.js",[f["Core/Series/Series.js"],f["Mixins/IndicatorRequired.js"],f["Core/Utilities.js"]],function(f,d,g){var h=this&&this.__extends||function(){var e=function(b,a){e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&
(a[c]=b[c])};return e(b,a)};return function(b,a){function c(){this.constructor=b}e(b,a);b.prototype=null===a?Object.create(a):(c.prototype=a.prototype,new c)}}(),l=f.seriesTypes.stochastic,q=f.seriesTypes,p=g.extend,m=g.merge;g=function(e){function b(){var a=null!==e&&e.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}h(b,e);b.prototype.init=function(){var a=arguments,b=this;d.isParentLoaded(q.stochastic,"stochastic",b.type,function(c){c.prototype.init.apply(b,a)})};
b.prototype.getValues=function(a,b){var c=b.periods,e=q.stochastic.prototype.getValues.call(this,a,b);a={values:[],xData:[],yData:[]};b=0;if(e){a.xData=e.xData.slice(c[1]-1);e=e.yData.slice(c[1]-1);var d=q.sma.prototype.getValues.call(this,{xData:a.xData,yData:e},{index:1,period:c[2]});if(d){for(var f=a.xData.length;b<f;b++)a.yData[b]=[e[b][1],d.yData[b-c[2]+1]||null],a.values[b]=[a.xData[b],e[b][1],d.yData[b-c[2]+1]||null];return a}}};b.defaultOptions=m(l.defaultOptions,{params:{periods:[14,3,3]}});
return b}(l);p(g.prototype,{nameBase:"Slow Stochastic"});f.registerSeriesType("slowstochastic",g);"";return g});w(f,"Stock/Indicators/Supertrend/SupertrendIndicator.js",[f["Core/Series/Series.js"],f["Core/Color/Palette.js"],f["Core/Utilities.js"]],function(f,d,g){function h(a,b,c){return{index:b,close:a.yData[b][c],x:a.xData[b]}}var l=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&
(a[c]=b[c])};return a(b,c)};return function(b,c){function e(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(e.prototype=c.prototype,new e)}}(),q=f.seriesTypes,p=q.atr,m=q.sma,e=g.correctFloat,b=g.isArray;q=g.extend;var a=g.merge,c=g.objectEach;g=function(f){function g(){var a=null!==f&&f.apply(this,arguments)||this;a.data=void 0;a.linkedParent=void 0;a.options=void 0;a.points=void 0;return a}l(g,f);g.prototype.init=function(){m.prototype.init.apply(this,arguments);var a=this.options;
a.cropThreshold=this.linkedParent.options.cropThreshold-(a.params.period-1)};g.prototype.drawGraph=function(){var b=this,e=b.options,d=b.linkedParent,f=d?d.points:[],g=b.points,k=b.graph,l=g.length,r=f.length-l;r=0<r?r:0;for(var p={options:{gapSize:e.gapSize}},q={top:[],bottom:[],intersect:[]},u={top:{styles:{lineWidth:e.lineWidth,lineColor:e.fallingTrendColor||e.color,dashStyle:e.dashStyle}},bottom:{styles:{lineWidth:e.lineWidth,lineColor:e.risingTrendColor||e.color,dashStyle:e.dashStyle}},intersect:e.changeTrendLine},
z,y,w,B,D,H,I,J;l--;)z=g[l],y=g[l-1],w=f[l-1+r],B=f[l-2+r],D=f[l+r],H=f[l+r+1],I=z.options.color,J={x:z.x,plotX:z.plotX,plotY:z.plotY,isNull:!1},!B&&w&&d.yData[w.index-1]&&(B=h(d,w.index-1,3)),!H&&D&&d.yData[D.index+1]&&(H=h(d,D.index+1,3)),!w&&B&&d.yData[B.index+1]?w=h(d,B.index+1,3):!w&&D&&d.yData[D.index-1]&&(w=h(d,D.index-1,3)),z&&w&&D&&B&&z.x!==w.x&&(z.x===D.x?(B=w,w=D):z.x===B.x?(w=B,B={close:d.yData[w.index-1][3],x:d.xData[w.index-1]}):H&&z.x===H.x&&(w=H,B=D)),y&&B&&w?(D={x:y.x,plotX:y.plotX,
plotY:y.plotY,isNull:!1},z.y>=w.close&&y.y>=B.close?(z.color=I||e.fallingTrendColor||e.color,q.top.push(J)):z.y<w.close&&y.y<B.close?(z.color=I||e.risingTrendColor||e.color,q.bottom.push(J)):(q.intersect.push(J),q.intersect.push(D),q.intersect.push(a(D,{isNull:!0})),z.y>=w.close&&y.y<B.close?(z.color=I||e.fallingTrendColor||e.color,y.color=I||e.risingTrendColor||e.color,q.top.push(J),q.top.push(a(D,{isNull:!0}))):z.y<w.close&&y.y>=B.close&&(z.color=I||e.risingTrendColor||e.color,y.color=I||e.fallingTrendColor||
e.color,q.bottom.push(J),q.bottom.push(a(D,{isNull:!0}))))):w&&(z.y>=w.close?(z.color=I||e.fallingTrendColor||e.color,q.top.push(J)):(z.color=I||e.risingTrendColor||e.color,q.bottom.push(J)));c(q,function(c,e){b.points=c;b.options=a(u[e].styles,p);b.graph=b["graph"+e+"Line"];m.prototype.drawGraph.call(b);b["graph"+e+"Line"]=b.graph});b.points=g;b.options=e;b.graph=k};g.prototype.getValues=function(a,c){var d=c.period;c=c.multiplier;var f=a.xData,g=a.yData,k=[],m=[],h=[],l=0===d?0:d-1,q=[],v=[],z;
if(!(f.length<=d||!b(g[0])||4!==g[0].length||0>d)){a=p.prototype.getValues.call(this,a,{period:d}).yData;for(z=0;z<a.length;z++){var y=g[l+z];var u=g[l+z-1]||[];var A=q[z-1];var w=v[z-1];var H=h[z-1];0===z&&(A=w=H=0);d=e((y[1]+y[2])/2+c*a[z]);var I=e((y[1]+y[2])/2-c*a[z]);q[z]=d<A||u[3]>A?d:A;v[z]=I>w||u[3]<w?I:w;if(H===A&&y[3]<q[z]||H===w&&y[3]<v[z])var J=q[z];else if(H===A&&y[3]>q[z]||H===w&&y[3]>v[z])J=v[z];k.push([f[l+z],J]);m.push(f[l+z]);h.push(J)}return{values:k,xData:m,yData:h}}};g.defaultOptions=
a(m.defaultOptions,{params:{multiplier:3,period:10},risingTrendColor:d.indicatorPositiveLine,fallingTrendColor:d.indicatorNegativeLine,changeTrendLine:{styles:{lineWidth:1,lineColor:d.neutralColor80,dashStyle:"LongDash"}}});return g}(m);q(g.prototype,{nameBase:"Supertrend",nameComponents:["multiplier","period"],requiredIndicators:["atr"]});f.registerSeriesType("supertrend",g);"";return g});w(f,"Stock/Indicators/VBP/VBPIndicator.js",[f["Core/Animation/AnimationUtilities.js"],f["Core/Series/Series.js"],
f["Core/Globals.js"],f["Core/Utilities.js"]],function(f,d,g,u){var h=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function e(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(e.prototype=c.prototype,new e)}}(),q=f.animObject,p=d.seriesTypes.sma;f=g.noop;var m=u.addEvent,e=u.arrayMax,b=u.arrayMin,
a=u.correctFloat,c=u.error,k=u.extend,y=u.isArray,v=u.merge,A=Math.abs,w=d.seriesTypes.column.prototype;u=function(d){function f(){var a=null!==d&&d.apply(this,arguments)||this;a.data=void 0;a.negWidths=void 0;a.options=void 0;a.points=void 0;a.posWidths=void 0;a.priceZones=void 0;a.rangeStep=void 0;a.volumeDataArray=void 0;a.zoneStarts=void 0;a.zoneLinesSVG=void 0;return a}h(f,d);f.prototype.init=function(a){g.seriesTypes.sma.prototype.init.apply(this,arguments);var b=this.options.params;var c=this.linkedParent;
b=a.get(b.volumeSeriesID);this.addCustomEvents(c,b);return this};f.prototype.addCustomEvents=function(a,b){function c(){e.chart.redraw();e.setData([]);e.zoneStarts=[];e.zoneLinesSVG&&(e.zoneLinesSVG.destroy(),delete e.zoneLinesSVG)}var e=this;e.dataEventsToUnbind.push(m(a,"remove",function(){c()}));b&&e.dataEventsToUnbind.push(m(b,"remove",function(){c()}));return e};f.prototype.animate=function(a){var b=this,c=b.chart.inverted,e=b.group,d={};!a&&e&&(a=c?"translateY":"translateX",c=c?b.yAxis.top:
b.xAxis.left,e["forceAnimate:"+a]=!0,d[a]=c,e.animate(d,k(q(b.options.animation),{step:function(a,c){b.group.attr({scaleX:Math.max(.001,c.pos)})}})))};f.prototype.drawPoints=function(){this.options.volumeDivision.enabled&&(this.posNegVolume(!0,!0),w.drawPoints.apply(this,arguments),this.posNegVolume(!1,!1));w.drawPoints.apply(this,arguments)};f.prototype.posNegVolume=function(a,b){var c=b?["positive","negative"]:["negative","positive"],e=this.options.volumeDivision,d=this.points.length,f=[],g=[],
k=0,m;a?(this.posWidths=f,this.negWidths=g):(f=this.posWidths,g=this.negWidths);for(;k<d;k++){var h=this.points[k];h[c[0]+"Graphic"]=h.graphic;h.graphic=h[c[1]+"Graphic"];if(a){var n=h.shapeArgs.width;var l=this.priceZones[k];(m=l.wholeVolumeData)?(f.push(n/m*l.positiveVolumeData),g.push(n/m*l.negativeVolumeData)):(f.push(0),g.push(0))}h.color=b?e.styles.positiveColor:e.styles.negativeColor;h.shapeArgs.width=b?this.posWidths[k]:this.negWidths[k];h.shapeArgs.x=b?h.shapeArgs.x:this.posWidths[k]}};f.prototype.translate=
function(){var b=this,c=b.options,d=b.chart,f=b.yAxis,g=f.min,k=b.options.zoneLines,m=b.priceZones,h=0,l,p,t;w.translate.apply(b);var q=b.points;if(q.length){var v=.5>c.pointPadding?c.pointPadding:.1;c=b.volumeDataArray;var y=e(c);var u=d.plotWidth/2;var K=d.plotTop;var M=A(f.toPixels(g)-f.toPixels(g+b.rangeStep));var G=A(f.toPixels(g)-f.toPixels(g+b.rangeStep));v&&(g=A(M*(1-2*v)),h=A((M-g)/2),M=A(g));q.forEach(function(c,e){p=c.barX=c.plotX=0;t=c.plotY=f.toPixels(m[e].start)-K-(f.reversed?M-G:M)-
h;l=a(u*m[e].wholeVolumeData/y);c.pointWidth=l;c.shapeArgs=b.crispCol.apply(b,[p,t,l,M]);c.volumeNeg=m[e].negativeVolumeData;c.volumePos=m[e].positiveVolumeData;c.volumeAll=m[e].wholeVolumeData});k.enabled&&b.drawZones(d,f,b.zoneStarts,k.styles)}};f.prototype.getValues=function(a,b){var e=a.processedXData,d=a.processedYData,f=this.chart,g=b.ranges,k=[],m=[],h=[],n;if(a.chart)if(n=f.get(b.volumeSeriesID))if((b=y(d[0]))&&4!==d[0].length)c("Type of "+a.name+" series is different than line, OHLC or candlestick.",
!0,f);else return(this.priceZones=this.specifyZones(b,e,d,g,n)).forEach(function(a,b){k.push([a.x,a.end]);m.push(k[b][0]);h.push(k[b][1])}),{values:k,xData:m,yData:h};else c("Series "+b.volumeSeriesID+" not found! Check `volumeSeriesID`.",!0,f);else c("Base series not found! In case it has been removed, add a new one.",!0,f)};f.prototype.specifyZones=function(c,d,f,g,k){if(c){var m=f.length;for(var h=f[0][3],n=h,l=1,p;l<m;l++)p=f[l][3],p<h&&(h=p),p>n&&(n=p);m={min:h,max:n}}else m=!1;m=(h=m)?h.min:
b(f);p=h?h.max:e(f);h=this.zoneStarts=[];n=[];var t=0;l=1;if(!m||!p)return this.points.length&&(this.setData([]),this.zoneStarts=[],this.zoneLinesSVG.destroy()),[];var r=this.rangeStep=a(p-m)/g;for(h.push(m);t<g-1;t++)h.push(a(h[t]+r));h.push(p);for(g=h.length;l<g;l++)n.push({index:l-1,x:d[0],start:h[l-1],end:h[l]});return this.volumePerZone(c,n,k,d,f)};f.prototype.volumePerZone=function(a,b,c,e,d){var f=this,g=c.processedXData,k=c.processedYData,m=b.length-1,h=d.length;c=k.length;var n,l,p,t,r;A(h-
c)&&(e[0]!==g[0]&&k.unshift(0),e[h-1]!==g[c-1]&&k.push(0));f.volumeDataArray=[];b.forEach(function(b){b.wholeVolumeData=0;b.positiveVolumeData=0;for(r=b.negativeVolumeData=0;r<h;r++)p=l=!1,t=a?d[r][3]:d[r],n=r?a?d[r-1][3]:d[r-1]:t,t<=b.start&&0===b.index&&(l=!0),t>=b.end&&b.index===m&&(p=!0),(t>b.start||l)&&(t<b.end||p)&&(b.wholeVolumeData+=k[r],n>t?b.negativeVolumeData+=k[r]:b.positiveVolumeData+=k[r]);f.volumeDataArray.push(b.wholeVolumeData)});return b};f.prototype.drawZones=function(a,b,c,e){var d=
a.renderer,f=this.zoneLinesSVG,g=[],k=a.plotWidth,m=a.plotTop,h;c.forEach(function(c){h=b.toPixels(c)-m;g=g.concat(a.renderer.crispLine([["M",0,h],["L",k,h]],e.lineWidth))});f?f.animate({d:g}):f=this.zoneLinesSVG=d.path(g).attr({"stroke-width":e.lineWidth,stroke:e.color,dashstyle:e.dashStyle,zIndex:this.group.zIndex+.1}).add(this.group)};f.defaultOptions=v(p.defaultOptions,{params:{ranges:12,volumeSeriesID:"volume"},zoneLines:{enabled:!0,styles:{color:"#0A9AC9",dashStyle:"LongDash",lineWidth:1}},
volumeDivision:{enabled:!0,styles:{positiveColor:"rgba(144, 237, 125, 0.8)",negativeColor:"rgba(244, 91, 91, 0.8)"}},animationLimit:1E3,enableMouseTracking:!1,pointPadding:0,zIndex:-1,crisp:!0,dataGrouping:{enabled:!1},dataLabels:{allowOverlap:!0,enabled:!0,format:"P: {point.volumePos:.2f} | N: {point.volumeNeg:.2f}",padding:0,style:{fontSize:"7px"},verticalAlign:"top"}});return f}(p);k(u.prototype,{nameBase:"Volume by Price",bindTo:{series:!1,eventName:"afterSetExtremes"},calculateOn:"render",markerAttribs:f,
drawGraph:f,getColumnMetrics:w.getColumnMetrics,crispCol:w.crispCol});d.registerSeriesType("vbp",u);"";return u});w(f,"Stock/Indicators/VWAP/VWAPIndicator.js",[f["Core/Series/Series.js"],f["Core/Utilities.js"]],function(f,d){var g=this&&this.__extends||function(){var d=function(e,b){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return d(e,b)};return function(e,b){function a(){this.constructor=e}
d(e,b);e.prototype=null===b?Object.create(b):(a.prototype=b.prototype,new a)}}(),h=f.seriesTypes.sma,l=d.error,q=d.isArray,p=d.merge;d=function(d){function e(){var b=null!==d&&d.apply(this,arguments)||this;b.data=void 0;b.points=void 0;b.options=void 0;return b}g(e,d);e.prototype.getValues=function(b,a){var c=b.chart,e=b.xData;b=b.yData;var d=a.period,f=!0,g;if(g=c.get(a.volumeSeriesID))return q(b[0])||(f=!1),this.calculateVWAPValues(f,e,b,g,d);l("Series "+a.volumeSeriesID+" not found! Check `volumeSeriesID`.",
!0,c)};e.prototype.calculateVWAPValues=function(b,a,c,e,d){var f=e.yData,g=e.xData.length,k=a.length;e=[];var h=[],m=[],l=[],p=[],r;g=k<=g?k:g;for(r=k=0;k<g;k++){var q=b?(c[k][1]+c[k][2]+c[k][3])/3:c[k];q*=f[k];q=r?e[k-1]+q:q;var y=r?h[k-1]+f[k]:f[k];e.push(q);h.push(y);p.push([a[k],q/y]);m.push(p[k][0]);l.push(p[k][1]);r++;r===d&&(r=0)}return{values:p,xData:m,yData:l}};e.defaultOptions=p(h.defaultOptions,{params:{period:30,volumeSeriesID:"volume"}});return e}(h);f.registerSeriesType("vwap",d);"";
return d});w(f,"Stock/Indicators/WilliamsR/WilliamsRIndicator.js",[f["Core/Series/Series.js"],f["Mixins/ReduceArray.js"],f["Core/Utilities.js"]],function(f,d,g){var h=this&&this.__extends||function(){var e=function(b,a){e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return e(b,a)};return function(b,a){function c(){this.constructor=b}e(b,a);b.prototype=null===a?Object.create(a):(c.prototype=a.prototype,
new c)}}(),l=f.seriesTypes.sma,q=d.getArrayExtremes;d=g.extend;var p=g.isArray,m=g.merge;g=function(e){function b(){var a=null!==e&&e.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}h(b,e);b.prototype.getValues=function(a,b){b=b.period;var c=a.xData,e=(a=a.yData)?a.length:0,d=[],f=[],g=[],h;if(!(c.length<b)&&p(a[0])&&4===a[0].length){for(h=b-1;h<e;h++){var m=a.slice(h-b+1,h+1);var l=q(m,2,1);m=l[0];l=l[1];var u=a[h][3];m=(l-u)/(l-m)*-100;c[h]&&(d.push([c[h],m]),
f.push(c[h]),g.push(m))}return{values:d,xData:f,yData:g}}};b.defaultOptions=m(l.defaultOptions,{params:{period:14}});return b}(l);d(g.prototype,{nameBase:"Williams %R"});f.registerSeriesType("williamsr",g);"";return g});w(f,"Stock/Indicators/WMA/WMAIndicator.js",[f["Core/Series/Series.js"],f["Core/Utilities.js"]],function(f,d){function g(e,b){b*=(b+1)/2;return e.reduce(function(a,b,e){return[null,a[1]+b[1]*(e+1)]})[1]/b}function h(e,b,a,c){a=g(e,e.length);b=b[c-1];e.shift();return[b,a]}var l=this&&
this.__extends||function(){var e=function(b,a){e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return e(b,a)};return function(b,a){function c(){this.constructor=b}e(b,a);b.prototype=null===a?Object.create(a):(c.prototype=a.prototype,new c)}}(),q=f.seriesTypes.sma,p=d.isArray,m=d.merge;d=function(e){function b(){var a=null!==e&&e.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=
void 0;return a}l(b,e);b.prototype.getValues=function(a,b){var c=b.period,e=a.xData,d=(a=a.yData)?a.length:0,f=1,g=e[0],m=a[0],l=[],n=[],q=[],r=-1;if(!(e.length<c)){p(a[0])&&(r=b.index,m=a[0][r]);for(b=[[g,m]];f!==c;)b.push([e[f],0>r?a[f]:a[f][r]]),f++;for(c=f;c<d;c++)f=h(b,e,a,c),l.push(f),n.push(f[0]),q.push(f[1]),b.push([e[c],0>r?a[c]:a[c][r]]);f=h(b,e,a,c);l.push(f);n.push(f[0]);q.push(f[1]);return{values:l,xData:n,yData:q}}};b.defaultOptions=m(q.defaultOptions,{params:{index:3,period:9}});return b}(q);
f.registerSeriesType("wma",d);"";return d});w(f,"Stock/Indicators/Zigzag/ZigzagIndicator.js",[f["Core/Series/Series.js"],f["Core/Utilities.js"]],function(f,d){var g=this&&this.__extends||function(){var d=function(f,e){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return d(f,e)};return function(f,e){function b(){this.constructor=f}d(f,e);f.prototype=null===e?Object.create(e):(b.prototype=e.prototype,
new b)}}(),h=f.seriesTypes.sma,l=d.merge;d=d.extend;var q=function(d){function f(){var e=null!==d&&d.apply(this,arguments)||this;e.data=void 0;e.points=void 0;e.options=void 0;return e}g(f,d);f.prototype.getValues=function(e,b){var a=b.lowIndex,c=b.highIndex,d=b.deviation/100;b=1+d;var f=1-d;d=e.xData;var g=e.yData;e=g?g.length:0;var h=[],m=[],l=[],p,n,q=!1,r=!1;if(!(!d||1>=d.length||e&&("undefined"===typeof g[0][a]||"undefined"===typeof g[0][c]))){var u=g[0][a];var w=g[0][c];for(p=1;p<e;p++){if(g[p][a]<=
w*f){h.push([d[0],w]);var E=[d[p],g[p][a]];q=n=!0}else g[p][c]>=u*b&&(h.push([d[0],u]),E=[d[p],g[p][c]],n=!1,q=!0);if(q){m.push(h[0][0]);l.push(h[0][1]);var z=p++;p=e}}for(p=z;p<e;p++)n?(g[p][a]<=E[1]&&(E=[d[p],g[p][a]]),g[p][c]>=E[1]*b&&(r=c)):(g[p][c]>=E[1]&&(E=[d[p],g[p][c]]),g[p][a]<=E[1]*f&&(r=a)),!1!==r&&(h.push(E),m.push(E[0]),l.push(E[1]),E=[d[p],g[p][r]],n=!n,r=!1);a=h.length;0!==a&&h[a-1][0]<d[e-1]&&(h.push(E),m.push(E[0]),l.push(E[1]));return{values:h,xData:m,yData:l}}};f.defaultOptions=
l(h.defaultOptions,{params:{lowIndex:2,highIndex:1,deviation:1}});return f}(h);d(q.prototype,{nameComponents:["deviation"],nameSuffixes:["%"],nameBase:"Zig Zag"});f.registerSeriesType("zigzag",q);"";return q});w(f,"Stock/Indicators/LinearRegression/LinearRegression.js",[f["Core/Series/Series.js"],f["Core/Utilities.js"]],function(f,d){var g=this&&this.__extends||function(){var d=function(e,b){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&
(a[c]=b[c])};return d(e,b)};return function(e,b){function a(){this.constructor=e}d(e,b);e.prototype=null===b?Object.create(b):(a.prototype=b.prototype,new a)}}(),h=f.seriesTypes.sma,l=d.isArray,q=d.extend,p=d.merge;d=function(d){function e(){var b=null!==d&&d.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}g(e,d);e.prototype.getRegressionLineParameters=function(b,a){var c=this.options.params.index,e=function(a,b){return l(a)?a[b]:a},d=b.reduce(function(a,b){return b+
a},0),f=a.reduce(function(a,b){return e(b,c)+a},0);d/=b.length;f/=a.length;var g=0,h=0,m;for(m=0;m<b.length;m++){var p=b[m]-d;var n=e(a[m],c)-f;g+=p*n;h+=Math.pow(p,2)}b=h?g/h:0;return{slope:b,intercept:f-b*d}};e.prototype.getEndPointY=function(b,a){return b.slope*a+b.intercept};e.prototype.transformXData=function(b,a){var c=b[0];return b.map(function(b){return(b-c)/a})};e.prototype.findClosestDistance=function(b){var a,c;for(c=1;c<b.length-1;c++){var e=b[c]-b[c-1];0<e&&("undefined"===typeof a||e<
a)&&(a=e)}return a};e.prototype.getValues=function(b,a){var c=b.xData;b=b.yData;a=a.period;var e,d={xData:[],yData:[],values:[]},f=this.options.params.xAxisUnit||this.findClosestDistance(c);for(e=a-1;e<=c.length-1;e++){var g=e-a+1;var h=e+1;var m=c[e];var l=c.slice(g,h);g=b.slice(g,h);h=this.transformXData(l,f);l=this.getRegressionLineParameters(h,g);g=this.getEndPointY(l,h[h.length-1]);d.values.push({regressionLineParameters:l,x:m,y:g});d.xData.push(m);d.yData.push(g)}return d};e.defaultOptions=
p(h.defaultOptions,{params:{xAxisUnit:void 0},tooltip:{valueDecimals:4}});return e}(h);q(d.prototype,{nameBase:"Linear Regression Indicator"});f.registerSeriesType("linearRegression",d);"";return d});w(f,"Stock/Indicators/LinearRegressionSlopes/LinearRegressionSlopes.js",[f["Core/Series/Series.js"],f["Core/Utilities.js"]],function(f,d){var g=this&&this.__extends||function(){var d=function(f,e){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&
(b[c]=a[c])};return d(f,e)};return function(f,e){function b(){this.constructor=f}d(f,e);f.prototype=null===e?Object.create(e):(b.prototype=e.prototype,new b)}}(),h=f.seriesTypes.linearRegression,l=d.extend,q=d.merge;d=function(d){function f(){var e=null!==d&&d.apply(this,arguments)||this;e.data=void 0;e.options=void 0;e.points=void 0;return e}g(f,d);f.prototype.getEndPointY=function(e){return e.slope};f.defaultOptions=q(h.defaultOptions);return f}(h);l(d.prototype,{nameBase:"Linear Regression Slope Indicator"});
f.registerSeriesType("linearRegressionSlope",d);"";return d});w(f,"Stock/Indicators/LinearRegressionIntercept/LinearRegressionIntercept.js",[f["Core/Series/Series.js"],f["Core/Utilities.js"]],function(f,d){var g=this&&this.__extends||function(){var d=function(f,e){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return d(f,e)};return function(f,e){function b(){this.constructor=f}d(f,e);f.prototype=
null===e?Object.create(e):(b.prototype=e.prototype,new b)}}(),h=f.seriesTypes.linearRegression,l=d.extend,q=d.merge;d=function(d){function f(){var e=null!==d&&d.apply(this,arguments)||this;e.data=void 0;e.options=void 0;e.points=void 0;return e}g(f,d);f.prototype.getEndPointY=function(e){return e.intercept};f.defaultOptions=q(h.defaultOptions);return f}(h);l(d.prototype,{nameBase:"Linear Regression Intercept Indicator"});f.registerSeriesType("linearRegressionIntercept",d);"";return d});w(f,"Stock/Indicators/LinearRegressionAngle/LinearRegressionAngle.js",
[f["Core/Series/Series.js"],f["Core/Utilities.js"]],function(f,d){var g=this&&this.__extends||function(){var d=function(e,b){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return d(e,b)};return function(e,b){function a(){this.constructor=e}d(e,b);e.prototype=null===b?Object.create(b):(a.prototype=b.prototype,new a)}}(),h=f.seriesTypes,l=h.sma,q=d.extend,p=d.merge;d=function(d){function e(){var b=
null!==d&&d.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}g(e,d);e.prototype.slopeToAngle=function(b){return 180/Math.PI*Math.atan(b)};e.prototype.getEndPointY=function(b){return this.slopeToAngle(b.slope)};e.defaultOptions=p(l.defaultOptions,{tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span>{series.name}: <b>{point.y}\u00b0</b><br/>'}});return e}(h.linearRegression);q(d.prototype,{nameBase:"Linear Regression Angle Indicator"});f.registerSeriesType("linearRegressionAngle",
d);"";return d});w(f,"Stock/Indicators/ABands/ABandsIndicator.js",[f["Core/Series/Series.js"],f["Mixins/MultipleLines.js"],f["Core/Utilities.js"]],function(f,d,g){var h=this&&this.__extends||function(){var e=function(b,a){e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return e(b,a)};return function(b,a){function c(){this.constructor=b}e(b,a);b.prototype=null===a?Object.create(a):(c.prototype=a.prototype,
new c)}}(),l=f.seriesTypes.sma,q=g.correctFloat,p=g.extend,m=g.merge;g=function(e){function b(){var a=null!==e&&e.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}h(b,e);b.prototype.getValues=function(a,b){var c=b.period,d=b.factor;b=b.index;var f=a.xData,g=(a=a.yData)?a.length:0,h=[],m=[],l=[],n=[],p=[],r;if(!(g<c)){for(r=0;r<=g;r++){if(r<g){var u=a[r][2];var w=a[r][1];var E=d;u=q(w-u)/(q(w+u)/2)*1E3*E;h.push(a[r][1]*q(1+2*u));m.push(a[r][2]*q(1-2*u))}if(r>=c){u=
f.slice(r-c,r);var z=a.slice(r-c,r);E=e.prototype.getValues.call(this,{xData:u,yData:h.slice(r-c,r)},{period:c});w=e.prototype.getValues.call(this,{xData:u,yData:m.slice(r-c,r)},{period:c});z=e.prototype.getValues.call(this,{xData:u,yData:z},{period:c,index:b});u=z.xData[0];E=E.yData[0];w=w.yData[0];z=z.yData[0];l.push([u,E,z,w]);n.push(u);p.push([E,z,w])}}return{values:l,xData:n,yData:p}}};b.defaultOptions=m(l.defaultOptions,{params:{period:20,factor:.001,index:3},lineWidth:1,topLine:{styles:{lineWidth:1}},
bottomLine:{styles:{lineWidth:1}},dataGrouping:{approximation:"averages"}});return b}(l);p(g.prototype,{drawGraph:d.drawGraph,getTranslatedLinesNames:d.getTranslatedLinesNames,linesApiNames:["topLine","bottomLine"],nameBase:"Acceleration Bands",nameComponents:["period","factor"],pointArrayMap:["top","middle","bottom"],pointValKey:"middle",toYData:d.toYData,translate:d.translate});f.registerSeriesType("abands",g);"";return g});w(f,"Stock/Indicators/TrendLine/TrendLineIndicator.js",[f["Core/Series/Series.js"],
f["Core/Utilities.js"]],function(f,d){var g=this&&this.__extends||function(){var d=function(e,b){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return d(e,b)};return function(e,b){function a(){this.constructor=e}d(e,b);e.prototype=null===b?Object.create(b):(a.prototype=b.prototype,new a)}}(),h=f.seriesTypes.sma,l=d.extend,q=d.merge,p=d.isArray;d=function(d){function e(){var b=null!==d&&d.apply(this,
arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}g(e,d);e.prototype.getValues=function(b,a){var c=b.xData,d=b.yData;b=[];var e=[],f=[],g=0,h=0,l=0,m=0,n=c.length,q=a.index;for(a=0;a<n;a++){var r=c[a];var u=p(d[a])?d[a][q]:d[a];g+=r;h+=u;l+=r*u;m+=r*r}d=(n*l-g*h)/(n*m-g*g);isNaN(d)&&(d=0);g=(h-d*g)/n;for(a=0;a<n;a++)r=c[a],u=d*r+g,b[a]=[r,u],e[a]=r,f[a]=u;return{xData:e,yData:f,values:b}};e.defaultOptions=q(h.defaultOptions,{params:{index:3}});return e}(h);l(d.prototype,{nameBase:"Trendline",
nameComponents:!1});f.registerSeriesType("trendline",d);"";return d});w(f,"masters/indicators/indicators-all.src.js",[],function(){})});
//# sourceMappingURL=indicators-all.js.map