/*
 Highstock JS v8.2.2 (2020-12-12)

 Indicator series type for Highstock

 (c) 2010-2019 Pawel Fus, Sebastian Bochan

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/indicators",["highcharts","highcharts/modules/stock"],function(e){a(e);a.Highcharts=e;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function e(a,b,c,h){a.hasOwnProperty(b)||(a[b]=h.apply(null,c))}a=a?a._modules:{};e(a,"Mixins/IndicatorRequired.js",[a["Core/Utilities.js"]],function(a){var b=a.error;return{isParentLoaded:function(a,
h,m,l,e){if(a)return l?l(a):!0;b(e||this.generateMessage(m,h));return!1},generateMessage:function(a,b){return'Error: "'+a+'" indicator type requires "'+b+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+a}}});e(a,"Stock/Indicators/SMA/SMAComposition.js",[a["Core/Series/Series.js"],a["Core/Utilities.js"]],function(a,b){var c=a.seriesTypes;a=c.line;var h=c.ohlc.prototype;c=b.addEvent;var e=b.extend;c(a,"init",function(a){a=a.options;a.useOhlcData&&"highcharts-navigator-series"!==
a.id&&e(this,{pointValKey:h.pointValKey,keys:h.keys,pointArrayMap:h.pointArrayMap,toYData:h.toYData})});c(a,"afterSetOptions",function(a){a=a.options;var b=a.dataGrouping;b&&a.useOhlcData&&"highcharts-navigator-series"!==a.id&&(b.approximation="ohlc")})});e(a,"Stock/Indicators/SMA/SMAIndicator.js",[a["Core/Series/Series.js"],a["Mixins/IndicatorRequired.js"],a["Core/Utilities.js"]],function(a,b,c){var e=this&&this.__extends||function(){var a=function(b,f){a=Object.setPrototypeOf||{__proto__:[]}instanceof
Array&&function(a,f){a.__proto__=f}||function(a,f){for(var d in f)f.hasOwnProperty(d)&&(a[d]=f[d])};return a(b,f)};return function(b,f){function g(){this.constructor=b}a(b,f);b.prototype=null===f?Object.create(f):(g.prototype=f.prototype,new g)}}(),p=a.seriesTypes.line,l=c.addEvent,q=c.error,m=c.extend,u=c.isArray,v=c.merge,w=c.pick,x=c.splat,y=b.generateMessage;b=function(b){function c(){var a=null!==b&&b.apply(this,arguments)||this;a.data=void 0;a.dataEventsToUnbind=void 0;a.linkedParent=void 0;
a.options=void 0;a.points=void 0;return a}e(c,b);c.prototype.destroy=function(){this.dataEventsToUnbind.forEach(function(a){a()});b.prototype.destroy.apply(this,arguments)};c.prototype.getName=function(){var a=this.name,b=[];a||((this.nameComponents||[]).forEach(function(a,d){b.push(this.options.params[a]+w(this.nameSuffixes[d],""))},this),a=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+b.join(", ")+")":""));return a};c.prototype.getValues=function(a,b){var c=b.period,d=a.xData;
a=a.yData;var f=a.length,e=0,g=0,r=[],t=[],h=[],k=-1;if(!(d.length<c)){for(u(a[0])&&(k=b.index?b.index:0);e<c-1;)g+=0>k?a[e]:a[e][k],e++;for(b=e;b<f;b++){g+=0>k?a[b]:a[b][k];var n=[d[b],g/c];r.push(n);t.push(n[0]);h.push(n[1]);g-=0>k?a[b-e]:a[b-e][k]}return{values:r,xData:t,yData:h}}};c.prototype.init=function(a,c){function e(){var a=d.points||[],b=(d.xData||[]).length,c=d.getValues(d.linkedParent,d.options.params)||{values:[],xData:[],yData:[]},e=[],f=!0;if(b&&!d.hasGroupedData&&d.visible&&d.points)if(d.cropped){if(d.xAxis){var g=
d.xAxis.min;var h=d.xAxis.max}b=d.cropData(c.xData,c.yData,g,h);for(g=0;g<b.xData.length;g++)e.push([b.xData[g]].concat(x(b.yData[g])));b=c.xData.indexOf(d.xData[0]);g=c.xData.indexOf(d.xData[d.xData.length-1]);-1===b&&g===c.xData.length-2&&e[0][0]===a[0].x&&e.shift();d.updateData(e)}else c.xData.length!==b-1&&c.xData.length!==b+1&&(f=!1,d.updateData(c.values));f&&(d.xData=c.xData,d.yData=c.yData,d.options.data=c.values);!1===d.bindTo.series&&(delete d.processedXData,d.isDirty=!0,d.redraw());d.isDirtyData=
!1}var d=this,f=d.requireIndicators();if(!f.allLoaded)return q(y(d.type,f.needed));b.prototype.init.call(d,a,c);a.linkSeries();d.dataEventsToUnbind=[];if(!d.linkedParent)return q("Series "+d.options.linkedTo+" not found! Check `linkedTo`.",!1,a);d.dataEventsToUnbind.push(l(d.bindTo.series?d.linkedParent:d.linkedParent.xAxis,d.bindTo.eventName,e));if("init"===d.calculateOn)e();else var g=l(d.chart,d.calculateOn,function(){e();g()})};c.prototype.processData=function(){var a=this.options.compareToMain,
c=this.linkedParent;b.prototype.processData.apply(this,arguments);c&&c.compareValue&&a&&(this.compareValue=c.compareValue)};c.prototype.requireIndicators=function(){var b={allLoaded:!0};this.requiredIndicators.forEach(function(c){a.seriesTypes[c]?a.seriesTypes[c].prototype.requireIndicators():(b.allLoaded=!1,b.needed=c)});return b};c.defaultOptions=v(p.defaultOptions,{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,period:14}});return c}(p);m(b.prototype,{bindTo:{series:!0,
eventName:"updatedData"},calculateOn:"init",hasDerivedData:!0,nameComponents:["period"],nameSuffixes:[],requiredIndicators:[],useCommonDataGrouping:!0});a.registerSeriesType("sma",b);"";return b});e(a,"masters/indicators/indicators.src.js",[],function(){})});
//# sourceMappingURL=indicators.js.map