/*
 Highstock JS v8.2.2 (2020-12-12)

 Indicator series type for Highstock

 (c) 2010-2019 Sebastian Bochan

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/indicators/macd",["highcharts","highcharts/modules/stock"],function(g){b(g);b.Highcharts=g;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function g(b,l,f,g){b.hasOwnProperty(l)||(b[l]=g.apply(null,f))}b=b?b._modules:{};g(b,"Stock/Indicators/MACD/MACDIndicator.js",[b["Core/Series/Series.js"],b["Core/Globals.js"],b["Core/Utilities.js"]],
function(b,l,f){var g=this&&this.__extends||function(){var b=function(d,a){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return b(d,a)};return function(d,a){function c(){this.constructor=d}b(d,a);d.prototype=null===a?Object.create(a):(c.prototype=a.prototype,new c)}}(),p=b.seriesTypes.sma,r=l.noop,t=f.extend,q=f.correctFloat,m=f.defined,n=f.merge;f=function(f){function d(){var a=null!==f&&f.apply(this,
arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;a.currentLineZone=void 0;a.graphmacd=void 0;a.graphsignal=void 0;a.macdZones=void 0;a.signalZones=void 0;return a}g(d,f);d.prototype.init=function(){b.seriesTypes.sma.prototype.init.apply(this,arguments);this.options&&(this.options=n({signalLine:{styles:{lineColor:this.color}},macdLine:{styles:{color:this.color}}},this.options),this.macdZones={zones:this.options.macdLine.zones,startIndex:0},this.signalZones={zones:this.macdZones.zones.concat(this.options.signalLine.zones),
startIndex:this.macdZones.zones.length},this.resetZones=!0)};d.prototype.toYData=function(a){return[a.y,a.signal,a.MACD]};d.prototype.translate=function(){var a=this,b=["plotSignal","plotMACD"];l.seriesTypes.column.prototype.translate.apply(a);a.points.forEach(function(c){[c.signal,c.MACD].forEach(function(e,d){null!==e&&(c[b[d]]=a.yAxis.toPixels(e,!0))})})};d.prototype.destroy=function(){this.graph=null;this.graphmacd=this.graphmacd&&this.graphmacd.destroy();this.graphsignal=this.graphsignal&&this.graphsignal.destroy();
b.seriesTypes.sma.prototype.destroy.apply(this,arguments)};d.prototype.drawGraph=function(){for(var a=this,c=a.points,d=c.length,e=a.options,f=a.zones,g={options:{gapSize:e.gapSize}},k=[[],[]],h;d--;)h=c[d],m(h.plotMACD)&&k[0].push({plotX:h.plotX,plotY:h.plotMACD,isNull:!m(h.plotMACD)}),m(h.plotSignal)&&k[1].push({plotX:h.plotX,plotY:h.plotSignal,isNull:!m(h.plotMACD)});["macd","signal"].forEach(function(c,d){a.points=k[d];a.options=n(e[c+"Line"].styles,g);a.graph=a["graph"+c];a.currentLineZone=c+
"Zones";a.zones=a[a.currentLineZone].zones;b.seriesTypes.sma.prototype.drawGraph.call(a);a["graph"+c]=a.graph});a.points=c;a.options=e;a.zones=f;a.currentLineZone=null};d.prototype.getZonesGraphs=function(a){var c=b.seriesTypes.sma.prototype.getZonesGraphs.call(this,a),d=c;this.currentLineZone&&(d=c.splice(this[this.currentLineZone].startIndex+1),d.length?d.splice(0,0,a[0]):d=[a[0]]);return d};d.prototype.applyZones=function(){var a=this.zones;this.zones=this.signalZones.zones;b.seriesTypes.sma.prototype.applyZones.call(this);
this.graphmacd&&this.options.macdLine.zones.length&&this.graphmacd.hide();this.zones=a};d.prototype.getValues=function(a,c){var d=0,e=[],f=[],g=[];if(!(a.xData.length<c.longPeriod+c.signalPeriod)){var k=b.seriesTypes.ema.prototype.getValues(a,{period:c.shortPeriod});var h=b.seriesTypes.ema.prototype.getValues(a,{period:c.longPeriod});k=k.values;h=h.values;for(a=1;a<=k.length;a++)m(h[a-1])&&m(h[a-1][1])&&m(k[a+c.shortPeriod+1])&&m(k[a+c.shortPeriod+1][0])&&e.push([k[a+c.shortPeriod+1][0],0,null,k[a+
c.shortPeriod+1][1]-h[a-1][1]]);for(a=0;a<e.length;a++)f.push(e[a][0]),g.push([0,null,e[a][3]]);c=b.seriesTypes.ema.prototype.getValues({xData:f,yData:g},{period:c.signalPeriod,index:2});c=c.values;for(a=0;a<e.length;a++)e[a][0]>=c[0][0]&&(e[a][2]=c[d][1],g[a]=[0,c[d][1],e[a][3]],null===e[a][3]?(e[a][1]=0,g[a][0]=0):(e[a][1]=q(e[a][3]-c[d][1]),g[a][0]=q(e[a][3]-c[d][1])),d++);return{values:e,xData:f,yData:g}}};d.defaultOptions=n(p.defaultOptions,{params:{shortPeriod:12,longPeriod:26,signalPeriod:9,
period:26},signalLine:{zones:[],styles:{lineWidth:1,lineColor:void 0}},macdLine:{zones:[],styles:{lineWidth:1,lineColor:void 0}},threshold:0,groupPadding:.1,pointPadding:.1,crisp:!1,states:{hover:{halo:{size:0}}},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Value: {point.MACD}<br/>Signal: {point.signal}<br/>Histogram: {point.y}<br/>'},dataGrouping:{approximation:"averages"},minPointLength:0});return d}(p);t(f.prototype,{nameComponents:["longPeriod",
"shortPeriod","signalPeriod"],requiredIndicators:["ema"],pointArrayMap:["y","signal","MACD"],parallelArrays:["x","y","signal","MACD"],pointValKey:"y",markerAttribs:r,getColumnMetrics:l.seriesTypes.column.prototype.getColumnMetrics,crispCol:l.seriesTypes.column.prototype.crispCol,drawPoints:l.seriesTypes.column.prototype.drawPoints});b.registerSeriesType("macd",f);"";return f});g(b,"masters/indicators/macd.src.js",[],function(){})});
//# sourceMappingURL=macd.js.map