/*
 Highstock JS v8.2.2 (2020-12-12)

 Indicator series type for Highstock

 (c) 2010-2019 Pawe Fus

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/pivot-points",["highcharts","highcharts/modules/stock"],function(m){a(m);a.Highcharts=m;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function m(a,k,d,h){a.hasOwnProperty(k)||(a[k]=h.apply(null,d))}a=a?a._modules:{};m(a,"Stock/Indicators/PivotPoints/PivotPointsPoint.js",[a["Core/Series/Series.js"]],function(a){function k(h,
c){var e=h.series.pointArrayMap,d=e.length;for(a.seriesTypes.sma.prototype.pointClass.prototype[c].call(h);d--;)c="dataLabel"+e[d],h[c]&&h[c].element&&h[c].destroy(),h[c]=null}var d=this&&this.__extends||function(){var a=function(c,e){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var e in c)c.hasOwnProperty(e)&&(a[e]=c[e])};return a(c,e)};return function(c,e){function d(){this.constructor=c}a(c,e);c.prototype=null===e?Object.create(e):(d.prototype=
e.prototype,new d)}}();return function(a){function c(){var c=null!==a&&a.apply(this,arguments)||this;c.P=void 0;c.pivotLine=void 0;c.series=void 0;return c}d(c,a);c.prototype.destroyElements=function(){k(this,"destroyElements")};c.prototype.destroy=function(){k(this,"destroyElements")};return c}(a.seriesTypes.sma.prototype.pointClass)});m(a,"Stock/Indicators/PivotPoints/PivotPointsIndicator.js",[a["Core/Series/Series.js"],a["Stock/Indicators/PivotPoints/PivotPointsPoint.js"],a["Core/Utilities.js"]],
function(a,k,d){var h=this&&this.__extends||function(){var a=function(c,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var g in a)a.hasOwnProperty(g)&&(b[g]=a[g])};return a(c,b)};return function(c,b){function g(){this.constructor=c}a(c,b);c.prototype=null===b?Object.create(b):(g.prototype=b.prototype,new g)}}(),c=a.seriesTypes.sma,e=d.merge,m=d.extend,n=d.defined,u=d.isArray;d=function(d){function f(){var b=null!==d&&d.apply(this,arguments)||
this;b.data=void 0;b.options=void 0;b.points=void 0;b.endPoint=void 0;b.plotEndPoint=void 0;return b}h(f,d);f.prototype.toYData=function(b){return[b.P]};f.prototype.translate=function(){var b=this;a.seriesTypes.sma.prototype.translate.apply(b);b.points.forEach(function(a){b.pointArrayMap.forEach(function(g){n(a[g])&&(a["plot"+g]=b.yAxis.toPixels(a[g],!0))})});b.plotEndPoint=b.xAxis.toPixels(b.endPoint,!0)};f.prototype.getGraphPath=function(b){for(var g=this,c=b.length,t=[[],[],[],[],[],[],[],[],[]],
d=[],e=g.plotEndPoint,f=g.pointArrayMap.length,p,l,h;c--;){l=b[c];for(h=0;h<f;h++)p=g.pointArrayMap[h],n(l[p])&&t[h].push({plotX:l.plotX,plotY:l["plot"+p],isNull:!1},{plotX:e,plotY:l["plot"+p],isNull:!1},{plotX:e,plotY:null,isNull:!0});e=l.plotX}t.forEach(function(b){d=d.concat(a.seriesTypes.sma.prototype.getGraphPath.call(g,b))});return d};f.prototype.drawDataLabels=function(){var b=this,g=b.pointArrayMap,c,d,e;if(b.options.dataLabels.enabled){var h=b.points.length;g.concat([!1]).forEach(function(f,
q){for(e=h;e--;)d=b.points[e],f?(d.y=d[f],d.pivotLine=f,d.plotY=d["plot"+f],c=d["dataLabel"+f],q&&(d["dataLabel"+g[q-1]]=d.dataLabel),d.dataLabels||(d.dataLabels=[]),d.dataLabels[0]=d.dataLabel=c=c&&c.element?c:null):d["dataLabel"+g[q-1]]=d.dataLabel;a.seriesTypes.sma.prototype.drawDataLabels.apply(b,arguments)})}};f.prototype.getValues=function(b,a){var c=a.period,g=b.xData,d=(b=b.yData)?b.length:0;a=this[a.algorithm+"Placement"];var e=[],f=[],h=[],l;if(!(g.length<c)&&u(b[0])&&4===b[0].length){for(l=
c+1;l<=d+c;l+=c){var m=g.slice(l-c-1,l);var k=b.slice(l-c-1,l);var n=m.length;var r=m[n-1];k=this.getPivotAndHLC(k);k=a(k);k=e.push([r].concat(k));f.push(r);h.push(e[k-1].slice(1))}this.endPoint=m[0]+(r-m[0])/n*c;return{values:e,xData:f,yData:h}}};f.prototype.getPivotAndHLC=function(b){var a=-Infinity,c=Infinity,d=b[b.length-1][3];b.forEach(function(b){a=Math.max(a,b[1]);c=Math.min(c,b[2])});return[(a+c+d)/3,a,c,d]};f.prototype.standardPlacement=function(b){var a=b[1]-b[2];return[null,null,b[0]+a,
2*b[0]-b[2],b[0],2*b[0]-b[1],b[0]-a,null,null]};f.prototype.camarillaPlacement=function(b){var a=b[1]-b[2];return[b[3]+1.5*a,b[3]+1.25*a,b[3]+1.1666*a,b[3]+1.0833*a,b[0],b[3]-1.0833*a,b[3]-1.1666*a,b[3]-1.25*a,b[3]-1.5*a]};f.prototype.fibonacciPlacement=function(b){var a=b[1]-b[2];return[null,b[0]+a,b[0]+.618*a,b[0]+.382*a,b[0],b[0]-.382*a,b[0]-.618*a,b[0]-a,null]};f.defaultOptions=e(c.defaultOptions,{params:{period:28,algorithm:"standard"},marker:{enabled:!1},enableMouseTracking:!1,dataLabels:{enabled:!0,
format:"{point.pivotLine}"},dataGrouping:{approximation:"averages"}});return f}(c);m(d.prototype,{nameBase:"Pivot Points",pointArrayMap:"R4 R3 R2 R1 P S1 S2 S3 S4".split(" "),pointValKey:"P",pointClass:k});a.registerSeriesType("pivotpoints",d);"";return d});m(a,"masters/indicators/pivot-points.src.js",[],function(){})});
//# sourceMappingURL=pivot-points.js.map