/*
 Highstock JS v8.2.2 (2020-12-12)

 Indicator series type for Highstock

 (c) 2010-2019 Daniel Studencki

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/price-channel",["highcharts","highcharts/modules/stock"],function(d){a(d);a.Highcharts=d;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function d(a,c,g,b){a.hasOwnProperty(c)||(a[c]=b.apply(null,g))}a=a?a._modules:{};d(a,"Mixins/MultipleLines.js",[a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,c){var g=
c.defined,b=c.error,f=c.merge,k=a.seriesTypes.sma;return{pointArrayMap:["top","bottom"],pointValKey:"top",linesApiNames:["bottomLine"],getTranslatedLinesNames:function(e){var a=[];(this.pointArrayMap||[]).forEach(function(b){b!==e&&a.push("plot"+b.charAt(0).toUpperCase()+b.slice(1))});return a},toYData:function(a){var e=[];(this.pointArrayMap||[]).forEach(function(b){e.push(a[b])});return e},translate:function(){var a=this,b=a.pointArrayMap,c=[],h;c=a.getTranslatedLinesNames();k.prototype.translate.apply(a,
arguments);a.points.forEach(function(e){b.forEach(function(b,t){h=e[b];null!==h&&(e[c[t]]=a.yAxis.toPixels(h,!0))})})},drawGraph:function(){var a=this,c=a.linesApiNames,d=a.points,h=d.length,l=a.options,q=a.graph,t={options:{gapSize:l.gapSize}},r=[],n;a.getTranslatedLinesNames(a.pointValKey).forEach(function(a,b){for(r[b]=[];h--;)n=d[h],r[b].push({x:n.x,plotX:n.plotX,plotY:n[a],isNull:!g(n[a])});h=d.length});c.forEach(function(c,q){r[q]?(a.points=r[q],l[c]?a.options=f(l[c].styles,t):b('Error: "There is no '+
c+' in DOCS options declared. Check if linesApiNames are consistent with your DOCS line names." at mixin/multiple-line.js:34'),a.graph=a["graph"+c],k.prototype.drawGraph.call(a),a["graph"+c]=a.graph):b('Error: "'+c+" doesn't have equivalent in pointArrayMap. To many elements in linesApiNames relative to pointArrayMap.\"")});a.points=d;a.options=l;a.graph=q;k.prototype.drawGraph.call(a)}}});d(a,"Mixins/ReduceArray.js",[],function(){return{minInArray:function(a,c){return a.reduce(function(a,b){return Math.min(a,
b[c])},Number.MAX_VALUE)},maxInArray:function(a,c){return a.reduce(function(a,b){return Math.max(a,b[c])},-Number.MAX_VALUE)},getArrayExtremes:function(a,c,d){return a.reduce(function(a,f){return[Math.min(a[0],f[c]),Math.max(a[1],f[d])]},[Number.MAX_VALUE,-Number.MAX_VALUE])}}});d(a,"Stock/Indicators/PC/PCIndicator.js",[a["Core/Series/Series.js"],a["Core/Color/Palette.js"],a["Mixins/MultipleLines.js"],a["Mixins/ReduceArray.js"],a["Core/Utilities.js"]],function(a,c,d,b,f){var k=this&&this.__extends||
function(){var a=function(c,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(c,b)};return function(c,b){function d(){this.constructor=c}a(c,b);c.prototype=null===b?Object.create(b):(d.prototype=b.prototype,new d)}}(),e=a.seriesTypes.sma,g=f.merge;f=f.extend;var u=b.getArrayExtremes;b=function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=
void 0;return b}k(b,a);b.prototype.getValues=function(a,b){b=b.period;var c=a.xData,d=(a=a.yData)?a.length:0,e=[],f=[],h=[],m;if(!(d<b)){for(m=b;m<=d;m++){var k=c[m-1];var g=a.slice(m-b,m);var p=u(g,2,1);g=p[1];var l=p[0];p=(g+l)/2;e.push([k,g,p,l]);f.push(k);h.push([g,p,l])}return{values:e,xData:f,yData:h}}};b.defaultOptions=g(e.defaultOptions,{params:{period:20},lineWidth:1,topLine:{styles:{lineColor:c.colors[2],lineWidth:1}},bottomLine:{styles:{lineColor:c.colors[8],lineWidth:1}},dataGrouping:{approximation:"averages"}});
return b}(e);f(b.prototype,{getTranslatedLinesNames:d.getTranslatedLinesNames,drawGraph:d.drawGraph,toYData:d.toYData,pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameBase:"Price Channel",nameComponents:["period"],linesApiNames:["topLine","bottomLine"],translate:d.translate});a.registerSeriesType("pc",b);"";return b});d(a,"masters/indicators/price-channel.src.js",[],function(){})});
//# sourceMappingURL=price-channel.js.map