/*
 Highstock JS v8.2.2 (2020-12-12)

 Indicator series type for Highstock

 (c) 2010-2019 Pawe Fus

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/stochastic",["highcharts","highcharts/modules/stock"],function(d){a(d);a.Highcharts=d;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function d(a,c,g,b){a.hasOwnProperty(c)||(a[c]=b.apply(null,g))}a=a?a._modules:{};d(a,"Mixins/MultipleLines.js",[a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,c){var g=c.defined,
b=c.error,f=c.merge,d=a.seriesTypes.sma;return{pointArrayMap:["top","bottom"],pointValKey:"top",linesApiNames:["bottomLine"],getTranslatedLinesNames:function(e){var a=[];(this.pointArrayMap||[]).forEach(function(b){b!==e&&a.push("plot"+b.charAt(0).toUpperCase()+b.slice(1))});return a},toYData:function(a){var e=[];(this.pointArrayMap||[]).forEach(function(b){e.push(a[b])});return e},translate:function(){var a=this,b=a.pointArrayMap,c=[],l;c=a.getTranslatedLinesNames();d.prototype.translate.apply(a,
arguments);a.points.forEach(function(e){b.forEach(function(b,u){l=e[b];null!==l&&(e[c[u]]=a.yAxis.toPixels(l,!0))})})},drawGraph:function(){var a=this,c=a.linesApiNames,k=a.points,l=k.length,p=a.options,h=a.graph,u={options:{gapSize:p.gapSize}},r=[],n;a.getTranslatedLinesNames(a.pointValKey).forEach(function(a,b){for(r[b]=[];l--;)n=k[l],r[b].push({x:n.x,plotX:n.plotX,plotY:n[a],isNull:!g(n[a])});l=k.length});c.forEach(function(c,h){r[h]?(a.points=r[h],p[c]?a.options=f(p[c].styles,u):b('Error: "There is no '+
c+' in DOCS options declared. Check if linesApiNames are consistent with your DOCS line names." at mixin/multiple-line.js:34'),a.graph=a["graph"+c],d.prototype.drawGraph.call(a),a["graph"+c]=a.graph):b('Error: "'+c+" doesn't have equivalent in pointArrayMap. To many elements in linesApiNames relative to pointArrayMap.\"")});a.points=k;a.options=p;a.graph=h;d.prototype.drawGraph.call(a)}}});d(a,"Mixins/ReduceArray.js",[],function(){return{minInArray:function(a,c){return a.reduce(function(a,b){return Math.min(a,
b[c])},Number.MAX_VALUE)},maxInArray:function(a,c){return a.reduce(function(a,b){return Math.max(a,b[c])},-Number.MAX_VALUE)},getArrayExtremes:function(a,c,d){return a.reduce(function(a,f){return[Math.min(a[0],f[c]),Math.max(a[1],f[d])]},[Number.MAX_VALUE,-Number.MAX_VALUE])}}});d(a,"Stock/Indicators/Stochastic/StochasticIndicator.js",[a["Core/Series/Series.js"],a["Mixins/MultipleLines.js"],a["Mixins/ReduceArray.js"],a["Core/Utilities.js"]],function(a,c,d,b){var f=this&&this.__extends||function(){var a=
function(c,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(c,b)};return function(c,b){function h(){this.constructor=c}a(c,b);c.prototype=null===b?Object.create(b):(h.prototype=b.prototype,new h)}}(),g=a.seriesTypes.sma,e=b.extend,v=b.isArray,k=b.merge;b=function(c){function b(){var a=null!==c&&c.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}f(b,c);
b.prototype.init=function(){a.seriesTypes.sma.prototype.init.apply(this,arguments);this.options=k({smoothedLine:{styles:{lineColor:this.color}}},this.options)};b.prototype.getValues=function(b,c){var e=c.periods[0];c=c.periods[1];var n=b.xData,k=(b=b.yData)?b.length:0,l=[],h=[],f=[],g=null,m;if(!(k<e)&&v(b[0])&&4===b[0].length){for(m=e-1;m<k;m++){var q=b.slice(m-e+1,m+1);var p=d.getArrayExtremes(q,2,1);var t=p[0];q=b[m][3]-t;t=p[1]-t;q=q/t*100;h.push(n[m]);f.push([q,null]);m>=e-1+(c-1)&&(g=a.seriesTypes.sma.prototype.getValues.call(this,
{xData:h.slice(-c),yData:f.slice(-c)},{period:c}),g=g.yData[0]);l.push([n[m],q,g]);f[f.length-1][1]=g}return{values:l,xData:h,yData:f}}};b.defaultOptions=k(g.defaultOptions,{params:{periods:[14,3]},marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>%K: {point.y}<br/>%D: {point.smoothed}<br/>'},smoothedLine:{styles:{lineWidth:1,lineColor:void 0}},dataGrouping:{approximation:"averages"}});return b}(g);e(b.prototype,{nameComponents:["periods"],
nameBase:"Stochastic",pointArrayMap:["y","smoothed"],parallelArrays:["x","y","smoothed"],pointValKey:"y",linesApiNames:["smoothedLine"],drawGraph:c.drawGraph,getTranslatedLinesNames:c.getTranslatedLinesNames,translate:c.translate,toYData:c.toYData});a.registerSeriesType("stochastic",b);"";return b});d(a,"masters/indicators/stochastic.src.js",[],function(){})});
//# sourceMappingURL=stochastic.js.map