/*
 Highstock JS v8.2.2 (2020-12-12)

 Indicator series type for Highstock

 (c) 2010-2019 Wojciech Chmiel

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/supertrend",["highcharts","highcharts/modules/stock"],function(p){a(p);a.Highcharts=p;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function p(a,n,k,x){a.hasOwnProperty(n)||(a[n]=x.apply(null,k))}a=a?a._modules:{};p(a,"Stock/Indicators/Supertrend/SupertrendIndicator.js",[a["Core/Series/Series.js"],a["Core/Color/Palette.js"],
a["Core/Utilities.js"]],function(a,n,k){function x(a,e,c){return{index:e,close:a.yData[e][c],x:a.xData[e]}}var p=this&&this.__extends||function(){var a=function(e,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,a){c.__proto__=a}||function(c,a){for(var d in a)a.hasOwnProperty(d)&&(c[d]=a[d])};return a(e,c)};return function(e,c){function d(){this.constructor=e}a(e,c);e.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),z=a.seriesTypes,C=z.atr,A=z.sma,B=k.correctFloat,
D=k.isArray;z=k.extend;var y=k.merge,E=k.objectEach;k=function(a){function e(){var c=null!==a&&a.apply(this,arguments)||this;c.data=void 0;c.linkedParent=void 0;c.options=void 0;c.points=void 0;return c}p(e,a);e.prototype.init=function(){A.prototype.init.apply(this,arguments);var c=this.options;c.cropThreshold=this.linkedParent.options.cropThreshold-(c.params.period-1)};e.prototype.drawGraph=function(){var c=this,d=c.options,a=c.linkedParent,e=a?a.points:[],k=c.points,p=c.graph,u=k.length,v=e.length-
u;v=0<v?v:0;for(var n={options:{gapSize:d.gapSize}},m={top:[],bottom:[],intersect:[]},w={top:{styles:{lineWidth:d.lineWidth,lineColor:d.fallingTrendColor||d.color,dashStyle:d.dashStyle}},bottom:{styles:{lineWidth:d.lineWidth,lineColor:d.risingTrendColor||d.color,dashStyle:d.dashStyle}},intersect:d.changeTrendLine},b,l,f,g,h,q,r,t;u--;)b=k[u],l=k[u-1],f=e[u-1+v],g=e[u-2+v],h=e[u+v],q=e[u+v+1],r=b.options.color,t={x:b.x,plotX:b.plotX,plotY:b.plotY,isNull:!1},!g&&f&&a.yData[f.index-1]&&(g=x(a,f.index-
1,3)),!q&&h&&a.yData[h.index+1]&&(q=x(a,h.index+1,3)),!f&&g&&a.yData[g.index+1]?f=x(a,g.index+1,3):!f&&h&&a.yData[h.index-1]&&(f=x(a,h.index-1,3)),b&&f&&h&&g&&b.x!==f.x&&(b.x===h.x?(g=f,f=h):b.x===g.x?(f=g,g={close:a.yData[f.index-1][3],x:a.xData[f.index-1]}):q&&b.x===q.x&&(f=q,g=h)),l&&g&&f?(h={x:l.x,plotX:l.plotX,plotY:l.plotY,isNull:!1},b.y>=f.close&&l.y>=g.close?(b.color=r||d.fallingTrendColor||d.color,m.top.push(t)):b.y<f.close&&l.y<g.close?(b.color=r||d.risingTrendColor||d.color,m.bottom.push(t)):
(m.intersect.push(t),m.intersect.push(h),m.intersect.push(y(h,{isNull:!0})),b.y>=f.close&&l.y<g.close?(b.color=r||d.fallingTrendColor||d.color,l.color=r||d.risingTrendColor||d.color,m.top.push(t),m.top.push(y(h,{isNull:!0}))):b.y<f.close&&l.y>=g.close&&(b.color=r||d.risingTrendColor||d.color,l.color=r||d.fallingTrendColor||d.color,m.bottom.push(t),m.bottom.push(y(h,{isNull:!0}))))):f&&(b.y>=f.close?(b.color=r||d.fallingTrendColor||d.color,m.top.push(t)):(b.color=r||d.risingTrendColor||d.color,m.bottom.push(t)));
E(m,function(a,b){c.points=a;c.options=y(w[b].styles,n);c.graph=c["graph"+b+"Line"];A.prototype.drawGraph.call(c);c["graph"+b+"Line"]=c.graph});c.points=k;c.options=d;c.graph=p};e.prototype.getValues=function(a,d){var c=d.period;d=d.multiplier;var e=a.xData,k=a.yData,p=[],u=[],v=[],n=0===c?0:c-1,m=[],w=[],b;if(!(e.length<=c||!D(k[0])||4!==k[0].length||0>c)){a=C.prototype.getValues.call(this,a,{period:c}).yData;for(b=0;b<a.length;b++){var l=k[n+b];var f=k[n+b-1]||[];var g=m[b-1];var h=w[b-1];var q=
v[b-1];0===b&&(g=h=q=0);c=B((l[1]+l[2])/2+d*a[b]);var r=B((l[1]+l[2])/2-d*a[b]);m[b]=c<g||f[3]>g?c:g;w[b]=r>h||f[3]<h?r:h;if(q===g&&l[3]<m[b]||q===h&&l[3]<w[b])var t=m[b];else if(q===g&&l[3]>m[b]||q===h&&l[3]>w[b])t=w[b];p.push([e[n+b],t]);u.push(e[n+b]);v.push(t)}return{values:p,xData:u,yData:v}}};e.defaultOptions=y(A.defaultOptions,{params:{multiplier:3,period:10},risingTrendColor:n.indicatorPositiveLine,fallingTrendColor:n.indicatorNegativeLine,changeTrendLine:{styles:{lineWidth:1,lineColor:n.neutralColor80,
dashStyle:"LongDash"}}});return e}(A);z(k.prototype,{nameBase:"Supertrend",nameComponents:["multiplier","period"],requiredIndicators:["atr"]});a.registerSeriesType("supertrend",k);"";return k});p(a,"masters/indicators/supertrend.src.js",[],function(){})});
//# sourceMappingURL=supertrend.js.map